#+TITLE:     心理的火
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs.css" />

#+BEGIN_VERSE

我不知道心灵什么样子，
姑且将之比喻为一团火。
这团火燃烧的太热烈总爱熄灭，
也许它能重新燃起，
可自己左看右看，
悲哀发现早不是当初模样。

疑惑审视，即使将之点燃的媒介相同，
不敢肯定是它从虚无的某处突兀地钻入你无意识的心海，
还是你漂泊无依的身躯找到同样漂泊的它。

只是命运般结合在一起，
所以不再比较相互之间优劣好坏，
自漆黑的幕后匆忙走出，
撕下片缕点燃第一把火：
哪怕这样的初生值得赞美也最容易让人困扰，
纯洁的火焰在襁褓中还未真正升华就已经开始迫不及待地展示。

那火不断高涨自己的气势与身姿，肆意散发自己的激情与精血。
身躯经受和风细雨的洗礼绝不愿停歇，路遇柔花嫩草化灰烬亦未尝怜悯。
灵魂牢笼之外纵肮脏泥泞也以为自由潇洒，密室之中无垢无尘可曾感受寂寞窒息。

或许风暴终有来临之时，
可在那之前唯有你独一无二的演绎，
并非展开原型本质宣告火焰的新生，
而只是自我确认的存在，
从此不再有空虚无归的身躯与灵魂，
晦暗阴影之下浮现真名模样。

你不曾考虑燃烧的本意、也没有细数燃烧的代价，
只看见璀璨已经如烧制成的琉璃，不过问火焰本身开始飘忽，
连原本的通透也一起灌入迄今为止仅有的作品之中。

依旧妄想岁月洗礼曾经不见衰容，
火焰也可以永远不带丝毫杂质，
只是下方薪柴已经堆积如山，
黑烟也在空中畅意弥漫，
哪怕无畏如你时有羞愧身后多少因你被迫或自愿付出，
时有恐惧在天空下的阴霾不自觉地笼罩中会就此迷离。

直到时间将一切打磨，敢于挑战者转瞬不复从前，
匍匐卑微于下也只能被当做虫蛀蚕食的腐臭，
铁律宣告声中怕纵使这片天地间的微尘亦无法逃离。
'
曾经助你挥霍的，
就是你踩在脚下的逐渐无力，
原本坚实硕壮的臂膀再也承担不起此等重量，
身架成齑粉，
精神也成墓碑上蚀刻的文字，
一切在灰烬中随风而去。

啊，新生的火，猛烈燃烧的火，纵你万般不愿，请只留下火种。
不变的长夜在黑暗中你还是那明亮的一点，
虽然无法将光明传递他人，却也不再继续肆意焚烧身边的可怜。

你不是，你不是，你不是，
永远不是新律的大声宣告者，永远不是光明。
也许当光明真的洒下，
你的虔诚让你自愿成为其中的一缕，
而非过早的熄灭，
转瞬湮没在呼吸的天地间。

你的心，你的血，
没了外力帮助显现原形，
是的，只不过似乎随时都会熄灭的火种。

也许这段时间不会太久，
也许让你刚有省悟的念头便抹去仅有的顾虑。
自你初生便有血脉的交织，
自你初生便有主宰指定交融，
当一切还未坍塌、在你刚开始沮丧的时候便将你重新燃起——
依旧炙热，依旧明亮，依旧蓬勃，依旧气盛。

失去的似乎如梦境般回转，
那温度正是你熟悉而又日思夜想的，但终究缺少什么？
你不愿意承认，不愿意细想，即使四周空旷，并无窃听偷窥。

只有重燃的那刻你清晰听到阴暗深处低吟着丧歌，
哭泣的歌声没有悲伤在痛哭嘶嚎，
只有被遗忘的哀愁已经那般惆怅，
是那般不值被火焰迅速焚烧变灰烬。
可知这丧歌由谁唱响第一个音符，
又为惊醒早已迷梦中的谁？

不必推倒青铜的火架，不再嫌弃漆黑的燃煤，
依旧豪华的装扮与帮助该是你所应有，
哪怕不是天生也是必需。

重燃的第二把火，
深藏的帷幕不再为你掀起，
茫茫天地的造化也不愿意被曾经失去的你再次肆意挥霍，
当黑暗地穴里的丑陋被第一次奋力凿出提炼，
你被明确地告之那是不再幼稚的你今后生命的唯一依赖，
那是有志光明的你开始洒下斑驳的最大凭借。

是瞬间迷思，还是长久彷惶，又或看似第一次的彻悟，
飘逸焰形哪怕何等随心也灌注了自己的模样，
哪怕何等天赋也被赠予平凡，是融入世界、也被踏入。

你知道了自己再也不是伟大自然被设定的造物，
无论炙热的风向还是温度都可以重新再来，
虽不至于狂妄地宣称是自己创造了显现的一切，
可却径直将你的迷思、你的彷惶、你的彻悟抽象在火焰核心，
你将膜拜从伟岸的神奇转向虔诚的光辉，
以为光辉便是光明。

什么声音开始在耳畔大声疾呼原初之火、那将铁律铸就的火，
不是仅仅将你点亮，而是其纷飞的灰烬被当做丝絮织就你眼中的朦胧，
而是那被燃烧的某物竟已成了不可名状的虚无。

只看见滚烫如熔岩，
殷红似黑暗中流淌着等待重生的鲜血，
啊，心意的渺小火焰怎能形容火山爆发与沉寂、巍峨与内敛，
无论幻象，还是表象，又或意象。
只能等候那偶尔思绪的一瞥最后也没能有言辞地形容、行为地表现，
火焰燃烧也并未就此升华，变得更加旺盛又或更加炙热。

是早不自觉沉浸梦中，直到空旷的幽黑某处开始陆续吹起泠洌寒风，
终于将你从尚未觉醒的沉郁和寂静中拉回，
然后眼前不是莫可名状，是鲜活的世界也渐渐如鬼域般阴森。

那风呼啸每一寸土地都将原本肥沃的黑土凝在冰霜的怀抱中，
哪怕肮脏也被无微不至地包装上纯白之色，
正如你当初亲手烧制的琉璃一般通透美丽，
也正如你当初为此所付代价一般致命丑陋。
只是这次不会任性如你再次肆意，也不是冷酷如你再次暴戾，
无需为此担负任何良心谴责，如何侵袭也不能将你再度熄灭。

可以冷眼旁观死亡的恐惧和生命的夭折不会对你有任何障碍，
而当那一具具倒下的冰冷身躯在你旁边垒堆成山，
如果没有因为重燃以后只愿烧煤的怪癖反而可以让你重温一番往昔。

从此面对自我拷问什么时候只留下沉沦或觉醒的单一选择，
若茫然有所失去一角的平衡与协调、在狂风骤雨之中没有被熄灭也变飘忽不定，
然后才知道并非什么诱惑逼迫武断的决心，
只是蚕食地发作不被关注最终让一切无法自拔地结下果，
这循环命运的视角纵使愿意放弃纯粹也拼命燃烧，
冰冷的肉体与固着的煤炭混合起来被魔鬼绑架进入底部。

所以坦然接受未尝如想象般痛苦，瞬间的罪恶也开始视作平常，
在自以为看透给予和掠夺的平衡心中也就只是等价的交换，
冷却这颗至今火热滚烫的核心不至于融化面目表现的冰冷。

你决心与寒风共舞一曲死亡，罔顾游魂尚未安息，
就算火焰此时失去原本的温暖与光芒也没有稀奇，
因为受难只是你斑驳的前奏，
眼前的罪恶同样并非自身软弱无力的控诉，
而是肉体虽然依旧朝气蓬勃，
梦魇中封喉的毒药已经静候伤口撕裂心胸。

心中块垒再难消除，竟被铭上不蚀刻印的凹凸，
刀剑挥劈之际即使被融为铁水也无法阻当地流向火焰皇冠的支架，
缓缓淌下犹如烛泪成堆时刻彰显那曾经的轰烈。

自我启迪思想的上帝被承认不是全能的审判，
怀疑之声从时间长河的碎语转向义正辞严的辩说，
坍塌的世界被极限压缩到没有立锥之地依旧不闻不问，
小丑在丰碑面前胡闹嬉戏、律令在心意看来放弃知觉，
又或早就以为根本的认知从自豪宣言被证明幻象作祟──
啊，那天蓝的火焰可是只在传说被歌颂，现实唯有暗红如鲜血已凝固囚笼中。

你在强迫承认的废墟里寻找崭新基石，已经不是真理审判庭上超然的在席法官，
沦为探长从感官虚幻与现实之间尝试去理清越发繁复的可知线索，
携带的笔记上用漆黑的墨迹描述浮现眼前的一切。

如果原有的装饰掩去了所有坚守的真实印记，
证明的双方竟开始利用当初犯下的罪过传播自我可信服的论调，
执迷之火未恢复炙热就开始执行天生的使命，
那么就永远不要怜惜被打倒后便注定付出的代价，
因为助燃的充实虽然太过短暂仓促却也反复不停，
否定的洞察总能在无视纯粹的资本之上助燃消融冰霜后的焰火。

不怕无尽的打击只带来无限的厄运，
一点微末光辉有所散发便不见踪影，在没有追逐被表现的绮丽与激烈，
丧失的可是只有这塑造被虚构后必然的崩坏？

显现吧，曾经因果便认为只是过去某时踪迹而放弃一切现实的掌控，
那样天真烂漫请不要紧随恶意而来；
辩护吧，理想大厦将倾而未倒会以为被糅合的混杂可以给予其新生，
那样单纯如意永远抗拒暗藏的真实，之后无数尸骸染上焦黑之色也不被肯定，
没有能力避免的颓废最终不是压抑太重，
而是诡辩的自由终于被再次扼住了喉咙。

承认没有功绩被表彰不是你如今真正渴望成就的丰收，
如果内外折磨的伤痕会因为火焰变幻的多态失去一切本该铭记的，
那么自身的改变终究不被具现，你请改变感官已显现的他物。

没有看见寒风凛冽世界每一个角落，
虽然刺骨也不是无法承受，因为你的抗拒已经成为你燃烧的温度。
没有多虑否定怀疑心意每一寸念想，
虽然妄真却已经苦郁焦灼，因为你的疼痛反而激起你飞扬的星火。
所以本不应有如此挥霍极端地运用，
炙热便将之灰烬，冰冷便将之包裹。

企图结合在一起的火焰呀，
你的主次先后被证明只是价值衡量后无尽的暴虐，
当付出的代价未尝舍得、当得到的收获也未尝犹豫，结合可是等于奴役？

偏爱着那燃烧的欢腾，厌恶的也是这凝固的荒寂，
也许不曾想将本性剔除、真名掩盖、纵使外形也与核心一样帷幕遮挡，
可这执迷的是自我的扭曲、痴迷的是外在的寄托，
珍视不曾精细权衡就忽略了意志深处埋葬在魔鬼底部的黑暗──
所以信仰被抛弃终成叛逆也是理所当然，
爱欲即便坚守以为自我也再非等同升华。

激荡灵魂左右，你被肉体紧箍不是意志抉择的自由，
如果真是如此，那么这飞扬跳脱和不曾控制的思绪该是你不满的体现，
在这暗无天日的囚笼当中哪怕扼住了唯一的命脉也不肯屈服。

所以这般困惑，眼前事实逼迫着你迷梦以外的接受，
纵使万种无奈，几次头破血流的伤痛也给了你令人侧目的记忆与成果，
是否依旧故我却罔顾当日漂泊的无依和如今被填补后的充足？
火焰只会如故，可以开始释放那已设定的应有炙热，
光辉缓缓洒下，你眼见那世界时钟上的指针已经按部就班朝向在正午，
亦步亦趋跟随不再在乎一点言辞有理的辩护和早蒙蔽的面目。

否定吧，否定吧，真诚怎会记挂曾经修饰的火架只是刻意拙劣的模仿；
律令吧，律令吧，变化怎会诡辩原本隔阂的双方永远孤立反叛的独行──
如果忘却了的天蓝终究无法追寻，被凝固的血斑，还请融化以为鲜红。

升腾是那最完美的英姿终于演绎在高处，
意想接近光明却不可感触，
未见背后酸苦迷茫早掩盖沉淀在了焰心，
徘徊欲求黑暗亦唯有恸哭。
是否拥有便不会失去，无须教训过去往昔，
又或不成熟的祭奠岂止此刻的风光，还有袒露以为所有的真实。

当告白的心声话语在喉咙中酝酿囚禁的自由，
虽然无法挽回却已经承认只是代价在补偿曾经尚未入狱的挥霍，
还有因为掩饰这未经记忆的悼词将所有的虚幻剥除。

这是你所犯下的罪孽被终于铭刻，
尖锐的凿子指向原本无形的焰心，
另一边的铁锤敲击开始震撼着燃烧，也将刻印越发地深入。
可为将脆弱的星火剔除，
摇摆的不是那颗依旧仿徨的核心，
而是这表面的绚丽终究太过浮华，怎禁敲打的自我还是真实的痛楚。

你早不为罪孽继续偿还任何，但这痛楚却是心甘情愿，
那丧歌也不再听见吟哦唱响，但这回音却是耳畔不能躲过，
因为你的沉湎不会继续罪孽的进行，而只是不可救药的罪恶强行逼迫疯狂。

是曾经给了火焰燃烧的事实，
再也不能回避熄灭后的因果，
纵使重燃以后循规蹈矩不会改变热烈的反思拷问心中，
那结论不曾担负罪孽，
却将罪恶的黑暗陆续阴霾最光辉的每个角落。

会有什么追求光辉的抚慰，就有什么将之变成痛楚，
已被凝固以后斑驳的暗下，这宿命的敲击没有停歇的时候，
支架之上抛下零星火种不会在意，反而被阴霾以后的罪恶是你亲手的付出。

被承认的与被漠视的，
多少代价也不会堆积在火架底部尸骸当中，
那处魔鬼的隐约将你诱惑，不曾将自身暴露。
一颗虔诚的核心在它燃烧的时候就企图照亮，
是否梦寐之间太过飘然，
焰形越发明亮底部也就越发漆黑如深夜？

被折磨的烈焰呀，你烧得郁郁无声是在啃食地穴的丑陋没有喧嚣，
沉郁着那未经打扫隐晦了面目与身躯的洁净，
被以为的罪恶多少沉重只是污垢沾染的自弃。

直到噼啪声响回荡耳边组织成歌，不是遮拦下方侵蚀的凶猛，
而是罪孽不曾有申讨，啃食让你身边仅存的鲜活从头开始悲鸣。
没有光辉意图延伸却总爱丰收最美丽的一束，
没有黑暗开始侵袭就注定尘埃的堆积是火焰无法燃烧也不能躲过，
那业报未尝等待来世也不曾从火焰每处寻找，
那空旷的世界有了阵阵回音响动却是你燃烧不能掩盖的痛哭。

怎会在罪恶中臣服、罪孽中罔顾，
你的燃烧不会比寒风酷冷，不会比光明崇高，
是这样的道德虽然有了铭刻的哭泣却不曾让刀剑遍体鳞伤在支架的每一个角落。

焰形未曾清晰显现，却经核心的某处有所呢喃；
燃烧不曾刻意奋举，却自灰烬的余烟有所磨练。
然后依旧没有明白的光辉并非从罪恶的深渊只手爬出、因罪孽的恒久终有忏悔，
依旧没有尝试的温暖也并非眼前的鲜活面前逃避、卷缩着地穴的丑陋无声啃食，
而是斑驳的发出终于在正午有了斑驳的回响，
那声音不会独自哭泣，只会为己欢呼。

不要留恋沉默在喉咙没有声响，
这样歌唱的灵魂只会为悲伤而泪流，
是否已经习惯沉重与罪恶的压抑，怎敢想象不羁还有狂想的时候。

在原本自由的核心坚固无法剥离的肉体牢笼，
却给你喉咙允许呐喊灵魂的美梦，
却给你燃烧的热度可以体验创造的抽象，
那早浓缩了的积压是曾经光明的幻想，
最终现实却给你仅有一缕明亮还将它彻身染成暗红，
如此愿景的美好，这般暗红却只与严酷为伍。

从长夜的黑暗在心中越发深沉、还在火架四周围绕不肯罢休，
当已有的光辉在红焰的攀升渐渐洒下斑点，
那么你的演绎即使无声也开始有伴奏。

火架高处不会有燃烧的练习等待挥舞独奏，
却从伴奏的演练交响成曲，然后灵魂的歌唱不再回荡喉咙的苦涩，
你燃烧的热度唯一决定灵魂温存依旧。
响起吧，响起吧，键音从杂乱开始有了节奏，
那交响的乐章从来不是你的独秀，
却已经是你做出的指挥、你体现的全部。

光辉不再是原本美梦的描述，只为申明不羁的潇洒并非漆黑幕后，
灵魂的实现哪怕承认没有肉体诉说，
隔却了火焰的温度，你的指挥却能为它而谱。

不再需要熔岩的炽热化去彻夜的霜冻假象看似不曾冰冷，
不再需要帷幕的掀起一瞥核心的黑暗模拟好比内外如一，
如果演绎的欢腾让你此刻满心欢喜，
伴奏与舞蹈随之生动有趣，
那么更多虚构的反复不会带来更多的美好，
只会让你谱曲的完美指挥双手却轻轻颤抖。

因为火焰的热情仅仅火焰的喜怒，
在无法改造的本质找到闪光或者污垢，
你屈服、你反叛、你痛斥、你歌颂、你逃避、你维护、你矛盾……

是这百态糅合唯一的烈焰所以编织坎坷如登山，
崎岖的旅程走过风景便恍惚失去记忆、不在此刻感染你的专注。
没有想象的完美纯粹若光明径直洒下，
也没有卑微的低头遮掩迷雾再看不清前方，
是火架支撑了脊梁、燃烧锻炼了铁骨，
你感觉到一座山的脉动。

知觉鼓荡起焰形飘忽并非唯一生命的起搏，
假如重峦叠嶂是你真实的肉体而非幻象般美丽窈窕，
那么这座冰冷的山是在火焰烘烤的苦痛之上、还是包容火焰在山中？

你看见那山已连绵成群在可悲的废墟上，
好像每一座如你一般感受着陌生的肉体也窥伺身旁，
这一触即破的美梦竟被全部打碎焚毁，
不是末日余晖也没有降临光明——
而是曾经幻象蒙蔽却也同样是保护，
直到剥离的表象终于被问可经烈焰承受。

坚硬的岩石变成沙、未经灼烧的开始太多被风化，
这残酷的剧本纵然惊醒以后也停止不自觉地演绎，
不再完美的身躯已经不会有公正的裁判面前面对升华的火焰。

因残破放下自身的保守与矜持，
只为按原本的雄壮在如今的空虚首先修补，
没有论断指明是拱卫的身躯保证火焰不被同样的大风吹熄，
还是只有矢志的火焰照亮身躯即便成沙砾也聚拢成堆。
这场没有结局的争论还没有开始已经被告停止，
在不成对手的失落下惊讶和在突兀所有的怀抱中喜悦。

火焰终于看见处境的真实，身躯也终于感到体内的温暖，
只有以这样的有力可以诉诸焰形的指挥与舞蹈，
那么也是这样的心意可以在无尽地呼啸中诉诸生命的意外。

不会类比演绎没有上溯也无法追寻的那一点，
然后在这一点的辉煌折射万般奇迹也无损原本的包容是奇迹也不再惊讶，
唯有苦痛的轮回与时隐时现的喧嚷让它中途分离却最终符合轨迹。
因为掌控的嘲弄总不在意自身填补多少珍奇，
只将一切占据己有、因为美梦的愚者总将它以为我，
这位愚者的一切也就全都属于它。

等到烈焰高举焚向天空、岩石紧握砸在地底，不是全能演绎引导，
是这原本全能的愚者终于感觉到自己所有的辉煌却不是它在帮忙，
而从废墟里看见耸立着的、是愚者的辉煌竟也早已变成平常。

没有什么比岩石的丰碑更加卓然，
也没有什么比火焰的核心更加炽热，
在这愚者引导演绎的新生后生命不再如其所具备的全能是唯一的全能，
只在呼啸中痛苦喘息、只在蹉跎后匍匐低头，
也在辉煌时满心憧憬、也在帷幕外侥幸偷窥，
直到终于发掘全能没有的珍奇、珍奇破坏后的全能。

是有着掠夺的身躯在岩石与沙砾不能超脱已有，
是有着焚烧的灰烬在火架与煤炭不能掩去刻印，
苛求的欲望只会誓言将岩石垒堆高山、火焰化作天蓝才在生命中凝聚。

所以陌生的、即使就在左右不曾感知到它的存在竟没有依托，
哪怕自然运作不是火焰所欲依旧履行职责，
给予隔阂的事实却没有任何体验能够享受。
所以熟悉的、哪怕知觉的深刻是如此清晰也不会被虚幻假借，
渴求真实的发现反而肯定自身狭隘与昏弱，
没有什么奇迹被创造只能依赖自然的拥有。

所以理想的，已经过去的没有留下独立的资格只能凭其所欲，
由此侵染四周将依托的主体改作茫然的我，
短暂的誓言没有得到实现却换来了重复的警示与长久的遵守。

不再有隔阂企图踏破未知的禁忌领域，
无声呢喃因而从哭嚎转作迫切的渴望，
撕裂的创伤终于渐渐涌动鲜红血液开始沸腾地奏响，
唯有从寂静的空旷中听到也感觉到身心无时无刻持续地运动，
然后这一片黑暗的恐怖纵使将双目遮掩也不会让保护着的火焰覆盖，
是它开始讲说真实与虚幻，由它将佝偻挑选坚石安放在身躯。

何曾是只用目盲的掠夺就被可以轻易拥有，
因为掠夺不是放置在火架供给燃烧，而是背负身躯成为一部分的我，
所以得到同样为之付出，最终放弃分辨，只为单一誓言长久。

字句中已经没有某日光辉的幻想和使命会降临刺破黑暗，
火焰必须自己又一次放弃这一缕的成就，
不再继续追逐光明的美好、那黑暗也不等同罪恶，
是照应着火焰此刻的无知警醒迷梦延伸目盲：
从此矢志燃烧成就破败身躯为了也终究得到独立，
眼见囚笼没有打破或者熔断，只是自由的掌握将钢铁首先包容其中。

你承认双携的合作是填补空隙与扩展狭隘，
而当它们真的实现并且融入也羞愧后放弃空占理想的奢求，
也自独立以后惶恐不敢以纯粹为名──你已经控制我，我自愿驱使你。

只将这最简陋的原始愿望放入空置的理想，
依旧保证唯一的独立却不能保证愿望可以得到实现、理想第一次完成，
因为伟大的真实扼住虚幻的美梦、却再不能侵入。
你我完美的合作就在唯一的限定下进行无阻，
可被那绝对的宣称否定，却被这天生的独特困扰，
刚刚发现已成印象的单纯在对比后竟是帷幕残留的天然。

那记忆割裂成了不可溯及的匪思臆想，
只是理想不容肆意更改、美梦也不能再次得逞，
依旧难以实现唯有在一切的否认中找到全新的含义诠释。

火焰或许无法达成目的却终究有了崭新的目标，
因为没有珍视然后感知的真实、虚幻从来不懂收敛深渊的神秘，
因为没有谨慎然后辨析的虚幻、真实只是放弃拼凑成功的图板，
所以你的纯粹不会将无知化为所有的不可知然后唯一是可知，
而是肉体与灵魂结合以后将蜕变的思想与行为同时燃烧，
然后在一片混沌的画像中拷问未知并将它付诸已知。

虚空不能夺走心神，幽暗不能腐蚀肌肤，
完整的拥有、完整的把握是无懈可击却只在焰心一簇、岩石搭构，
可看清混沌已经汇聚抽象的无知，还在图像的本质？

昔日奋斗的一缕终于明白、在明白了自己以后，
梦魇伟大的光辉没有从天而降也无需在旁明亮，
不是燃烧的帮助取暖与消融冰霜而是燃烧必须的自我行动。
没有意志如你、没有形态似你、没有呢喃告诉你——
辉煌的你是至高的你、伟岸的你是恒久的你、明晰的你是全知的你，
只有岩石的双目是浑浊、火焰的心灵是破坏，你才是需要帮助。

冷却躁动的焰形左右飘忽使火焰逐渐高涨，
暂停纷乱的碎石急迫安放因岩层需要稳固，
没有答复从虚空传来、自山巅显露让铁律的法则早已偷换原则。

不再以心中完美忙于指挥的流畅、火焰的明亮，
这重复与长久的警示竟是原本因为你认识的如此简陋，
万般不及它虚空的幽深、铁律的严苛。
所以追求如理想放弃定义的、开始缓慢被塑造，
而当记忆仅仅记忆、印象再也没有体验般深刻，
曾经伟岸是神奇如今奇迹已平常。

只有火焰燃烧的极限比苍穹那般不可触及，
山峰暂停后的高度也不允许继续攀升，
放下虚空与铁律，眼前已经足够惊醒你的所有没有被玩弄却一直被包括。

被名奇迹终有褪去光鲜的时候、那是曾经亲手披上的外衣，
不是未知可以无冕为皇而以完全的拥有盖上浅薄遮拦，
总在四顾与迷离间才察觉后痛苦唾弃它的平常。
何时以火焰激烈的燃烧反而平静自由的暴虐然后正视，
哪怕面对混沌的恐怖一步踏出可以拓展你色彩的鲜艳与奇迹的平常，
那便没有火焰的宣言只有火焰的倾听，没有岩石的姿态只有岩石的笃行。

#+END_VERSE
