#+TITLE:     心理的火
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs.css" />

#+BEGIN_VERSE

我们不知道心灵是什么样子，姑且将之比喻为一团火。
这团火，燃烧的太热烈总爱熄灭，
也许它能重新燃起，可自己左看右看，悲哀发现早就不是当初模样。
疑惑审视，即使将之点燃的媒介相同，
不敢肯定是它从虚无的某处突兀地钻入你无意识的心海，
还是你漂泊无依的身躯找到同样漂泊的它。
你们只是命运般结合在一起，从此不再刻意比较相互之间优劣好坏，
自漆黑的幕后匆忙走出，撕下片缕点燃了第一把火。

初生最是值得赞美却也最容易让人困扰，
纯洁的火焰在襁褓中还未真正升华便迫不及待地展示——
那火，那火，不断高涨自己的气势与身姿，肆意散发自己的激情与精血；
那火，那火，经受和风细雨的洗礼绝不愿停歇，路遇柔花嫩草化灰烬亦未尝怜悯；
那火，那火，牢笼之外纵肮脏泥泞也以为自由潇洒，密室之中无垢无尘可曾想你寂寞窒息。
也许风暴终有来袭之时，可在那之前唯有你独一无二的演绎：
并非展开原型本质宣告火焰的新生，而只是自我确认的存在，
从此不再有空虚无归的身躯与灵魂，火焰阴影之中浮现真名与模样。

此时岁月洗礼犹未见衰容，火焰也仍旧不带丝毫杂质，
只是下方薪柴早堆积如山，黑烟也在畅意弥漫，
哪怕无畏如你时有羞愧身后多少因你被迫或自愿付出，
时有恐惧在天空下的阴霾不自觉地笼罩中会就此迷离。
火焰并不曾为谁自愿燃烧，也更没有放弃过谁，
当沙被烧制成璀璨的琉璃，火焰本身却已开始忽明忽暗，
似乎连原本的通透也一起灌入迄今为止仅有的作品之中。

是时间在将一切打磨，敢于挑战者转眼间不复从前，
匍匐卑微于下也只能被当做虫蛀蚕食的腐臭，
铁律宣告声中怕纵使这片天地间的微尘亦无法逃离。
当助你挥霍的、就是你踩在脚下的逐渐无力，
原本坚实硕壮的臂膀再也承担不起此等重量，
身架成齑粉，精神也成墓碑上蚀刻的文字，一切必将随风而去。
啊，新生的火，猛烈燃烧的火，纵你万般不愿，请只留下火种。
不变的长夜在黑暗中你也还是那明亮的一点，
虽然无法将光明传递他人，却也不再继续肆意焚烧身边的可怜。
你不是，你不是，永远不是新律的大声宣告者，永远不是光明。
也许当光明真的洒下，你自愿成为其中一缕，
而非过早的熄灭，转瞬湮没于呼吸的天地间。

你的心，你的血，没了外力帮助显现原形，
是的，就只不过似乎随时都会熄灭的火种。
可这段时间不会太久，也许让你刚有省悟的念头便抹去仅有的顾虑，
自你初生便有的朋友，自你初生便有上苍指定与你血脉相连的亲人，
他们在你还没知觉到的时候便将你重新燃起，
依旧炙热，依旧明亮，依旧蓬勃，依旧气盛……
曾经失去的重回，那温度正是你熟悉而又日思夜想的，但终究失去什么？
你不愿意承认，不愿意细想，即使四周空旷，并无窃听偷窥。
啊，可在重新燃起的那刻你清晰听到阴暗深处低吟着丧歌，哭泣的丧歌——
是否知道这丧歌由谁唱响第一个音符，又为惊醒迷梦中的谁？

何以推倒青铜的火架，何以嫌弃漆黑的燃煤，
豪华的装扮与帮助是你所应有，哪怕不是天生也是必需。
重燃的第二把火，深藏的帷幕不再为你掀起，
茫茫天地的造化也不愿意被曾经失去的你再次肆意挥霍，
当黑暗地穴里的丑陋被第一次奋力凿出提炼，
你被明确地告之那是不再幼稚的你今后生命的唯一依赖，
那是有志光明的你开始洒下斑驳的最大凭借。

无论是有了瞬间的迷思，还是长久的彷惶，又或看似不曾有过的彻悟，
飘逸的焰形哪怕何等随心也灌注了自己的模样，
哪怕何等天赋也被赠予平凡的恩赐，是融入世界、也被踏入。
你知道了自己再也不是伟大自然被设定的造物，
虽不至于狂妄地宣称是自己创造了显现的一切，
可却径直将你的迷思、你的彷惶、你的彻悟抽象在火焰核心，
你将膜拜从伟岸的神奇转向虔诚的光辉，以为光辉便是光明。
什么声音开始在耳畔大声疾呼原初之火，那将铁律铸就的火，
不是仅仅将你点亮，而是其纷飞的灰烬被当做丝絮织就你眼中的朦胧，
而是那被燃烧的某物竟已成了不可名状的虚无——
你只看见滚烫如熔岩，鲜红似黑暗中流淌着等待重生的鲜血，
啊，心意的渺小火焰又怎形容火山爆发与沉寂、巍峨与内敛，
无论幻象，还是表象，又或意象。

那偶尔思绪的一瞥终究没能有言辞地形容、行为地表现，
火焰燃烧也并未就此升华，变得更加旺盛又或更加炙热。
是早不自觉地沉浸梦中，直到空旷的幽黑某处开始陆续吹起泠洌寒风，
终于将你从尚未觉醒的沉郁和寂静中拉回，
然后眼前不是莫可名状，是鲜活的世界也渐渐如鬼域般阴森。
那风呼啸每一寸土地都将原本肥沃的黑土凝在冰霜的怀抱中，
哪怕肮脏也被无微不至地包装上纯白之色，
正如你当初亲手烧制的琉璃一般通透美丽，
也正如你当初为此所付代价一般致命丑陋，
只是这次不是任性如你再次肆意，不是冷酷如你再次暴戾：
你无需为此担负任何良心地谴责，如何侵袭也不能将你再度熄灭，
冷眼旁观死亡的恐惧和生命的夭折也不会对你有任何障碍。
当那一具具倒下的冰冷身躯在你旁边垒堆成山，
如果没有因重燃以后只愿烧煤的怪癖反而可以让你重温一番往昔。

面对自我反复拷问什么时候仅仅只剩沉沦或觉醒的选择，
若茫然有所失去一角的平衡与协调，
纵使烈焰哪怕在狂风骤雨之中没有被熄灭也变飘忽不定，
然后才知道并非什么诱惑逼迫武断，
只是蚕食的发作不被关注最终让一切无法自拔地结下果，
循环命运的视角愿放弃纯粹也燃烧，
冰冷的肉体与固着的煤炭混合起来被魔鬼绑架进入底部。

坦然接受未尝如想象般痛苦，瞬间的罪恶也开始视作平常，
在自以为看透给予和掠夺的平衡心中也就只是等价的交换，
安慰这颗至今火热滚烫的核心不至于融化面目表现的冰冷。
你决心与寒风共舞一曲死亡，罔顾游魂尚未安息，
就算火焰此时失去原本的温暖与光芒也没有稀奇，
因为受难是你斑驳的前奏，眼前的罪恶并非只是自身软弱无力的控诉，
而是肉体虽依旧朝气蓬勃，梦魇中那封喉的毒药也静候伤口撕裂心胸。
自我启迪思想的上帝终被承认不是那全能的审判，
怀疑之声从时间长河的碎语转向义正辞严地辩说，
坍塌的世界被极限压缩到没有立锥之地依旧不闻不问，
小丑在丰碑面前胡闹嬉戏、律令在心意看来放弃知觉，
又或早就以为根本的认知从自豪宣言被证明幻象作祟──
啊，那天蓝的火焰可是只在传说被歌颂，现实唯有暗红如鲜血已凝固囚笼中。

心中块垒再难消除，竟被铭上了不蚀刻印的凹凸，
刀剑挥劈之际即使被融为铁水也无法阻当地流向火焰皇冠的支架，
缓缓淌下犹如烛泪成堆在时刻彰显着曾经的轰烈，
原有装饰也终于被掩盖所有往昔坚守真实的印记。
你在直观强迫承认的废墟里寻找崭新基石，
已经不是那真理审判庭上超然的在席法官，
沦为探长从感官虚幻与现实之中尝试去理清越发繁复的可知线索，
携带的笔记里用漆黑的墨迹描述浮现眼前的一切。
如果证明的双方竟利用当初犯下的原罪在传播自我可信服的论调，
执迷之火未恢复原有炙热就开始执行天生的使命，
那么就永远不要怜惜被打倒后便注定付出的代价，
因为助燃的充实虽然太过短暂仓促却也反复不停，
否定的洞察总能在无视纯粹的资本之上燃烧起冰霜已消融的焰火。

不怕无尽的打击只带来无限的厄运，一点微末光辉有所散发便不见踪影，
在没有了追逐被表现的绮丽与激励，丧失的可是只有这塑造虚构的崩坏？
显现吧，也许认为曾经因果便只是过去某时踪迹而失去一切现实的掌控，
那样天真烂漫请不要紧随恶意降临，被淬炼的依旧松脆可也有杂质排出。
辩护吧，理想大厦将倾而未倒会以为被糅合的混杂已经给予其真正新生，
那样单纯洁白永远抗拒暗藏的真实，无数尸骸染上焦黑之色也不被肯定，
没有能力避免的颓废不是压抑太重，而是诡辩的自由被再次扼住了喉咙。

寒风凛冽世界每一个角落，虽然刺骨难耐却也不是无法承受；
否定怀疑心意每一寸念想，虽然虚伪妄真却也只是痛苦焦灼：
没有功绩被表彰不是你如今真正渴望成就的丰收，
如果内外折磨的伤痕会因为火焰变幻的多态失去一切本该铭记的失败，
那么自身的改变终究不被具现，你请改变感官已显现的他物。
怎么可以是挥霍极端地运用，炙热将之灰烬、冰冷将之包裹，
企图结合在一起的心意呀，从仆的归属证明主次先后只是价值的衡量，
付出的代价未尝没有，得到的收获未尝犹豫，结合可应互补？
偏爱着那燃烧的欢腾，厌恶的也是这凝固的荒寂，
也许不曾想将本性剔除、真名掩盖、纵使外形也与核心一样帷幕遮挡，
可这执迷的是自我的扭曲、痴迷的是外在的寄托，
珍视不曾精细权衡就忽略了意志深处埋葬在魔鬼底部的黑暗：
信仰抛弃终成叛逆也是理所当然，爱欲坚守以为自我也再非等同升华。

激荡灵魂左右，你被肉体紧箍可是意志抉择的自由，
如果真是如此，那么这飞扬跳脱和不曾控制的思绪该是你不满的体现，
在这暗无天日的囚笼当中哪怕扼住了唯一的命脉也不肯屈服？
必是这般困惑，眼前事实逼迫着你迷梦以外的接受，
纵使万种无奈，几次头破血流的伤痛也给了你令人侧目的记忆与成果，
是否依旧故我却罔顾当日漂泊的无依和如今被填补后的充足？
火焰只会如故，可以开始释放那已设定的应有炙热，
光辉缓缓洒下，你眼见那世界时钟上的指针已经按部就班朝向在正午，
亦步亦趋跟随不再在乎一点言辞有理的辩护和早蒙蔽的面目。
分解吧，分解吧，执着怎会硬塞旧日往事的偏爱以为现实空虚的梦幻；
否定吧，否定吧，真诚怎会记挂曾经修饰的火架只是刻意拙劣的模仿；
律令吧，律令吧，变化怎会诡辩原本隔阂的双方永远孤立反叛的独行──
如果忘却了的天蓝终究无法追寻，被凝固的血斑，还请融化以为鲜红。

升腾是那最完美的英姿终于演绎在高处，意想接近光明，
未见背后酸苦迷茫早掩盖沉淀在了焰心，徘徊欲求黑暗，
是否拥有便不会失去，无须背负过去往昔。
唯有丧歌的呢喃还在耳边隐隐声响，置之不理可以如常，
又或不成熟的祭奠岂止此刻的风光，还有袒露以为真实，
告白的心声话语在喉咙中酝酿囚禁的自由，
虽然无法挽回却承认只是代价在补偿尚未入狱时的挥霍。

这是你所犯下的罪孽被终于铭刻，尖锐的凿子指向原本无形的焰心，
另一边的铁锤敲击开始震撼着燃烧，也将刻印越发地深入。
可为将脆弱的星火剔除，摇摆的不是那颗依旧仿徨的核心，
而是这表面的绚丽终究太过浮华，怎禁敲打的自我还是真实的痛楚。
你早不为罪孽继续偿还任何，但这痛楚却是心甘情愿，
那丧歌也不再听见吟哦唱响，但这回音却是耳畔不能躲过，
因为你的沉湎不会继续罪孽的进行，而只是不可救药的罪恶强行逼迫疯狂。
是曾经给了火焰燃烧的事实，再也不能回避熄灭后的因果，
纵使重燃以后循规蹈矩不会改变热烈的反思拷问心中，
那结论不曾担负罪孽，却将罪恶的黑暗陆续阴霾最光辉的每个角落。
会有什么追求光辉的安抚，就有什么将安抚变成痛楚，
已被凝固以后斑驳的暗下，这宿命的敲击没有停歇的时候，
支架之上抛下零星火种不会在意，反而被阴霾以后的罪恶是你亲手的付出。

被承认的与被漠视的，多少代价也不会堆积在火架底部尸骸当中，
那处魔鬼的隐约将你诱惑，不曾将自身暴露。
一颗虔诚的核心在它燃烧的时候就企图照亮，
是否梦寐之间太过飘然，焰形越发明亮底部也就越发漆黑如深夜？
被折磨的烈焰呀，你烧的郁郁无声是在啃食地穴的丑陋没有喧嚣，
沉郁着那未经打扫阴晦了面目与身躯的洁净，
被以为的罪恶多少沉重只是污垢沾染的自弃。
可当噼啪声响回荡耳边组织成歌，不是遮拦下方侵蚀的凶猛，
而是罪孽不曾有申讨，啃食让你身边仅存的鲜活从头开始的悲鸣。
没有光辉意图繁衍却总爱丰收最美丽的一束，
没有黑暗开始侵袭就注定尘埃的堆积是火焰无法燃烧也不能躲过，
那业报未尝等待来世也不曾从火焰每处寻找，
那空旷的世界有了阵阵回音响动却是你燃烧不能掩盖的痛哭。

怎会在罪恶中臣服、罪孽中罔顾，你的燃烧不会比寒风酷冷、不会比光明崇高。
是这样的道德已经有了铭刻的哭泣却不曾让刀剑遍体鳞伤在支架的每一个角落，
是焰形从不曾清晰显现，却在核心的某处有所呢喃；
是燃烧从不曾刻意奋举，却自灰烬的余烟有所磨练。
然后依旧没有明白的光辉并非从罪恶的深渊只手爬出、因罪孽的恒久终有忏悔，
依旧没有尝试的温暖也并非燃烧的鲜活面前放弃、卷缩着地穴的丑陋无声啃食，
而是斑驳的发出在正午有了斑驳的回响，那声音不会独自哭泣，只会为己欢呼。

如果沉默在喉咙无法声响，那么歌唱的灵魂终究为悲鸣而泪流，
是否已经习惯了罪孽的沉重和罪恶的伤痛，怎敢想象不羁还有狂想的时候。
在原本自由的核心坚固无法剥离的肉体牢笼，却给你喉咙呐喊灵魂的美梦，
却给你燃烧的热度体验创造的抽象，那早浓缩了的积压是曾经光明的幻想，
最终现实却给你仅有一缕明亮还将它彻身染成暗红。
那样的愿景是如此美好，这般暗红却又与严酷为伍，
无论长夜的黑暗在心中越发深沉、还在火架四周围绕不肯罢休，
如果光辉能在红焰的攀升洒下斑点，那么你的演绎即使无声也开始有伴奏。
火架高处不会有燃烧的练习等待挥舞独奏，却从伴奏的演练指挥交响成曲，
然后灵魂的歌唱不再从沙哑的喉咙发出，你燃烧的热度决定灵魂温存依旧。
响起吧，响起吧，交响的乐章从不是你的独秀，却是你的全部，
哪怕光辉不为原本的美梦指挥，只为不羁的潇洒并非漆黑幕后，
灵魂的实现没有肉体诉说，你的指挥已经为它而谱。

不再需要熔岩的炽热化去彻夜的霜冻假象看似不曾冰冷，
不再需要帷幕的掀起一瞥核心的黑暗模拟好比内外如一，
如果演绎的欢腾让你此刻满心欢喜、伴奏与舞蹈随之生动有趣，
那么更多虚构的反复不会带来更多的美好，
只会让你歌曲的完美指挥双手却轻轻颤抖。
也许火焰的热情仅仅火焰的享受以及被哭诉的迷茫痛苦，
在无法改造的火焰本质找到闪光或者污垢，
你屈服、你反叛、你痛斥、你歌颂、你逃避、你维护、你矛盾……
是这百态糅合唯一的烈焰编织坎坷如登山，
崎岖蜿蜒的旅程走过风景便恍惚记忆、不在此刻感染你的专注。
知道最初的尸骸压在山的底部，寒冬随之铺垫盖上冰棺，
没有想象的完美纯粹若光明之火，也没有卑微的低头遮掩迷雾，
是火架支撑了脊梁、燃烧锻炼了铁骨，你感觉到一座山的脉动。
#+END_VERSE
