#+TITLE:     心理的火
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs.css" />

#+BEGIN_VERSE
我们不知道心灵是什么样子，姑且将之比喻为一团火。
这团火，燃烧的太热烈总爱熄灭，
也许它能重新燃起，可自己左看右看，悲哀发现早不是当初模样。
疑惑审视，即使将之点燃的媒介相同，
不敢肯定是它从虚无的某处突兀地钻入你无意识的心海，
还是你漂泊无依的身躯找到同样漂泊的它。
迷茫也不待细察，你们只是命运地结合在一起，
从此不再刻意比较相互之间优劣好坏，
自漆黑的幕后匆忙走出，撕下片缕点燃了第一把火。

初生最是值得赞美却也最容易让人困扰，
纯洁的火焰在襁褓中还未真正升华便迫不及待地展示——
那火，那火，不断高涨自己的气势与身姿，肆意散发自己的激情与精血；
那火，那火，经受和风细雨的洗礼绝不愿停歇，路遇柔花嫩草化灰烬亦未尝怜悯；
那火，那火，牢笼之外纵肮脏泥泞也以为自由潇洒，密室之中无垢无尘可曾想你寂寞窒息。
也许风暴终有来袭之时，可在那之前唯有你独一无二的演绎：
并非展开原型本质宣告火焰的新生，而只是自我确认的存在，
从此不再有空虚无归的身躯与灵魂，火焰阴影之下显出真名与形状。

此时岁月洗礼犹未见衰容，火焰也仍旧不带丝毫杂质，
只是下方薪柴早堆积如山，黑烟也在畅意弥漫，
哪怕无畏如你时有羞愧身后多少因你被迫或自愿付出，
时有恐惧在天空下的阴霾不自觉地笼罩中会就此迷离。
火焰至今没有过为谁燃烧，也更没有放弃过谁，
当沙被烧制成璀璨的琉璃，火焰本身却已开始忽明忽暗，
似乎连原本的通透也一起灌入迄今为止仅有的作品之中。

是时间在将一切打磨，敢于挑战者转眼间不复从前，
匍匐卑微于下也只能被当做虫蛀蚕食的腐臭，
铁律宣告声中怕纵使这片天地间的虚无亦无法逃离。
当助你挥霍的、就是你踩在脚下的逐渐无力，
原本坚实硕壮的臂膀再也承担不起此等重量，
身架成齑粉，精神也成墓碑上蚀刻的文字，一切必将随风而去。
啊，新生的火，猛烈燃烧的火，纵你万般不愿，请只留下火种。
火种，火种，黑暗中你依旧是那明亮的一点，
虽然无法将光明传递他人，却也不再继续焚烧身边的可怜。
你不是，你不是，永远不是新律的宣告者，永远不是光明，
也许当光明真的洒下，你自愿成为其中一缕，
而非过早的熄灭，转瞬湮没于呼吸的天地间。

你的心，你的血，没了外力帮助显现原形，
是的，就只不过似乎随时都会熄灭的火种。
可这段时间不会太久，也许让你刚有省悟的念头便抹去仅有的顾虑，
自你初生便有的朋友，自你初生便有上苍指定与你血脉相连的亲人，
他们在你还没知觉到的时候便将你重新燃起，
依旧炙热，依旧明亮，依旧蓬勃，依旧气盛……
曾经失去的重回，那温度正是你熟悉的，日思夜想的，可终究失去什么？
你不愿意承认，不愿意细想，即使四周空旷，并无窃听偷窥。
啊，重新燃起的瞬间你确实清晰听到阴暗深处低吟着丧歌，哭泣的丧歌——
可知这丧歌由谁唱起那第一个音符，又为早早惊醒梦中的谁？

何以推倒青铜的火架，何以嫌弃漆黑的燃煤，
豪华的装扮与帮助是你所应有，哪怕不是天生也是必需。
重燃的第二把火，深藏的帷幕不再为你掀起，
茫茫天地的造化也不愿意被曾经失去的你再次肆意挥霍，
当黑暗地穴里的丑陋被第一次奋力凿出提炼，
你被明确地告之那是不再幼稚的你今后生命的唯一依赖，
那是有志光明的你开始洒下斑驳的最大凭借。

无论是有了瞬间的迷思，还是长久的彷惶，又或看似不曾有过的彻悟，
飘逸的焰形哪怕何等随心也灌注了自己的模样，
哪怕何等天赋也被赠予平凡的恩赐，是融入世界、也被踏入。
你知道了自己再也不是伟大自然被设定的造物，
虽不至于狂妄地宣称是自己创造了显现的一切，
可却径直将你的迷思、你的彷惶、你的彻悟抽象在火焰核心，
你将膜拜从伟岸的神奇转向虔诚的光辉，以为光辉便是光明。
什么声音开始在耳畔大声疾呼原初之火，那将铁律铸就的火，
不是仅仅将你点亮，而是其纷飞的灰烬被当做丝絮织就你眼中的朦胧，
而是其被燃烧的某物竟已成了不可名状的虚无——
你只看见滚烫如熔岩，鲜红似黑暗中流淌着等待重生的鲜血，
啊，心意的渺小火焰又怎形容火山爆发与沉寂、巍峨与内敛，
无论幻象，还是显象，又或表象。

那偶尔思绪的一瞥终究没能有言辞地形容、行为地表现，
火焰燃烧也并未就此升华，变得更加旺盛又或更加炙热。
是早不自觉地沉浸梦中，直到空旷的幽暗某处开始陆续吹起泠洌寒风，
终于将你从尚未觉醒的沉郁和寂静中拉回，
然后眼前不是莫可名状，是鲜活的世界也渐渐如鬼域般阴森。
那风呼啸每一寸土地都将原本肥沃的黑土凝在冰霜的怀抱中，
哪怕肮脏也被无微不至地包装上纯白之色，
正如你当初亲手烧制的琉璃一般通透美丽，
也正如你当初为此所付代价一般致命丑陋，
只是这次不是任性如你再次疯狂，不是冷酷如你再次暴戾：
你无需为此担负任何良心地谴责，如何侵袭也不能将你再度熄灭，
冷眼旁观死亡的恐惧和生命的夭折也不会对你有任何障碍，
当那一具具倒下的冰冷身躯在你旁边垒堆成山，
如果没有因重燃后的只愿烧煤的怪癖反而可以让你重温一番往昔。

面对自我反复拷问什么时候仅仅只剩沉沦或觉醒的选择，
若茫然有所失去一角的平衡与协调，
纵使烈焰哪怕在狂风骤雨之中没有被熄灭也变飘忽不定，
然后才知道并非什么诱惑逼迫武断，
只是蚕食的发作不被关注最终让一切无法自拔地结下果，
循环命运的视角愿放弃纯粹也燃烧，
冰冷的肉体与固着的煤炭混合起来被魔鬼绑架进入底部。

坦然接受未尝如想象般痛苦，瞬间的罪恶也开始视作平常，
在自以为看透给予和掠夺的平衡心中也就只是等价的交换，
安慰这颗至今火热滚烫的核心不至于融化面目表现的冰冷。
你决心与寒风共舞一曲死亡，罔顾游魂尚未安息，
就算火焰此时失去原本的温暖与光芒也没有稀奇，
因为受难是你斑驳的前奏，眼前的罪恶不仅只是自身无力的控诉，
而是肉体即使朝气蓬勃，梦想中封喉的毒药也静候伤口渗出露珠。
自我启迪思想的上帝终被承认不是那全能的审判，
怀疑之声从时间长河的碎语转向义正辞严地辩说，
坍塌的世界被极限压缩到没有立锥之地依旧不闻不问，
小丑在丰碑面前胡闹嬉戏、律令在心意看来放弃知觉，
又或早就以为根本的认知从自豪宣言被证明幻象作祟──
啊，那天蓝的火焰可是只在传说被歌颂，现实唯有暗红如鲜血已凝固囚笼中。

心中块垒再难消除，已被铭上了不蚀刻印的凹凸，
刀剑挥劈之间即使被融为铁水也无法阻当地流向火焰皇冠的支架，
缓缓淌下犹如烛泪成堆在时刻彰显着曾经的轰烈，
原有装饰也终于被掩盖所有往昔坚守真实的印记。
你在直观强迫承认的废墟里寻找崭新基石，
已经不是那真理审判庭上超然的在席法官，
沦为探长从感官虚幻与现实之中尝试去理清越发繁复的可知线索，
携带的笔记里用漆黑的墨迹描述浮现眼前的一切：
如果证明的双方在利用当初犯下的原罪来传播自我可信服的论调，
执迷之火未恢复原有炙热就开始执行天生的使命，
那么就永远不要怜惜被打倒后便注定付出的代价，
因为助燃的充实虽然太过短暂仓促却也反复不停，
否定的洞察必将在无视纯粹的资本之上燃起连冰霜也融化的焰火。

如果无尽的打击只带来无限的厄运，一点微末光辉有所散发便不见踪影，
在没有了追逐被表现的绮丽与激励，丧失的可是只有这塑造虚构的崩坏？
显现吧，也许认为曾经因果便只是过去某时踪迹而失去一切现实的掌控，
那样天真烂漫请不要紧随恶意降临，被淬炼的依旧松脆可也有杂质排出。
辩护吧，理想大厦将倾而未倒会以为被糅合的混杂已经给予其真正新生，
那样单纯洁白永远抗拒暗藏的真实，无数尸骸染上焦黑之色也不被肯定，
没有能力避免的颓废不是压抑太重，而是逃离的自由被再次扼住了喉咙。

（未完待续）
#+END_VERSE
