#+TITLE: 心理的火
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs.css" />

#+BEGIN_VERSE

我们不知道心灵是什么样子，姑且将之比喻为一团火。
这团火，燃烧的太热烈总爱熄灭，
也许它能重新燃起，可自己左看右看，悲哀发现早不是当初模样。
疑惑审视，即使将之点燃的媒介相同，
不敢肯定是它从虚无的某处突兀地钻入你无意识的心海，
还是你漂泊无依的身躯找到同样漂泊的它。
迷茫也不待细察，你们只是命运地结合在一起，
从此不再刻意比较相互之间优劣好坏，
自漆黑的幕后匆忙走出，撕下片缕点燃了第一把火。

初生最是值得赞美却也最容易让人困扰，
纯洁的火焰在襁褓中还未真正升华便迫不及待地展示——
那火，那火，不断高涨自己的气势与身姿，肆意散发自己的激情与精血；
那火，那火，经受和风细雨的洗礼亦绝不停歇，路遇柔花嫩草化为灰烬也未尝怜悯；
那火，那火，牢笼之外纵肮脏泥泞也以为自由潇洒，密室之中无垢无尘可曾想你寂寞窒息。
也许风暴终有来袭之时，可在那之前唯有你独一无二的演绎：
并非展开原型本质宣告火焰的新生，而是自我确认的存在，
从此不再有空虚无归的身躯与灵魂，火焰阴影之下显出真名与形状。

此时岁月洗礼犹未见衰容，火焰也仍旧不带丝毫杂质，
只是下方薪柴堆积如山，黑烟也在空气中弥漫，
哪怕无畏如你时有羞愧身后多少因你被迫或自愿付出，
时有恐惧在天空下的阴霾不自觉地笼罩中会就此迷离。
火焰至今没有过为谁燃烧，也更没有放弃过谁，
当沙被烧制成璀璨的琉璃，火焰本身却已开始忽明忽暗，
似乎连原本的通透也一起灌入迄今为止仅有的作品之中。

是时间在将一切打磨，敢于挑战者转眼间不复从前，
匍匐卑微也只能当做被蚕食的腐肉，
铁律宣告之下怕纵使这片天地间的虚无亦无法逃离。
当助你挥霍的、就是你踩在脚下的逐渐无力，
原本坚实硕壮的臂膀再也承担不起此等重量，
身架成齑粉，精神成墓碑上凹凸的文字，一切随风而去。
啊，新生的火，猛烈燃烧的火，纵你万般不愿，请只留下火种。
火种，火种，黑暗中你依旧是明亮的一点，
虽无法将光明传递他人，却也不再继续焚烧身边的可怜。
你不是，你不是，永远不是新律的宣告者，永远不是光明，
也许当光明真的洒下，你自愿成为其中的一缕，
而非过早熄灭，湮没在呼吸的天地间。

你的心，你的血，没了外力帮助露出原形，
是的，仅仅似乎随时都会熄灭的火种。
可这段时间不会太久，也许让你刚有省悟的念头便过去，
自你初生便有的朋友，自你初生便有上苍指定与你血脉相连的亲人，
他们在你尚未意识到的时候便将你重新燃起，
依旧炙热，依旧明亮，依旧蓬勃，依旧繁华……
曾经失去的重回，那温度正是你熟悉的，日思夜想的，可终究失去了什么？
你不愿意承认，不愿意细想，即使四周空旷，并无窃听偷窥。
啊，重新燃起的那一刻你确实清晰听到阴暗中低吟着丧歌，哭泣的丧歌——
可知丧歌由谁唱起那第一个音符，又为早早惊醒梦中的谁？

何以推倒青铜的火架，何以嫌弃漆黑的燃煤，
豪华的装扮与帮助是你所应有，哪怕不是天生也是必需。
重燃的第二把火，深藏的帷幕不再为你掀起，
茫茫天地的造化也不愿被曾经失去的你肆意挥霍，
当黑暗地穴里的丑陋被第一次奋力凿出提炼，
你被告之那是不再幼稚的你今后生命的唯一依赖，
那是有志光明的你开始洒下斑驳的最大凭借。

无论是有了瞬间的迷思，还是长久的彷惶，又或看似不曾有过的彻悟，
飘逸的焰形哪怕何等随心也灌注了自己的模样，
哪怕何等天赋也被赠予平凡的恩赐，是融入世界、也被踏入。
你知道了自己再也不是伟大自然被设定的造物，
虽不至于狂妄宣称自己创造了显现的一切，
可却将你的迷思、你的彷惶、你的彻悟抽象在火焰的核心，
你将膜拜从伟岸的神奇转向虔诚的光辉，以为光辉便是光明。
什么声音开始在耳畔大声疾呼原初之火，那将铁律铸就的火，
并非仅仅将你点亮，而是其纷飞的灰烬被当丝絮织就你眼中的朦胧，
而是其被燃烧的某物竟是不可名状的虚无——
你只看见滚烫如熔岩，鲜红似黑暗中流淌着等待重生的鲜血，
啊，想象中的渺小火焰又怎形容火山爆发与沉寂、巍峨与内敛，
无论幻象，还是表象，又或本质。

（未完待续）
#+END_VERSE
