#+TITLE: 林徽因

* 林徽因在李庄

作者：魏谜底

发布日期：2015.07.11 20:01

1937 年 12 月初，林徽因一家自长沙奔赴昆明。

卢沟桥事变后，抗日战争全面爆发。1937 年 7 月，北平沦陷。一个月后，困守北平的梁思成和林徽因夫妇，决定离开北平。而此时的林徽因，肺部已经出现了空洞。

提起林，我们大多数人想起的都是在“太太的客厅”里自在优雅的沙龙女主人，她如临云端般的美丽，以及她身后留下的诸多情事趣闻。然而，每一个人穷尽一生都在寻找的自我，也许并非时常出现在软纱帘子和一树丁香之下，起码在她这里，正是在流亡中，在病痛中，在李庄，她才真正成为了林徽因。

此时的梁家，已经从开始流亡时大不一样，他们抛弃了北平精致的一切，除了书籍论文和工作必备的仪器，仿佛在失火的博物馆中，人们总会捧起自己最珍贵的一件宝物。而林徽因的肺病，梁思成的脊椎组织软化，无不在这场燃烧到生活边缘的大火中，向他们吐露黑烟。从北京到天津，从天津乘船到烟台，转车到潍坊，青岛，之后再到济南，郑州，最后方抵达长沙。而此时，日军将他们临时的住所轰炸成一片废墟，战争的残酷不由得人忧郁，他们又终于要奔赴遥远的大后方——昆明。

从北平北总部胡同 3 号太太的客厅，到四川李庄某处的一个破旧的小院子，这战火与荆棘的道路上，她的脸一天天消瘦下来，但唯一不变的，是眼里那道清丽的光。去昆明的途中，他们应邀到沈从文的老家去看看。湘西一如往常的平静安抚了在战火中颠沛的人们，可短暂的良辰美景，并不能抹去肉体上的折磨。走到湘黔边境的一个小县城，林徽因病倒了。

她得了肺炎，彻夜咳嗽，没有医院，没有抗生素，甚至没有地方可供住宿。一场大病，仿佛抽尽了林的生命能量，它如同一个临界点，在未来的人生里，疾病的阴云时常笼罩在头顶，她不再是那个满脸胶原蛋白，可以挥霍青春的女子，而成为了一个真正直面生活的妇人。

刚到昆明，梁思成脊椎病就发作了。在逃亡路上，他每天都要在衬衣里穿一件铁架子，以支撑身体，可这次发作导致的肌肉痉挛让他整夜难眠，疾病将他捆绑在了帆布椅上，而此时的林徽因，才开始展现属于那一代知识分子特有的担当。她每天坚持越过四个山坡去给云南大学的学生补习英语，用脆弱的肺面对高海拔的山；她担任家里全部的劳动，生火做饭，做从来没做过的粗活累活。流利的英语，高超的社交技能，清秀的外表，都帮不上她任何忙，唯一能倚仗的，是那颗勇气满溢的心。

他们心爱的建筑事业并未荒废，拿到工资的第一个月林徽因便去购买了考察古建筑用的皮尺，这种刻骨的热爱并没有白费，在昆明世界建筑权威刊物《笔尖》发表了梁思成的论文。他们跑遍了整个四川，而林徽因正如支撑梁的铁架子一样，在衬衫内发挥着坚强的能量。

幸好还有朋友，在给友人费慰梅的信中她写道：“我喜欢听老金和若奚笑，这在某种程度上帮助我忍受这场战争……”他们的笑是宽慰和支持的象征，也是友谊在战火中开出的最温暖的花。她还曾写道，“思诚笑着，驼着背（他的背比以前更驼了），孩子们，现在是五个——我们家两个，两个姓黄的，还有一个是思永的，宝宝常带着一种娴静的笑，长得越来越漂亮，而小弟是结实的……”家庭生活中的一点温情，让她更加坚信，自己虽然放弃了许多，但最终留下的，确实是让生活得以完整的部分。

然而，这种生活也并没有长久。1940 年，林徽因带着孩子和母亲，前往偏僻的李庄。离开了朋友，离开了城市，生活给了她一个彻头彻尾的真相。孤独击溃了她苦苦支撑的心理防线，与此同时，她又病倒了。肺病再次侵袭了她的身体，一连几个月的高烧，她躺在床上静静触摸着一生中最为艰苦的岁月，没有医院，梁思成只好自己给她打针，他们互相支撑着，翻越生命中漫长的严冬。

1941 年，林徽因的弟弟在一次空战中牺牲，命运似乎仍没有放弃考验这可怜的人们，面对妻子不容乐观的精神状况，梁思成选择了隐瞒。“好比说我这种人需不需要活，不需要的话，这种悬着的日子也不都是奢侈？好比说一个非常有精神喜欢挣扎着生存的人，为什么需要肺病？如果需要，许多希望健康的念想在她就很奢侈……”在给沈从文的一封信里，她疲惫的问询。

林徽因有时会给孩子们读罗曼罗兰的《贝多芬传》和《米开朗琪罗传》，在这种朗读中，她激励着孩子们也激励着自己，“这是未来的日子”，杜甫和陆游后期的诗歌，将中国传统文人的情怀传递给她，她终于选择了希望和坚持。封闭的生活显然不能再允许有任何迷人的幻想和洒脱，反而让她将全部精神投入在古建筑研究当中，她读着《史记》和《汉书》，为研究汉代建筑作文献准备，就在李庄如豆的烛光和如豆的生命之火中，他们开始写作《中国建筑史》。喝着粗茶，守着属于他们自己的，战火无法抹灭的那片“归去来兮”。

我们如今谈起林，津津乐道的总是她在泰戈尔欢迎会上的落落大方，是她和徐志摩在一起的女儿情态，是和金岳霖的山高水长，是和梁思成的相濡以沫，这些错综复杂的故事看似给她戴上了一枚女神的花冠，但也让她的身影变得那么不真实，她似乎总是隐藏在男性身边，做一个柔和的点缀。但唯有李庄，是她与自己的战争，战争的对手，是她从未见识的生活，是一路的苦痛，是作为人必须承担的责任，也是她为自己选择的事业寄托。即使是那样的日子，她唯一没有放弃的，是内心对精神生活的坚守。真正的女神，不是穿华美的大衣，不是眼波的流转，而是身体里的那一点“韧性”，那一点“忍耐”，那一点见过命运惨淡之后的热爱和冷静。

我时常在想离开李庄时的林徽因。坐在船上，看着水波里自己瘦削的身影，看着船中未完的书稿，桨声灯影里的她，会想什么呢？会想起那个陪伴她上街买菜的篮子？还是躺在病床上写下的诗？或是给两个孩子补过的袜子？还是因肺病而喝下的无数苦药汤？也许她什么都没有想。战争结束了，他们终于熬到了春天。而也只有林徽因自己知道，这段被命名为“李庄”的日子，是她生命中格外深沉的苦和甜。

水声潺潺如诉，经此一役，她才真正成为了林徽因。
