#+TITLE:     古诗的狂想与乱语
#+AUTHOR: 
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs.css" />

子曰：“贤哉，回也！一箪食，一瓢饮，在陋巷，人不堪其忧，回也不改其乐。贤哉，回也！”

颜回之乐异乎寻常，若将它解释为知足常乐则太浅了。知足常乐是有参照的乐，而有参照的乐并非长乐。不改其乐，颜回之乐可以算是长乐，或者说是长乐的一种，它是无参照的，无需也不可能效仿的。

在这里我试图寻回一种初见和当前思考的结合，它的目的在于理清自己日益混乱的思路，所以很大程度上是极端偏见的和不全面的，它的不成熟尤其体现在仅仅对个人观点的贯彻上。有时这贯彻也会出现疏忽，或许转念再想，若干月后又想，会是另外一番光景了。

-----

#+begin_quote
长安古意 卢照邻

长安大道连狭斜，青牛白马七香车。玉辇纵横过主第，金鞭络绎向侯家。

龙衔宝盖承朝日，凤吐流苏带晚霞。百丈游丝争绕树，一群娇鸟共啼花。

啼花戏蝶千门侧，碧树银台万种色。复道交窗作合欢，双阙连甍垂凤翼。

梁家画阁天中起，汉帝金茎云外直。楼前相望不相知，陌上相逢讵相识。

借问吹箫向紫烟，曾经学舞度芳年。得成比目何辞死，原作鸳鸯不羡仙。

比目鸳鸯真可羡，双去双来君不见。生憎帐额绣孤鸾，好取门帘帖双燕。

双燕双飞绕画梁，罗纬翠被郁金香。片片行云著蝉鬓，纤纤初月上鸦黄。

鸦黄粉白车中出，含娇含态情非一。妖童宝马铁连钱，娼妇盘龙金屈膝。

御史府中乌夜啼，廷尉门前雀欲栖。隐隐朱城临玉道，遥遥翠幰没金堤。

挟弹飞鹰杜陵北，探丸借客渭桥西。俱邀侠客芙蓉剑，共宿娼家桃李蹊。

娼家日暮紫罗裙，清歌一啭口氛氲。北堂夜夜人如月，南陌朝朝骑似云。

南陌北堂连北里，五剧三条控三市。弱柳青槐拂地垂，佳气红尘暗天起。

汉代金吾千骑来，翡翠屠苏鹦鹉杯。罗襦宝带为君解，燕歌赵舞为君开。

别有豪华称将相，转日回天不相让。意气由来排灌夫，专权判不容萧相。

专权意气本豪雄，青虬紫燕坐春风。自言歌舞长千载，自谓骄奢凌五公。

节物风光不相待，桑田碧海须臾改。昔时金阶白玉堂，即今唯见青松在。

寂寂寥寥扬子居，年年岁岁一床书。独有南山桂花发，飞来飞去袭人裾。
#+end_quote

“青虬紫燕坐春风”一作“青虬紫燕坐生风”，有些道理，参考。

有一类诗歌，当它写出来的时候已然是名篇，而后人带着后世的记忆再去看则又是一番新面貌，恍惚间有这样的记忆和没有这样的记忆一首诗就像两首不同的诗一样。《长安古意》的好，有一半就在它勾起了读者的想象，就从开头的两句开始，让读者的记忆和文字鉴赏分别被它吸引，但看到了最后却只有惘然若失的感觉。它的好也好在没有“死气”，完全区别于晚唐的大部分作品，是一种沉郁，是一种没有用力在嘶嚎而是娓娓道来的哀而不伤。在这方面，能有同样气质的唐朝后来者恐怕只有韩愈一人，其他算是模仿者，而他也一并继承了“初唐四杰”（以时代论其实应该说“盛唐四杰”，“初唐四杰”似指唐诗初期的意思，区别于上官体，上官仪之死可以算一个标志性事件）的另一个特征。

这首诗的意境不同寻常，比如《长恨歌》步步上推，到最后意境圆满，但《长安古意》不同。它的意其实不用过半大概已经明了，但它的景几句就是一变一转，到最后甚至不敢确定这意境究竟是如何圆满的，但它就是已经明白，这或许正是诗人为配合他的意而写出来的效果。

这种恰到好处的沉郁，卢照邻并非每首都做到了，比如在《行路难》中有：“一朝零落无人问，万古摧残君讵知。人生贵贱无终始，倏忽须臾难久恃。谁家能驻西山日，谁家能堰东流水。汉家陵树满秦川，行来行去尽哀怜。自昔公卿二千石，咸拟荣华一万年。不见朱唇将白貌，惟闻素棘与黄泉。”如此便已是太过，这与作者的人生经历不无关系。与之相似，死气太溢，刘希夷《代悲白头翁》。

四杰都是年少成名，可仕途不顺，潦倒坎坷。他们的诗都是“以赋为诗”，写赋的本事远远超过了写诗的本事，不同于后来者所谓“以赋为诗”是追求某些特质而为之（又或其他人牵强附会），他们是不自觉的，这点在他们的作品气质上体现淋漓尽致。区别于诗作的那种特有精致，他们的诗作精彩，名句用词也是绝伦，但不精致，不精致也是一种精致。

再举例一首，唐朝的诗歌依旧流行唱，这是诗也是歌词。这种界限的区分，在诗与文之间，在诗与赋之间，在诗与歌之间，时而分明，时而模糊，可一旦有所清晰的时候，那么模糊也就是一种假装的模糊了。这是从整体上说的，细分到个人，乃至单篇，是有出入的。

#+begin_quote
明月引 卢照邻

洞庭波起兮鸿雁翔，风瑟瑟兮野苍苍。浮云卷霭，明月流光。荆南兮赵北，碣石兮潇湘。

澄清规於万里，照离思於千行。横桂枝於西第，绕菱花於北堂。

高楼思妇，飞盖君王。文姬绝域，侍子他乡。

见胡鞍之似练，知汉剑之如霜。试登高而骋目，莫不变而回肠。
#+end_quote

唐诗是从多方面过渡的，纯粹以诗论，它脱离了南北朝写美女情态、写贵族生活、写闺室、写宫廷，转而写沧桑、风景、山水、田园、个人等等。但是，正如上面所说，这是从整体上说的，细分到个人，举梁简文帝为例，他的才情、写景、写意哪怕放到唐诗中也是不可多得的。在他的时代，写美女情态、贵族生活又何尝不是一种创新，哪怕是当时的民歌也有类似的男女情意，二者是互相影响的。在《诫当阳公大心书》中他说：“立身之道，与文章异，立身先须谨重，文章且须放荡。”他的大部分诗符合一种诗作的精致，显然“放荡”二字也不是肆意的。

#+begin_quote
咏内人昼眠 萧纲

北窗聊就枕，南檐日未斜。攀钩落绮障，插捩举琵琶。

梦笑开娇靥，眠鬟压落花。簟文生玉腕，香汗浸红纱。

夫婿恒相伴，莫误是倡家。
#+end_quote

#+begin_quote
赋得入阶雨 萧纲

细雨阶前入，洒砌复沾帷。

渍花枝觉重，湿鸟羽飞迟。

傥令斜日照，并欲似游丝。
#+end_quote

#+begin_quote
采桑 萧纲

春色映空来，先发院边梅。细萍重叠长，新花历乱开。

连珂往淇上，接幰至丛台。丛台可怜妾，当窗望飞蝶。

忌趺行衫领，熨斗成褫襵。下床着珠佩，捉镜安花镊。

薄晚畏蚕饥，竞采春桑叶。寄语采桑伴，讶今春日短。

枝高攀不及，叶细笼难满。年年将使君，历乱遣相闻。

欲知琴里意，还赠锦中文。何当照梁日，还作入山云。

重门皆已闭，方知留客袂。可怜黄金络，复以青丝系。

必也为人时，谁令畏夫婿。
#+end_quote

#+begin_quote
雁门太守行 萧纲

轻霜中夜下，黄叶远辞枝。寒苦春难觉，边城秋易知。

风急旌旗断，涂长铠马疲。少解孙吴法，家本幽并儿。

非关买雁肉，徒劳皇甫规。
#+end_quote

#+begin_quote
江南曲 萧纲

阳春路，时使佳人度。枝中水上春并归，长杨扫地桃花飞。

清风吹人光照衣。光照衣，景将夕，掷黄金，留上客。
#+end_quote

最后一首参考[[https://zh.wikisource.org/wiki/藝文類聚/卷042][《艺文类聚・卷四十二・乐部二 乐府》]]，“长杨扫地”一作“长杨拂地”。

“宫体诗”之弊只在情感的柔靡无力，有血肉少骨筋，这与细腻敏感仅一线之隔却是天差地别，所以才华如萧纲可以这样写，别人写出便是废纸了。它在唐朝被批判，乃至近代同样被批判（比如闻一多先生），可以说是必然的，尺度的把握向来都是诗人最难也最不擅长的。

所谓“文如其人”，或许是句真话，但“诗如其人”则绝对是句假话。诗歌体裁和内容的不断演变就是在不断创造新的“诗中的我”，一旦有所穷尽必然迎来衰败，直到找到“新的我”，然后盛极一时，如此循环。“我”的建立第一次就在建安诗人身上，千百年往后时有创新，但万变不离其宗，我认为这就是诗歌的正统主流，唐诗的美就美在它不只是创造出了一个“我”，以数量论、以质量论、乃至以技术的创新论，都是顶峰。虽然，顶峰过后，岂无绝景。

#+begin_quote
石鼓歌 韩愈

张生手持石鼓文，劝我试作石鼓歌。少陵无人谪仙死，才薄将奈石鼓何。

周纲陵迟四海沸，宣王愤起挥天戈。大开明堂受朝贺，诸侯剑佩鸣相磨。

蒐于岐阳骋雄俊，万里禽兽皆遮罗。镌功勒成告万世，凿石作鼓隳嵯峨。

从臣才艺咸第一，拣选撰刻留山阿。雨淋日炙野火燎，鬼物守护烦㧑呵。

公从何处得纸本，毫发尽备无差讹。辞严义密读难晓，字体不类隶与科。

年深岂免有缺画，快剑斫断生蛟鼍。鸾翔凤翥众仙下，珊瑚碧树交枝柯。

金绳铁索锁钮壮，古鼎跃水龙腾梭。陋儒编诗不收入，二雅褊迫无委蛇。

孔子西行不到秦，掎摭星宿遗羲娥。嗟乎好古生苦晚，对此涕泪双滂沱。

忆昔初蒙博士征，其年始改称元和。故人从军在右辅，为我度量掘臼科。

濯冠沐浴告祭酒，如此至宝存岂多。毡包席裹可立致，十鼓只载数骆驼。

荐诸太庙比郜鼎，光价岂止百倍过。圣恩若许留太学，诸生讲解得切磋。

观经鸿都尚填咽，坐见举国来奔波。剜苔剔藓露节角，安置妥帖平不颇。

大厦深檐与盖覆，经历久远期无佗。中朝大官老于事，讵肯感激徒媕婀。

牧童敲火牛砺角，谁复著手为摩挲。日销月铄就埋没，六年西顾空吟哦。

羲之俗书趁姿媚，数纸尚可博白鹅。继周八代争战罢，无人收拾理则那。

方今太平日无事，柄任儒术崇丘轲。安能以此上论列，愿借辨口如悬河。

石鼓之歌止于此，呜呼吾意其蹉跎。
#+end_quote

欧阳修《集古录》云：石鼓文在岐阳，初不见称于世，至唐人始盛称之，而韦应物以为周文王之鼓，至宣王刻诗尔，韩退之直以为宣王之鼓，在今凤翔孔子庙。鼓有十，先时散弃于野，郑馀庆始置于庙，而亡其二。皇祐四年，向传师求于民间，得之，十鼓乃足。石鼓文可见者，其略曰：“我车既攻，我马既同。”又曰：“我车既好，我马既𫘦。君子员猎，员猎员游。麋鹿速速，君子之求。”又曰：“左骖幡幡，右骖騝騝。秀弓时射，麋豕孔庶。”又曰：“其鱼维何，维𫚈（左鱼右与）维鲤。何以橐之，维杨与柳。”

单论沉郁，韩愈可谓杜甫以后第一人，也只有他源于杜、出于杜。自刘长卿始，再加上杜甫，唐诗可谓“老气寒秋，白发连篇”，模仿者只学了杜甫的沉郁外貌，便连沉郁也没有学全。没有学全却也写尽了，香艳开始抬头，隐晦恶劣。韩愈沉郁，凝重肃穆，“诗中的我”如此鲜明却不仅仅只有一个我，所引发的共鸣让人沉郁之外更有一种激昂，所以《石鼓歌》是一首极适合起歌唱诵的诗歌。也只有起歌唱诵，读者才能真正进入这首诗作的意境。我想象的场景，是一个五音不全的老书生大清早站在自家门口磕磕绊绊、但偏偏极为投入地吟诵这首《石鼓歌》。

#+begin_quote
谒衡岳庙遂宿岳寺题门楼 韩愈

五岳祭秩皆三公，四方环镇嵩当中。火维地荒足妖怪，天假神柄专其雄。

喷云泄雾藏半腹，虽有绝顶谁能穷。我来正逢秋雨节，阴气晦昧无清风。

潜心默祷若有应，岂非正直能感通。须臾静扫众峰出，仰见突兀撑青空。

紫盖连延接天柱，石廪腾掷堆祝融。森然魄动下马拜，松柏一径趋灵宫。

粉墙丹柱动光彩，鬼物图画填青红。升阶伛偻荐脯酒，欲以菲薄明其衷。

庙令老人识神意，睢盱侦伺能鞠躬。手持杯珓导我掷，云此最吉余难同。

窜逐蛮荒幸不死，衣食才足甘长终。侯王将相望久绝，神纵欲福难为功。

夜投佛寺上高阁，星月掩映云朣朦。猿鸣钟动不知曙，杲杲寒日生于东。
#+end_quote

他并不能说是“以赋为诗”，纯以上面两首诗论，应该是“以文为诗”，其中的区别尤其体现在诗句中更多透露出了那种文的自在，不是散漫，而是自在，这是赋、是诗都有所不及的。自在但又纤细，写景抒情钜细靡遗，比兴巧妙，这三者缺了任何一种就落入下成。确实，韩愈有很多诗作都用上了这类手法，同样优秀的再比如《八月十五日夜赠张功曹》。但是这并不是说只能做到如此，当他时而抛却后写出的作品，你会发现在遣词造句、在选景用意古今几无与他相似之人。其中尺度把握之妙直让人惊叹，但凡稍偏半分便落入奇诡，可算夺人眼球的佳作，但是现在，现在不可能仅仅用“以文为诗”四字去概况。这种情况是诗作大家所共有的特征，但凡真正的大家，都是不可能三言两语可以概况的，要去概况就总觉得不对劲。

我认为，韩愈对尺度的把握高明之处在两个地方，第一在“以文为诗”，第二在“选景写景”。需要注意的，几乎所有的大诗人都会在“选景写景”上倾注大量的精力，可往往又将之当作配角而非主题，他们每个人的理解不是一致的，他们尺度的把握更是不同的，阅读朗诵不妨从这个方向多加留意。

#+begin_quote
山石 韩愈

山石荦确行径微，黄昏到寺蝙蝠飞。升堂坐阶新雨足，芭蕉叶大栀子肥。

僧言古壁佛画好，以火来照所见稀。铺床拂席置羹饭，疏粝亦足饱我饥。

夜深静卧百虫绝，清月出岭光入扉。天明独去无道路，出入高下穷烟霏。

山红涧碧纷烂漫，时见松枥皆十围。当流赤足蹋涧石，水声激激风吹衣。

人生如此自可乐，岂必局束为人鞿？嗟哉吾党二三子，安得至老不更归。
#+end_quote

两三百年后北宋的黄庭坚写下《松风阁》，写景选景布置皆是不及，唯有其情相通，当然如果再以书法论，那么《松风阁诗帖》也是天下一绝（如果一定要有一个标准，行书第一颜真卿《争座位帖》、《祭侄文稿》，第二苏轼《黄州寒食诗帖》，第三王羲之信札行书，第四《松风阁诗帖》）。

《山石》一首可称韩愈诗作第一。在他诗作中普遍出现的特征，一个是意境上的“黄昏”，一个是诗作本身所表现的“清新”。“黄昏”也许还好理解，什么是“清新”？清，借用陶渊明《归去来兮辞》中的一句就是“临清流而赋诗”；新，也借用《尚书・胤征》中的一句“旧染污俗，咸与唯新”，这里的新在景、在意、在体裁与手法与文字。“清新”二字同样体现在他的文当中，甚至比诗作更加酣畅。事实上，若非做到了“清新”，那么谁都不能称作“大家”。《山石》全篇弥漫着诗人的情绪，但他就是不直白说出口，哪怕最后四句其实也是侧面的表达，不是诗人自己创作时的情绪。由此营造的，诗中句句有诗人自己，诗中句句找不到一点是写自己，它的景仿佛一篇游记，就好像单纯就是游记。这种手法的另一个极端，王安石《游褒禅山记》，句句有王安石自己，句句也写王安石自己，因为他最需要表达的是一个独特的思考，所以一切服从于这样一个思考，它是一篇游记，但根本不是游记。

在唐诗以后，如果纯以宋诗论，会发现一大批“文章诗”，这种风气的开端就在韩愈身上（尤其体现在《南山诗》、《谢自然诗》等），其中最优秀的作品展现出的是一种理性与辨证之美，而非纯粹声色滋味之美。七古是个绝佳的场地，可以比肩的，首推李白。但这是两种完全不同类型的诗，都是议论、写景，可本质上韩愈乃是学者风范，李白则性情天然。唯一的问题，韩愈有时写诗太长太芜杂，往往极好的写景夹杂在“平平无奇”当中，这是“文章诗”的一大弊端，宋诗也一并承袭了。最劣，比如《落齿诗》、《赠刘师命》，落齿之苦恐怕让韩愈写诗都不能思考了。可李白，李白写诗不讲技巧，直抒胸臆，尤其对民歌（比如南北朝时期的《子夜四时歌》）进行了前所未有、后亦不曾见的改造，可称化境。他是《诗经》的直接继承者，所以李白的诗越长越优秀，可谓多多益善。求仙，亦或对仙人生活的向往，对李白影响极大，至少：1、清新；2、更有意境上的丰富，是仙气。但凡写景必往大处、高处开始，还有“以赋为诗”之实，但不同于“初唐四杰”及其模仿者，因为夹杂对民歌的运用，便让人感觉这首诗自然如此，不这样反而不行。单以“赋”论，其实是另类的，从“赋”着手理解也是不全的，不如从对民歌的理解开始。

在七古、五古之外，韩愈对七绝的擅长就在他对写景选景的擅长上，试举例几首，实际看有数十首皆是上佳，水平发挥极为稳定。大诗人，稳居一流的大诗人。

#+begin_quote
闻梨花发赠刘师命 韩愈

桃蹊惆怅不能过，红艳纷纷落地多。

闻道郭西千树雪，欲将君去醉如何。
#+end_quote

#+begin_quote
梨花下赠刘师命 韩愈

洛阳城外清明节，百花寥落梨花发。

今日相逢瘴海头，共惊烂漫开正月。
#+end_quote

#+begin_quote
晚春 韩愈

草树知春不久归，百般红紫斗芳菲。

杨花榆荚无才思，惟解漫天作雪飞。
#+end_quote

#+begin_quote
早春呈水部张十八员外 其一 韩愈

天街小雨润如酥，草色遥看近却无。

最是一年春好处，绝胜烟柳满皇都。
#+end_quote

骆宾王《畴昔篇》鸿篇巨制，更在《帝京篇》之上，写景选景并算出彩，但这是一篇极佳的议论诗赋。他曾说：“夫在心为志，发言为诗。诗有不得尽言，言不得尽意。”按照这个说法，那么骆宾王写《畴昔篇》时一定是五味杂陈，自己也恐怕难明白自己到底什么意，但又偏偏在心中那般深刻。所以写下以后，诗中空间时间交错，铿锵可咏，居然还一点不让人感到凌乱。议论好，抒情好，议论与抒情选择的对象也好，真是一篇好诗作，可惜实在太长的，如果能稍稍分割一下，成组诗那就更好了。《畴昔篇》现在这样，是一首适合放在某某诗歌鉴赏书当中最后一页的作品，它的好并不是所有人都能欣赏的。但仅此一首，我认为骆宾王现在的历史地位还是被低估了，尤其这种时空与场景的转换极为罕见。这里留一个原文[[https://so.gushiwen.cn/shiwenv_64dc973df8e3.aspx][链接]]。

#+begin_quote
从军中行路难 其一 骆宾王

君不见封狐雄虺自成群，冯深负固结妖氛。

玉玺分兵征恶少，金坛受律动_一作劝 将军。将军拥旄宣庙略，战士横行_一作戈 静夷落。

长驱一息背铜梁，直指三巴登剑阁。阁道岧峣起戍楼，剑门遥裔俯灵丘。

邛关九折无平路，江水双源有急流。

征役无期返，他乡岁华晚。杳杳丘陵出，苍苍林薄远。

途危紫盖峰，路涩青泥坂。去去指哀牢，行行入不毛。

绝壁千里_一作重 险，连山四望高。中外分区宇，夷夏殊风土。

交趾枕南荒，昆弥临北户。川原绕_一作饶 毒雾，溪谷多淫雨。

行潦四时流，崩查千岁古。

漂梗飞蓬不自安，扪藤引葛度危峦。昔时闻道从军乐，今日方知行路难。

苍江绿水东流驶，炎洲丹徼南中地。南中南斗映星河，秦川秦塞阻烟波。

三春边地风光少，五月泸中瘴疠多。

朝驱疲斥候，夕息倦樵歌。向月弯繁弱，连星转太阿。

重义轻生怀一顾，东伐西征凡几度。夜夜朝朝斑鬓新，年年岁岁戎衣故。

灞城隅，滇池水，天涯望转积，地际行无已。 

徒觉炎凉节物非，不知关山千万里。

弃置勿重陈，征行多苦辛。且悦清笳杨柳曲，讵忆芳园桃李人。

绛节朱旗分白羽，丹心白刃酬明主。但令一被君王知，谁惮三边征战苦。

行路难_一本下有行路难岐路字 ，几千端。无复归云凭短翰，空馀望日想长安。
#+end_quote

#+begin_quote
从军中行路难 其二 骆宾王

君不见玉关尘色暗边庭，铜鞮杂虏寇长城。天子按剑征馀勇，将军受脤事横行。

七德龙韬开玉帐，千里鼍鼓垒_一作干重龟垒动 金钲。阴山苦雾埋高垒，交河孤月照连营。

连营去去无穷极，拥旆遥遥过绝国。阵云朝结晦天山，寒沙夕涨迷疏勒。

龙鳞水上开鱼贯，马首山前振雕翼。长驱万里詟祁连，分麾三命武功宣。

百发乌号遥碎柳，七尺龙文迥照莲。春来秋去移灰琯，兰闺柳市芳尘断。

雁门迢递尺书稀，鸳被相思双带缓。行路难，行路难，誓令氛祲静皋兰。

但使封侯龙额贵，讵随中妇凤楼寒。
#+end_quote

两首《从军中行路难》应是骆宾王除了《畴昔篇》、《帝京篇》外最优秀的作品，有说这两首是辛常伯写的，还有说是辛常伯与骆宾王一起写的。我无从考证，但辛常伯除此之外连一首都没留下来，所以我更倾向就是骆宾王自己写的。类似的诗意，比如在《从军行》中，他也写：“平生一顾重，意气溢三军。野日分戈影，天星合剑文。弓弦抱汉月，马足践胡尘。不求生入塞，唯当死报君。”而在文章方面，《代李敬业讨武氏檄》是诗人意气达到了一个巅峰，只有当他的意气被兵败消磨殆尽，他的创作生涯也就基本告终了。

#+begin_quote
宋考功（即宋之问）以事累贬黜，后放还，至江南，游灵隐寺。夜月极明，在长廊吟行，且为诗曰：“鹫岭郁岧峣，龙宫隐寂寥。”第二联搜奇思，终不如意。有老僧点长明灯，座大禅状，问曰：“少年夜夕久不寐，而吟讽甚苦，何邪？”之问答曰：“弟子业诗，适偶欲题此寺，而兴思不属。”僧曰：“试吟上联。”即吟与听之。再三吟讽，因曰：“何不云‘楼观沧海日，门听浙江潮。’”之问愕然，讶其遒丽。又续终篇曰：“桂子月中落，天香云外飘。扪萝登塔远，刳木取泉遥。霜薄花更发，冰轻叶未凋。待入天台路，看余度石桥。”僧所赠句，乃为一篇之警策。迟明更访之，则不复见矣。寺僧有知者，曰：“此骆宾王也。”之问诘之，曰：“当敬业之败，与宾王俱逃，捕之不获。将帅虑失大魁，得不测罪，时死者数万人，因求戮类二人者，函首以献。”后虽知不死，不敢捕送，故敬业得为衡山僧，年九十余乃卒。宾王亦落发，遍游名山，至灵隐，以周岁卒。当时虽败，且以匡复为名，故人多获脱之。
#+end_quote

这段是我从《唐人轶事汇编・卷七》里摘下来的，故事流传可以说极广的，但真假恐怕还有的说。无论如何，从骆宾王给出的两句可知其人才情此时依旧，但落发的骆宾王已无心气，只有句没有诗了。他的五律比五言、七言杂体诗差了一筹不止，如上所说，骆宾王是位极擅议论抒情的诗人，但他的写景选景比较地说就差了，五律、七律、五绝、七绝尤其讲究一个“景”字，算是一个短处吧。到了晚年，“楼观沧海日，门听浙江潮”如果真是他写的，那么此消彼长，议论抒情没有了，写景选景功夫厉害了，这两句在他的所有诗作中比都是极佳的。这里还不得不提他七岁时候的作品，那首《咏鹅》也是写景选景极为上佳的天才作品，所以骆宾王是个很有意思的人，他不是不会写景，而是选择的，若到了旁人身上，恐怕有一样都是幸运的了。

#+begin_quote
叙寄员半千 骆宾王

薄宦三河道，自负十馀年。不应惊若厉，只为直如弦。 

坐历山川险，吁嗟陵谷迁。长吟空抱膝，短翮讵冲天。 

魂归沧海上，望断白云前。钓名劳拾紫，隐迹自谈玄。 

不学多能圣，徒思鸿宝仙。斯志良难已，此道岂徒然。 

嗟为刀笔吏，耻从绳墨牵。岐路情虽狎，人伦地本偏。 

长揖谢时事，独往访林泉。寄言二三子，生死不来旋。
#+end_quote

#+begin_quote
在狱咏蝉 骆宾王

西陆蝉声唱，南冠客思侵。那堪玄鬓影，来对白头吟。

露重飞难进，风多响易沉。无人信高洁，谁为表予心。
#+end_quote

并序：余禁所禁垣西，是法厅事也，有古槐数株焉。虽生意可知，同殷仲文之古树；而听讼斯在，即周召伯之甘棠，每至夕照低阴，秋蝉疏引，发声幽息，有切尝闻。岂人心异于曩时，将虫响悲于前听。嗟乎！声以动容，德以象贤。故洁其身也，禀君子达人之高行；蜕其皮也，有仙都羽化之灵姿。候时而来，顺阴阳之数； 应节为变，审藏用之机。有目斯开，不以道昏而昧其视；有翼自薄，不以俗厚而易其真。吟乔树之微风，韵姿天纵； 饮高秋之坠露，清畏人知。仆失路艰虞，遭时徽纆。不哀伤而自怨，未摇落而先衰。闻蟪蛄之流声，悟平反之已奏；见螳螂之抱影，怯危机之未安。感而缀诗，贻诸知己。庶情沿物应，哀弱羽之飘零；道寄人知，悯余声之寂寞。非谓文墨，取代幽忧云尔。

骆宾王之议论抒情，从《在狱咏蝉》一首中可以体现淋漓尽致，并非无景，而是他选择议论。

#+begin_quote
久客临海有怀 骆宾王

天涯非日观，地屺望星楼。练光摇乱马，剑气上连牛。

草湿姑苏夕，叶下洞庭秋。欲知凄断意，江上涉安流。
#+end_quote

#+begin_quote
送郭少府探得忧字 骆宾王

开筵枕德水，辍棹舣仙舟。贝阙桃花浪，龙门竹箭流。 

当歌凄别曲，对酒泣离忧。还望青门外，空见白云浮。
#+end_quote

#+begin_quote
于易水送人 骆宾王

此地别燕丹，壮士发冲冠。昔时人已没，今日水犹寒。
#+end_quote

一般来说诗作中多多少少都能体现出一个“诗中的我”，甚至有人会认为写诗本身就是为了追求这个“诗中的我”，但这是一个错觉，这是一件极为奢侈的事情，而不是什么理所当然。倒不是说它有多么难，而是被写诗的目的所主导了，乃至诗人本人就是被其他人所约束的，由此诗人甚至特地去伪装、磨灭“诗中的我”，以免有额外的影响。所以，“诗中的我”第一次明确被建立是建安诗人，更确切地说就是曹操，在他这个位置，写诗的目的与建立“诗中的我”是没有冲突的，或者说在一个大方向上还是有助益的。

南北朝时期有一首极为优秀的乐府诗，《木兰辞》，诗中人物的形象如此鲜活，传唱千古，但是这里需要有一个区分。诗所描述的人物形象鲜活并不等于诗所表现的“我”就是鲜活的，个人之见，虽有建安诗人、魏晋风流在前，南北朝的《木兰辞》依旧是一首没有“诗中的我”的乐府诗。“诗中的我”以诗歌总量比较，其实是小众的。如果在建安以前继续上溯，一直到诗经的时代，我依旧感觉不到“诗中的我”存在，但每每阅读、每每吟诵，眼前便仿佛站着的不是一个人，不是一个“我”，而是无数“我们”。所以《诗经》所营造的，比如《无衣》、《硕鼠》、《关雎》、《氓》等等等等，是“诗中的我们”。这个“诗中的我们”广泛存在于佚名的古诗及民歌当中，便是《木兰辞》这般，所表现出来的其实是“诗中的我们”。再进一步，李白的伟大之处，他对民歌的运用很大程度，就在他将“诗中的我们”与“诗中的我”极为完美地结合起来，他的诗带着极为鲜明的“诗中的我”，但也让人感受到“诗中的我们”，从而产生一种自发的共鸣。这点，不是天纵奇材是什么！

没有“诗中的我们”，没有“诗中的我”，诗作只能以句为胜，大多写不长，其中也有优秀的作品，大诗人。在唐诗的初期，张说有着一大批“奉和圣制”、“侍宴”、“送赠”作品，这些诗作本身就有极为优秀的，除此之外贬谪时还有许多写景与抒情相互糅合的佳作。“清新”二字，张说当之无愧，尤其擅长五言，擅长山水。或许，会有人觉得贬谪以后作品比之前的要好一筹，我不以为然，因为之后的作品张说也犯了诗人的一个通病，他的尺度把握有些失控了，所以有一部分反而不如从前。纯以作品论，至少那时诗人是乐在其中的，也是有控制力的，而他诗歌才情从始至终没有消减，这点尤其难能可贵。

#+begin_quote
清明日诏宴宁王山池赋得飞字 张说

今日清明宴，佳境惜芳菲。摇扬花杂下，娇啭莺乱飞。

绿渚传歌榜，红桥度舞旂。和风偏应律，细雨不沾衣。 

承恩如改火，春去春来归。
#+end_quote

#+begin_quote
四月十三日诏宴宁王亭子赋得好字 张说

何许承恩宴，山亭风日好。绿嫩鸣鹤洲，阴秾斗鸡道。 

果思夏来茂，花嫌春去早。行乐无限时，皇情及芳草。
#+end_quote

#+begin_quote
送王光庭 张说

同居洛阳陌，经日懒相求。及尔江湖去，言别怅悠悠。

楚云眇羁翼，海月倦行舟。爱而不可见，徒嗟芳岁流。
#+end_quote

#+begin_quote
南中赠高六戬 张说

北极辞明代，南溟宅放臣。丹诚由义尽，白发带愁新。 

鸟坠炎洲气，花飞洛水春。平生歌舞席，谁忆不归人。
#+end_quote

#+begin_quote
入海 其一 张说

乘桴入南海，海旷不可临。茫茫失方面，混混如凝阴。 

云山相出没，天地互浮沉。万里无涯际，云何测广深。 

潮波自盈缩，安得会虚心。 
#+end_quote

#+begin_quote
游灉湖上寺 张说

湖上奇峰积，山中芳树春。何知绝世境，来遇赏心人。

清旧岩前乐，呦嘤鸟兽驯。静言观听里，万法自成轮。
#+end_quote

#+begin_quote
过蜀道山 张说

我行春三月，山中百花开。披林入峭蒨，攀登陟崔嵬。 

白云半峰起，清江出峡来。谁知高深意，缅邈心幽哉。
#+end_quote

#+begin_quote
山夜闻钟 张说

夜卧闻夜钟，夜静山更响。霜风吹寒月，窈窕虚中上。

前声既舂容，后声复晃荡。听之如可见，寻之定无像。

信知本际空，徒挂生灭想。
#+end_quote

或许，有人会说，唐诗山水与六朝山水何异？都是山水，为什么张说的山水及其更后来者就是“清新”？更重要的，“新”从何来？试以上官仪当宰相时的五绝，《入朝洛堤步月》为例。诗曰：“脉脉广川流，驱马历长洲。鹊飞山月曙，蝉噪野风秋。”诗好吗？的确不差，但比张说恐怕差了一筹不止，上官仪的诗依旧是六朝风范。六朝山水诗，他们并未形成一整套雅致的选景用词体系（好的地方在常有惊人之语，不流俗），“宜诗”的语言是无意识的，就好比一个粗胚尤待打磨锤炼，这是其一。其二，所谓“宜诗宜画”，六朝山水诗在选景布置上是有缺陷的，常常将几个意象硬生生拼凑在了一起，却不管它们是否契合。但是，历代题画诗整体上都要好于非题画诗（自唐以后），为什么？因为非题画诗带来了太多意象上的空白和不协调，张说的山水诗就已经有了“入画”的迹象。更进一步，山水诗其实也是一种意境诗，并非纯粹为景而写景，是一种“意”布置了“景”，“景”衬托出“意”。六朝山水诗是意境诗，但他们的意是静止的，他们的景是没有时间概念的，也就是说纯粹景的意象的组合。而在唐朝，山水动了，意境动了，以致于真正高明的诗人所呈现出来的，“意”与“景”分不清谁是谁的附庸，谁又呈现出谁，山水即意，意即山水——究竟意动山水动，还是山水动意动？在这里，王维将它发扬光大，运用自如，天才。孟浩然则稍逊一筹，并非差在写景，是在“意”上，牢骚愁肠的更好一些。

什么是意境的表达？什么是“宜诗”的语言？在我看来，每一首诗首先是文字的表达，但这种表达再想用另外的文字同义表达便会感到千难万难，左右都不合适，古诗意境之妙就在这里。它的表达或许不是文字最美的、修辞技艺高超的，但它一定是最契合诗人本意的，以至于再难有第二种形容，这是文字的魅力所在。但它也带来同等恶劣的影响，因为模仿，因为从群，一个“好的词汇”用在其他人其他地方至少是可以添色的，所以会出现“老气寒秋，白发连篇”，但其实这些美丽的字词是最不符合诗人自身的。在唐朝，诗人的地位可以说是古今以来最高的，他们最坏的处境也至少是衣食无忧，基本大小都有一个官身，哪来那么多愁肠！若说他们家国情怀，感伤所以愁，可字里行间偏偏让人只看见年纪轻轻强说愁。所以诗歌其实是一个萝卜一个坑，我用得你便用不得了，最讲究创新，不创新，诗歌就是死的。

这里离题插一首，若是愁绪如此，那么也是极佳的，古今这类诗作杰出者很多。好在何处？愁绪不在我而我忧患，是一种责任的担当，“诗中的我”非但不让人腻烦，反而让人感触良多，曲中所述之意加强了这种情绪的发酵。至于《谪仙怨》，后来人怀疑本就是有调无词的，书上说唐玄宗“洞晓音律，制作诸曲，随意即成”，到现在这调恐怕也没有留下。

#+begin_quote
广谪仙怨 窦弘余

并序：天宝十五载正月，安禄山反，陷没洛阳。王师败绩，关门不守。车驾幸蜀，途次马嵬驿，六军不发，赐贵妃自尽，然后驾行。次骆谷，上登高下马，望秦川，遥辞陵庙，再拜，呜咽流涕，左右皆泣。谓力士曰：“吾听九龄之言，不到于此。”乃命中使往韶州，以太牢祭之。因上马索长笛，吹笛，曲成，潸然流涕，伫立久之。时有司旋录成谱，及銮驾至成都，乃进此谱，请名曲。帝谓：“吾因思九龄，亦别有意，可名此曲为《谪仙怨》。”其旨属马嵬之事。厥后以乱离隔绝，有人自西川传得者，无由知，但呼为《剑南神曲》。其音怨切，诸曲莫比。大历中，江南人盛为此曲。随州刺史刘长卿左迁睦州司马，祖筵之内，长卿遂撰其词。吹之为曲，意颇自得，盖亦不知本事。余既备知，聊因暇日撰其辞，复命乐工唱之，用广其不知者。

胡尘犯阙冲关，金辂提携玉颜。云雨此时萧散，君王何日归还。

伤心朝恨暮恨，回首千山万山。独望天边初月，蛾眉犹自弯弯。
#+end_quote

杨贵妃之死，一个有趣的切入点，在当时、在后世都有很多诗人诗作，但基本都作为一种讽喻的对象，写尽了贵妃之死，主旨却从来没有在她身上。这何尝不是一种弄巧成拙，何尝不是一种模仿的重复。

回到山水，再举例几首杨素的诗，最少能得一个“清”字。杨素的诗是有控制力的，区别于风流后的疏狂，乃至带上了几分自我轻纵的意思，他的诗清朗平直，颇得雅意。可惜，可惜他流传下来太少了，也可能是因为杨素自己都没把自己当作一个真正的诗人。

#+begin_quote
赠薛内史 杨素

耿耿不能寐，京洛久离群。横琴还独坐，停杯遂待君。

待君春草歇，独坐秋风发。朝朝唯落花，夜夜空明月。

明月徒流光，落花空自芳。别离望南浦，相思在汉阳。

汉阳隔陇吟，南浦达桂林。山川虽未远，无由得寄音。
#+end_quote

#+begin_quote
山斋独坐赠薛内史 其一 杨素

居山四望阻，风云竟朝夕。深溪横古树，空岩卧幽石。

日出远岫明，鸟散空林寂。兰庭动幽气，竹室生虚白。

落花入户飞，细草当阶积。桂酒徒盈樽，故人不在席。

日落山之幽，临风望羽客。
#+end_quote

#+begin_quote
出塞 其一 杨素

漠南胡未空，汉将复临戎。飞狐出塞北，碣石指辽东。

冠军临瀚海，长平翼大风。云横虎落阵，气抱龙城虹。

横行万里外，胡运百年穷。兵寝星芒落，战解月轮空。

严鐎息夜斗，骍角罢鸣弓。北风嘶朔马，胡霜切塞鸿。

休明大道暨，幽荒日用同。方就长安邸，来谒建章宫。
#+end_quote

要了解陈子昂，可以从一篇小文章开始。在《与东方左史虬修竹篇・并书》中，他说：“东方公足下：文章道弊，五百年矣。汉魏风骨，晋宋莫传，然而文献有可征者。仆尝暇时观齐梁间诗，彩丽竞繁，而兴寄都绝，每以永叹。思古人，常恐逦逶颓靡，风雅不作，以耿耿也。一昨于解三处，见明公《咏孤桐篇》，骨气端翔，音情顿挫，光英朗练，有金石声。遂用洗心饰视，发挥幽郁。不图正始之音，复睹于兹，可使建安作者，相视而笑。解君云，张茂先、何敬祖，东方生与其比肩。仆亦以为知言也。故感叹雅制，作《修竹诗》一首，当有知音以传示之。”

《咏孤桐篇》今已失传，《修竹篇》留了下来，它最有价值的部分是上面这段文字。陈子昂是个历史地位十分特殊的诗人，有人觉得从他开始唐诗才与前代有所切割成真正的唐诗，所以誉为“唐诗奠基人”。这未免过誉了，奠定唐诗的基础并做到于前代有所切割的，至少有四人：张说与宋之问，陈子昂与张九龄。而且这也只是不严谨地举例而已，没有卢照邻，没有骆宾王，还可以再加上李峤（可惜太多太多应制诗作）、上官仪、沈佺期、乔知之等人，那么也是不完整的。可是，所有这些人，在任何一本、乃至一篇介绍唐诗初期的书里、文章里独独最不可缺的，恐怕还是陈子昂一人。这里面有他那篇几乎所有中国人一看就知道的作品的原因，这个放在后面说，但更重要的是他如此鲜明的观点，所找到的路正是唐诗大趋势所走的路。

他的诗作不能与唐诗站在顶峰的那几个人比，就是抒情恐怕也略逊张九龄，只是得了沉郁二字的情，缺少了沉郁二字的意。要做一个比喻，那么陈子昂可谓“初唐老杜”。要欣赏他的诗作，我意最好抛却从历史角度对他的所有评价，那么陈子昂可以说是一位杰出诗人。

#+begin_quote
送客 陈子昂

故人洞庭去，杨柳春风生。相送河洲晚，苍茫别思盈。

白蘋已堪把，绿芷复含荣。江南多桂树，归客赠生平。
#+end_quote

#+begin_quote
感遇 陈子昂

兰若生春夏，芊蔚何青青。幽独空林色，朱蕤冒紫茎。

迟迟白日晚，袅袅秋风生。岁华尽摇落，芳意竟何成。
#+end_quote

#+begin_quote
感遇 陈子昂

苍苍丁零塞，今古缅荒途。亭堠何摧兀，暴骨无全躯。

黄沙幕南起，白日隐西隅。汉甲三十万，曾以事匈奴。

但见沙场死，谁怜塞上孤。
#+end_quote

#+begin_quote
答洛阳主人 陈子昂

平生白云志，早爱赤松游。事亲恨未立，从宦此中州。

主人亦何问，旅客非悠悠。方谒明天子，清宴奉良筹。

再取连城璧，三陟平津侯。不然拂衣去，归从海上鸥。

宁随当代子，倾侧且沉浮。
#+end_quote

#+begin_quote
登幽州台歌 陈子昂

前不见古人，后不见来者。念天地之悠悠，独怆然而涕下。
#+end_quote

“悠悠”二字乃是陈子昂的特色，在几篇诗作中他都有使用。《登幽州台歌》一首，以后世的认识看是绝佳的极上品，但以诗人他自己的眼光看恐怕未必，平常作。这里尤其误导的，在对“古人”二字的认识上，我们以为的“古人”那就是古人，是历史上所有的人。但诗人自己认为的“古人”，恐怕是指更古时那些礼贤下士的明君明主，他是在感慨自己怀才不遇。其中区别太大，因为少却了那份对生命的沧桑感，至少在诗人自己是没有的。所以我前面说陈子昂有沉郁的情，没有沉郁的意。说到这里，或许有对诗人贬低的嫌疑，因为随陈子昂一起的还有一种新的体裁的流行，即怀古。这并非陈子昂无意间的创新，而是有意识的，除了上面举例的，还有比如《登泽州城北楼宴》等等，并非个例。

要在文字中找寻真正的沧桑，古诗是有极限的，尤其缺乏的是一种文字的酝酿，往往限于字数和段落一开始就完全展开了，所以不如先在更早期的辞赋中寻找。《楚辞》当中屈原的《远游》说：“惟天地之无穷兮，哀人生之长勤。往者余弗及兮，来者吾不闻。”我认为这是最贴切的表达，全篇极为精彩，可惜太长，这里就不列出来了。再者，比如贾谊的《鵩鸟赋》说：“且夫天地为炉兮，造化为工；阴阳为炭兮，万物为铜。”同样精彩。请注意，这里的精彩莫被句子本身的精彩所蒙蔽，需要注意到全篇的气息运动，这里所表现出来的精彩才是真正的精彩，这里的精彩才是文字的酝酿，古诗所缺乏的。

#+begin_quote
鵩鸟赋 贾谊

谊为长沙王傅三年，有鵩飞入谊舍，止于坐隅。鵩似鸮，不祥鸟也。谊即以谪居长沙，长沙卑湿，谊自伤悼，以为寿不得长，乃为赋以自广。其辞曰：

单阏之岁兮，四月孟夏，庚子日斜兮，鵩集予舍。止于坐隅兮，貌甚闲暇。异物来萃兮，私怪其故。发书占之兮，谶言其度，曰：“野鸟入室兮，主人将去。” 请问于鵩兮，予去何之？吉乎告我，凶言其灾。淹速之度兮，语予其期。鵩乃叹息，举首奋翼，口不能言，请对以臆：

“万物变化兮，固无休息。斡流而迁兮，或推而还。形气转续兮，变化而蟺。沕穆无穷兮，胡可胜言！祸兮福所倚，福兮祸所伏；忧喜聚门兮，吉凶同域。彼吴强大兮，夫差以败；越栖会稽兮，勾践霸世。斯游遂成兮，卒被五刑；傅说胥靡兮，乃相武丁。夫祸之与福兮，何异纠纆；命不可说兮，孰知其极！水激则旱兮，矢激则远；万物回薄兮，振荡相转。云蒸雨降兮，纠错相纷；大钧播物兮，坱圠无垠。天不可预虑兮，道不可预谋；迟速有命兮，焉识其时。

且夫天地为炉兮，造化为工；阴阳为炭兮，万物为铜。合散消息兮，安有常则？千变万化兮，未始有极，忽然为人兮，何足控抟；化为异物兮，又何足患！小智自私兮，贱彼贵我；达人大观兮，物无不可。贪夫殉财兮，烈士殉名。夸者死权兮，品庶每生。怵迫之徒兮，或趋西东；大人不曲兮，意变齐同。愚士系俗兮，窘若囚拘；至人遗物兮，独与道俱。众人惑惑兮，好恶积亿；真人恬漠兮，独与道息。释智遗形兮，超然自丧；寥廓忽荒兮，与道翱翔。乘流则逝兮，得坻则止；纵躯委命兮，不私与己。其生兮若浮，其死兮若休；澹乎若深渊之静，泛乎若不系之舟。不以生故自宝兮，养空而浮；德人无累兮，知命不忧。细故蒂芥兮，何足以疑！”
#+end_quote

盛唐诗作如果少了李颀的五古、七古是不完整的。为什么这么说？人们下意识地以为，一个盛世，生活其下的诗人必然有着盛世的诗作。但事实则是相反的，如果看多了唐诗，又或找本《唐诗选》去看，那么就会产生一种错觉，所谓盛唐其实是残唐，所谓盛世其实是乱世。盛世是难能可贵的，能够描写盛世、有着盛世气象的诗人是更稀缺的，唐朝的幸运在于它拥有了不止一个、两个盛世的诗人。他们为什么不写盛世，为什么偏偏要把愁闷混在字里行间？远远早于唐朝，诗作文学就已经开始类艺术化了，它不只是一种瞬间情感发泄的工具，是苦心造诣，是有意而为之。所以问题的原因并非在于他们不想写，他们没有能力写，亦或他们没有这个意识去写，而在于“艺术化”从一开始也并不等于“美”，不等于“好”，不等于“善”。“艺术”是使某某对象成为艺术品的方式，它没有这个惯性就一定要产生“美”、甚至等于“美”。它所呈现出来的只需要有一个意义，人的意义，而人的意义在折磨中永远要比在享受中更能得到体现（这里产生了上面说的那种沧桑感，不妨回味《远游》，也不能继续说下去，不然就离题了）。古人又说“哀而不伤”是一种高境界，它所体现出来的是更能体现人的意义，但它的底色从始至终都是“哀”。所以，能够描写盛世，盛世的诗人，他至少要跨越上述所有难题，达到一个更高的境界，恰如盛世难得，盛世的诗人也是诗作世界里的大治。可以说，有着盛世的诗篇他一定是大诗人，但大诗人并不一定就有盛世的诗篇。

#+begin_quote
赠张旭 李颀

张公性嗜酒，豁达无所营。皓首穷草隶，时称太湖精。

露顶据胡床，长叫三五声。兴来洒素壁，挥笔如流星。

下舍风萧条，寒草满户庭。问家何所有，生事如浮萍。

左手持蟹螯，右手执丹经。瞪目视霄汉，不知醉与醒。

诸宾且方坐，旭日临东城。荷叶裹江鱼，白瓯贮香粳。

微禄心不屑，放神于八纮。时人不识者，即是安期生。
#+end_quote

#+begin_quote
别梁锽 李颀

梁生倜傥心不羁，途穷气盖长安儿。回头转眄似雕鹗，有志飞鸣人岂知。

虽云四十无禄位，曾与大军掌书记。抗辞请刃诛部曲，作色论兵犯二帅。

一言不合龙额侯，击剑拂衣从此弃。朝朝饮酒黄公垆，脱帽露顶争叫呼。

庭中犊鼻昔尝挂，怀里琅玕今在无。时人见子多落魄，共笑狂歌非远图。

忽然遣跃紫骝马，还是昂藏一丈夫。洛阳城头晓霜白，层冰峨峨满川泽。

但闻行路吟新诗，不叹举家无担石。莫言贫贱长可欺，覆篑成山当有时。

莫言富贵长可托，木槿朝看暮还落。不见古时塞上翁，倚伏由来任天作。

去去沧波勿复陈，五湖三江愁杀人。
#+end_quote

李颀的一生，位卑才高，失意豁达，终其一生最高也是一个县尉，最后还辞职了。乍看之下，如何能说盛世的诗作，反而让人生出一种悲慨。这是读者的第一感受，然后？李颀的五古与七古几乎每一首都有一个人，他写的每一个人就好像那个人就在眼前：其一他的选景和写景能力一流，但并不喧宾夺主，始终控制在服务于人物描写上；其二他写的人本人就有极为鲜明的个性，豪放不羁，尤其着重写出了他们正直、倔傲、洒脱的性格，一吐心中所有的块垒。他的诗是让人畅快淋漓的诗，他写的人是让人憧憬钦佩的人，而所有这些仿佛活生生的人就生活在那个年代，包括李颀，即便是千年以后的我们还能读到、感受到，而我相信再过千年也不会改变。

李颀的诗还玄妙在“诗中的我”，或许是他写人的本事实在太好太稳了，每一首五古和七古几乎没有劣作，由此“诗中的我”的形象反而被掩盖下来，“诗中的人”的形象占据了全篇。但越是如此，越是难以从单篇找到“诗中的我”，就越能从整卷的诗集中找到“诗中的我”。无论诗人有意或者无意，李颀是一位能够在上百首诗的诗集中找到单一形象、并且形象鲜明的“诗中的我”的大诗人。常人营造意境，能得一句已经优秀，有一篇诗作那就算难的了，而想在诗集中（尤其在并非自己拟定的诗集中）营造意境几乎难以想象，甚至，再有狂语，要造一生意境？我不知这算称赞还是贬低。李颀“诗中的我”形象其实十分简单，简单到纯粹，而且与他诗中的每一个人都气味相投，尤其显得可爱。

明朝的胡应麟在《诗薮》中说：“古诗窘于格调，近体束于声律，惟歌行大小短长，错综阖辟，素无定体，故极能发人才思。”歌行之盛，盛在盛唐，这并非偶然，因为要克服“窘于格调”的缺点。什么是“格调”？在这里应该指的是浅抒情、泛写景，最后才是律韵的问题，它不能适应一个盛世较为开放、自由、向上的时代气氛，同样也不能拘束着一位位唐朝诗人个个想建功立业的追求。是这个时代一直呼唤着变革，呼唤着要将新的内容参与其中，李颀的五古、七古就是这股时代浪潮的先锋。论五古，论七古，论质论量，唐朝李颀、李白、韩愈三人是顶峰。

后人赞许李颀的七律，在我看来远不及他在五古、七古上的成就，但这不是说他的七律就是不好的。这里需要结合时代背景看，在李颀生活的年代，七律仍是草创，数量不多，质量普遍较差，李颀的七律已经是跳出了时代的局限，他因此被赞赏完全是应得的。

#+begin_quote
缓歌行 李颀

小来托身攀贵游，倾财破产无所忧。暮拟经过石渠署，朝将出入铜龙楼。

结交杜陵轻薄子，谓言可生复可死。一沉一浮会有时，弃我翻然如脱屣。

男儿立身须自强，十年闭户颍水阳。业就功成见明主，击钟鼎食坐华堂。

二八蛾眉梳堕马，美酒清歌曲房下。文昌宫中赐锦衣，长安陌上退朝归。

五陵宾从莫敢视，三省官僚揖者稀。早知今日读书是，悔作从前任侠非。
#+end_quote

《缓歌行》便如李颀自传一般，最后一句虽说有悔，实则自得其乐，毫无悔意。从“业就功成见明主”到“三省官僚揖者稀”是一种典型思维，也没有排斥或讽刺的意思，与其说本该如此，不如说可以如此。

#+begin_quote
赠别高三十五 李颀

五十无产业，心轻百万资。屠酤亦与群，不问君是谁。

饮酒或垂钓，狂歌兼咏诗。焉知汉高士，莫识越鸱夷。

寄迹栖霞山，蓬头睢水湄。忽然辟命下，众谓趋丹墀。

沐浴著赐衣，西来马行迟。能令相府重，且有函关期。

黾勉从寸禄，旧游梁宋时。皤皤邑中叟，相候鬓如丝。

官舍柳林静，河梁杏叶滋。摘芳云景晏，把手秋蝉悲。

小县情未惬，折腰君莫辞。吾观圣人意，不久召京师。
#+end_quote

#+begin_quote
送陈章甫 李颀

四月南风大麦黄，枣花未落桐阴长。青山朝别暮还见，嘶马出门思旧乡。

陈侯立身何坦荡，虬须虎眉仍大颡。腹中贮书一万卷，不肯低头在草莽。

东门酤酒饮我曹，心轻万事皆鸿毛。醉卧不知白日暮，有时空望孤云高。

长河浪头连天黑，津口停舟渡不得。郑国游人未及家，洛阳行子空叹息。

闻道故林相识多，罢官昨日今如何。
#+end_quote

#+begin_quote
听董大弹胡笳声兼寄语弄房给事 李颀

蔡女昔造胡笳声，一弹一十有八拍。胡人落泪沾边草，汉使断肠对归客。

古戍苍苍烽火寒，大荒沉沉飞雪白。先拂商弦后角羽，四郊秋叶惊摵摵。

董夫子，通神明，深山窃听来妖精。言迟更速皆应手，将往复旋如有情。

空山百鸟散还合，万里浮云阴且晴。嘶酸雏雁失群夜，断绝胡儿恋母声。

川为净其波，鸟亦罢其鸣。乌孙部落家乡远，逻娑沙尘哀怨生。

幽音变调忽飘洒，长风吹林雨堕瓦。迸泉飒飒飞木末，野鹿呦呦走堂下。

长安城连东掖垣，凤凰池对青琐门。高才脱略名与利，日夕望君抱琴至。
#+end_quote

#+begin_quote
寄司勋卢员外 李颀

流澌腊月下河阳，草色新年发建章。秦地立春传太史，汉宫题柱忆仙郎。

归鸿欲度千门雪，侍女新添五夜香。早晚荐雄文似者，故人今已赋长杨。
#+end_quote

#+begin_quote
寄綦毋三 李颀

新加大邑绶仍黄，近与单车去洛阳。顾眄一过丞相府，风流三接令公香。

南川粳稻花侵县，西岭云霞色满堂。共道进贤蒙上赏，看君几岁作台郎。
#+end_quote

#+begin_quote
野老曝背 李颀

百岁老翁不种田，惟知曝背乐残年。

有时扪虱独搔首，目送归鸿篱下眠。
#+end_quote

上官婉儿，开元初收集她的诗作有整整二十卷，可现在失传了，《全唐诗》只留下寥寥几篇，实在令人痛心。这是唐诗的一大损失，不敢想象其中有多少优秀作品。从《游长宁公主流杯池二十五首》看，上官仪写景细致清丽的功夫在上官婉儿身上得到更胜一筹的继承，可以想象其人心中的逸趣才情，绝非仅仅应制伪装的，由此居然做到能在应制作品中模糊一窥“诗中的我”。在这里，单就逸趣而言，上官婉儿须胜过她的祖父，上官仪。上官仪作品时而不自觉官气太重，与“清”字一道有长处有短处，上官婉儿则将这种短处降低到了最低，由此显得长处无人企及，因为如果再要突破，必须要在“新”字上有所开拓。上官婉儿将她的“清”推到了一个极限，看她的诗仿佛年方二八、才气横溢，可事实上写这些诗的时候已经四十多岁了，如此年龄写这样的诗足以羞煞后世一众年纪轻轻整日愁肠白发的诗人。

#+begin_quote
游长宁公主流杯池二十五首 上官婉儿

长宁公主，韦庶人所生，下嫁扬慎交。皇帝制曰，门下特进行右散骑常侍驸马都尉观国公杨慎交，分荣戚里，藉宠公门。恭肃著于立身，协勤效于从政。凤皇楼上，宛符琴瑟之欢；乌鹊桥边，载协松萝之契。宜覃茅土，式广山河。因造第于东都，府财几竭。又取西京高士廉第，左金吾卫废营，改为宅，作三重楼，筑山浚池。帝及后数临幸，令昭容赋诗，群臣属和。

---

逐仙赏，展幽情，逾昆阆，迈蓬瀛。

游鲁馆，陟秦台。污山壁，愧琼瑰。

---

檀栾竹影，飙䫻松声。不烦歌吹，自足娱情。

仰循茅宇，俯眄乔枝。烟霞问讯，风月相知。

枝条郁郁，文质彬彬。山林作伴，松桂为邻。

清波汹涌，碧树冥蒙。莫怪留步，因攀桂丛。

莫论圆峤，休说方壶。何如鲁馆，即是仙都。

---

玉环腾远创，金埒荷殊荣。弗玩珠玑饰，仍留仁智情。

凿山便作室，凭树即为楹。公输与班尔，从此遂韬声。

---

登山一长望，正遇九春初。结驷填街术，闾阎满邑居。

斗雪梅先吐，惊风柳未舒。直愁斜日落，不畏酒尊虚。

---

霁晓气清和，披襟赏薜萝。玳瑁凝春色，琉璃漾水波。

跂石聊长啸，攀松乍短歌。除非物外者，谁就此经过。

---

暂尔游山第，淹留惜未归。霞窗明月满，涧户白云飞。

书引藤为架，人将薜作衣。此真攀玩所，临睨赏光辉。

---

放旷出烟云，萧条自不群。漱流清意府，隐几避嚣氛。

石画妆苔色，风梭织水文。山室何为贵，唯馀兰桂熏。

---

策杖临霞岫，危步下霜蹊。志逐深山静，途随曲涧迷。

渐觉心神逸，俄看云雾低。莫怪人题树，只为赏幽栖。

---

攀藤招逸客，偃桂协幽情。水中看树影，风里听松声。

携琴侍叔夜，负局访安期。不应题石壁，为记赏山时。

泉石多仙趣，岩壑写奇形。欲知堪悦耳，唯听水泠泠。

岩壑恣登临，莹目复怡心。风篁类长笛，流水当鸣琴。

懒步天台路，惟登地肺山。幽岩仙桂满，今日恣情攀。

暂游仁智所，萧然松桂情。寄言栖遁客，勿复访蓬瀛。

瀑溜晴疑雨，丛篁昼似昏。山中真可玩，暂请报王孙。

傍池聊试笔，倚石旋题诗。豫弹山水调，终拟从钟期。

横铺豹皮褥，侧带鹿胎巾。借问何为者，山中有逸人。

---

沁水田园先自多，齐城楼观更无过。

倩语张骞莫辛苦，人今从此识天河。

---

参差碧岫耸莲花，潺湲绿水莹金沙。

何须远访三山路，人今已到九仙家。

---

凭高瞰险足怡心，菌阁桃源不暇寻。

馀雪依林成玉树，残霙点岫即瑶岑。
#+end_quote

#+begin_quote
彩书怨 上官婉儿

叶下洞庭初，思君万里馀。露浓香被冷，月落锦屏虚。

欲奏江南曲，贪封蓟北书。书中无别意，惟怅久离居。
#+end_quote

杜牧，才子风范，类似的出生、类似的气质、类似的仕途，唐朝前有崔颢，后就是杜牧了。所谓才子风范，见物咏物，见事咏事，乃是纯粹的诗家。23岁写出的《阿房宫赋》是最好的议论，在他的诗作中从未超越，乃至重新达到这样的高度，而换来的则是他在选景写景上超人的发挥。《杜秋娘诗》写的极好，立意极佳，但它实在有些可惜了。因为对人物的塑造，杜牧不可避免减弱了他最擅长的选景和写景，诗中的景变得普通，而在议论恐怕是已经流俗了。《杜秋娘诗》一首极好，但还可以更好，杜牧写它应该在大和七年（833年），他可能自己意识到了这个问题，所以在《张好好诗》中几乎放弃了议论（写在大和八年），纯以抒情为胜，抒的是自己的情。以我个人之见，《杜秋娘诗》虽然有问题，但它依旧是杜牧最好的五言古诗，可惜了。可惜的不仅仅是这一首诗，因为对一位大诗人来说一首诗的突破意味着今后诗作整体上可以再上一个大台阶，绝非昙花一现那么简单。

杜牧的选景与写景最完美的体现是在他的七绝中，整个唐朝，论质论量，恐怕第一，没有劣作。《赠别》两首、《念昔游》三首应该都写在诗人青年向中年过渡的时候，意气与柔情的糅合，绝妙。到了中年，杜牧仕途受阻，便趋向咏怀与伤感，最出名的比如《泊秦淮》，七律的一些出彩作品应该也是这个时期诞生的。最后晚年，诗作如同白话，临终前还留了一首给他两个儿子，诗曰：“万物有丑好，各一姿状分。唯人即不尔，学与不学论。学非探其花，要自拨其根。孝友与诚实，而不忘尔言。根本既深实，柯叶自滋繁。念尔无忽此，期以庆吾门。”

#+begin_quote
赠别二首 杜牧

娉娉袅袅十三馀，豆蔻梢头二月初。春风十里扬州路，卷上珠帘总不如。

---

多情却似总无情，唯觉尊前笑不成。蜡烛有心还惜别，替人垂泪到天明。
#+end_quote

#+begin_quote
念昔游三首 杜牧

十载飘然绳检外，樽前自献自为酬。秋山春雨闲吟处，倚遍江南寺寺楼。

---

云门寺外逢猛雨，林黑山高雨脚长。曾奉郊宫为近侍，分明㩳㩳羽林枪。

---

李白题诗水西寺，古木回岩楼阁风。半醒半醉游三日，红白花开山雨中。
#+end_quote

#+begin_quote
雨 杜牧

连云接塞添迢递，洒幕侵灯送寂寥。

一夜不眠孤客耳，主人窗外有芭蕉。
#+end_quote

#+begin_quote
汉江 杜牧

溶溶漾漾白鸥飞，绿净春深好染衣。

南去北来人自老，夕阳长送钓船归。
#+end_quote

#+begin_quote
山行 杜牧

远上寒山石径斜，白云生处有人家。

停车坐爱枫林晚，霜叶红于二月花。
#+end_quote

“白云生处”有些版本写作“白云深处”，但显然“深处”二字之妙不及“生处”。明末清初超揆有个《杜牧诗意图轴》，他写的是“深处”，但看他的画就可以明白“生处”二字之形象生动。这是一首绝佳的“题画诗”，[[https://g2.ltfc.net/view/SUHA/608a6c1be11ca96100860cac][图的链接]]。清代还有邹一桂，也画了类似的场景，题上了这首诗，可惜他也写“深处”，[[https://g2.ltfc.net/view/SUHA/608a61890af29f5c808a41aa][图的链接]]。这首诗最出色的不在最后两句，是在第二句，先有第二句的出色，然后才显现出最后两句的优秀。最绝妙的地方，不仅仅作者本人欣赏了这样的美景，还有“人家”，而且他们所欣赏的、从高处欣赏的又有区别于作者本人。

#+begin_quote
清明 杜牧

清明时节雨纷纷，路上行人欲断魂。

借问酒家何处有，牧童遥指杏花村。
#+end_quote

写这首诗时诗人本人是没有办法扫墓的，但他看见别人去扫墓，在外，所以断魂。而真正扫墓的人不是断魂，要我个人体验，是麻木了知觉的。杜牧京兆府万年县人，属于一个极其显赫的高门士族，京兆杜氏从西汉一直存在到五代十国，有近千年的历史。自隋唐以来，最早最出名的是杜如晦，杜牧的爷爷是杜佑，《通典》的编撰者，杜牧出生那年，杜佑成了宰相。他还有个堂兄，叫杜悰，娶了唐宪宗的女儿岐阳公主，之后步步升迁也做了宰相。但杜牧的仕途并不顺利，他多年辗转在外作刺史，自己恐怕是觉得潦倒的，正因如此，清明时节才会有断魂之感。

#+begin_quote
初冬夜饮 杜牧

淮阳多病偶求欢，客袖侵霜与烛盘。

砌下梨花一堆雪，明年谁此凭阑干。
#+end_quote

#+begin_quote
杏园 杜牧

夜来微雨洗芳尘，公子骅骝步贴匀。

莫怪杏园憔悴去，满城多少插花人。
#+end_quote

#+begin_quote
江南春 杜牧

千里莺啼绿映红，水村山郭酒旗风。

南朝四百八十寺，多少楼台烟雨中。
#+end_quote

#+begin_quote
兰溪_在蕲州西 杜牧

兰溪春尽碧泱泱，映水兰花雨发香。

楚国大夫憔悴日，应寻此路去潇湘。
#+end_quote

#+begin_quote
题宣州开元寺_寺置于东晋时 杜牧

南朝谢脁城，东吴最深处。亡国去如鸿，遗寺藏烟坞。

楼飞九十尺，廊环四百柱。高高下下中，风绕松桂树。

青苔照朱阁，白鸟两相语。溪声入僧梦，月色晖粉堵。

阅景无旦夕，凭阑有今古。留我酒一樽，前山看春雨。
#+end_quote

#+begin_quote
偶题二首 其二 杜牧

有恨秋来极，无端别后知。夜阑终耿耿，明发竟迟迟。

信已凭鸿去，归唯与燕期。只因明月见，千里两相思。
#+end_quote

#+begin_quote
寝夜 杜牧

蛩唱如波咽，更深似水寒。露华惊弊褐，灯影挂尘冠。

故国初离梦，前溪更下滩。纷纷毫发事，多少宦游难。
#+end_quote

#+begin_quote
题宣州开元寺水阁阁下宛溪夹溪居人 杜牧

六朝文物草连空，天淡云闲今古同。鸟去鸟来山色里，人歌人哭水声中。

深秋帘幕千家雨，落日楼台一笛风。惆怅无因见范蠡，参差烟树五湖东。
#+end_quote

#+begin_quote
酬张祜处士见寄长句四韵 杜牧

七子论诗谁似公，曹刘须在指挥中。荐衡昔日知文举，乞火无人作蒯通。

北极楼台长挂梦，西江波浪远吞空。可怜故国三千里，虚唱歌词满六宫。

/最后两句意指张祜《宫词》二首，其一：“故国三千里，深宫二十年。一声何满子，双泪落君前”，其二：“自倚能歌日，先皇掌上怜。新声何处唱，肠断李延年。”/
#+end_quote

王勃，但在说王勃之前，需要先理清一个问题，也是一条脉络。首先，应该如何看待应制、宫廷、狎妓、宴游等作品？在说张说时我说它们没有“诗中的我”，但其中依旧有优秀的作品，但仅仅如此的说明还是不清晰的。因为以现代人的认识，几乎都是戴着有色的眼光，大多是批判性质的，再进一步便找到它们普遍的缺点，“浅抒情，泛写景”，换句话说读这些诗作便仿佛喝了一杯白开水，除了最后肚胀便没有感觉了。正因如此，很容易忽略它们，全盘否定它们，而没有精力花在深究它们上。所有这些缺陷我们能看见、想到的，我不认为写出这些诗作的诗人，有名亦或无名，其中有一人是自己不知道的。他们这样写，第一的确因为各种因素的限制只可以“浅抒情，泛写景”，第二因为这些限制这些诗作反而回到了最基本也是最根本的较量上，即文字本身的表现力。所以现代人正确的欣赏方式，对于这些诗作而言，应该是对文字用词的欣赏，对句的欣赏，可以忽略对诗作整体的要求。

要说明文字的表现力，这涉及第二个问题。唐诗的辉煌大半是建立在盛唐上的，对于初唐其实有些轻视，至多找出几位所谓“诗歌改革家”，仿佛他们几人登高一呼，诗风随之一新，盛唐开启。但这是最愚蠢的幻想，也是最自大的幻想，诗人只能做到自己革新自己、自己突破自己，而对于潮流而言永远是随波逐流的，没有所谓“诗歌的改革”，只有时代提出的要求和演绎。那么什么是潮流？诗歌从《诗经》开始对四言进行文字表现力的探索，直到魏武曹操的出现。能够做到在一首诗开头有“对酒当歌，人生几何。譬如朝露，去日苦多”的厌世颓废，又在同一首诗结尾有“山不厌高，海不厌深。周公吐哺，天下归心”的气魄，古今魏武一人而已。四言在他身上其实已经到头了，甚至早在他之前，而他与其他几位建安诗人是最后一批能写四言诗的人。但诗歌是不断发展的，所以在汉朝就有以《古诗十九首》为代表对五言进行文字表现力的探索，同样经过了建安诗人，到了六朝时期，儒学式微到了极点，谈玄大兴。这就产生了两个极端，一种因为对个人风格的强烈倾向和厌世玄理风气将五言诗作个性化，萌发出因思想核心与时代机遇的固有缺陷所以模糊又类似的“诗中的我”，另一种便是应制、宫廷等等单单追求文字用词、句的精巧。两种极端，产生的诗作整体效果却是相同的，谈玄在一开始就要求“浅抒情，泛写景”，这个风气、两种极端都让初唐接了下来，一并接下的还有对五言、以及更原始的七言的文字探索。这里还需要额外说明一点，魏晋谈玄，假托老子与庄子，他们的风格却与老子、庄子在文学上的风格大异，而且老子的风格与庄子的风格也是完全不同的，这个以后说，绝不代表老子、庄子也是“浅抒情，泛写景”。

原始的开拓固然困难重重，但当它丰收时，成果也必将是辉煌的。两种极端，一种因为谈玄风气在思想上的破除，真正的个人风格自然而然百花齐放，另一种则在初唐更加细腻巧妙的应制诗中其实已经完成了对五言在纯粹文字表现力上的探索。当这两种极端都在初唐走了出来（亦或可以说走到尽头），盛唐诗作的辉煌其实已经是必然的了，所以，没有改革，只有潮流。

回到王勃。多数人对王勃的认识，也包括我，都是从《滕王阁序》开始的，又或被那句“海内存知己，天涯若比邻”所吸引。这里有个很奇怪的现象，在《滕王阁序》中四言、五言、六言、七言混杂交错，文章仿佛天成，但到了诗作便只有五言了。私以为以王勃的性格其实更适合七言，或者杂体古诗，五言是对他发挥的一种限制。但即便有了这个限制，王勃的五律、五绝依旧有绝品。他的诗作，如果根据传闻记载，那么也可以包括他的文章，全是凭借一腔意气写就，意气的宣泄首先全落到了现实生活中的景，然后和抒情讲述式的结合在一起。他对山水的理解从根本上不同于张说等人，也不等同于王维等人，既要跳出应制的束缚，也不愿将山水纯粹化，而是将山水个人化，有时还是拟人化。这里需要注意他的诗作每一首中对于写景的动词使用，既将景写得鲜活，而同样的动词完全也可以用在人身上。

意气的宣泄成就如王勃这般才情第一等的诗人，但对尺度的把握会是大难题，而王勃在他早逝的生命里没有这个时间去消化，所以我们现在看到他的诗作是一位大诗人可以想象到能够有的前期的诗作。如《别薛华》、《重别薛华》两首，单纯文字论应该是上品，而且是王勃的上品，但他将尺度写绝了、写死了，类似的情况还有很多。

王勃还作过几首极是不错的杂曲，并且不止他一人，整个唐朝众多优秀的诗人其实都作过、留下数量不少的杂曲，同时也应该注意到在敦煌留下的一系列作品。这是宋词的先声，这是唐诗漫长征途的辉煌之下一直隐藏着的暗线，探索永远不是一朝一夕一人。

#+begin_quote
山中 王勃

长江悲已滞，万里念将归。

况属高风晚，山山黄叶飞。
#+end_quote

意境天成，气概辽阔。最后一句“黄”字，便如岑参的“大漠草黄马正肥”一般，不能纯粹用单一黄色理解，可以想象天地间各种色调的黄的集合体，以此，私以为五绝悲秋第一。论秋，论颜色，王绩《野望》一首有句“树树皆秋色，山山唯落晖”还要稍逊，弱在意境和胸襟。若要争论第一，恐怕意境的大而不粗疏要普遍更有优势。

#+begin_quote
送杜少府之任蜀州 王勃

城阙辅三秦，风烟望五津。与君离别意，同是宦游人。

海内存知己，天涯若比邻。无为在歧路，儿女共沾巾。
#+end_quote

#+begin_quote
咏风 王勃

肃肃凉景生，加我林壑清。驱烟寻涧户，卷雾出山楹。

去来固无迹，动息如有情。日落山水静，为君起松声。
#+end_quote

#+begin_quote
忽梦游仙 王勃

仆本江上客，牵迹在方内。寤寐霄汉间，居然有灵对。

翕尔登霞首，依然蹑云背。电策驱龙光，烟途俨鸾态。

乘月披金帔，连星解琼珮。浮识俄易归，真游邈难再。

寥廓沉遐想，周遑奉遗诲。流俗非我乡，何当释尘昧。
#+end_quote

#+begin_quote
秋夜长 王勃

秋夜长，殊未央。月明白露澄清光，层城绮阁遥相望。

遥相望，川无梁。北风受节南雁翔，崇兰委质时菊芳。

鸣环曳履出长廊，为君秋夜捣衣裳。

纤罗对凤皇，丹绮双鸳鸯，调砧乱杵思自伤。

思自伤，征夫万里戍他乡。

鹤关音信断，龙门道路长。君在天一方，寒衣徒自香。
#+end_quote

开篇我说有些诗作带着后世记忆看便有一番新面貌，现在要说的是还有一类人，这些诗人本身就有着极高的才情，可如果我们现在拿他们和所处的时代再那么一看，就会越发觉得这些诗人的可贵之处，杰出，超越了同时代所有人。韦应物就是这样一位诗人，出生开元，死在贞元，主要活动时间是在大历前后，这个几乎看不见大诗人的时代。所谓“大历十才子”，没有一个才子风范。再如刘长卿、戴叔伦，刘长卿成句无篇，情不足，“白发”始作俑者，最好的比如《长沙过贾谊宅》反而是没有“白发”二字的；戴叔伦更逊一筹，好句难有，好篇几无，才情少有可观之处，五律还能以句稍加掩饰，到了其他地方暴露无遗。《屯田词》是他的好作品，但纵观唐诗人中有名亦或无名也只是中等偏下水平。《早春曲》，艳情复现，开了倒车（可以试问，为什么戴叔伦在这里就是历史的倒车，到了宋词比如柳永等人身上反而是进步的了？中间有多少诗人为这样的演绎助力？）。

#+begin_quote
登楼 韦应物

兹楼日登眺，流岁暗蹉跎。

坐厌淮南守，秋山红树多。
#+end_quote

#+begin_quote
闻雁 韦应物

故园眇何处，归思方悠哉。

淮南秋雨夜，高斋闻雁来。
#+end_quote

#+begin_quote
登楼寄王卿 韦应物

踏阁攀林恨不同，楚云沧海思无穷。

数家砧杵秋山下，一郡荆榛寒雨中。
#+end_quote

首先还是“哀而不伤”的问题，历代的大诗人都能给出自己的解答，但总归有一个前提。“哀而不伤”，落到文字上，不仅不能有“伤”，便连“哀”也是不允许的，总是要侧面的、模拟的、比兴的，所以最后落到读者吟诵，至多感到有一份淡淡却真切的“哀”，以及遐想中更淡的“伤”。到那里，就是读者自己的“伤”，却非诗人所表达的了。韦应物是其中的高手，他营造出一个系列的意象，“秋”的意象占据多数，“春”和“冬”的意象从旁衬托，这样独特且成系列的氛围即便在诗歌历史的长河中都是前所未有的。为了营造意象首先要成景，绝句是极好的体裁，所以韦应物最优秀的作品是在五绝和七绝。但只是如此的成景还是不完整的，少却了一份清竣高忍之外的旷达和自然，是孤而不自负，而这一缺少的部分在韦应物的律诗中得到了弥补。我的看法，韦应物的诗作单独看值得欣赏，但他所营造出的整体、他“诗中的我”在全部诗作中一点一点的弥补更值得品味，至于品味后的优劣就还得先看读者自己趣味如何了。

《伤逝》、《秋夜二首》等十九首，也可以成一个系列，都是在同德精舍旧居的诗作。风格独特，虽然哀伤到了极点毫无尺度可言，也是极佳的作品，可谓鬼诗。好诗，但不可多读，更不可学，要写时自然有，要不写何必求一首鬼诗。

韦应物有才有情，绝句律诗皆擅长，并没有明显的短处，唯一有一点，他太过注重景与氛围，在内容上始终做不到对自己的突破，是一位浪漫大诗人。

#+begin_quote
效何水部二首 其二 韦应物

夕漏起遥恨，虫响乱秋阴。

反复相思字，中有故人心。
#+end_quote

#+begin_quote
秋夜寄丘二十二员外 韦应物

怀君属秋夜，散步咏凉天。

山空松子落，幽人应未眠。
#+end_quote

#+begin_quote
上皇三台 韦应物

不寐倦长更，披衣出户行。

月寒秋竹冷，风切夜窗声。
#+end_quote

#+begin_quote
雪中闻李儋过门不访聊以寄赠 韦应物

度门能不访，冒雪屡西东。已想人如玉，遥怜马似骢。

乍迷金谷路，稍变上阳宫。还比相思意，纷纷正满空。
#+end_quote

#+begin_quote
效陶彭泽 韦应物

霜露悴百草，时菊独妍华。物性有如此，寒暑其奈何。

掇英泛浊醪，日入会田家。尽醉茅檐下，一生岂在多。
#+end_quote

#+begin_quote
游西山 韦应物

时事方扰扰，幽赏独悠悠。弄泉朝涉涧，采石夜归州。

挥翰题苍峭，下马历嵌丘。所爱唯山水，到此即淹留。
#+end_quote

#+begin_quote
善福精舍秋夜迟诸君 韦应物

广庭独闲步，夜色方湛然。丹阁已排云，皓月正高悬。

繁露降秋节，苍林郁芊芊。仰观天气凉，高咏古人篇。

抚己亮无庸，结交赖群贤。属予翘思时，方子中夜眠。

相去隔城阙，佳期屡徂迁。如何日夕待，见月三四圆。
#+end_quote

#+begin_quote
饯雍聿之潞州谒李中丞 韦应物

郁郁雨相遇，出门草青青。酒酣拔剑舞，慷慨送子行。

驱马涉大河，日暮怀洛京。前登太行路，志士亦未平。

薄游五府都，高步振英声。主人才且贤，重士百金轻。

丝竹促飞觞，夜宴达晨星。娱乐易淹暮，谅在执高情。
#+end_quote

#+begin_quote
闲居寄诸弟 韦应物

秋草生庭白露时，故园诸弟益相思。

尽日高斋无一事，芭蕉叶上独题诗。
#+end_quote

#+begin_quote
寒食寄京师诸弟 韦应物

雨中禁火空斋冷，江上流莺独坐听。

把酒看花想诸弟，杜陵寒食草青青。
#+end_quote

#+begin_quote
假中枉卢二十二书亦称卧疾兼讶李二久不访问以诗答书因亦戏李二 韦应物

微官何事劳趋走，服药闲眠养不才。花里棋盘憎鸟污，枕边书卷讶风开。

故人问讯缘同病，芳月相思阻一杯。应笑王戎成俗物，遥持麈尾独徘徊。
#+end_quote

#+begin_quote
王母歌 韦应物

众仙翼神母，羽盖随云起。

上游玄极杳冥中，下看东海一杯水。

海畔种桃经几时，千年开花千年子。

玉颜眇眇何处寻，世上茫茫人自死。
#+end_quote

身份的转变对一位诗人来说至关重要，可以是现实生活中的转变，可以是心理上的大变革，但说到底、最为彻底的终究要从现实生活中汲取，自愿亦或不自愿。诗人只在一种身份游荡，便如身陷囹圄，便极难突破自己，诗情便容易单一，久了就成乏味，是自身的乏味。所以在历史上诗人往往做官然后贬谪，四处奔波，在物质基础的供给下，写出的作品总能高明一筹。但这世上颠沛流离的从来不少，诗人也不少，为什么大诗人每个时代又那么少？因为身份的转变只是最初的一步，首先得先意识到这点，其次诗作中本就能够有了清晰的“诗中的我”，能做到上面两点已经很少了，但还是不够。意识到身份的转变带来的直接影响是“诗中的我”的转变，一首诗作是一首诗作的转变，十首诗作还仅仅只是十首诗作的转变吗？组合了看，便是诗人形象从头到尾的更新，脱胎换骨式的更新，这才是突破自己，突破的是原本的“诗中的我”和诗人思想中的自己。清，“诗中的我”的建立；新，“形象的我”的转变，清新即是大诗人。倘若清新而雅，就不是我这种水平能够妄言的了。

崔颢，正如之前所说，乃是才子风范，但深究了说，他的经历以及对自身的革新要比杜牧更深一些、猜测也坎坷许多。现今看来，第一他存世的诗作总量实在太少了，题材未能因量的提升有质变，比如在边塞题材上其实已经与高适、岑参有所区别，而在最出色的旅途类中已经独树一帜，选景写景极有玩味之处，都是上佳诗作，没有劣作；第二相比在律诗上的成就，七古不免逊色许多，未能完成出色的作品，而在绝句因为数量太少不能判断。

似崔颢这般，景的对象、意象都是随现实而变，并未有一种或几种专擅。好处是时有奇句，让人意想不到，耳目一新，坏处则是倘若现实无力可借，那么就会流俗。他擅长旅途，擅长边塞并非偶然，而是因为这样一种特质自然有这样的擅长。

《江畔老人愁》、《邯郸宫人怨》，叙事风格，但太轻议论，也没有选景。

#+begin_quote
行路难 崔颢

君不见建章宫中金明枝，万万长条拂地垂。二月三月花如霰，九重幽深君不见。

艳彩朝含四宝宫，香风旦入朝云殿。汉家宫女春未阑，爱此芳香朝暮看。

来看去看心不忘，攀折将安镜台上。双双素手剪不成，两两红妆笑相向。

建章昨夜起春风，一花飞落长信宫。长信丽人见花泣，忆此珍树何嗟及。

我昔初在昭阳时，朝攀暮折登玉墀。只言岁岁长相对，不悟今朝遥相思。
#+end_quote

#+begin_quote
游天竺寺 崔颢

晨登天竺山，山殿朝阳晓。厓泉争喷薄，江岫相萦绕。

直上孤顶高，平看众峰小。南州十二月，地暖冰雪少。

青翠满寒山，藤萝覆冬沼。花龛瀑布侧，青壁石林杪。

鸣钟集人天，施饭聚猿鸟。洗意归清净，澄心悟空了。

始知世上人，万物一何扰。
#+end_quote

#+begin_quote
入若耶溪 崔颢

轻舟去何疾，已到云林境。起坐鱼鸟间，动摇山水影。

岩中响自答，溪里言弥静。事事令人幽，停桡向馀景。
#+end_quote

#+begin_quote
题潼关楼 崔颢

客行逢雨霁，歇马上津楼。山势雄三辅，关门扼九州。

川从陕路去，河绕华阴流。向晚登临处，风烟万里愁。
#+end_quote

#+begin_quote
黄鹤楼 崔颢

昔人已乘白云去，此地空馀黄鹤楼。黄鹤一去不复返，白云千载空悠悠。

晴川历历汉阳树，芳草萋萋鹦鹉洲。日暮乡关何处是，烟波江上使人愁。
#+end_quote

#+begin_quote
古游侠呈军中诸将 崔颢

少年负胆气，好勇复知机。仗剑出门去，孤城逢合围。

杀人辽水上，走马渔阳归。错落金锁甲，蒙茸貂鼠衣。

还家行且猎，弓矢速如飞。地迥鹰犬疾，草深狐兔肥。

腰间带两绶，转盼生光辉。顾谓今日战，何如随建威。
#+end_quote

#+begin_quote
赠轻车 崔颢

悠悠远行归，经春涉长道。幽冀桑始青，洛阳蚕欲老。

忆昨戎马地，别时心草草。烽火从北来，边城闭常早。

平生少相遇，未得展怀抱。今日杯酒间，见君交情好。
#+end_quote

#+begin_quote
雁门胡人歌 崔颢

高山代郡东接燕，雁门胡人家近边。解放胡鹰逐塞鸟，能将代马猎秋田。

山头野火寒多烧，雨里孤峰湿作烟。闻道辽西无斗战，时时醉向酒家眠。
#+end_quote

#+begin_quote
辽西作 崔颢

燕郊芳岁晚，残雪冻边城。四月青草合，辽阳春水生。

胡人正牧马，汉将日征兵。露重宝刀湿，沙虚金鼓鸣。

寒衣著已尽，春服与谁成。寄语洛阳使，为传边塞情。
#+end_quote

虞世南。古诗的发展是个人风格化的发展，这与其他文学作品乃至其他领域的艺术作品发展是相通的，总是要进行风格化的发展，总是要向着如何越发触动人的内心去加强影响。这些作品的产生一切似乎都是那样合乎本性，自然而然，但越是如此越是精心构建出来的，而且这样的构建绝非一代人的功夫可以完成，作品写在诗人手上，他的自然是过去不自然留下的精华和提炼。如此，当我们看到这样的作品然后再往前看，比如看到初唐的虞世南身上，其实是隋朝诗人了，他的作品会给人一种隐约的不自然、一种隐约的刻意。但是，作为读者这种感觉的浮现，恰恰是作为作者仅就写诗这一面时趋向自然的体现，风格化的考量与加强在他写作时是不存在的。

读这些诗作，或许时常生出一种有才而未逢其时的感叹，思考倘若虞世南做出风格化的诗作又该如何，但大可不必如此。风格化的发展的确是这样发展的，但并不等于这样的发展就是百利而无一害的，所以现实的发展从一开始就是交替的，能够早在先秦的诸子身上找到已经风格化到了极点的文章辞赋，也能在之后几百年、上千年找到非风格化、有着原始意味的诗作。但再往后，这类诗作的数量越来越少、以至于几乎绝迹，它带来的后果就是风格化作品越发难以找到可以直接汲取营养的新源泉，只能从自己身上、只能从刻意中寻觅刻意，风格中树立新风格。

虞世南最优秀的作品是应制，唐诗中顶尖，作品气质便和如今碑刻中他留下的书法一样，可惜没有墨迹留存，《汝南公主墓志铭》恐怕是伪的。

#+begin_quote
拟饮马长城窟 虞世南

驰马渡河干，流深马渡难。前逢锦车使，都护在楼兰。

轻骑犹衔勒，疑兵尚解鞍。温池下绝涧，栈道接危峦。

拓地勋未赏，亡城律岂宽。有月关犹暗，经春陇尚寒。

云昏无复影，冰合不闻湍。怀君不可遇，聊持报一餐。
#+end_quote

#+begin_quote
出塞 虞世南

上将三略远，元戎九命尊。缅怀古人节，思酬明主恩。

山西多勇气，塞北有游魂。扬桴上陇坂，勒骑下平原。

誓将绝沙漠，悠然去玉门。轻赍不遑舍，惊策骛戎轩。

凛凛边风急，萧萧征马烦。雪暗天山道，冰塞交河源。

雾锋黯无色，霜旗冻不翻。耿介倚长剑，日落风尘昏。
#+end_quote

#+begin_quote
发营逢雨应诏 虞世南

豫游欣胜地，皇泽乃先天。油云阴御道，膏雨润公田。

陇麦沾逾翠，山花湿更然。稼穑良所重，方复悦丰年。
#+end_quote

#+begin_quote
赋得临池竹应制 虞世南

葱翠梢云质，垂彩映清池。波泛含风影，流摇防露枝。

龙鳞漾嶰谷，凤翅拂涟漪。欲识凌冬性，唯有岁寒知。
#+end_quote

#+begin_quote
侍宴应诏赋韵得前字 虞世南

芬芳禁林晚，容与桂丹前。横空一鸟度，照水百花然。

绿野明斜日，青山澹晚烟。滥陪终宴赏，握管类窥天。
#+end_quote

#+begin_quote
蝉 虞世南

垂緌饮清露，流响出疏桐。

居高声自远，非是藉秋风。
#+end_quote

#+begin_quote
咏萤 虞世南

的历流光小，飘飖弱翅轻。

恐畏无人识，独自暗中明。
#+end_quote

……

[[./word.org::*20220310 判断][附录：2022年3月-5月 一点记录]]
