#+TITLE:     古诗的狂想与乱语
#+AUTHOR: 
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs.css" />

子曰：“贤哉，回也！一箪食，一瓢饮，在陋巷，人不堪其忧，回也不改其乐。贤哉，回也！”

颜回之乐异乎寻常，若将它解释为知足常乐则太浅了。知足常乐是有参照的乐，而有参照的乐并非长乐。不改其乐，颜回之乐可以算是长乐，或者说是长乐的一种，它是无参照的，无需也不可能效仿的。

在这里我试图寻回一种初见和当前思考的结合，它的目的在于理清自己日益混乱的思路，所以很大程度上是极端偏见的和不全面的，它的不成熟尤其体现在仅仅对个人观点的贯彻上。有时这贯彻也会出现疏忽，或许转念再想，若干月后又想，会是另外一番光景了。

-----

#+begin_quote
长安古意 卢照邻

长安大道连狭斜，青牛白马七香车。玉辇纵横过主第，金鞭络绎向侯家。

龙衔宝盖承朝日，凤吐流苏带晚霞。百丈游丝争绕树，一群娇鸟共啼花。

啼花戏蝶千门侧，碧树银台万种色。复道交窗作合欢，双阙连甍垂凤翼。

梁家画阁天中起，汉帝金茎云外直。楼前相望不相知，陌上相逢讵相识。

借问吹箫向紫烟，曾经学舞度芳年。得成比目何辞死，原作鸳鸯不羡仙。

比目鸳鸯真可羡，双去双来君不见。生憎帐额绣孤鸾，好取门帘帖双燕。

双燕双飞绕画梁，罗纬翠被郁金香。片片行云著蝉鬓，纤纤初月上鸦黄。

鸦黄粉白车中出，含娇含态情非一。妖童宝马铁连钱，娼妇盘龙金屈膝。

御史府中乌夜啼，廷尉门前雀欲栖。隐隐朱城临玉道，遥遥翠幰没金堤。

挟弹飞鹰杜陵北，探丸借客渭桥西。俱邀侠客芙蓉剑，共宿娼家桃李蹊。

娼家日暮紫罗裙，清歌一啭口氛氲。北堂夜夜人如月，南陌朝朝骑似云。

南陌北堂连北里，五剧三条控三市。弱柳青槐拂地垂，佳气红尘暗天起。

汉代金吾千骑来，翡翠屠苏鹦鹉杯。罗襦宝带为君解，燕歌赵舞为君开。

别有豪华称将相，转日回天不相让。意气由来排灌夫，专权判不容萧相。

专权意气本豪雄，青虬紫燕坐春风。自言歌舞长千载，自谓骄奢凌五公。

节物风光不相待，桑田碧海须臾改。昔时金阶白玉堂，即今唯见青松在。

寂寂寥寥扬子居，年年岁岁一床书。独有南山桂花发，飞来飞去袭人裾。
#+end_quote

“青虬紫燕坐春风”一作“青虬紫燕坐生风”，有些道理，参考。

有一类诗歌，当它写出来的时候已然是名篇，而后人带着后世的记忆再去看则又是一番新面貌，恍惚间有这样的记忆和没有这样的记忆一首诗就像两首不同的诗一样。《长安古意》的好，有一半就在它勾起了读者的想象，就从开头的两句开始，让读者的记忆和文字鉴赏分别被它吸引，但看到了最后却只有惘然若失的感觉。它的好也好在没有“死气”，完全区别于晚唐的大部分作品，是一种沉郁，是一种没有用力在嘶嚎而是娓娓道来的哀而不伤。在这方面，能有同样气质的唐朝后来者恐怕只有韩愈一人，其他算是模仿者，而他也一并继承了“初唐四杰”（以时代论其实应该说“盛唐四杰”，“初唐四杰”似指唐诗初期的意思，区别于上官体，上官仪之死可以算一个标志性事件）的另一个特征。

这首诗的意境不同寻常，比如《长恨歌》步步上推，到最后意境圆满，但《长安古意》不同。它的意其实不用过半大概已经明了，但它的景几句就是一变一转，到最后甚至不敢确定这意境究竟是如何圆满的，但它就是已经明白，这或许正是诗人为配合他的意而写出来的效果。

这种恰到好处的沉郁，卢照邻并非每首都做到了，比如在《行路难》中有：“一朝零落无人问，万古摧残君讵知。人生贵贱无终始，倏忽须臾难久恃。谁家能驻西山日，谁家能堰东流水。汉家陵树满秦川，行来行去尽哀怜。自昔公卿二千石，咸拟荣华一万年。不见朱唇将白貌，惟闻素棘与黄泉。”如此便已是太过，这与作者的人生经历不无关系。与之相似，死气太溢，刘希夷《代悲白头翁》。

四杰都是年少成名，可仕途不顺，潦倒坎坷。他们的诗都是“以赋为诗”，写赋的本事远远超过了写诗的本事，不同于后来者所谓“以赋为诗”是追求某些特质而为之（又或其他人牵强附会），他们是不自觉的，这点在他们的作品气质上体现淋漓尽致。区别于诗作的那种特有精致，他们的诗作精彩，名句用词也是绝伦，但不精致，不精致也是一种精致。

再举例一首，唐朝的诗歌依旧流行唱，这是诗也是歌词。这种界限的区分，在诗与文之间，在诗与赋之间，在诗与歌之间，时而分明，时而模糊，可一旦有所清晰的时候，那么模糊也就是一种假装的模糊了。这是从整体上说的，细分到个人，乃至单篇，是有出入的。

#+begin_quote
明月引 卢照邻

洞庭波起兮鸿雁翔，风瑟瑟兮野苍苍。浮云卷霭，明月流光。荆南兮赵北，碣石兮潇湘。

澄清规於万里，照离思於千行。横桂枝於西第，绕菱花於北堂。

高楼思妇，飞盖君王。文姬绝域，侍子他乡。

见胡鞍之似练，知汉剑之如霜。试登高而骋目，莫不变而回肠。
#+end_quote

唐诗是从多方面过渡的，纯粹以诗论，它脱离了南北朝写美女情态、写贵族生活、写闺室、写宫廷，转而写沧桑、风景、山水、田园、个人等等。但是，正如上面所说，这是从整体上说的，细分到个人，举梁简文帝为例，他的才情、写景、写意哪怕放到唐诗中也是不可多得的。在他的时代，写美女情态、贵族生活又何尝不是一种创新，哪怕是当时的民歌也有类似的男女情意，二者是互相影响的。在《诫当阳公大心书》中他说：“立身之道，与文章异，立身先须谨重，文章且须放荡。”他的大部分诗符合一种诗作的精致，显然“放荡”二字也不是肆意的。

#+begin_quote
咏内人昼眠 萧纲

北窗聊就枕，南檐日未斜。攀钩落绮障，插捩举琵琶。

梦笑开娇靥，眠鬟压落花。簟文生玉腕，香汗浸红纱。

夫婿恒相伴，莫误是倡家。
#+end_quote

#+begin_quote
赋得入阶雨 萧纲

细雨阶前入，洒砌复沾帷。

渍花枝觉重，湿鸟羽飞迟。

傥令斜日照，并欲似游丝。
#+end_quote

#+begin_quote
采桑 萧纲

春色映空来，先发院边梅。细萍重叠长，新花历乱开。

连珂往淇上，接幰至丛台。丛台可怜妾，当窗望飞蝶。

忌趺行衫领，熨斗成褫襵。下床着珠佩，捉镜安花镊。

薄晚畏蚕饥，竞采春桑叶。寄语采桑伴，讶今春日短。

枝高攀不及，叶细笼难满。年年将使君，历乱遣相闻。

欲知琴里意，还赠锦中文。何当照梁日，还作入山云。

重门皆已闭，方知留客袂。可怜黄金络，复以青丝系。

必也为人时，谁令畏夫婿。
#+end_quote

#+begin_quote
雁门太守行 萧纲

轻霜中夜下，黄叶远辞枝。寒苦春难觉，边城秋易知。

风急旌旗断，涂长铠马疲。少解孙吴法，家本幽并儿。

非关买雁肉，徒劳皇甫规。
#+end_quote

#+begin_quote
江南曲 萧纲

阳春路，时使佳人度。枝中水上春并归，长杨扫地桃花飞。

清风吹人光照衣。光照衣，景将夕，掷黄金，留上客。
#+end_quote

最后一首参考[[https://zh.wikisource.org/wiki/藝文類聚/卷042][《艺文类聚・卷四十二・乐部二 乐府》]]，“长杨扫地”一作“长杨拂地”。

“宫体诗”之弊只在情感的柔靡无力，有血肉少骨筋，这与细腻敏感仅一线之隔却是天差地别，所以才华如萧纲可以这样写，别人写出便是废纸了。它在唐朝被批判，乃至近代同样被批判（比如闻一多先生），可以说是必然的，尺度的把握向来都是诗人最难也最不擅长的。

所谓“文如其人”，或许是句真话，但“诗如其人”则绝对是句假话。诗歌体裁和内容的不断演变就是在不断创造新的“诗中的我”，一旦有所穷尽必然迎来衰败，直到找到“新的我”，然后盛极一时，如此循环。“我”的建立第一次就在建安诗人身上，千百年往后时有创新，但万变不离其宗，我认为这就是诗歌的正统主流，唐诗的美就美在它不只是创造出了一个“我”，以数量论、以质量论、乃至以技术的创新论，都是顶峰。虽然，顶峰过后，岂无绝景。

#+begin_quote
石鼓歌 韩愈

张生手持石鼓文，劝我试作石鼓歌。少陵无人谪仙死，才薄将奈石鼓何。

周纲陵迟四海沸，宣王愤起挥天戈。大开明堂受朝贺，诸侯剑佩鸣相磨。

蒐于岐阳骋雄俊，万里禽兽皆遮罗。镌功勒成告万世，凿石作鼓隳嵯峨。

从臣才艺咸第一，拣选撰刻留山阿。雨淋日炙野火燎，鬼物守护烦㧑呵。

公从何处得纸本，毫发尽备无差讹。辞严义密读难晓，字体不类隶与科。

年深岂免有缺画，快剑斫断生蛟鼍。鸾翔凤翥众仙下，珊瑚碧树交枝柯。

金绳铁索锁钮壮，古鼎跃水龙腾梭。陋儒编诗不收入，二雅褊迫无委蛇。

孔子西行不到秦，掎摭星宿遗羲娥。嗟乎好古生苦晚，对此涕泪双滂沱。

忆昔初蒙博士征，其年始改称元和。故人从军在右辅，为我度量掘臼科。

濯冠沐浴告祭酒，如此至宝存岂多。毡包席裹可立致，十鼓只载数骆驼。

荐诸太庙比郜鼎，光价岂止百倍过。圣恩若许留太学，诸生讲解得切磋。

观经鸿都尚填咽，坐见举国来奔波。剜苔剔藓露节角，安置妥帖平不颇。

大厦深檐与盖覆，经历久远期无佗。中朝大官老于事，讵肯感激徒媕婀。

牧童敲火牛砺角，谁复著手为摩挲。日销月铄就埋没，六年西顾空吟哦。

羲之俗书趁姿媚，数纸尚可博白鹅。继周八代争战罢，无人收拾理则那。

方今太平日无事，柄任儒术崇丘轲。安能以此上论列，愿借辨口如悬河。

石鼓之歌止于此，呜呼吾意其蹉跎。
#+end_quote

欧阳修《集古录》云：石鼓文在岐阳，初不见称于世，至唐人始盛称之，而韦应物以为周文王之鼓，至宣王刻诗尔，韩退之直以为宣王之鼓，在今凤翔孔子庙。鼓有十，先时散弃于野，郑馀庆始置于庙，而亡其二。皇祐四年，向传师求于民间，得之，十鼓乃足。石鼓文可见者，其略曰：“我车既攻，我马既同。”又曰：“我车既好，我马既𫘦。君子员猎，员猎员游。麋鹿速速，君子之求。”又曰：“左骖幡幡，右骖騝騝。秀弓时射，麋豕孔庶。”又曰：“其鱼维何，维𫚈（左鱼右与）维鲤。何以橐之，维杨与柳。”

单论沉郁，韩愈可谓杜甫以后第一人，也只有他源于杜、出于杜。自刘长卿始，再加上杜甫，唐诗可谓“老气寒秋，白发连篇”，模仿者只学了杜甫的沉郁外貌，便连沉郁也没有学全。没有学全却也写尽了，香艳开始抬头，隐晦恶劣。韩愈沉郁，凝重肃穆，“诗中的我”如此鲜明却不仅仅只有一个我，所引发的共鸣让人沉郁之外更有一种激昂，所以《石鼓歌》是一首极适合起歌唱诵的诗歌。也只有起歌唱诵，读者才能真正进入这首诗作的意境。我想象的场景，是一个五音不全的老书生大清早站在自家门口磕磕绊绊、但偏偏极为投入地吟诵这首《石鼓歌》。

他并不能说是“以赋为诗”，纯以此诗论，应该是“以文为诗”，其中的区别尤其体现在诗句中更多透露出了那种文的自在，不是散漫，而是自在，这是赋、是诗都有所不及的。确实，韩愈有很多诗作都有这种手法，同样优秀的比如《八月十五日夜赠张功曹》，但是这并不是说只能做到如此，当他时而抛却后写出的作品，你会发现在遣词造句、在选景用意古今几无与他相似之人。其中尺度把握之妙直让人惊叹，但凡稍偏半分便落入奇诡，可算夺人眼球的佳作，但是现在，现在不可能仅仅用“以文为诗”四字去概况。这种情况是诗作大家所共有的特征，但凡真正的大家，都是不可能三言两语可以概况的，要去概况就总觉得不对劲。

#+begin_quote
山石 韩愈

山石荦确行径微，黄昏到寺蝙蝠飞。升堂坐阶新雨足，芭蕉叶大栀子肥。

僧言古壁佛画好，以火来照所见稀。铺床拂席置羹饭，疏粝亦足饱我饥。

夜深静卧百虫绝，清月出岭光入扉。天明独去无道路，出入高下穷烟霏。

山红涧碧纷烂漫，时见松枥皆十围。当流赤足蹋涧石，水声激激风吹衣。

人生如此自可乐，岂必局束为人鞿？嗟哉吾党二三子，安得至老不更归。
#+end_quote

两三百年后北宋的黄庭坚写下《松风阁》，写景选景布置皆是不及，唯有其情相通，当然如果再以书法论，那么《松风阁诗帖》也是天下一绝（如果一定要有一个标准，行书第一颜真卿《争座位帖》、《祭侄文稿》，第二苏轼《黄州寒食诗帖》，第三王羲之信札行书，第四《松风阁诗帖》）。

《山石》一首可称韩愈诗作第一。在他诗作中普遍出现的特征，一个是意境上的“黄昏”，一个是诗作本身所表现的“清新”。“黄昏”也许还好理解，什么是“清新”？清，借用陶渊明《归去来兮辞》中的一句就是“临清流而赋诗”；新，也借用《尚书・胤征》中的一句“旧染污俗，咸与唯新”，这里的新在景、在意、在体裁与手法与文字。“清新”二字同样体现在他的文当中，甚至比诗作更加酣畅。事实上，若非做到了“清新”，那么谁都不能称作“大家”。

在唐诗以后，如果纯以宋诗论，会发现一大批“文章诗”，这种风气的开端就在韩愈身上，展现出的是一种理性与辨证之美，而非纯粹声色滋味之美。七古是个绝佳的场地，可以比肩的，首推李白。但这是两种完全不同类型的诗，都是议论、写景，可本质上韩愈乃是学者风范，李白则性情天然。唯一的问题，韩愈有时写诗太长太芜杂，往往极好的写景夹杂在“平平无奇”当中，这是“文章诗”的一大弊端，宋诗也一并承袭了。最劣，比如《落齿诗》、《赠刘师命》，落齿之苦恐怕让韩愈写诗都不能思考了。可李白，李白写诗不讲技巧，直抒胸臆，尤其对民歌（比如南北朝时期的《子夜四时歌》）进行了前所未有、后亦不曾见的改造，可称化境。他是《诗经》的直接继承者，所以李白的诗越长越优秀，可谓多多益善。求仙，亦或对仙人生活的向往，对李白影响极大，至少：1、清新；2、更有意境上的丰富，是仙气。但凡写景必往大处、高处开始，还有“以赋为诗”之实，但不同于“初唐四杰”及其模仿者，因为夹杂对民歌的运用，便让人感觉这首诗自然如此，不这样反而不行。单以“赋”论，其实是另类的，从“赋”着手理解也是不全的，不如从对民歌的理解开始。

在七古、五古之外，韩愈对七绝的擅长就在他对写景选景的擅长上，试举例几首，实际看有数十首皆是上佳，水平发挥极为稳定。大诗人，稳居一流的大诗人。

#+begin_quote
闻梨花发赠刘师命 韩愈

桃蹊惆怅不能过，红艳纷纷落地多。

闻道郭西千树雪，欲将君去醉如何。
#+end_quote

#+begin_quote
梨花下赠刘师命 韩愈

洛阳城外清明节，百花寥落梨花发。

今日相逢瘴海头，共惊烂漫开正月。
#+end_quote

#+begin_quote
晚春 韩愈

草树知春不久归，百般红紫斗芳菲。

杨花榆荚无才思，惟解漫天作雪飞。
#+end_quote

骆宾王《畴昔篇》鸿篇巨制，更在《帝京篇》之上，写景选景并算出彩，但这是一篇极佳的议论诗赋。他曾说：“夫在心为志，发言为诗。诗有不得尽言，言不得尽意。”按照这个说法，那么骆宾王写《畴昔篇》时一定是五味杂陈，自己也恐怕难明白自己到底什么意，但又偏偏在心中那般深刻。所以写下以后，诗中空间时间交错，铿锵可咏，居然还一点不让人感到凌乱。议论好，抒情好，议论与抒情选择的对象也好，真是一篇好诗作，可惜实在太长的，如果能稍稍分割一下，成组诗那就更好了。《畴昔篇》现在这样，是一首适合放在某某诗歌鉴赏书当中最后一页的作品，它的好并不是所有人都能欣赏的。但仅此一首，我认为骆宾王现在的历史地位还是被低估了，尤其这种时空与场景的转换极为罕见。这里留一个原文[[https://so.gushiwen.cn/shiwenv_64dc973df8e3.aspx][链接]]。

#+begin_quote
从军中行路难 其一 骆宾王

君不见封狐雄虺自成群，冯深负固结妖氛。

玉玺分兵征恶少，金坛受律动_一作劝 将军。将军拥旄宣庙略，战士横行_一作戈 静夷落。

长驱一息背铜梁，直指三巴登剑阁。阁道岧峣起戍楼，剑门遥裔俯灵丘。

邛关九折无平路，江水双源有急流。

征役无期返，他乡岁华晚。杳杳丘陵出，苍苍林薄远。

途危紫盖峰，路涩青泥坂。去去指哀牢，行行入不毛。

绝壁千里_一作重 险，连山四望高。中外分区宇，夷夏殊风土。

交趾枕南荒，昆弥临北户。川原绕_一作饶 毒雾，溪谷多淫雨。

行潦四时流，崩查千岁古。

漂梗飞蓬不自安，扪藤引葛度危峦。昔时闻道从军乐，今日方知行路难。

苍江绿水东流驶，炎洲丹徼南中地。南中南斗映星河，秦川秦塞阻烟波。

三春边地风光少，五月泸中瘴疠多。

朝驱疲斥候，夕息倦樵歌。向月弯繁弱，连星转太阿。

重义轻生怀一顾，东伐西征凡几度。夜夜朝朝斑鬓新，年年岁岁戎衣故。

灞城隅，滇池水，天涯望转积，地际行无已。 

徒觉炎凉节物非，不知关山千万里。

弃置勿重陈，征行多苦辛。且悦清笳杨柳曲，讵忆芳园桃李人。

绛节朱旗分白羽，丹心白刃酬明主。但令一被君王知，谁惮三边征战苦。

行路难_一本下有行路难岐路字 ，几千端。无复归云凭短翰，空馀望日想长安。
#+end_quote

#+begin_quote
从军中行路难 其二 骆宾王

君不见玉关尘色暗边庭，铜鞮杂虏寇长城。天子按剑征馀勇，将军受脤事横行。

七德龙韬开玉帐，千里鼍鼓垒_一作干重龟垒动 金钲。阴山苦雾埋高垒，交河孤月照连营。

连营去去无穷极，拥旆遥遥过绝国。阵云朝结晦天山，寒沙夕涨迷疏勒。

龙鳞水上开鱼贯，马首山前振雕翼。长驱万里詟祁连，分麾三命武功宣。

百发乌号遥碎柳，七尺龙文迥照莲。春来秋去移灰琯，兰闺柳市芳尘断。

雁门迢递尺书稀，鸳被相思双带缓。行路难，行路难，誓令氛祲静皋兰。

但使封侯龙额贵，讵随中妇凤楼寒。
#+end_quote

两首《从军中行路难》应是骆宾王除了《畴昔篇》、《帝京篇》外最优秀的作品，有说这两首是辛常伯写的，还有说是辛常伯与骆宾王一起写的。我无从考证，但辛常伯除此之外连一首都没留下来，所以我更倾向就是骆宾王自己写的。类似的诗意，比如在《从军行》中，他也写：“平生一顾重，意气溢三军。野日分戈影，天星合剑文。弓弦抱汉月，马足践胡尘。不求生入塞，唯当死报君。”而在文章方面，《代李敬业讨武氏檄》是诗人意气达到了一个巅峰，只有当他的意气被兵败消磨殆尽，他的创作生涯也就基本告终了。

#+begin_quote
宋考功（即宋之问）以事累贬黜，后放还，至江南，游灵隐寺。夜月极明，在长廊吟行，且为诗曰：“鹫岭郁岧峣，龙宫隐寂寥。”第二联搜奇思，终不如意。有老僧点长明灯，座大禅状，问曰：“少年夜夕久不寐，而吟讽甚苦，何邪？”之问答曰：“弟子业诗，适偶欲题此寺，而兴思不属。”僧曰：“试吟上联。”即吟与听之。再三吟讽，因曰：“何不云‘楼观沧海日，门听浙江潮。’”之问愕然，讶其遒丽。又续终篇曰：“桂子月中落，天香云外飘。扪萝登塔远，刳木取泉遥。霜薄花更发，冰轻叶未凋。待入天台路，看余度石桥。”僧所赠句，乃为一篇之警策。迟明更访之，则不复见矣。寺僧有知者，曰：“此骆宾王也。”之问诘之，曰：“当敬业之败，与宾王俱逃，捕之不获。将帅虑失大魁，得不测罪，时死者数万人，因求戮类二人者，函首以献。”后虽知不死，不敢捕送，故敬业得为衡山僧，年九十余乃卒。宾王亦落发，遍游名山，至灵隐，以周岁卒。当时虽败，且以匡复为名，故人多获脱之。
#+end_quote

这段是我从《唐人轶事汇编・卷七》里摘下来的，故事流传可以说极广的，但真假恐怕还有的说。无论如何，从骆宾王给出的两句可知其人才情此时依旧，但落发的骆宾王已无心气，只有句没有诗了。他的五律比五言、七言杂体诗差了一筹不止，如上所说，骆宾王是位极擅议论抒情的诗人，但他的写景选景比较地说就差了，五律、七律、五绝、七绝尤其讲究一个“景”字，算是一个短处吧。到了晚年，“楼观沧海日，门听浙江潮”如果真是他写的，那么此消彼长，议论抒情没有了，写景选景功夫厉害了，这两句在他的所有诗作中比都是极佳的。这里还不得不提他七岁时候的作品，那首《咏鹅》也是写景选景极为上佳的天才作品，所以骆宾王是个很有意思的人，他不是不会写景，而是选择的，若到了旁人身上，恐怕有一样都是幸运的了。

#+begin_quote
叙寄员半千 骆宾王

薄宦三河道，自负十馀年。不应惊若厉，只为直如弦。 

坐历山川险，吁嗟陵谷迁。长吟空抱膝，短翮讵冲天。 

魂归沧海上，望断白云前。钓名劳拾紫，隐迹自谈玄。 

不学多能圣，徒思鸿宝仙。斯志良难已，此道岂徒然。 

嗟为刀笔吏，耻从绳墨牵。岐路情虽狎，人伦地本偏。 

长揖谢时事，独往访林泉。寄言二三子，生死不来旋。
#+end_quote

#+begin_quote
在狱咏蝉 骆宾王

西陆蝉声唱，南冠客思侵。那堪玄鬓影，来对白头吟。

露重飞难进，风多响易沉。无人信高洁，谁为表予心。
#+end_quote

并序：余禁所禁垣西，是法厅事也，有古槐数株焉。虽生意可知，同殷仲文之古树；而听讼斯在，即周召伯之甘棠，每至夕照低阴，秋蝉疏引，发声幽息，有切尝闻。岂人心异于曩时，将虫响悲于前听。嗟乎！声以动容，德以象贤。故洁其身也，禀君子达人之高行；蜕其皮也，有仙都羽化之灵姿。候时而来，顺阴阳之数； 应节为变，审藏用之机。有目斯开，不以道昏而昧其视；有翼自薄，不以俗厚而易其真。吟乔树之微风，韵姿天纵； 饮高秋之坠露，清畏人知。仆失路艰虞，遭时徽纆。不哀伤而自怨，未摇落而先衰。闻蟪蛄之流声，悟平反之已奏；见螳螂之抱影，怯危机之未安。感而缀诗，贻诸知己。庶情沿物应，哀弱羽之飘零；道寄人知，悯余声之寂寞。非谓文墨，取代幽忧云尔。

骆宾王之议论抒情，从《在狱咏蝉》一首中可以体现淋漓尽致，并非无景，而是他选择议论。

#+begin_quote
久客临海有怀 骆宾王

天涯非日观，地屺望星楼。练光摇乱马，剑气上连牛。

草湿姑苏夕，叶下洞庭秋。欲知凄断意，江上涉安流。
#+end_quote

#+begin_quote
送郭少府探得忧字 骆宾王

开筵枕德水，辍棹舣仙舟。贝阙桃花浪，龙门竹箭流。 

当歌凄别曲，对酒泣离忧。还望青门外，空见白云浮。
#+end_quote

一般来说诗作中多多少少都能体现出一个“诗中的我”，甚至有人会认为写诗本身就是为了追求这个“诗中的我”，但这是一个错觉，这是一件极为奢侈的事情，而不是什么理所当然。倒不是说它有多么难，而是被写诗的目的所主导了，乃至诗人本人就是被其他人所约束的，由此诗人甚至特地去伪装、磨灭“诗中的我”，以免有额外的影响。所以，“诗中的我”第一次明确被建立是建安诗人，更确切地说就是曹操，在他这个位置，写诗的目的与建立“诗中的我”是没有冲突的，或者说在一个大方向上还是有助益的。

南北朝时期有一首极为优秀的乐府诗，《木兰辞》，诗中人物的形象如此鲜活，传唱千古，但是这里需要有一个区分。诗所描述的人物形象鲜活并不等于诗所表现的“我”就是鲜活的，个人之见，虽有建安诗人、魏晋风流在前，南北朝的《木兰辞》依旧是一首没有“诗中的我”的乐府诗。“诗中的我”以诗歌总量比较，其实是小众的。如果在建安以前继续上溯，一直到诗经的时代，我依旧感觉不到“诗中的我”存在，但每每阅读、每每吟诵，眼前便仿佛站着的不是一个人，不是一个“我”，而是无数“我们”。所以《诗经》所营造的，比如《无衣》、《硕鼠》、《关雎》、《氓》等等等等，是“诗中的我们”。这个“诗中的我们”广泛存在于佚名的古诗及民歌当中，便是《木兰辞》这般，所表现出来的其实是“诗中的我们”。再进一步，李白的伟大之处，他对民歌的运用很大程度，就在他将“诗中的我们”与“诗中的我”极为完美地结合起来，他的诗带着极为鲜明的“诗中的我”，但也让人感受到“诗中的我们”，从而产生一种自发的共鸣。这点，不是天纵奇材是什么！

没有“诗中的我们”，没有“诗中的我”，诗作只能以句为胜，大多写不长，其中也有优秀的作品，大诗人。在唐诗的初期，张说有着一大批“奉和圣制”、“侍宴”、“送赠”作品，这些诗作本身就有极为优秀的，除此之外贬谪时还有许多写景与抒情相互糅合的佳作。“清新”二字，张说当之无愧，尤其擅长五言，擅长山水。或许，会有人觉得贬谪以后作品比之前的要好一筹，我不以为然，因为之后的作品张说也犯了诗人的一个通病，他的尺度把握有些失控了，所以有一部分反而不如从前。纯以作品论，至少那时诗人是乐在其中的，也是有控制力的，而他诗歌才情从始至终没有消减，这点尤其难能可贵。

#+begin_quote
清明日诏宴宁王山池赋得飞字 张说

今日清明宴，佳境惜芳菲。摇扬花杂下，娇啭莺乱飞。

绿渚传歌榜，红桥度舞旂。和风偏应律，细雨不沾衣。 

承恩如改火，春去春来归。
#+end_quote

#+begin_quote
四月十三日诏宴宁王亭子赋得好字 张说

何许承恩宴，山亭风日好。绿嫩鸣鹤洲，阴秾斗鸡道。 

果思夏来茂，花嫌春去早。行乐无限时，皇情及芳草。
#+end_quote

#+begin_quote
送王光庭 张说

同居洛阳陌，经日懒相求。及尔江湖去，言别怅悠悠。

楚云眇羁翼，海月倦行舟。爱而不可见，徒嗟芳岁流。
#+end_quote

#+begin_quote
南中赠高六戬 张说

北极辞明代，南溟宅放臣。丹诚由义尽，白发带愁新。 

鸟坠炎洲气，花飞洛水春。平生歌舞席，谁忆不归人。
#+end_quote

#+begin_quote
入海 其一 张说

乘桴入南海，海旷不可临。茫茫失方面，混混如凝阴。 

云山相出没，天地互浮沉。万里无涯际，云何测广深。 

潮波自盈缩，安得会虚心。 
#+end_quote

#+begin_quote
过蜀道山 张说

我行春三月，山中百花开。披林入峭蒨，攀登陟崔嵬。 

白云半峰起，清江出峡来。谁知高深意，缅邈心幽哉。
#+end_quote

#+begin_quote
山夜闻钟 张说

夜卧闻夜钟，夜静山更响。霜风吹寒月，窈窕虚中上。

前声既舂容，后声复晃荡。听之如可见，寻之定无像。

信知本际空，徒挂生灭想。
#+end_quote

或许，有人会说，唐诗山水与六朝山水何异？都是山水，为什么张说的山水及其更后来者就是“清新”？更重要的，“新”从何来？试以上官仪当宰相时的五绝，《入朝洛堤步月》为例。诗曰：“脉脉广川流，驱马历长洲。鹊飞山月曙，蝉噪野风秋。”诗好吗？的确不差，但比张说恐怕差了一筹不止，上官仪的诗依旧是六朝风范。六朝山水诗，他们并未形成一整套雅致的选景用词体系（好的地方在常有惊人之语，不流俗），“宜诗”的语言是无意识的，就好比一个粗胚尤待打磨锤炼，这是其一。其二，所谓“宜诗宜画”，六朝山水诗在选景布置上是有缺陷的，常常将几个意象硬生生拼凑在了一起，却不管它们是否契合。但是，历代题画诗整体上都要好于非题画诗（自唐以后），为什么？因为非题画诗带来了太多意象上的空白和不协调，张说的山水诗就已经有了“入画”的迹象。更进一步，山水诗其实也是一种意境诗，并非纯粹为景而写景，是一种“意”布置了“景”，“景”衬托出“意”。六朝山水诗是意境诗，但他们的意是静止的，他们的景是没有时间概念的，也就是说纯粹景的意象的组合。而在唐朝，山水动了，意境动了，以致于真正高明的诗人所呈现出来的，“意”与“景”分不清谁是谁的附庸，谁又呈现出谁，山水即意，意即山水——究竟意动山水动，还是山水动意动？在这里，王维将它发扬光大，运用自如，天才。孟浩然则稍逊一筹，并非差在写景，是在“意”上，牢骚愁肠的更好一些。

什么是意境的表达？什么是“宜诗”的语言？在我看来，每一首诗首先是文字的表达，但这种表达再想用另外的文字同义表达便会感到千难万难，左右都不合适，古诗意境之妙就在这里。它的表达或许不是文字最美的、修辞技艺高超的，但它一定是最契合诗人本意的，以至于再难有第二种形容，这是文字的魅力所在。但它也带来同等恶劣的影响，因为模仿，因为从群，一个“好的词汇”用在其他人其他地方至少是可以添色的，所以会出现“老气寒秋，白发连篇”，但其实这些美丽的字词是最不符合诗人自身的。在唐朝，诗人的地位可以说是古今以来最高的，他们最坏的处境也至少是衣食无忧，基本大小都有一个官身，哪来那么多愁肠！若说他们家国情怀，感伤所以愁，可字里行间偏偏让人只看见年纪轻轻强说愁。所以诗歌其实是一个萝卜一个坑，我用得你便用不得了，最讲究创新，不创新，诗歌就是死的。

这里离题插一首，若是愁绪如此，那么也是极佳的，古今这类诗作杰出者很多。好在何处？愁绪不在我而我忧患，是一种责任的担当，“诗中的我”非但不让人腻烦，反而让人感触良多，曲中所述之意加强了这种情绪的发酵。至于《谪仙怨》，后来人怀疑本就是有调无词的，书上说唐玄宗“洞晓音律，制作诸曲，随意即成”，到现在这调恐怕也没有留下。

#+begin_quote
广谪仙怨 窦弘余

并序：天宝十五载正月，安禄山反，陷没洛阳。王师败绩，关门不守。车驾幸蜀，途次马嵬驿，六军不发，赐贵妃自尽，然后驾行。次骆谷，上登高下马，望秦川，遥辞陵庙，再拜，呜咽流涕，左右皆泣。谓力士曰：“吾听九龄之言，不到于此。”乃命中使往韶州，以太牢祭之。因上马索长笛，吹笛，曲成，潸然流涕，伫立久之。时有司旋录成谱，及銮驾至成都，乃进此谱，请名曲。帝谓：“吾因思九龄，亦别有意，可名此曲为《谪仙怨》。”其旨属马嵬之事。厥后以乱离隔绝，有人自西川传得者，无由知，但呼为《剑南神曲》。其音怨切，诸曲莫比。大历中，江南人盛为此曲。随州刺史刘长卿左迁睦州司马，祖筵之内，长卿遂撰其词。吹之为曲，意颇自得，盖亦不知本事。余既备知，聊因暇日撰其辞，复命乐工唱之，用广其不知者。

胡尘犯阙冲关，金辂提携玉颜。云雨此时萧散，君王何日归还。

伤心朝恨暮恨，回首千山万山。独望天边初月，蛾眉犹自弯弯。
#+end_quote

回到山水，再举例几首杨素的诗，最少能得一个“清”字。杨素的诗是有控制力的，区别于风流后的疏狂，乃至带上了几分自我轻纵的意思，他的诗清朗平直，颇得雅意。可惜，可惜他流传下来太少了，也可能是因为杨素自己都没把自己当作一个真正的诗人。

#+begin_quote
赠薛内史 杨素

耿耿不能寐，京洛久离群。横琴还独坐，停杯遂待君。

待君春草歇，独坐秋风发。朝朝唯落花，夜夜空明月。

明月徒流光，落花空自芳。别离望南浦，相思在汉阳。

汉阳隔陇吟，南浦达桂林。山川虽未远，无由得寄音。
#+end_quote

#+begin_quote
山斋独坐赠薛内史 其一 杨素

居山四望阻，风云竟朝夕。深溪横古树，空岩卧幽石。

日出远岫明，鸟散空林寂。兰庭动幽气，竹室生虚白。

落花入户飞，细草当阶积。桂酒徒盈樽，故人不在席。

日落山之幽，临风望羽客。
#+end_quote

#+begin_quote
出塞 其一 杨素

漠南胡未空，汉将复临戎。飞狐出塞北，碣石指辽东。

冠军临瀚海，长平翼大风。云横虎落阵，气抱龙城虹。

横行万里外，胡运百年穷。兵寝星芒落，战解月轮空。

严鐎息夜斗，骍角罢鸣弓。北风嘶朔马，胡霜切塞鸿。

休明大道暨，幽荒日用同。方就长安邸，来谒建章宫。
#+end_quote

要了解陈子昂，可以从一篇小文章开始。在《与东方左史虬修竹篇・并书》中，他说：“东方公足下：文章道弊，五百年矣。汉魏风骨，晋宋莫传，然而文献有可征者。仆尝暇时观齐梁间诗，彩丽竞繁，而兴寄都绝，每以永叹。思古人，常恐逦逶颓靡，风雅不作，以耿耿也。一昨于解三处，见明公《咏孤桐篇》，骨气端翔，音情顿挫，光英朗练，有金石声。遂用洗心饰视，发挥幽郁。不图正始之音，复睹于兹，可使建安作者，相视而笑。解君云，张茂先、何敬祖，东方生与其比肩。仆亦以为知言也。故感叹雅制，作《修竹诗》一首，当有知音以传示之。”

《咏孤桐篇》今已失传，《修竹篇》留了下来，它最有价值的部分是上面这段文字。陈子昂是个历史地位十分特殊的诗人，有人觉得从他开始唐诗才与前代有所切割成真正的唐诗，所以誉为“唐诗奠基人”。这未免过誉了，奠定唐诗的基础并做到于前代有所切割的，至少有四人：张说与宋之问，陈子昂与张九龄。而且这也只是不严谨地举例而已，没有卢照邻，没有骆宾王，还可以再加上李峤（可惜太多太多应制诗作）、上官仪、沈佺期、乔知之等人，那么也是不完整的。可是，所有这些人，在任何一本、乃至一篇介绍唐诗初期的书里、文章里独独最不可缺的，恐怕还是陈子昂一人。这里面有他那篇几乎所有中国人一看就知道的作品的原因，这个放在后面说，但更重要的是他如此鲜明的观点，所找到的路正是唐诗大趋势所走的路。

他的诗作不能与唐诗站在顶峰的那几个人比，就是抒情恐怕也略逊张九龄，只是得了沉郁二字的情，缺少了沉郁二字的意。要做一个比喻，那么陈子昂可谓“初唐老杜”。要欣赏他的诗作，我意最好抛却从历史角度对他的所有评价，那么陈子昂可以说是一位杰出诗人。

#+begin_quote
送客 陈子昂

故人洞庭去，杨柳春风生。相送河洲晚，苍茫别思盈。

白蘋已堪把，绿芷复含荣。江南多桂树，归客赠生平。
#+end_quote

#+begin_quote
感遇 陈子昂

兰若生春夏，芊蔚何青青。幽独空林色，朱蕤冒紫茎。

迟迟白日晚，袅袅秋风生。岁华尽摇落，芳意竟何成。
#+end_quote

#+begin_quote
感遇 陈子昂

苍苍丁零塞，今古缅荒途。亭堠何摧兀，暴骨无全躯。

黄沙幕南起，白日隐西隅。汉甲三十万，曾以事匈奴。

但见沙场死，谁怜塞上孤。
#+end_quote

#+begin_quote
答洛阳主人 陈子昂

平生白云志，早爱赤松游。事亲恨未立，从宦此中州。

主人亦何问，旅客非悠悠。方谒明天子，清宴奉良筹。

再取连城璧，三陟平津侯。不然拂衣去，归从海上鸥。

宁随当代子，倾侧且沉浮。
#+end_quote

#+begin_quote
登幽州台歌 陈子昂

前不见古人，后不见来者。念天地之悠悠，独怆然而涕下。
#+end_quote

“悠悠”二字乃是陈子昂的特色，在几篇诗作中他都有使用。《登幽州台歌》一首，以后世的认识看是绝佳的极上品，但以诗人他自己的眼光看恐怕未必，平常作。这里尤其误导的，在对“古人”二字的认识上，我们以为的“古人”那就是古人，是历史上所有的人。但诗人自己认为的“古人”，恐怕是指更古时那些礼贤下士的明君明主，他是在感慨自己怀才不遇。其中区别太大，因为少却了那份对生命的沧桑感，至少在诗人自己是没有的。所以我前面说陈子昂有沉郁的情，没有沉郁的意。说到这里，或许有对诗人贬低的嫌疑，因为随陈子昂一起的还有一种新的体裁的流行，即怀古。这并非陈子昂无意间的创新，而是有意识的，除了上面举例的，还有比如《登泽州城北楼宴》等等，并非个例。

要在文字中找寻真正的沧桑，古诗是有极限的，尤其缺乏的是一种文字的酝酿，往往限于字数和段落一开始就完全展开了，所以不如先在更早期的辞赋中寻找。《楚辞》当中屈原的《远游》说：“惟天地之无穷兮，哀人生之长勤。往者余弗及兮，来者吾不闻。”我认为这是最贴切的表达，全篇极为精彩，可惜太长，这里就不列出来了。再者，比如贾谊的《鵩鸟赋》说：“且夫天地为炉兮，造化为工；阴阳为炭兮，万物为铜。”同样精彩。请注意，这里的精彩莫被句子本身的精彩所蒙蔽，需要注意到全篇的气息运动，这里所表现出来的精彩才是真正的精彩，这里的精彩才是文字的酝酿，古诗所缺乏的。

#+begin_quote
鵩鸟赋 贾谊

谊为长沙王傅三年，有鵩飞入谊舍，止于坐隅。鵩似鸮，不祥鸟也。谊即以谪居长沙，长沙卑湿，谊自伤悼，以为寿不得长，乃为赋以自广。其辞曰：

单阏之岁兮，四月孟夏，庚子日斜兮，鵩集予舍。止于坐隅兮，貌甚闲暇。异物来萃兮，私怪其故。发书占之兮，谶言其度，曰：“野鸟入室兮，主人将去。” 请问于鵩兮，予去何之？吉乎告我，凶言其灾。淹速之度兮，语予其期。鵩乃叹息，举首奋翼，口不能言，请对以臆：

“万物变化兮，固无休息。斡流而迁兮，或推而还。形气转续兮，变化而蟺。沕穆无穷兮，胡可胜言！祸兮福所倚，福兮祸所伏；忧喜聚门兮，吉凶同域。彼吴强大兮，夫差以败；越栖会稽兮，勾践霸世。斯游遂成兮，卒被五刑；傅说胥靡兮，乃相武丁。夫祸之与福兮，何异纠纆；命不可说兮，孰知其极！水激则旱兮，矢激则远；万物回薄兮，振荡相转。云蒸雨降兮，纠错相纷；大钧播物兮，坱圠无垠。天不可预虑兮，道不可预谋；迟速有命兮，焉识其时。

且夫天地为炉兮，造化为工；阴阳为炭兮，万物为铜。合散消息兮，安有常则？千变万化兮，未始有极，忽然为人兮，何足控抟；化为异物兮，又何足患！小智自私兮，贱彼贵我；达人大观兮，物无不可。贪夫殉财兮，烈士殉名。夸者死权兮，品庶每生。怵迫之徒兮，或趋西东；大人不曲兮，意变齐同。愚士系俗兮，窘若囚拘；至人遗物兮，独与道俱。众人惑惑兮，好恶积亿；真人恬漠兮，独与道息。释智遗形兮，超然自丧；寥廓忽荒兮，与道翱翔。乘流则逝兮，得坻则止；纵躯委命兮，不私与己。其生兮若浮，其死兮若休；澹乎若深渊之静，泛乎若不系之舟。不以生故自宝兮，养空而浮；德人无累兮，知命不忧。细故蒂芥兮，何足以疑！”
#+end_quote

……

[[./word.org::*20220310 判断][附录：2022年3月-5月 一点记录]]
