#+TITLE:     杂烩
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../read/emacs-book.css" />

* 20201107 万法合一到万法践行

最近我注意到有那么一种倾向，或许早已存在，在每个领域都试图去寻找一种解决方法、一种解决工具然后便以为可以完成至少这一领域的所有工作，并且如果找到了自以为更好的便抛却过去的，不再有更多理会。这样做对吗，按照一般道理，如果找到了更好的、这样的更好至少已经得到无可置疑的旁证所以被认识到，那么难道就不应该舍弃因为现有的对比、已经明细看出已有的不好更死守它？在我看来，并没有这么简单，至少不应该如此线性地过渡。

首先应该得到认识的是所谓 “万法合一”，这个 “合” 是什么，“一” 又是什么。禅宗有著名的 “万法归一，一归何处” 诘问，它的 “归” 与 “合” 便首先不同，归代表着在不舍弃自身存在的前提下有归属性，合则代表着放弃或剥夺自身的独立并与其他连为一体。有关 “一” 的讨论由来已久，我将其简略地套用在其他几个不同名词上，它在西方哲学当中意味着 “理念”、更进一步解释则基本概括 “形而上学”，它在老子书中意味着 “道”，它在宋朝意味着 “理”，它在明朝意味着 “心”…… 它在孔子口中最为直白，一就意味着一，再无更多需要代替和解释可言。所有的这些最大的特点在于它们都是思想，而且不是明确带有任何倾向和含义的思想，换句话说它们作为一个思想概念是无法直接指导行为的，之所以能够海纳百川地归纳结合，是因为某种程度上将这一思想概念推向更高层次乃至最高层次，然后才会有空间将其他所有一切置放身后。由此，这里产生了一个观点，如果真有万法合一，那么这一法便已经失去了指导行为的所有可能，妄图继续尝试的古今中外已经有无数证据证明都是失败和荒谬的。

再后需要进一步尝试的是所谓 “万法践行”。当思想的一无法直接实践行为，它必须依赖万法的具体倾向性思想去引领行为的实践，与此同时万法也依赖思想的一去归纳梳理自己的倾向和抉择最终选择的倾向，以此得到不同倾向性思想之间在作为人这一独立个体上的彼此呼应。所以我看到的，没有什么是在践行之前首先明确万法中的某一法便是正确无误所以才去做的，没有什么是万法中的某一法去做就一定有什么结果的，只有去做直到结果发生在事后回顾以后才明白万法的这一法在这一践行过程中哪里对哪里错，只有去做更可能做不下去了才试图以思想的一、个体的一重新选择万法中新的一法继续去做，因此获得的是万法的延续、万法的呼应、万法的得舍。

* 20210414 估值定量与定性

股票的估值可以定量、可以定性。

先说定量。所谓定量，根本是数学的，是统计的，是概率的。有位著名的科幻作家，叫艾西莫夫，他在作品《基地》系列里面提出一个叫 “心理史学” 的学说，意即以各个学科为基础统计和预测整个世界人口未来活动。它的本质一个在数据处理，一个在数据应用，这并非天方夜谭，和在 20 世纪火热至今并演变的控制论、系统论、信息论所意图做到的并无差别。缩小到单单股票范畴，有处理各种财务和历史模型，有应用各种量化交易和分析，发展到现在绝大一个好处在于历史被越来越明晰地看到，反之也意味着历史被越来越人看到，甚至可以武断地认为除了自己没去了解以外每个人对此一清二楚。这里引发的悖论在于，股票的两种赚钱来源：第一公司本身增量赚钱被数据处理并发掘，使之本来的慢钱更多人瓜分并推高资产价格，由此越发缓慢赚钱；第二市场博弈零和赚钱，在此距离数据越近越多越有能力处理越赚钱，二八效应终究会变成一九，直到市场某个临界点，唯一的一也将暂时失效不赚钱，市场从火热走向崩溃、从崩溃走向复苏循环。

定量的估值还将追随根植于数学本身固有的缺陷，即数学是抽象的，以此得到的统计、概率严格意义来说也是抽象的。抽象无法被直接应用在实际，而定量的估值目前就是在拿抽象得到的直接应用在实际，以此它避免了人为主观因素的干扰，以此它遇到了抽象与实际的不符进而失灵失效的问题。在现实，所有的概率和可能都是二元，没有现实之前 1% 的概率也是在结果看来 50% 的可能，越是不可能越是可能，所有的 “意外” 不是概率 1%，而是结果的 100%。之后，当结果真的发生，数据重新被纳入和处理，它做不到真正的更新和避免同样错误，因为数学就是抽象的，而现实没有一分一秒是可以被抽象的。

再说定性。估值的定性有一句很有名的话可以形容，“估值是艺术”，估值当然不真的等于艺术，但落到最后试图判断恐怕也与艺术没有区别，因为判断的客观落到结论的唯一就是主观。艺术有什么特点？艺术没有懂与不懂，只有是与不是，落到估值的定性就是估值没有会与不会，只有高与不高。艺术未有过作品的诞生即被价值的承认，落到估值的定性就是未有过目标的判断即价值的公认。艺术从来没有绝对的至高是无时无刻被遵从的，落到估值的定性就是从未有估值是权威并且等同于现实的。或许还能举出更多特点，但可能已经没有这个必要，在艺术的争执在定性估值当中都会存在，因为艺术追求着结论的唯一，估值不可避免也在追求结论的唯一，而这样的主观注定只是个人所有，以此在其他任何人看来都是有修正余地的。

或许有人会说利用定量的数据处理，然后在试图做出定性的估值判断，这可能是一个尽可能避免缺陷的办法。但在我看来，这或许是最错误的，因为数据处理如果没有数据应用那么定量本身就是不成立的，而定性在结论之前至少做到了判断搜集的最大限度客观，将搜集的信息置换为纯粹的数据，那便失去了立体的主观议论，它的结论恐怕是不伦不类的。所谓的互相补充，实则以定量的抽象覆盖以个人的主观，或者以个人的主观遮掩以定量的纯粹，它的主要作用仅仅在于表面增强自身的说服力，无论是用于说服自己，还是用于说服别人。

它的一个更深层次危险也在于将一切引向了不可知论，当所有手段被现实希望泼灭，当定量与定性最终必然地发生判断上的冲突，所有一切都会指向那个结果的未知是不可控的，所以它是不可知的，所谓估值也就是不可知的。这个问题的错误在于忽略了经验的认识本身就是具备价值的，无论这个认识是否被证伪，都将作为今后论据的基础，前提是处理它、利用它，以定量或者以定性的方式。

* 20210416 具体价格不是估值

任何给出具体价位的买入卖出意愿都不能算是估值，其结果既非定量，也非定性，而只是心理活动。这样结论来源于主观的心理想法，依据也基于主观的心理想法，哪怕在这一结论之前给出如何详实的数据和多少投资大师的观念。但是任何资产终究是要被定价的，如果具体价位不算估值，那么估值干什么，资产又怎么去定价呢。市场首先是交易的，交易的前提是认同，让越来越多人认同也就促成更多的交易。如何让人与人认同就成了市场必须解决的问题，而估值的唯一工作就在于协助解决这个问题，它试图以更合理（却从未绝对合理）的方式获取人的认同，进而达到市场本身趋向合理、交易繁荣的目的。交易的结果最终是价格被确定，估值可以使得一次交易变得更加合理，但做不到使得一次交易直接被确认，因为交易的对象是人与人，是主观面向主观。严格意义说，任何一次交易都有着博弈因素，它的定价可以被限制在估值给定的一个大致范围区间内，之后这个区间便失去了合理的外衣，演变为人与人纯粹的博弈，落到个人头上，即是心理活动的问题了。

* 20210417 市场愚蠢不是个人愚蠢

以个人的愚蠢看待市场的愚蠢，那么一定只是自己的愚蠢，而不是市场自有的。通常来说，一个人总爱用对估值的判断来阐述市场的偏差，以此证明市场的无效，最终得到结论市场是愚蠢的，这样的做法只能是个人对市场的不认同。不认同来源于变量的加入，必有额外因素的加入，或者变量的减少，必有现存因素不曾（不需）被考量。

在看待市场的无效与愚蠢的结论之前，首先应该先判断个人用以判断市场的结论的依据，它的变量是增是减，如果这一判断是自己无从着手理清的，那么在一开始就不应该对市场做出评价。这样的错误通常只是基于对某个理论的简单认同，比如均值复归理论，我只是对这一理论表示认同进而用以判断目前的市场，那么变量在我其实根本不存在，我没有建立也没有减少变量，我本身就是模仿者、舆论的追随者，就是市场的一部分。在此以外，唯有确定了变量是增是减，然后检验变量被直接用于驳倒市场的有效，还是建立在市场有效的合理性之上。一般意义上，当变量是增加时被认为只有建立在市场自有合理性之上的额外因素，当变量是减少时被认为直接用于反驳和对抗市场。我所追求并且认同的，是以变量的增加为核心，当变量减少时是应该警惕的，因为通常来说未经反复验证和思辨的反驳都不是对群体智慧的嘲讽，而只是个人智慧的嘲弄。同时，更应该认识到的，对市场并不需要每时每刻保证有一个明确的观点，变量也不是时时刻刻都必须被认识到，在这里、作为个人愚蠢的表现，可以借用巴顿・比格斯在《对冲基金风云录》里的一段话说明：

#+begin_quote
反潮流显得很有品位，麻烦在于现在人人都反起潮流来。看来，现在要想时髦不能做反潮流者，而要做反反潮流者才行。
#+end_quote

* 20210420 生物医药与医疗问题

在看待生物医药之前，首先是需要问一个问题。如果按照李克强总理所说，有六亿人每月平均工资一千，那么我就在想这六亿人的医疗问题怎么解决，他们过去、现在的医疗状况又是怎么样的？医院面对这样的实际情况，以及过去必然更为恶劣的情况，他们又只能够采取怎样的措施？然后将视角放大到世界，医药行业内生的矛盾会更加清晰，所有的措施和现状都是以不同态度妥协的结果。对于生物药企，研发漫漫无期、九死一生，哪怕结合了各种资本和手段的风险保护，成功者寥寥。而当他们真的研发成功了，前期资本的护航、研发本身大量的投入自然就要换来足够的回报，任何创新的产物都是价高的。这是一个滚雪球的过程，所有的生物药企步入成功、乃至还在成功的路上，紧随其后的就是新一轮资本的并购和整合，药企需要有的不只是研发能力，还要战略能力，还要资本能力，还要整合能力，还要销售能力等等等等。

创新药很少有能够遏制其高价的因素，前提是这个药确实有临床价值，但反过来当一个创新药具备了临床价值，它的高价就很难是大众能够承担的。从 1981 年开始，日本政府开始医保控费，全面控费的结果就是药企在日本难以获取利润和增长，企业只有将业务重心从国内倾斜国外，它的增长根本来源也是海外收益。但在中国这是一个好做法吗？日本有多少就医患者，中国有多少就医患者？药物定价自由如美国，谈判定价如德国，难遏药价高昂的根本，所谓海外业务的高增长便是来源于此。生物医药只有在国内能够走出一条区别于其他国家的路，回答文章开头的问题，然后才有问海外业务多少增长，才有长久的可能。如果一个新生药企一开始就是以海外业务为主，那么它已然自动回避了最大的问题，又怎么期待去解决问题呢。

再说一点 CRO，以一个 “卖水人” 的形象似乎怎么都能够赚钱，却大多忽略了能够赚钱背后需要承担的责任和风险，事实上如果有一天新闻报告 CRO 某某公司黑天鹅事件并不是件让人惊讶的事情，而且大几率迟早会发生的。因为行业特性决定了这个行业是专业化的、也是服务化的，这便意味着所有最脏最累的活一定就是它干的，在药物研发过程中这便意味着试药和临床数据。试药有拿对应病症患者试药的，但更危险却必要的是拿健康常人试药，以此检验功效和副作用，当然在此之前有各种动物实验，但最终人体实验是不可缺的。临床数据涉及造假，但更重要和麻烦的是涉及它的准确性，并不一定真的造假，却有准确性的模糊化。创新研发本就成功者少，CRO 并不是魔力就让它起死回生，这就意味着 CRO 在研发失败时自己中断自己的业务。CRO 是一个好行业，但正如所有的美好，都不是完美无缺的，如果找到一个无暇，一定只是盲目。

* 20210429 是又不是

#+begin_verse
没有的动作，
只有的语言，
虚晃过二十几年，
不变的忐忑，
善变的容颜。

我问虚伪话音，
几时舒缓僵硬，
便能走上
菜市的讲演堂，
无息的墓穴。

这活力没有差别，
字句会喷涌，
意思听了便能懂，
但却参差无律，
都回头自己做事。

莫非选择，
无论一条前途，
厌弃居中调节，
难腻混杂名气，
装作不是个人。
#+end_verse

2021/5/1 评：《是又不是》是旧的，是我尽力想不要去写的，是小品。为什么，因为让人看不懂听不明白，没有 “锄禾日当午”，没有 “何以解忧，唯有杜康”，没有过去白居易写诗妇孺皆知的追求。这首的价值也就剩茶余饭后助兴，不冷不热笑一声，消食而已。我写这首花了半个小时，它的价值不算读完它的十秒钟，也就是笑声里的这一两秒钟了。

* 20210509 知道自己写的是什么

真的知道自己写的是什么，说的是什么，做的是什么吗？所有的文字明明就是自己亲手写下的，但到头来却根本说不清所以然，反而需要越发堆砌文字进去，不断阐述再解释，其实什么也没有，其实什么也不懂。一个是因为自己本就毫无“主义”可言，甚至蔑弃“主义”，不持一端，以为高明。这是心中无“主义”，口头说“问题”，手上没“问题”。还有一个，自己是本来有定论的，因为各种原因就不肯明白说出来，偏要旁敲侧击、拐弯抹角，稀里糊涂到最后反而自己绕了进去。这是心中想“主义”，口头喊“主义”，手上出“问题”。所谓“主义”，天然便带着一丝危险性，因为这意味着只有一条路了，做不来首鼠两端，乃至还带着排斥因素，见不得人反了自己的“主义”，只有少数是有包容的，这种包容还在不阻碍自己“主义”实行的前提下才成立，并非毫无界限可言的。没“主义”并非一件稀奇事，也不是一件人生不可或缺必做的事情，但没“主义”却偏爱参与“主义”的事，没“主义”却偏觉得自己有“主义”，大抵兴致所趋，一两年后回头再看自己的文字便觉犹如看一个陌生人的文字了。

* 20211228 看待药企

我只是在用一个普通人的眼光看待医药公司，绝不深研它的管线、它的临床数据，一旦深研进去那就还没有开始已经注定是失败的了。反之，当我将一家相对高精尖的医药公司只是作为一家随处可见的商业公司看待，我发现在这里面的收获会多得多。创新药会失败吗？会失败。能避免吗？任何一家公司都不敢自称能完全避免。这首先是投医疗器械的原因，也是器械类很多时候跑赢药的原因。但真的风险就不可控了吗？也不一定，那是因噎废食。会有人诟病大药企整天只会仿制，只会买买买，不搞创新，但你能想象恒瑞因为一个临床失败跌70%吗？能想象国外大药企辉瑞、默沙东等等因为一个临床失败跌70%吗？不能，因为不可能，所以这样的诟病其实不合理，大药企在用它的稳定换来它的安全，也用它的稳定失去它的大创新。反之，当想着去搞创新研发了，那么也就不要怨天尤人有一天出现这样的情况，如今日的开拓药业、如前几日美国的Allokos。之前都说创新药双十定律，但其实双十定律在两个方面都超标了，一方面十年十亿根本不够，另一方面药企甚至都活不到十年验证自己成功还是失败。所以哪怕PD1现在降价成这样，无论国内还是国外也泛滥成这样，但还是要说中国的PD1是抓住了历史机遇的，而第一批用PD1成功的药企是已经在所有人面前证明了自己一次的。最后再补充一句，我其实不怎么关心信达明年2月份FDA会不会给审批，这是信达高管需要关心的事情，不是我一个韭菜需要关心的，我关心一件事，买。

* 20211229 微创看法

写一点关于微创医疗的看法。首先是两点常识。

第一，关于医疗器械监管法规，顾名思义，管的就是医疗器械上市与否，除了中国，最主流的获批也就是美国和欧盟。其中尤其需要注意欧盟，它获批那就不只是欧洲这一小块地方，过去欧洲所有的殖民地现在都基本默认它的批准也就能在当地上市。关于这个我看过最好的科普是一期播客节目，名字叫“生物医学工程BME”，它在2015年录制了一期迈瑞医疗给一群学生讲医疗器械监管法规的节目，有兴趣可以找来听听。

第二，医疗器械研发难度。或许有人觉得创新药研发九死无生，然后会默认医疗器械研发相对要简单很多，但事实是二十个研发里面能活一个已经谢天谢地了。而它研发的周期，如果想做到尖端，那么比起创新药也是不遑多让的，所以它的壁垒其实非常高。

说完这两点，就可以直接切入正题，我觉得微创医疗的价值在哪呢？我觉得也有两点，分别对内和对外。

对内。从最近信达的事情就可以看出不管是药还是械，想要通过药监局获批，还没跨过上市的门槛已经是千难万难。那么一个很现实的问题就是，一家企业从头开始按照各自不同的医疗器械监管法规慢慢整理出队伍和数据去获批好，还是说在一个平台上直接利用早已老练的队伍去获批好？我认为这是不言而喻的，微创就是这样一个平台。这个平台有耐心，有底蕴接下研发的担子，然后将剩下的事情交由统一的队伍去执行，而不是各自为战。一个火鹰支架敢花上十几年时间，电生理也花了十几年，现在市值比母公司还高的机器人也是从2014年开始做、到现在也刚刚有临床成功案例。所以我认为对内微创的价值在于它是一个资源整合性的创新平台。

对外。过去有人遐想微创旗下二十几个子公司不是世界第一就是第二，万亿市值近在眼前，触手可及。这是微创股价七十多的时候，故事延续到了未来七百港币一股，可现在已经沦为赔钱货、吸血鬼，微创母公司也成了早晚被掏空的控股公司，故事延续到了资不抵债、破产清算。但这是在瞬息万变的资本市场，在实际医疗情况下呢？随着微创旗下产品越来越多上市，越来越广泛铺开，就会发现无论在哪个细分子行业都会有微创的产品，而且这个产品还不赖，甚至可以说极好。有人质疑微创的经营能力，原因就是十几年如一日的亏损，还看不到头，但显然这种质疑所理解的经营与微创所理解的经营并不是一回事。微创所经营的是一家公司严格意义上可以拥有的最大无形资产，那就是这家公司的品牌。所有的子公司在“微创”这个品牌下一荣俱荣、一损俱损，而微创所产出的子公司就是这个品牌的一张张名片，只有在某个领域达到极致，然后上市，然后这个品牌才能够持续下去，才能够更加强大，它所带来的效应我认为不需要几年就能慢慢看出来。

* 20220104 关于药械国际化

关于国际化。我在去年四月份也写过一小段短文，并不看好现在的国际化，现在我依然不看好，或者说不能全指望用国际化破局。过去曾经了解日本药械企业的成长，他们确实靠着国际化成长到现在，但中国不是日本，中国药械企业也不等于日本的药械企业，简单的复制成功经验永远都是最落后、最低效的。

首先一个前提，目前中国的药械企业要比目前一等的全球化药械企业无论在技术上、还是在销售上弱的。这就相当于总体上在拿自己不擅长的偏要往别人最擅长而且惯用的地方使劲，永远都是事倍功半的，叠加现在的外部环境，那么这个事倍功半还要继续打个大折扣。

对中国自身而言有两大优势，足以在未来、也包括现在养活自己的创新药企。

第一、无论药械都是工业化制品。既然是工业化制品，那么就符合工业化的规律，即制造越多成本越低，对于药械这种完全标准化的产品，成本的下降可以低到不可思议的程度。中国的人口基数决定它发展起来就有其他国家难及的使用量，量变终将引发质变。而在另一方面，中国拥有大量相对低成本、但一样高学历的人才，CRO就是这么起来的，CRO能够凭借这个起来，难道其他地方就没有这个优势了吗，乃至其他行业就没用这个优势了吗？制作低成本、人员低成本，两个低成本，这是中国药械企业绝对的优势，如果再加一个高水准呢？

第二、医保支付能力。如果按照一般说法，中国的医保余额会在二零三几年完全耗尽，以此论证出集采的必要性。但只要按照这个算法，所有发达国家有一个算一个、包括美国他们的医保早就破产了，但事实是他们的医保始终维持在一个相当高的水准上，这是因为医保支付能力先看国家GDP后看国家发债能力，最后还可以加个商业保险的补充。为什么说国际化一个在美国，一个在欧洲，一个日本，因为他们首先就是GDP世界领先的、然后就是发债能力强的。所谓发债能力看的就是国家主权货币，有主权货币然后才能谈发债能力。东南亚一众国家、非洲一众国家、中东一众国家，他们自身GDP体量较小且并不稳定，然后在货币上又牵制于人，所以创新药械国际化难普及到他们。但所有的问题都可以靠相对的低价一定程度上解决，谁的低价，谁能低价？重回原题，我的结论：GDP决定医保支付的大致体量和增长可能性，发债能力则决定这个国家能养活多少创新药企。这才是发达国家的经验，要不要走发债老路先不谈，这或许不是条可循环的好路，所以需要探索，但中国医保支付能力无论在GDP、还是在发债能力都是有保障的。

* 20220310 判断

  2022/3/10 18:38 参照中国古典诗词曲，在文字的造诣上，给自己写的现代诗一个明确的水平判断，截止《观景》第31小节，大概就是“鹅鹅鹅”水平，只会“鹅鹅鹅”，然后就没有了。

  2022/3/11 10:19 先剥去古典诗词曲的几层必要的外衣，例如：平仄格律、韵脚、对仗、孤平、诗意、境界，古典诗词曲的核心优势才得以显露出来，在两个字上：精练；在四个字上：文字精练。也就是说古典诗词曲乃是一种文字精练达到一种极致的完美艺术，这种极致、这种完美让一首诗当中缺失任何一个字眼都会失去它的全部。而这种文字上的精练成体系的、是在四言诗、五言诗上达到了一种极致的极致。但是也应该看到随着时间的推移，这种文字精练其实是不断妥协的，妥协的对象在于让人看懂，在于让人听得愉悦，即在于让人理解。发展的方向无需更多的判断，前辈们指明的道路就是将文字的精练更进一步向让人理解倾斜，这种倾斜到今天甚至让人再难保证在相同的易读性前提下对文字的精练发起一轮新的、平等的攻势，以至于溃不成军，根本无法比较。这是一条错误的路线，想要在文字精练的现有含义下媲美古典诗词曲是不可能的，除非直接变成它的模样。但在另一方面，文字精练是任何一首可以被称作“诗”这个概念所必须拥有的，绝不可以放弃的。所以在这种情况下我认为模仿是一条死路，只有开拓，开拓、赋予文字的精练一种新的含义：如果说以前是在文字精练的前提下让人理解，那么现在就要做到让人理解的前提下文字精练。具体怎么做？我不知道。

  2022/3/21 20:04 要考虑一种直白的叙事，新诗反而做不到与古典诗等同，写出一样的叙事诗。新诗必须要有更多、更重视兴比二手法地运用，技巧的运用。因为古典诗自带了文字的艺术美感，而新诗就白话而言使用太过普遍，本身并没有一种可称独特的美存在，如何赋予它即为一个难题。在此，古典的直白叙事可以参考杜甫《北征》，乔冠华在三八线上催棉衣诗。可书性？必要性？王维《九月九日忆山东兄弟》，直白的，甚至没有什么诗意，但就能够纯粹凭借言情的记述以文字取胜。同例，杜甫《又呈吴郎》……不列举了，诗的意象，在新诗当中还需重塑诗意的字词，古人建立了几套，几套？最后再记一笔，李白《下终南山过斛斯山人宿置酒》。所以叙事也在于景的营造，景的联想，这点仍然是相通的。我没有想得很明白。

  #+begin_verse
  2022/3/22 13:04 补：从直白的叙事，到入画卷当中，最后一句来个抒情。李白《下终南山过斛斯山人宿置酒》给叙事诗交了一份满分答卷。直白叙事重要，画卷重要，简单的抒情重要，缺失任何一个部分，那么它便不算上品。但它是一首李白的诗，哪怕李白没有专门去写过类似的主题（倾向于田园诗范畴），但他只需借着天才的直觉便抓住了所有的要素，再加上他的用词。我的叙事诗不一样，直白叙事有了，画卷是动态的、时空的，也算做了一半，但我没有把想抒的情写出来，大多只是暗含着。含的深，以致于有时候、或者说绝大多数时候根本只会让人注意到那再直白不过的叙事，便没有其他了。我没有做到抒情当中叙事，或者叙事当中抒情，极少有两个方面在一首当中做得好的。从另一个角度，我思考的角度，我还以为暗含着抒情也是一种手法，你说李白最后一句抒情高明吗？独特吗？它让人舒服，但并不见得独一无二，所以如果没有什么特别的抒情，为什么不干脆把它藏起来，只让人看到叙事，看到那一幅画，然后自己有所抒情？此当为景的联想。

  2022/4/26 11:13 左延年写出《秦女休行》，后来又有傅玄、李白也写出了同样主题的诗作，三者比较，我认为最好的还是左延年这首，它就胜在直白叙事，将议论、将抒情全藏了起来。李白一句“秀色如琼花”实在是废句，不如没有，已然最下乘，万万不及左延年一句“休年十四五”。李白写下这句当是一种想当然，或者更准确地说是不自觉，从这里、也以三首相互比较可以看出在历史前进过程中诗歌文辞的改造。
  #+end_verse

  2022/3/27 22:16 有必要对叙事有一个深入的补充。作为叙事的目的是景的营造，景有三种，一种描写他物的叙事，一种描写自己的叙事，还有一种是诗人所有诗篇当中所体现出来的叙事。今天要说的就是第三种叙事。这个叙事不表现在某个具体文字当中，但它真实存在，构成了一个叫做“我”的印象。只要对任何单个诗人的诗篇阅读足够多，那么这个“我”的叙事也就会自然而然诞生。现在的问题在于作为一个诗人的“我”的叙事在数量上太少了，有限的叙事随着时间长河几乎阐述殆尽。诗人花费好大功力，自以为抒情深厚，岂知其实拾人牙慧，甚至到了不仅仅作为“我”的叙事被优秀的作品填满，连第一、第二种叙事也难创新。没有创新等于死亡。所以我认为的一个方向在于将“我”的叙事不交由诗人完成，而是由读者完成。读者如何去完成，不受诗人的影响？在于诗人自己首先放弃抒情，或者说直白的抒情，乃至放弃抒情作为一行文字的存在。在此之外，诗人需要利用直白的叙事和诗歌技巧引发读者自己完成一首诗的联想，最后在阅读、朗诵的过程中完成“我”的叙事，读者自身的“我”的叙事。而诗人又如何才能尽可能做到这一点？在于文字，在于将诗歌的前提不仅仅口号式的，而是发自内心的认为需要做到让人理解的前提下文字精练，不是为了文字的精练的艺术性尝试牺牲它的理解。这只是一个方向，更好的做法自然在找到新的“我”，这种思考是不成熟的，需要再想。

  #+begin_verse
  2022/3/28 10:09 从可读性出发，作为诗歌总量的95%是只能自读的，或者说更倾向于自读。要想成为总量的5%，需要做到“我”的叙事是引发群众共鸣的、不分时代背景，此乃诗歌之正统。它的建立，以单个有名有姓的诗人为起点，始于初期的建安，极盛于初、盛唐。对于建安以前的《诗经》、《古诗十九首》等佚名作品，需要更加慎重、重视地对待，并不能在我的这个框架下很好解释。
  #+end_verse

  2022/3/29 21:03 需要自我明确一个问题，还是文字的问题，华丽又或直白。在绝大多数时候直白永远是比华丽更有效用的，文章浮华经过无数文学家的批判，几乎所有文学爱好者（我自然是其中之一）都知道这一大弊病。但是在理所当然使用直白的文字之前，需要自问一个问题，华丽的极限在哪里？如果直白是这样那样，那么华丽应该怎样怎样？我所以为的华丽真的是华丽吗？现实与思考恰相反，在现实中找不到一个华丽的诗人，乃至在历史中寻找，这样的诗人都是稀有的。对诗篇来说，数量虽然多了一些，但越是走向现代这样的诗篇也变得越来越少。华丽，从立意到意象到结构到词组，岂是一个“文章浮华”可以概括的，文章浮华所批判的也根本不是那样的诗篇，而是它的跟风之作。我想这就是我写《心理的火》意义所在，它是未完成的，但它永远能告诉我，我所能够做到的华丽究竟达到怎样的地步，而到了下一个阶段又能够达到怎样的地步。在这一基础上，尝试直白的可能，在有了华丽的可能的尝试以后。

  2022/4/2 08:20 需要对美的最原始的判断有个明确。美学区别于哲学，哲学思想是个人的独创然后论述出来，美学虽然同样是被知觉的、然后论述出来，但它不是个人的独创，从来不是。美属于群体，美学也来自群体。这个群体或许无法代表了所有的人，但它最终、最后将是所有的人所共同享有的。由此在诗歌当中，在诗歌的景的联想当中，诗人将谨记在文字、在哲思他可以形成个人独特的风格，但在美则完全不同。诗人需要做到一点，他笔下可以有我，他心里、在他抒情的心里不该有我，有我这样一个唯一的、独立的个体，否则便会陷入苦吟当中无法自拔，以至于越吟越苦、越苦越吟。即便诗歌一篇，所咏的只是某个特定人物，或者某个事件当中的主要人物，他所咏的、在心中绝非具体的某一个人，更不应该是他自己。

  2022/4/8 21:20 有一种艺术，开始想将艺术从美中分化出来，也将美从艺术中解放出来，美成了一种观念的哲学。但后来，便为了这个初衷，将艺术完全与美剥离，它可以表述一切意义，但它就是不表现美的，有意识地规避美，于是失去了其中的继承。到最后，它反而找不到属于自己的美，而已经抛弃的美也再不可能重回。有继承有创新，无继承也有创新，这种创新初看是收获极大的，但最后、乃至无需等到最后，它就展现出更为巨大的破坏性。破坏性的后果不是在废墟上重建，而是凭空创造。

  2022/4/9 17:53 要避免一种情况，将文字精练以为炼句。从古至今，专注于炼句的，拿一句话可以从早推敲到晚上的，有几人传世，有几篇可称名篇？寥寥无几。炼句在实质上更多赋予文字一种匠气。所有诗句都是人工的，但就有那么一些文字可以一眼看出其中作者的小心思，但也有那么一些文字仿佛天生就该这样存在，毫无修饰点缀的痕迹。炼句不是没有好的，但它的这种“好”在于让读者感受到他心思上的巧妙，而未经炼句写出的则完全不是一个概念，那是一种直接的美感，是这种直接的美感塑造了诗歌本身所应该拥有的“美”（需要注意这种诗句的美感与诗歌的美也不是可以等同的）。当然这也是比较而言的，并不是说那就可以完全不去推敲自己的文字，应该避免的，是炼句式的过多倾向侧重于自己的文字。文字精练在于一个整体，在于相对于一首诗歌所表达的含义而言它是克制简洁的，所以首先、最基本的，应该做到在含义上的推敲，这可以是长久的、持续的。

  2022/4/10 09:41 叙事的诗难在何处？难在诗意的持续。诗歌是靠诗意支撑的，所有的文字都在配合诗意，当它最强盛的时候最好也就是它结束的时候，但是叙事的诗无法完美做到这点，因为除了诗意它需要做到第二本职，叙事本身。叙事的细节几乎总能让人脱离诗歌所营造的状态，去注意叙事本身的情节，这在小说是完美的，这在诗歌则是致命的。李白说“大雅久不作”，引述者很多，但很少有人能够据此改善自己的作品，因为“大雅”是有历史的，而有历史则需历史的叙事，诗歌一大最难点就在叙事，恐怕反而弄巧成拙。以上叙事的讨论之后，再考虑悲剧相关。叙事为了什么？“大雅”可算一个终极的目标，但更多时候叙事是悲剧的，或者说其中内含了悲剧的元素。在这里首先要对悲剧进行区分，悲剧与悲剧是不同的，不同在悲剧元素与悲剧美，悲剧美必然包含了悲剧元素，悲剧元素并不一定能表达出悲剧美。悲剧，所有的，都会带有一种普遍性。只是一般的悲剧元素所带来的普遍性是针对读者的，是让读者代入其中，告诉读者自己就是悲剧的一员，所以在叙事当中尤其注意单个主角的悲剧性塑造，将主角的人格、独立人格抹除，取代以同样的普遍性，即人格的平庸、或者说人格的模糊。悲剧美所带来的普遍性则针对叙事的作品所塑造的所有人物而言，通过极为激烈的抗争，但最终结局必定要是悲剧的，它让读者看见“美的化身、乃至美本身的死亡”。其中特别注意一点，叙事作品如果能够营造出悲剧美，那么这个悲剧美一定是结合了时代背景的，又或它与读者是默认共享相同的知识背景的。所以悲剧美的普遍性不只是体现在作品的所有人物身上，也体现在这一预设的时代背景的所有人身上，但它就是不体现在读者自己身上。到这里，结合诗歌本身在叙事方面的弱势，可以看出诗歌的悲剧在更大程度上只是一般的悲剧元素，鲜有、但不是没有诗歌可以做到悲剧美。首先应该问自己的是，叙事的诗当中能够塑造几个人物，这几个人物的人格是否可以避免读者的直接代入，而是要代入相应时代背景的，我做不到。

  #+begin_verse
  2022/4/13 20:25 我应该直接面对这个问题，而不是躲闪、旁敲侧击，要在叙事、在悲剧美两方面尝试写出一首新的不长不短的诗，主角原型可以是庄子，主题是逍遥，放在《观景》第42小节、第3分段。庄子本人的诗意会有极大帮助，他的哲思则是更大的帮助，而从现在看，庄子这个人的悲剧美就是成立的，在思想、在现实，更重要的、他难以引起直接的代入。需要注意，第42小节的第1和第2分段可以有略微的文字修改，但是这两个分段是不可或缺的，必须放在前面的。

  2022/4/14 12:25 问：从《诗经·大雅》的叙事，到汉乐府叙事，到唐杜甫、白居易、元稹等抒情叙事，到吴伟业叙事，各优点、缺点在哪里？（只以私心而论，我认为吴之叙事虽技艺高超但不可多学，可多参考，问题在于纯粹文人视角的审美和态度，但也不应该以这个原因苛责贬低作者。）这首诗需要对《庄子》这本书有一个整体的思考，所以首先是庄子的原文，然后是庄子的史料记载，然后是庄子的历代注疏和评论。最后它要有一个现代的反思，这个反思绝不能是在诗的文字当中野蛮套入的，而是成为悲剧美的最大基础，隐身在诗句的背后。换句话说，这个反思应该是我与读者所默认共享的时代背景。是的，这个默认共享的时代背景不可以是被营造出来的庄子的战国时期，而是建立在现代思想、现代物质文明的时代背景之上，只有这样悲剧美才会最完美的展现出来。

  2022/4/14 17:21 需要认清一点：中国古典叙事诗最优秀的传统在于“诗即史”。不是借助史料然后写作，而是作者亲历其中，所以能将自己的作品变成史学材料，在《诗经》钱谦益就曾说：“春秋未作以前之诗皆国史也。”但是反观现在我这首还未写出的诗，它是做不到“诗即史”的，更有可能因为庄子本人事迹记载实在太少，它支撑不起一首叙事诗的体量，所以连做到“史”的退化、“演义”都是困难的。我只有在这里加上一些尝试进去，也因此不能冠以庄子之名，比如将标题写成《庄子吟》之类的。我只能把原型给定为庄子这个对象，然后，然后试试吧。在某种意义上，《观景》的其中几个小节反而是略微符合“诗即史”这个传统的，至少它们写了今时今日。最后，在这里，尤其需要避免一点，因为叙事形式的不确定，将之不自觉转变为咏怀之作，这是从根本上错误的，破坏性的错误，如此这般，不如不写。

  2022/4/20 19:17 诗写完了，应该回到原来的话题，我认为这次体验有值得总结的地方。今天一天没有看原文，回想起来局部有些设计、有些思考其实还是挺满意的，只是我认为自己没有做到这首诗的初衷，没有在叙事上有什么新建树，这地方只有一句不满意、不好。可见叙事这种东西并不是看上去这样简单，也不仅仅诗歌自己的诗意问题。要考虑到诗人本身的诗意，它更是要连贯的，要在叙事上做到诗人自身首先的诗意连贯。这一点，除非本人亲历，而且深受其震撼、深受其影响，乃至改变诗人自身的命运，是做不到的。这就是为什么叙事诗的大发展、大踏步往往发生在极乱世，因为那种时候诗人是被裹挟进入时代的浪潮，那样的震撼是诗意连贯的基础。但作为我个人，我宁愿不要这种基础，所以我应该如何对待叙事，有什么叙事可以不同于上述的叙事？
  
  2022/4/20 21:40 说来说去，其实还是回到了王夫之的“情景”。但可以尝试将王夫之的“景”作更详细的说明，不能是静止的“景”，而应该限定在发展的“景”、能动的“景”，这何尝不是一种叙事？为何必须限定在发展和能动？因为我认为从现在看，首先哲学就是应该以发展、以能动为基础的，在这个基础上才出现各自分歧。说到发展，说到能动，最近想起庄子，不由也想起孔孟，想起老子，想起墨子。我认为儒家最可贵一点在于它是发展的，它是能动的，何以见得？如果说诸子皆以理论的提出然后推导出应该如何言行，儒家则首先提出了言行，它以发展的言行、能动的言行然后理解（不是提出、不是推导、是理解）出自己的理论，所以理论反而不是最重要的，最重要的在于一种言行的态度。发展与能动，诗歌能够做到的是给出这样的“景”。但只是如此恐怕还是有缺陷，我需要再想想，或者说再有更多更多的尝试。我的第一反应就可以诘难，有什么景是完全静止的，有什么诗是完全静止的，所以动与动、叙景与叙物与叙事、乃至兴比可否算一种动，这些都是问题。
  #+end_verse

  2022/4/16 12:13 一个问题，文白混杂问题。就是说白话文发展到今天，它如果想做到与文言文混杂在一起，如何区分与近代自五四运动以来（乃至更早以前）白话试验的那种近似不自觉的文白混杂。当代若要用文白混杂，它必是有意为之的，那么如何区分？如果这个文白混杂是与五四时期的文白混杂一个样，那么不如不写，写也白写。第二个问题，所谓有意为之，这个有意到底是什么意，在什么情况下会到了必须使用文言文的形式，否则表达就不清不明的？如果它是为了某种特殊的效果，那么最好在这个效果差不多达成了以后马上切换回白话文，文言文切切不可多写。所谓文白混杂，它的比例不应该是九比一，而是九十九比一。因为比起它所达到的效果，文字不仅仅在损害文言文的美，也在损害白话文的美，更让读者无所适从。我在第三小段开头类文言文还是多用了。
  
  2022/4/22 13:17 我想在景的联想当中继续补充一句。如果要有一种朦胧不可或缺，那么这种朦胧应该仅仅存在于“景的联想”当中、亦即读者可能的联想当中。朦胧的，进而是多样的，这样的联想如果能够做到，可以算是一种成功。
 
  2022/4/24 09:36 有朦胧成功的一面，那就有与朦胧相反但同样成功的一面。我想，一种联想若能够极为明确的、在刚刚读了一遍以后马上能联想到自己的某一个经历，那么也算是一种成功，而如果能让人以一种新的角度去看待那段经历中自己所做出的行动，那就是成功当中最成功的。但是，这里会有一个捷径的问题，因为相比较人与人之间几乎不可能相同的生活经历，要在这里找到一种契合无疑是难上加难，而要找到相同的、或者说仅仅类似的感情则容易得多，所以会出现一种倾向，与其费尽心力叙事，不如直接抒情，而且这个抒情必须是极为强烈的，尤其能引人共鸣。可是，需要提出一个问题，叙事的难在于以它复杂的叙事情节影响了诗歌诗意的弥漫，那么这样一种带有强烈且必然是直接的感情色彩的抒情（它的诗意或许有了）是否会影响诗歌的境界的美感？我认为是破坏性的，它的破坏或许比叙事的破坏更加严重。所以有种方法是将这种感情变得朦胧起来，然后依旧直接的抒情，而它的效果、虽然经过了朦胧的处理，能够引起的联想依旧是比景的联想更加广泛的，甚至可以变得更加广泛，取得一种与朦胧完全相反的广泛。对此我认为可以有更好的方法，因为诗人本身一种感情的强烈外露是错误，但不等于就需要朦胧的处理，它应该是克制的，克制不等于朦胧。朦胧的抒情应该尤其警惕诗人自己的感情就是朦胧。那么应该怎么克制？我现在认为通过景的叙事，在发展的、能动的景，它就可以自带了一层克制，至于是否能够达到一种多面的协调更应该看诗人到底如何去处理，在这方面我的尝试和经验依然是缺少的。这样的克制其实也可以理解为对抒情的一种弱化，它从直接变成间接，前提仅仅存在于给出的景必须是发展的、能动的。 

  2022/5/7 13:09 问：一段散文、甚至散文诗经过少量修辞上的改进，分段成白话诗的样式，是否就是白话诗？是也不是。是，因为散文的文字之美放在白话诗的样式当中它的美依旧是存在的，尤其对于优秀的散文作品来说更是如此。不是，这里说其中一种原因。首先要问如果散文自己就可以体现出它的美，为什么还要换成诗歌的样式，徒惹人阅读上的障碍，它实际效果是反而减弱的。而站在白话诗的角度，从散文修改然后分段的作品会有一种可感知的不协调，这种不协调导致作品整体的下乘。不协调来源于作品成分的主次矛盾。散文所侧重的是叙事逻辑，然后兼顾抒情逻辑，由此往往出现景在动作，情则是一点一滴慢慢展露出来，它更多时候是一种静止状态的情，或者是一种缓慢发展改变的情。随着景的描写长度在增加，这种情极其细微（也可以说是细腻）改变着，直到成为一本小说，它的情才会有彻底的转变。白话诗则侧重抒情逻辑，但我个人认为抒情逻辑不应该用议论式的、说明式的表达，而是只有通过叙事逻辑、对意象的营造（是营造，不是意象的摘取）来获得表达。它依然是抒情逻辑的侧重，但应该兼顾叙事逻辑，乃至表面就是叙事逻辑。在兼顾的过程中，会发现两种逻辑的矛盾，情永远在要求叙事是跳跃的，叙事则要求情是渐进的，乃至不自觉出现主次侧重的争夺（因为情的感性体验，更容易产生争夺的冲动），但白话诗绝大多数时候又要求是短诗，处理更容易演变为矛盾的堆砌，而不是矛盾的统一，这就是不协调。将散文分段变成白话诗是一种矛盾的堆砌，抒情诗本身也是一种隐晦的矛盾的堆砌，如果反过来将白话诗的分段重新合并为文章，那么就会发现它是根本不成文的，它会更近似于散文的造句、散句。从这里出发，先看到白话诗本身的矛盾，再将范围进一步扩大，白话诗意图在古今中外所有文学体裁中获得借鉴，对其中几类还是改造式的借鉴，应该同样发问这是矛盾的堆砌？是矛盾的统一？都有哪些矛盾在堆砌？哪些矛盾已经尝试统一？统一又是以何种方式、何种态度获得统一的？矛盾于我而言依旧混沌。

  #+begin_verse
  2022/5/8 17:30 以乐府为参考，比如《饮马长城窟行》（青青河畔草……），这些佚名的大诗人是怎样写出如此美妙的诗歌？他们有想过什么矛盾的统一吗？恐怕不见得，那么他们是怎么做到的？他们没想过，那么他们在想什么？我是否想复杂了？这样复杂有它的必要在今天，但应该把同样的、类似的复杂带到创作的过程中吗？恐怕也不见得。我自己写得不好，但从经历看也是没有想那么多的，是之后想，之前想。写下《饮马长城窟行》的大诗人没有想什么矛盾的统一，但他个人的思考结果完美地体现在作品当中，他的矛盾是换了一张面目、依旧存在，依旧冲击着作者的心灵。
  #+end_verse
  
  2022/9/4 22:12 一本小说、一个故事写什么？有只为故事自身设计而写，有为反映现实或历史种人物与场景而写，当二者都有意向时必然在构建中发生冲突。一种办法是在两个方向之间妥协然后得以缓解冲突继续写下去，但更理想的则是向上服从于在一个更为隐蔽的新方向、或者说应该是动笔之先首先提出的方向。这样一个方向，是无论文字、人物、场景、情节等等都向上抉择于小说的目的。目的有的小到只为个人，有的大到可以体现人类的某一面，这样一个可以广泛映射且具备象征意义的人群的一面，它之所以可以成为作者写下故事的目的，我认为是出于作者的不同角度出发产生的不满。这样的不满如果只是出于自身，那么故事的目的即便描述毫无干系，它也是只为个人的；如果出于对人类、对社会的观察、并且进而在自身体验中得到应证，不是一次、不是两次，而是同样广泛意义上的应证，那么这样的不满作为故事的目的所体现出来的就是人类的某一面，进而作为一个整体形成悲剧艺术。我问我自己，有什么不满吗？确实有，但这极少数的不满是个人的，没有是可以观察然后应证的，所以我的不满仅仅我个人，如果我写下一个故事，那么这故事其实对我来说是没有价值的，只有对故事自身设计、只有对现实或历史实则虚假的代入，其实是生不出这样一个隐蔽的第三（或者应该说第一）方向的。抛开故事不谈，那么没有这样的不满则是件幸事，而对故事自己内部的作用、精进之下谁又知道还有一条新路？

* 20230929 和谐

写完《山水动静》以后，我开始时不时盘算重新修改《心理的火》，但在修改之前要问自己一个问题：我修改的标准是什么？在2021年5月12号以后，我已经两年时间没有直接查看《心理的火》文本，那个文档仿佛不存在一样。到了今天，2023年的九月底，我为自己总结了一个词，“和谐”。两年的《观景》，可见的依旧没有结束迹象，但至少我学会了一点，就是和谐，尤其在字与字、词与词、句与句之间的和谐。遥想过去，从大概2012年的一天开始，我在一辆客运大巴上用手机写下“不敢肯定是它从虚无的某处突兀地钻入你无意识的心海，还是你漂泊无依的身躯找到同样漂泊的它”。那时的我根本没有意识到这是一首长诗、一次真正长跑的开始，我只是随着自己性子漫不经心写下，然后就放下不管了。一直等到我接触了弗洛伊德、荣格精神分析和康德哲学和中国经学的连续交叉轰炸，我才开始捡起这个句子，并将它命名为《心理的火》。可是，如此时机、乃至等到20、21年，我都已经停下笔，不继续写下去了，都没有真正认识到《心理的火》内部蕴藏着巨大的不和谐。我只是本能地意识到有那么一些不对劲了，所以就停下了。那么什么是和谐，什么又是不和谐？对于诗歌而言，无论古言还是白话，都有一个统一的黄金准则，或者说是第一准则，就是朗诵。如果一首诗朗诵让人错误频频，甚至不经过长时间重复训练和背诵都无法正常读下去，那么这首诗就是不和谐的。对于《心理的火》，哪怕是我这个创作者，我自己都不能做到从头到尾顺畅读下去，直至读完，所以它就是不和谐的。我在《观景》第一首上面为了警醒自己，说了“写诗歌的现代化”，那么什么又是所谓的“现代化”呢？我以为在这样一个领域，现代化的成就就是将不和谐纳入和谐，将不和谐可以与和谐平静相处，从而本身也最后变得和谐。而说到现代化的劣处，那就是不是每一个时候、每一个人都能够做到将不和谐纳入和谐，而当他们、当这个时间段做不到的时候，便只能任由不和谐充斥一切，乃至击垮和谐，最后孤芳自赏，其实臭不可闻。我在这里说“现代化”，说“和谐”，并不是为了与过去历史割裂，而是在说，在他们的时代一样有着他们的“现代化”，他们的“和谐与不和谐”，有时做到了，有时没有做到，这点并无二致。回到《心理的火》，当我终于结束了一个似乎不像结尾的结尾，我放下了精神分析，放下了康德哲学，也放下了诸子和四书。唯一残留的也概括在两字，“修身”。这不是第一次我开始去探究这“修身”究竟是什么，而是我第一次去体验什么是“修身”，修身是体验的，不是讨论的。由此，我开始感受到和谐，感受到不和谐，进而通过《观景》的训练意识到文字的和谐和不和谐。所以究竟怎么去做到将不和谐纳入和谐？我其实依旧没有答案，但只有尽可能多的尝试以后才有可能知道，这点是我确信的，至少我已经能够大概判断识别什么是不和谐了。《心理的火》修改并不意味着要将所有的不和谐删除，这无异于自杀，而是要有更多的思考。当时在写的时候，我苦叹自己人生经历太少，现在已是三十而立的年纪，我依旧苦叹自己人生经历太少，思考太少。
