#+TITLE:     杂烩
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../read/emacs-book.css" />

* 20201107 万法合一到万法践行

最近我注意到有那么一种倾向，或许早已存在，在每个领域都试图去寻找一种解决方法、一种解决工具然后便以为可以完成至少这一领域的所有工作，并且如果找到了自以为更好的便抛却过去的，不再有更多理会。这样做对吗，按照一般道理，如果找到了更好的、这样的更好至少已经得到无可置疑的旁证所以被认识到，那么难道就不应该舍弃因为现有的对比、已经明细看出已有的不好更死守它？在我看来，并没有这么简单，至少不应该如此线性地过渡。

首先应该得到认识的是所谓 “万法合一”，这个 “合” 是什么，“一” 又是什么。禅宗有著名的 “万法归一，一归何处” 诘问，它的 “归” 与 “合” 便首先不同，归代表着在不舍弃自身存在的前提下有归属性，合则代表着放弃或剥夺自身的独立并与其他连为一体。有关 “一” 的讨论由来已久，我将其简略地套用在其他几个不同名词上，它在西方哲学当中意味着 “理念”、更进一步解释则基本概括 “形而上学”，它在老子书中意味着 “道”，它在宋朝意味着 “理”，它在明朝意味着 “心”…… 它在孔子口中最为直白，一就意味着一，再无更多需要代替和解释可言。所有的这些最大的特点在于它们都是思想，而且不是明确带有任何倾向和含义的思想，换句话说它们作为一个思想概念是无法直接指导行为的，之所以能够海纳百川地归纳结合，是因为某种程度上将这一思想概念推向更高层次乃至最高层次，然后才会有空间将其他所有一切置放身后。由此，这里产生了一个观点，如果真有万法合一，那么这一法便已经失去了指导行为的所有可能，妄图继续尝试的古今中外已经有无数证据证明都是失败和荒谬的。

再后需要进一步尝试的是所谓 “万法践行”。当思想的一无法直接实践行为，它必须依赖万法的具体倾向性思想去引领行为的实践，与此同时万法也依赖思想的一去归纳梳理自己的倾向和抉择最终选择的倾向，以此得到不同倾向性思想之间在作为人这一独立个体上的彼此呼应。所以我看到的，没有什么是在践行之前首先明确万法中的某一法便是正确无误所以才去做的，没有什么是万法中的某一法去做就一定有什么结果的，只有去做直到结果发生在事后回顾以后才明白万法的这一法在这一践行过程中哪里对哪里错，只有去做更可能做不下去了才试图以思想的一、个体的一重新选择万法中新的一法继续去做，因此获得的是万法的延续、万法的呼应、万法的得舍。

* 20210414 估值定量与定性

股票的估值可以定量、可以定性。

先说定量。所谓定量，根本是数学的，是统计的，是概率的。有位著名的科幻作家，叫艾西莫夫，他在作品《基地》系列里面提出一个叫 “心理史学” 的学说，意即以各个学科为基础统计和预测整个世界人口未来活动。它的本质一个在数据处理，一个在数据应用，这并非天方夜谭，和在 20 世纪火热至今并演变的控制论、系统论、信息论所意图做到的并无差别。缩小到单单股票范畴，有处理各种财务和历史模型，有应用各种量化交易和分析，发展到现在绝大一个好处在于历史被越来越明晰地看到，反之也意味着历史被越来越人看到，甚至可以武断地认为除了自己没去了解以外每个人对此一清二楚。这里引发的悖论在于，股票的两种赚钱来源：第一公司本身增量赚钱被数据处理并发掘，使之本来的慢钱更多人瓜分并推高资产价格，由此越发缓慢赚钱；第二市场博弈零和赚钱，在此距离数据越近越多越有能力处理越赚钱，二八效应终究会变成一九，直到市场某个临界点，唯一的一也将暂时失效不赚钱，市场从火热走向崩溃、从崩溃走向复苏循环。

定量的估值还将追随根植于数学本身固有的缺陷，即数学是抽象的，以此得到的统计、概率严格意义来说也是抽象的。抽象无法被直接应用在实际，而定量的估值目前就是在拿抽象得到的直接应用在实际，以此它避免了人为主观因素的干扰，以此它遇到了抽象与实际的不符进而失灵失效的问题。在现实，所有的概率和可能都是二元，没有现实之前 1% 的概率也是在结果看来 50% 的可能，越是不可能越是可能，所有的 “意外” 不是概率 1%，而是结果的 100%。之后，当结果真的发生，数据重新被纳入和处理，它做不到真正的更新和避免同样错误，因为数学就是抽象的，而现实没有一分一秒是可以被抽象的。

再说定性。估值的定性有一句很有名的话可以形容，“估值是艺术”，估值当然不真的等于艺术，但落到最后试图判断恐怕也与艺术没有区别，因为判断的客观落到结论的唯一就是主观。艺术有什么特点？艺术没有懂与不懂，只有是与不是，落到估值的定性就是估值没有会与不会，只有高与不高。艺术未有过作品的诞生即被价值的承认，落到估值的定性就是未有过目标的判断即价值的公认。艺术从来没有绝对的至高是无时无刻被遵从的，落到估值的定性就是从未有估值是权威并且等同于现实的。或许还能举出更多特点，但可能已经没有这个必要，在艺术的争执在定性估值当中都会存在，因为艺术追求着结论的唯一，估值不可避免也在追求结论的唯一，而这样的主观注定只是个人所有，以此在其他任何人看来都是有修正余地的。

或许有人会说利用定量的数据处理，然后在试图做出定性的估值判断，这可能是一个尽可能避免缺陷的办法。但在我看来，这或许是最错误的，因为数据处理如果没有数据应用那么定量本身就是不成立的，而定性在结论之前至少做到了判断搜集的最大限度客观，将搜集的信息置换为纯粹的数据，那便失去了立体的主观议论，它的结论恐怕是不伦不类的。所谓的互相补充，实则以定量的抽象覆盖以个人的主观，或者以个人的主观遮掩以定量的纯粹，它的主要作用仅仅在于表面增强自身的说服力，无论是用于说服自己，还是用于说服别人。

它的一个更深层次危险也在于将一切引向了不可知论，当所有手段被现实希望泼灭，当定量与定性最终必然地发生判断上的冲突，所有一切都会指向那个结果的未知是不可控的，所以它是不可知的，所谓估值也就是不可知的。这个问题的错误在于忽略了经验的认识本身就是具备价值的，无论这个认识是否被证伪，都将作为今后论据的基础，前提是处理它、利用它，以定量或者以定性的方式。

* 20210416 具体价格不是估值

任何给出具体价位的买入卖出意愿都不能算是估值，其结果既非定量，也非定性，而只是心理活动。这样结论来源于主观的心理想法，依据也基于主观的心理想法，哪怕在这一结论之前给出如何详实的数据和多少投资大师的观念。但是任何资产终究是要被定价的，如果具体价位不算估值，那么估值干什么，资产又怎么去定价呢。市场首先是交易的，交易的前提是认同，让越来越多人认同也就促成更多的交易。如何让人与人认同就成了市场必须解决的问题，而估值的唯一工作就在于协助解决这个问题，它试图以更合理（却从未绝对合理）的方式获取人的认同，进而达到市场本身趋向合理、交易繁荣的目的。交易的结果最终是价格被确定，估值可以使得一次交易变得更加合理，但做不到使得一次交易直接被确认，因为交易的对象是人与人，是主观面向主观。严格意义说，任何一次交易都有着博弈因素，它的定价可以被限制在估值给定的一个大致范围区间内，之后这个区间便失去了合理的外衣，演变为人与人纯粹的博弈，落到个人头上，即是心理活动的问题了。

* 20210417 市场愚蠢不是个人愚蠢

以个人的愚蠢看待市场的愚蠢，那么一定只是自己的愚蠢，而不是市场自有的。通常来说，一个人总爱用对估值的判断来阐述市场的偏差，以此证明市场的无效，最终得到结论市场是愚蠢的，这样的做法只能是个人对市场的不认同。不认同来源于变量的加入，必有额外因素的加入，或者变量的减少，必有现存因素不曾（不需）被考量。

在看待市场的无效与愚蠢的结论之前，首先应该先判断个人用以判断市场的结论的依据，它的变量是增是减，如果这一判断是自己无从着手理清的，那么在一开始就不应该对市场做出评价。这样的错误通常只是基于对某个理论的简单认同，比如均值复归理论，我只是对这一理论表示认同进而用以判断目前的市场，那么变量在我其实根本不存在，我没有建立也没有减少变量，我本身就是模仿者、舆论的追随者，就是市场的一部分。在此以外，唯有确定了变量是增是减，然后检验变量被直接用于驳倒市场的有效，还是建立在市场有效的合理性之上。一般意义上，当变量是增加时被认为只有建立在市场自有合理性之上的额外因素，当变量是减少时被认为直接用于反驳和对抗市场。我所追求并且认同的，是以变量的增加为核心，当变量减少时是应该警惕的，因为通常来说未经反复验证和思辨的反驳都不是对群体智慧的嘲讽，而只是个人智慧的嘲弄。同时，更应该认识到的，对市场并不需要每时每刻保证有一个明确的观点，变量也不是时时刻刻都必须被认识到，在这里、作为个人愚蠢的表现，可以借用巴顿・比格斯在《对冲基金风云录》里的一段话说明：

#+begin_quote
反潮流显得很有品位，麻烦在于现在人人都反起潮流来。看来，现在要想时髦不能做反潮流者，而要做反反潮流者才行。
#+end_quote

* 20210420 生物医药与医疗问题

在看待生物医药之前，首先是需要问一个问题。如果按照李克强总理所说，有六亿人每月平均工资一千，那么我就在想这六亿人的医疗问题怎么解决，他们过去、现在的医疗状况又是怎么样的？医院面对这样的实际情况，以及过去必然更为恶劣的情况，他们又只能够采取怎样的措施？然后将视角放大到世界，医药行业内生的矛盾会更加清晰，所有的措施和现状都是以不同态度妥协的结果。对于生物药企，研发漫漫无期、九死一生，哪怕结合了各种资本和手段的风险保护，成功者寥寥。而当他们真的研发成功了，前期资本的护航、研发本身大量的投入自然就要换来足够的回报，任何创新的产物都是价高的。这是一个滚雪球的过程，所有的生物药企步入成功、乃至还在成功的路上，紧随其后的就是新一轮资本的并购和整合，药企需要有的不只是研发能力，还要战略能力，还要资本能力，还要整合能力，还要销售能力等等等等。

创新药很少有能够遏制其高价的因素，前提是这个药确实有临床价值，但反过来当一个创新药具备了临床价值，它的高价就很难是大众能够承担的。从 1981 年开始，日本政府开始医保控费，全面控费的结果就是药企在日本难以获取利润和增长，企业只有将业务重心从国内倾斜国外，它的增长根本来源也是海外收益。但在中国这是一个好做法吗？日本有多少就医患者，中国有多少就医患者？药物定价自由如美国，谈判定价如德国，难遏药价高昂的根本，所谓海外业务的高增长便是来源于此。生物医药只有在国内能够走出一条区别于其他国家的路，回答文章开头的问题，然后才有问海外业务多少增长，才有长久的可能。如果一个新生药企一开始就是以海外业务为主，那么它已然自动回避了最大的问题，又怎么期待去解决问题呢。

再说一点 CRO，以一个 “卖水人” 的形象似乎怎么都能够赚钱，却大多忽略了能够赚钱背后需要承担的责任和风险，事实上如果有一天新闻报告 CRO 某某公司黑天鹅事件并不是件让人惊讶的事情，而且大几率迟早会发生的。因为行业特性决定了这个行业是专业化的、也是服务化的，这便意味着所有最脏最累的活一定就是它干的，在药物研发过程中这便意味着试药和临床数据。试药有拿对应病症患者试药的，但更危险却必要的是拿健康常人试药，以此检验功效和副作用，当然在此之前有各种动物实验，但最终人体实验是不可缺的。临床数据涉及造假，但更重要和麻烦的是涉及它的准确性，并不一定真的造假，却有准确性的模糊化。创新研发本就成功者少，CRO 并不是魔力就让它起死回生，这就意味着 CRO 在研发失败时自己中断自己的业务。CRO 是一个好行业，但正如所有的美好，都不是完美无缺的，如果找到一个无暇，一定只是盲目。

* 20210429 是又不是

#+begin_verse
没有的动作，
只有的语言，
虚晃过二十几年，
不变的忐忑，
善变的容颜。

我问虚伪话音，
几时舒缓僵硬，
便能走上
菜市的讲演堂，
无息的墓穴。

这活力没有差别，
字句会喷涌，
意思听了便能懂，
但却参差无律，
都回头自己做事。

莫非选择，
无论一条前途，
厌弃居中调节，
难腻混杂名气，
装作不是个人。
#+end_verse

2021/5/1 评：《是又不是》是旧的，是我尽力想不要去写的，是小品。为什么，因为让人看不懂听不明白，没有 “锄禾日当午”，没有 “何以解忧，唯有杜康”，没有过去白居易写诗妇孺皆知的追求。这首的价值也就剩茶余饭后助兴，不冷不热笑一声，消食而已。我写这首花了半个小时，它的价值不算读完它的十秒钟，也就是笑声里的这一两秒钟了。

* 20210509 知道自己写的是什么

真的知道自己写的是什么，说的是什么，做的是什么吗？所有的文字明明就是自己亲手写下的，但到头来却根本说不清所以然，反而需要越发堆砌文字进去，不断阐述再解释，其实什么也没有，其实什么也不懂。一个是因为自己本就毫无“主义”可言，甚至蔑弃“主义”，不持一端，以为高明。这是心中无“主义”，口头说“问题”，手上没“问题”。还有一个，自己是本来有定论的，因为各种原因就不肯明白说出来，偏要旁敲侧击、拐弯抹角，稀里糊涂到最后反而自己绕了进去。这是心中想“主义”，口头喊“主义”，手上出“问题”。所谓“主义”，天然便带着一丝危险性，因为这意味着只有一条路了，做不来首鼠两端，乃至还带着排斥因素，见不得人反了自己的“主义”，只有少数是有包容的，这种包容还在不阻碍自己“主义”实行的前提下才成立，并非毫无界限可言的。没“主义”并非一件稀奇事，也不是一件人生不可或缺必做的事情，但没“主义”却偏爱参与“主义”的事，没“主义”却偏觉得自己有“主义”，大抵兴致所趋，一两年后回头再看自己的文字便觉犹如看一个陌生人的文字了。

* 20211228 看待药企

我只是在用一个普通人的眼光看待医药公司，绝不深研它的管线、它的临床数据，一旦深研进去那就还没有开始已经注定是失败的了。反之，当我将一家相对高精尖的医药公司只是作为一家随处可见的商业公司看待，我发现在这里面的收获会多得多。创新药会失败吗？会失败。能避免吗？任何一家公司都不敢自称能完全避免。这首先是投医疗器械的原因，也是器械类很多时候跑赢药的原因。但真的风险就不可控了吗？也不一定，那是因噎废食。会有人诟病大药企整天只会仿制，只会买买买，不搞创新，但你能想象恒瑞因为一个临床失败跌70%吗？能想象国外大药企辉瑞、默沙东等等因为一个临床失败跌70%吗？不能，因为不可能，所以这样的诟病其实不合理，大药企在用它的稳定换来它的安全，也用它的稳定失去它的大创新。反之，当想着去搞创新研发了，那么也就不要怨天尤人有一天出现这样的情况，如今日的开拓药业、如前几日美国的Allokos。之前都说创新药双十定律，但其实双十定律在两个方面都超标了，一方面十年十亿根本不够，另一方面药企甚至都活不到十年验证自己成功还是失败。所以哪怕PD1现在降价成这样，无论国内还是国外也泛滥成这样，但还是要说中国的PD1是抓住了历史机遇的，而第一批用PD1成功的药企是已经在所有人面前证明了自己一次的。最后再补充一句，我其实不怎么关心信达明年2月份FDA会不会给审批，这是信达高管需要关心的事情，不是我一个韭菜需要关心的，我关心一件事，买。

* 20211229 微创看法

写一点关于微创医疗的看法。首先是两点常识。

第一，关于医疗器械监管法规，顾名思义，管的就是医疗器械上市与否，除了中国，最主流的获批也就是美国和欧盟。其中尤其需要注意欧盟，它获批那就不只是欧洲这一小块地方，过去欧洲所有的殖民地现在都基本默认它的批准也就能在当地上市。关于这个我看过最好的科普是一期播客节目，名字叫“生物医学工程BME”，它在2015年录制了一期迈瑞医疗给一群学生讲医疗器械监管法规的节目，有兴趣可以找来听听。

第二，医疗器械研发难度。或许有人觉得创新药研发九死无生，然后会默认医疗器械研发相对要简单很多，但事实是二十个研发里面能活一个已经谢天谢地了。而它研发的周期，如果想做到尖端，那么比起创新药也是不遑多让的，所以它的壁垒其实非常高。

说完这两点，就可以直接切入正题，我觉得微创医疗的价值在哪呢？我觉得也有两点，分别对内和对外。

对内。从最近信达的事情就可以看出不管是药还是械，想要通过药监局获批，还没跨过上市的门槛已经是千难万难。那么一个很现实的问题就是，一家企业从头开始按照各自不同的医疗器械监管法规慢慢整理出队伍和数据去获批好，还是说在一个平台上直接利用早已老练的队伍去获批好？我认为这是不言而喻的，微创就是这样一个平台。这个平台有耐心，有底蕴接下研发的担子，然后将剩下的事情交由统一的队伍去执行，而不是各自为战。一个火鹰支架敢花上十几年时间，电生理也花了十几年，现在市值比母公司还高的机器人也是从2014年开始做、到现在也刚刚有临床成功案例。所以我认为对内微创的价值在于它是一个资源整合性的创新平台。

对外。过去有人遐想微创旗下二十几个子公司不是世界第一就是第二，万亿市值近在眼前，触手可及。这是微创股价七十多的时候，故事延续到了未来七百港币一股，可现在已经沦为赔钱货、吸血鬼，微创母公司也成了早晚被掏空的控股公司，故事延续到了资不抵债、破产清算。但这是在瞬息万变的资本市场，在实际医疗情况下呢？随着微创旗下产品越来越多上市，越来越广泛铺开，就会发现无论在哪个细分子行业都会有微创的产品，而且这个产品还不赖，甚至可以说极好。有人质疑微创的经营能力，原因就是十几年如一日的亏损，还看不到头，但显然这种质疑所理解的经营与微创所理解的经营并不是一回事。微创所经营的是一家公司严格意义上可以拥有的最大无形资产，那就是这家公司的品牌。所有的子公司在“微创”这个品牌下一荣俱荣、一损俱损，而微创所产出的子公司就是这个品牌的一张张名片，只有在某个领域达到极致，然后上市，然后这个品牌才能够持续下去，才能够更加强大，它所带来的效应我认为不需要几年就能慢慢看出来。

* 20220104 关于药械国际化

关于国际化。我在去年四月份也写过一小段短文，并不看好现在的国际化，现在我依然不看好，或者说不能全指望用国际化破局。过去曾经了解日本药械企业的成长，他们确实靠着国际化成长到现在，但中国不是日本，中国药械企业也不等于日本的药械企业，简单的复制成功经验永远都是最落后、最低效的。

首先一个前提，目前中国的药械企业要比目前一等的全球化药械企业无论在技术上、还是在销售上弱的。这就相当于总体上在拿自己不擅长的偏要往别人最擅长而且惯用的地方使劲，永远都是事倍功半的，叠加现在的外部环境，那么这个事倍功半还要继续打个大折扣。

对中国自身而言有两大优势，足以在未来、也包括现在养活自己的创新药企。

第一、无论药械都是工业化制品。既然是工业化制品，那么就符合工业化的规律，即制造越多成本越低，对于药械这种完全标准化的产品，成本的下降可以低到不可思议的程度。中国的人口基数决定它发展起来就有其他国家难及的使用量，量变终将引发质变。而在另一方面，中国拥有大量相对低成本、但一样高学历的人才，CRO就是这么起来的，CRO能够凭借这个起来，难道其他地方就没有这个优势了吗，乃至其他行业就没用这个优势了吗？制作低成本、人员低成本，两个低成本，这是中国药械企业绝对的优势，如果再加一个高水准呢？

第二、医保支付能力。如果按照一般说法，中国的医保余额会在二零三几年完全耗尽，以此论证出集采的必要性。但只要按照这个算法，所有发达国家有一个算一个、包括美国他们的医保早就破产了，但事实是他们的医保始终维持在一个相当高的水准上，这是因为医保支付能力先看国家GDP后看国家发债能力，最后还可以加个商业保险的补充。为什么说国际化一个在美国，一个在欧洲，一个日本，因为他们首先就是GDP世界领先的、然后就是发债能力强的。所谓发债能力看的就是国家主权货币，有主权货币然后才能谈发债能力。东南亚一众国家、非洲一众国家、中东一众国家，他们自身GDP体量较小且并不稳定，然后在货币上又牵制于人，所以创新药械国际化难普及到他们。但所有的问题都可以靠相对的低价一定程度上解决，谁的低价，谁能低价？重回原题，我的结论：GDP决定医保支付的大致体量和增长可能性，发债能力则决定这个国家能养活多少创新药企。这才是发达国家的经验，要不要走发债老路先不谈，这或许不是条可循环的好路，所以需要探索，但中国医保支付能力无论在GDP、还是在发债能力都是有保障的。
