#+TITLE:  判断获得的关于认识的充足理由律
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

[[./as1-2.主体对象的第二概念层次.org][主体对象的第二概念层次]]
[[./as1.充足理由律的四重根-1813.org][充足理由律的四重根 1813]]

如果一个判断想要表达任何种类的认识，它就必须具有一个充足的理由，借助这种性质，这个判断才获得真实的谓词。这样，真理就成为一个不同于某件事物本身的被称之为该事物的理由或根据的判断的联系，关于判断的理由的认识曾经被认为是理性的最高功能和根本任务。

使判断能够建立的根据可以分为四个不同种类，通过判断获得的真理，也将相应地有所不同。

- 逻辑的真理

一个判断可以有另一个判断来做自身的理由，在这种情况下，这个判断便有了逻辑的或形式的真理，但不等于具有或据以建立的判断系列具有一个实质的真理。这种推演就是一个完整的三段论，或者产生于对当法，或者产生于小前提，绝不涉及判断以外的任何其他东西。整个三段论的科学就是关于将充足理由律运用于判断间的相互关系时的各种规则的总和，因而也就是逻辑的真理的准则。

通过四个思维规律[fn:1]而使自身的真理显而易见的那些判断，本身也必须同样被看作以另外一些判断为基础，因为这四条规律本身恰恰就是判断，另外那些判断的真理就是由此产生的。

如果说逻辑学的*内在的真理*至今已被归结为一切唯独以思维的四个规律为基础的判断，也就是说如果这些判断已被直接地判定为真的，并且如果说这种内在的逻辑的真理由于被归结为一切具有另一个判断作为自己的理由的判断而同外在的逻辑的真理区分开了，我是不能赞同的。每一个真理都是一个判断与某种外在于它的东西之间的关系，而内在的真理这个提法是自相矛盾的。

- 经验的真理

一个判断可以建立在第一表象层次、即经验的基础之上，这样的判断具有*实质的真理*，而且如果它直接地建立在经验之上，那就是经验的真理。

这个判断的各个概念是按照它由以被推出的直觉表象的要求而连接、分离和限制的。获得这种认识是判断力的直接功能，这是认识的直觉能力与抽象推论能力之间的中间环节，是知性与理性的中间环节。

- 超验的真理

存在于知性和纯粹感性之中的各种形式的直觉的、经验的认识，作为一切可能经验的条件，可以是一个判断的根据，在这种情况下是先验综合判断。

这种判断具有实质的真理，由此它的真理是超验的，不仅以经验为基础，而且也以存在于我们之中的*一切可能经验的条件*为基础。[fn:2]

- 超逻辑的真理

一个判断可以建立在包含在理性之中的一切思维的形式条件上，即为超逻辑的真理。

当理性在致力于对四个规律[fn:1]相抵触的思维时毫无结果，它认识到这些规律是一切可能的思维的条件。假如对于主体来说认识自身是可能的，那末这些规律就将直接地被我们所认识，并且不在把它们放到对象、也就是表象上去试验。在这方面，这恰好与那些具有超验的真理的判断的理由一样，因为这些理由也并不直接地进入我们的意识，而首先以具体的方式，通过对象（表象）才进入我们的意识。

在超验的真理和超逻辑的真理之间存在非常的相似性和联系，这表明这两种真理是产生于一个共同的根据。我们在本章看到充足理由律主要是作为超逻辑的真理，而它又可以作为超验的真理而表现出来。正因如此在本书中，我为要把充足理由律确立为一个有四重理由的判断而煞费苦心，并不是四种不同的理由偶然地导致一个相同判断，而是一个理由从四个方面把自己展示出来，这就是所谓的四重根据。

如果在超验的真理中为另外三种超逻辑的真理寻求一个同源语，那么为选中的一个就是：实体，指的是物质，不灭的。

[[./as1-2yb.对理性的认识的观点.org][对理性的认识的观点]]

[fn:1] P109 同一律、矛盾律、排中律、认识的充足理由律。
[fn:2] P111 整个纯粹数学，同样，我有关先验的文章以及康德《自然科学的形而上学基础》中的大部原理，严格来说都可以被用来证实这种真理。
