#+TITLE:     充足理由律的四重根 1813
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

*先验的法则，理性是本质的，预先就假定自然同自身的一致。*

* 归同法则；统一律 homogeneität

通过观察事物的类似性和一致性，把事物综合为类，再由类到种、由种到属，如此等等，直到最后达到最有概括性的概念为止。

14 世纪逻辑学家、圣方济各会修士奥卡姆的威廉：“如无必要，切勿增加实体的数目。”

* 分异法则；分解律 Specifikation

把同一个综合概念中的不同的属彼此加以区分，不应当混淆每一个属中较高级的种和较低级的种，不要跳过任何下级的种，更不直接在综合概念下将它加以分类。每个概念都允许再行划分，不过没有一个会退回到单纯的直观。

#+begin_quote
康德：“不要轻率地减少实体的多样性。”

康德 纯粹理性批判 1781 B871：“把就其类别和起源而言彼此有别的知识隔离开来，并小心翼翼地防止它们与其他在应用中通常相结合的知识混为一体，这是非常重要的。化学家在分解物质时、数学家在其纯粹的量的学说中所做的事情，哲学家更有责任勉力为之，以便能够准确无误地规定一个特殊种类的知识在四处漫游的知性应用那里所占的份额、其自身的价值和影响。”
#+end_quote

* 充足理由律：任何事物都有其为什么存在而不是不存在的理由

一切事物必有其理由的先验假设，使之有权在任何地方去探求为什么，才有把握地把这个为什么称为一切科学之母。
充足理由律都能使我们有理由去询问一个为什么，这是它的一个本质的性质。

- 理由 Grund：认识和证明一个事物的存在
- 原因 Ursache：认识和证明一个事物为什么存在
[[./descartes-spinoza.org][笛卡尔和斯宾诺莎对上帝、存在、理由的看法]]

#+begin_quote
凯斯维特 Kiesewetter 《逻辑学》：“逻辑的理由（认识的理由）与事实的理由（原因）是不能混淆的。充足理由律属于逻辑学，因果规律则属于形而上学。前者是思维的基本原则，后者则是经验的基本原则。原因涉及真实的事物，逻辑的理由则只是用于观念。”
#+end_quote

诸如完美、无限这些属性就是一个既定观念的本质，没有这些属性，这个观念就不会被理解。这些属性本身的本质属性，同样可以由纯粹的逻辑分析而得知，结果就有了逻辑的真理，这就是它们在既定的观念中具有认识的理由。于是现实性或存在这种属性也可以从这种武断的思维观念中抽取，与之相应客体立即被断定为独立于这一观念而真实存在着。

#+begin_quote
亚里士多德《后分析篇》第七章：给一个事物下定义同证明它的存在，永远是彼此分开的两码事；因为其中一个告诉我们这个事物是什么意思，而另一个则是指这样一个事物是存在的。他说：“存在并不属于一个事物的本质，因为存在并不是一种特性。”
#+end_quote

如果一个观念潜在包含了它所有的本质属性，那么只通过分析判断就明显地从这个观念中把这些属性展示出来，它们的总和就是这个观念的定义——这个定义与其观念本身只是形式上的差别，并无内容的不同。就这些判断表现出它的本质来说，它们有在观念中存在的理由。从它们的理由来考察，也可以把这些判断看成那个观念的结论。

** 关于充足理由律的证明

由于每一个证明都是某种已被认识了的事物的依据，并且如果我们对这件事物继续要求证明，不论怎样，我们最终都会得到这样一些命题，这些命题表达了一切思维和认识的形式和规律，因而也就是表达了它们的条件，从而，一切思维和和认识也就在于这些命题和条件的运用。这样，确定性不过就是与这些条件、形式和规律的一致，因此它们自身的确定性是不能再由其他命题来证明的。

我们进行认识活动的意识，把自身体现为内在的和外在的感性（或说接收力）以及知性和理性，又进一步把自己划分为主体的和对象的，此外还包含着无。成为主体的对象和成为我们的表象是同一回事。所有我们的表象都是主体的对象，而所有主体的对象都是我们的表象。我们的全部表象都在一种有规律的联系中相互依赖，这种有规则的联系可以被确认为*先验*的，并且正因为是这样，任何彼此独立的存在物，任何单个的或孤立的东西，都不能成为我们的对象。充足理由律从自身的“普遍”意义上所表明的，就是这种联系。

- [[./as1-1.主体对象的第一表象层次.org][主体对象的第一表象层次]]
    - [[./as1-1y.以因果规律形式为据关于生成的充足理由律.org][以因果规律形式为据关于生成的充足理由律]]
    - [[./as1-1yb.先验的知性与因果规律.org][先验的知性与因果规律]]
    - [[./as1-1ybs.休谟因果到康德先验.org][休谟因果到康德先验]]

-----

- [[./as1-2.主体对象的第二概念层次.org][主体对象的第二概念层次]]
    + [[./as1-2y.判断获得的认识的充足理由律.org][判断获得的关于认识的充足理由律]]
    + [[./as1-2yb.对理性的认识的观点.org][对理性的认识的观点]]

-----

- [[./as1-3.主体对象的第三直觉层次.org][主体对象的第三直觉层次]]_+空间和时间关系的关于存在的充足理由律
