#+TITLE: 小逻辑 1817
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

* 哲学不可以假定表象所直接接受的为其对象，不可以假定在认识的开端和进程里有一种现成的认识方法。

哲学对象类似宗教对象。

哲学是以思想、范畴，或更确切地说，是以概念去代替表象。

具有思想与概念是一回事，知道符合这些思想和概念的表象、直观、情绪又是一回事。

假如哲学的看法与宗教的观念之间出现了差异，哲学必须辩明它的各种规定何以异于宗教观念的理由。

- [[./hg1-y0.哲学以真理为对象.org][哲学以真理为对象]]
- [[./hg-y1.哲学以有限事物的世界为对象.org][哲学以有限事物的世界为对象]]

** 就思想的全部普遍性而言，它就是理念或绝对。关于理念或绝对的科学，本质上应是一个体系，因为真理作为具体的，它必定是在自身中展开其自身，而且必定是联系在一起的和保持在一起的统一体，换言之，真理就是全体。全体的自由性，与各个环节的必然性，只有通过对各环节加以区别和规定才有可能。

哲学的每一部分都是一个*哲学全体*，哲学的理念在每一部分里只表达出一个特殊的规定性或因素。部分也是整体，只有打破它特殊因素予之限制，从而建立更广泛的整体而成必然的环节，进而终成理念全体。

各部门的初步划分，正如最初对于理念的认识一样，只能是某种预想的东西。达到概念的概念，自己满足自己，自己返回自己，哲学这门科学可以分为三部分：
须认识到个别部门的科学，每一部门的内容既是存在着的对象，同样又是直接地在这内容中向着它的较高范畴（kreis）的过渡，不曾并列，更非静止。

- 逻辑学，研究理念自在自为的科学。
- 自然哲学，研究理念的异在或外在化的科学。
- 精神哲学，研究理念由它的异在而返回到它自身的科学。

* 逻辑学研究纯粹理念，所谓纯粹理念就是思维的最抽象的要素所形成的理念。

就思维的通常主观的意义，思维是精神的许多活动或能力之一，与感觉、直观、想象、欲望意志等并列杂陈 → 思维活动的产物，思维的形式或规定性一般是普遍的抽象的东西。思维作为能动性，因而便可称能动的普遍 → 既然活动的产物是普遍性的，则思维便可称自身实现的普遍体 → 就思维被认主体而言，便是能思者，*存在的能思的主体的*简称就叫我。

- 感性事物与思想的区别在于前者的特点是个别性的。既是个别之物也是彼此联系，所以凡是感性事物都是些彼此相外 Aussereinander 的个别东西，它们确切抽象的形式，是彼此并列 Nebeneinander 和彼此相续 Nacheinander 的。[[./engels-sensibility.org][恩格斯讨论感性相外、并列、相续问题]]

- 多种个别化的、简单的规定或谓词，不管有无内在联系，勉强连缀在一起，这些谓词虽以其主词为联系，但它们之间仍然是互相外在的。表象与知性的区别，在于知性尚能建立普遍与特殊、原因与效果等关系，从而使表象的孤立化的表象规定有必然性的联系，而表象只能让这些孤立化的规定在模糊的意识背景里彼此挨近排列。二者的区别还具有更大的重要性，因为一般讲来，哲学除了把表象转变为思想，更进一步把单纯抽象的思想转变为概念之外，没有别的工作。

思维和对象的关系是主动的，是对某物的反思，因此思维活动的产物、普遍概念就包含有事情的价值，亦即本质、内在实质、真理。

- [[./hg1-y2.反思的客观思想.org][反思的客观思想]]
- [[./hg1-y3.有限的无限的思维.org][有限的无限的思维]]

-----

- [[./hg1-s1.形而上学本体论.org][形而上学本体论]]
- [[./hg1-s2.形而上学理性心理学&灵魂学.org][形而上学理性心理学&灵魂学]]
- [[./hg1-s3.形而上学宇宙论.org][形而上学宇宙论]]
- [[./hg1-s4.形而上学自然的或理性的神学.org][形而上学自然的或理性的神学]]

-----

- [[./hg1-sf.经验主义.org][经验主义]]
- [[./hg1-sy.批判哲学.org][批判哲学]]
