#+TITLE: 主体对象的第一个层次 - 表象层次
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

[[./as1.充足理由律的四重根-1813.org][充足理由律的四重根 1813]]

主体对象的第一个层次就是直观的、完整的、经验的表象层次。这些表象的形式就是内在和外在的感觉形式，或者说时间和空间。

两种经验的表象形式都有着根本的区别，这是由于对其中一个来说本质的东西，对于另一个来说不具有任何意义。然而经验的从属于实在有序复合体的表象，还是在这两种形式中同时出现，而且两种形式的内在统一就是实在的条件。

- 假如时间是这些表象唯一形式，那么就不会有共存，因而也就没有任何永恒的东西，也不存在延续。因为时间只有被充实才能被感知，而且它的进程只有通过充实于其中的东西所发生的变化才能被感知。因此，一个对象的永恒只有同另一个与之共存的对象所发生的变化相对照，才能被认识。
  - 对于现象来说一个跟着另一个而无须一个来自另一个，因果规律依然可以断定每一个变化都是另一个变化的结果，只是每一个变化不仅跟随另一个作为其原因的单个变化，而且也跟随着与这个原因同时发生的一切其他变化，不具有任何因果连续。在时间中的彼此之间不具有因果联系的事件的连续，恰恰就是称之为偶然性的东西，能够在我的理解中被客观地确定，而不是被意志所主观地确定。
- 假如空间是这些表象唯一形式，一切事物都是互相并列的，那么就会不存在有变化，因为变化是状态的连续，而连续只有在时间中才是可能的。

经验的实在，尽管只是就知性而言，从这些形式的相互渗透中产生了，而且是作为一种集合的表象产生，形成一个复合体。属于这一层次的每一单个表象都是复合体的一部分，都按照先验的法则来取得自己在其中的位置。[fn:1]

- 如果我们对一个对象的客观性加以抽象，或者说对它被表象出来的东西加以抽象，如果把它作为对象的性质去掉然而却希望保留些什么，我们所遇见的就只能是主体。相反，如果我们对主体的主观性进行抽象而又想得到留下来的东西，那么这就将走向唯物主义。

就身体器官是我们关于一切其他对象的知觉的起点，也就是中间环节来说，在本书第一版，我把它称为直接的对象。但这种直接的把握并未使身体本身成为一个可知觉的对象，相反到此为止，一切依然是主观的，也就依然是感觉。即便从这种感觉产生对作为这种感觉的原因的所有其他对象的知觉，并且这些原因也作为对象把自身呈现给我们，但对于身体本身来说不是这样，仅仅为意识提供感觉，我们对身体的这种客观认识也仅仅是间接的。

实在论忘记了对象如果离开了与主体的关联就不成其为对象，并且如果我们撇开了这种联系，或者想把它撇开，我们也就立即消除了一切对象的存在。莱布尼茨虽然清楚地感觉到了主体是对象的必要条件，然而却没有能够摆脱对象是凭借自身而存在并且是不依赖于任何一种同主体的关系而存在、即不依赖于它的被表象而存在的思想。

#+begin_quote
[[./hg1.小逻辑-1817.org][小逻辑 1817]] P99 经验一切取决于用什么样的精神 Sinn 去把握现实。一个伟大的精神创造出伟大的经验，能够在纷然杂陈的现象中洞见到有决定意义的东西。理念是当前存在的，也是现实的，并不是某种远在天外隐在物后的东西。
#+end_quote

[fn:1]: 目前这个关于经验的实在的粗略轮廓，将在 作为意志和表象的世界 1818 第一卷第四节中进一步完善起来，在那里，将对知性导致这种统一并因而为自己本身创造了经验世界的方式，做出周密的解释。读者还可以从附于同一本书第二卷第四章“时间、空间和物质的先天知性概念”中得到非常重要的帮助，我建议读者对此能给以足够的注意：因为它特别表明在因果关系的形式下面，时间与空间的对立是怎样作为结果而在物质中均等地得到平衡的。
