#+TITLE: 主体对象的第二概念层次
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

[[./as1.充足理由律的四重根-1813.org][充足理由律的四重根 1813]]

人类在自己大脑中容纳其他来自于直觉表象的抽象表象，被叫做概念，因为每一个概念都在自身之中，确切说是在自身之下，都包含了无数的个别事物，并由此构成综合。可以把这种表象定义为来自于表象的表象，抽象的能力把完整的、直觉的表象分解为它们的组成部分，以便规则地分别思维每一个部分，亦必然丧失它们的*可知觉性*。通过舍弃众多在知觉中提供的东西形成概念，使剩余的部分能够通过自身而被思维，因此概念就是一种小于知觉范围的思维。[fn:1]

抽象概念的表象如果不在我们的感觉种被一些任意的符号固定和保留下来，就将从意识中溜掉，并且从它们注定要参与的思维过程看对意识毫无用处，这些符号就是文字。

- 概念所包含的内容少于它们由以抽取出来的表象，所以概念也就比表象更加容易处理，因此能够只去思考所有这些表象种的为每一个别的目的所要求的那些部分和关系。[fn:2]
- 最严格的含义就是理智借助于概念的占有：现在放在我们面前的这一层次的表象在我们意识中的呈现，也就是所谓的反思。
- 反思给人以深入思考的能力，能够在一个概念下思考许多事物，又始终只是思考每一事物中的本质部分，能够按照自己的意愿去舍弃任何一种区别，甚至舍弃在时间、空间上的区别，并且就此获得在思维种进行概括的能力，对过去和将来、对不存在的东西。

思维以文字进行抽象反思，严格地把自己保持在自己固有的范围内，或者为了同知觉表象达成一个知性而涉及到了知觉表象的界限，以便使经验所给予并为知觉所把握的东西同清晰的反思所导致的抽象概念联系起来，并且由此而达到对它的完全占有。因此在思维中，不是在探索概念或者既定知觉所从属的规则，就是探索对既定的概念或规则予以证明的特殊场合，思维就是*判断力*的活动，（按康德的划分）在第一场合是反思的活动，第二场合是归纳的活动。

- 判断力是直觉认识和抽象认识之间的中间环节，或者说是知性和理性之间的中间环节。
- 思维并不是抽象概念在意识中的直接呈现，毋宁说是逻辑学在判断理论中所表明的在各种限制和修饰下两个或更多的抽象概念间的联系或分离。被清晰地思想和表达出来的概念之间的这种关系，称之为判断。

[[./as1-2y.判断获得的认识的充足理由律.org][判断获得的关于认识的充足理由律]]

[fn:1] P101 舍弃属于每一个表象的不同的东西而把它们共同的东西保留下来，那末结果就将是这些种的属。所以属的概念就是在扣除那些不为每一个种所具有的东西后，在其中包含了每一个种概念的概念。这样，由于每一个可能的概念都可以被认为是一个属，所以一个概念就始终是一个一般的东西，并且因此而是不可知觉的。由于这个原因，每一个概念也都有着自己的领域，作为在其中所能被思维的东西总和。在抽象思维中，我们上升越高，所舍弃的也就越多，因而剩下的要被思维的东西也就越少。最高的也就是最一般的概念，是最为空洞和最为贫乏的，最后就成了纯粹的外壳，诸如存在、本质、事物、形成等等。
[fn:2] P105 当我们利用这样的概念表象时，我们总是意识到了这些表象并不满足于它们所体现的概念，并且充满了任意的规定。
