#+TITLE:  对理性的认识的观点
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

[[./as1-2y.判断获得的认识的充足理由律.org][判断获得的关于认识的充足理由律]]
[[./as1.充足理由律的四重根-1813.org][充足理由律的四重根 1813]]

为自己的杜撰和捏造需要理性的地盘和名称，或者说为那种完全虚构的能力而要求理性的地盘和名称，帮助从康德使之自身陷入的困境中摆脱出来：虚构的是一种直接的、形而上学的认识能力，是一种超越于一切可能经验的认识能力，它能够从事物本身和事物的关系中直接把握事物和世界——因而它首先是上帝的意识，它直接地认识出上帝就是主宰，先验地对上帝创造宇宙的方式加以解释，如果听起来太平常，那末就是先验地解释上帝从自身之中制造出宇宙的方式，或者说上帝在一定程度上通过多少必要的有生命的过程把宇宙生产出来的方式，再或者作为一种最为简洁的程序把宇宙“解散”并让它自己发展。

按照最大胆的说法，理性有一种对于绝对的直接的直觉，甚至有一种无限的不受约束性及其向有限展开的不受约束性。另一些不那么大胆的人则认为，理性接受这一信息的方式，与其说带有视觉的性质，不如说带有听觉的性质，只是听到了发生在云雀国[fn:1]中的事情，然后如实地把它所得到的东西转达给知性。按照耶可比的一个双关语，德文中关于理性的名称 Vernunft 也是从改了装的 Vernehmen （听见）那里派生出来的，而它又显然是来自于由语言来传达并以理性为条件的 Vernehmen，从而也就指明了对于文字的独特的知觉及其含义，这与动物也具有的单纯感性的听觉是对立的。最谨慎的则又主张，理性既不能去看也不能去听，因此接收不到所有这些神奇的画面和音响，包含着一种单纯的模糊的“惩戒”（Ahndung），或对这些东西的焦虑。但是把这个词中的 d 去掉，从这个字中得到的独到感觉步入殿堂，转而为知。

我的主张是这样的：一切在我们整个认识能力中固有的东西，因而一切先验的并独立于经验的东西，都严格地局限于认识的形式部分，也就是说局限于关于理智的特殊功能的意识，以及关于这些功能可能发生作用的唯一方式的意识。但是，为了提供物质的认识，所有这些能力就都需要来自外部的物质。因此在我们之中存在着外部的、客观知觉的形式——时间和空间、还有因果规律，它作为知性的纯粹形式使知性能够构造出一个客观的、有形的世界。

- 抽象认识的形式部分被放在逻辑之中探讨，逻辑即称之为关于理性的理论。但正是这个逻辑同时也构成那些涉及全部逻辑规律的判断和结论的概念，在质料和内容上必须依赖于直觉的认识，就像产生出这种直觉认识的知性在为它的先验形式提供了内容的质料上依赖于感觉一样。

以此，一切存在于我们认识中的物质的东西（一切不能被归结为主观形式的东西）不能被归结为个体的活动方式的东西，不能被归结为理智的功能的东西——也就是认识的全部质料——都是来自于外部。这就是说，最终是来自起源于感觉的、对有形世界的客观知觉。正是这种直觉的并就涉及物质内容而言的经验的认识，被真正的理性整理成为概念，并借助于文字感性地固定下来，这些概念又通过构成我们思维世界中的经纬线的判断和推理而为理性的无穷无尽的组合提供了质料。

- 理性从来不能从自身的源泉而提供或具有物质的内容，仅仅具有形式的内容，是逻辑学的对象，其中只包含思维活动的形式和对象。


[fn:1] P116 阿里斯多芬《云雀》第 821 页。
