#+TITLE: 先验的知性与因果规律
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

[[./as1.充足理由律的四重根-1813.org][充足理由律的四重根 1813]]

知性的主要作用就在于通过其特有的因果关系，连同以因果关系为前提的纯粹的感性形式时间和空间，从根本上创造和产生了由少数感官的原始材料组成的对象的外部世界。

知性借助于它本身的特有的形式，因而是先验的，把已知的肉体感觉设想为一个结果（唯独知性才能理解的一个词汇），这样的结果必然地包含了一个原因。它同时唤起同样现成地存在于它的理智（大脑）中的外感觉形式空间的协助，以便把这个原因移到机体之外。正是由于这样，外部世界才首次产生，只有空间才能使它成为可能，这就使先验的纯粹直观必须为经验的知觉提供基础。这种理智的作用并不是借助于概念和词句的推理和反思而从抽象中产生，相反它是一个直观的和完全直接的过程。只有这样，因而只是唯独在知性之中并且由于知性，真实的、客观的、充实于三维空间的有形世界，才按照相同的因果规律使自身得到体现，并进而在时间中变化和在空间中移动。

知性由于它所熟悉并且立刻便想象出来的东西而把通常的原因当成真的，尽管理性能够通过一条不同的途径而到达真理，因为知性的认识先于理性的认识，而理性的说教难以进入理智，所以幻觉（也就是知性的欺骗）便依旧故我，尽管谬误（理性的欺骗）已被排除。*由知性而正确得知的是实在，由理性而正确得知的是真理*，或者说，一个具有充足理由的判断，我们使幻觉与实在相对立，谬误与真理相对立。

- 一切动物，哪怕最低等的动物，都必定具有知性，也就是具有因果规律的知识，尽管在精细和明确的不同程度上具有这种知识，它们具有的知性至少满足它们的感觉所引起的知觉的需要。

[[./hume-kant.org][休谟因果到康德先验]] 超验的唯心主义者停留于对某种在经验上是真实的事物的错觉（某种存在于我们外部空间的事物的知觉），而不需要因果推论来赋予它实在性。只是在超验意义上，有什么可能存在于我们之外时，也就是当我们寻找*自在之物*时，因果关系才由于同知觉相关而被提到。

在我看来，因果规律的必然性在作为其产物的经验知觉中被消溶和消失了，因而在关于自在之物的完全超验的问题上是不能实行的。甚至时间和空间，正如康德所最终证明的，也是我们理智的主观形式。*经验知觉的一切要素都存在于我们内部*，并且其中所包含的任何东西都不能向我们提供任何关于一个与我们完全不同的自在之物的可靠指示。在物质概念下所想到的，是物体被抽去他们的形状和一切特性后所剩的残余：一个恰恰由于这个原因而必定在一切物体中都是相同的残余。[fn:1]

- 不去考虑这些形状和属性，剩下的就只是单纯的一般意义上的作用性，被客观地想象出来的纯粹作用本身、因果关系本身，也就是我们自身知性固有的反思，知性固有功能的外在化的图像；而物质也就是完全纯粹的因果关系，物质的本身也就是一般意义上的作用。[fn:2]
- 纯粹的因果关系，单纯的作用，不具有任何规定了方式的作用，不能成为可知觉的东西，因此也就不能进入任何经验内部，又成为因果规律为什么不能运用于物质本身的原因。_实体不灭规律

[fn:1] P84 这些被我们抽象出来的形态和属性，不过就是这些物体在其中发生作用的特殊的、专门规定了的方式。
[fn:2] P85 这就是为什么纯粹的物质不能被知觉，而只能被思想的原因，在思想它的时候，物质是被我们作为基础而附加到每一个实在上面的东西。
