#+TITLE:     休谟因果到康德先验
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs.css" />

[[./as1.充足理由律的四重根-1813.org][充足理由律的四重根 1813]]

P81 因果规律怎么能从经验得到，本身又什么时候在本质上被经验所预先假定？恰恰因为这绝不可能，并且因为洛克的哲学取消了所有的先验性质，休谟才否定了因果观念的全部真实性。在他《人类理智研究》第七节，指出两个错误的假说，一个关于意志的结果以我们身体的器官为基础，一个外部对象对我们强力的抵抗是因果关系的起因和原型。休谟按照自己的方式和观念体系反驳了这两个假说，而我的反驳如下：意志的行动和身体的活动之间，不存在任何因果联系，二者完全是同一回事情，只不过从两方面而觉察到。要想从根本上说明因果关系概念不依赖于任何经验，只有证明经验的全部可能性都是以因果关系概念为条件的。

P23 休谟所达到的结论，因果性不过是我们通过习惯而熟知的发生于时间中的一连串事件和状态的经验感觉。这个问题本身成了康德的深入研究的动力和起点，并通过这种研究导致了以往的唯心主义所不能比拟的一种更为深刻更为彻底的唯心主义观点。它导致了一种超验的唯心主义，从这里产生一种确信，从整体来说世界依赖于我们，正如我们在细节上依赖于世界一样。

P87 《纯粹理性批判》的一个主要目的是要表明对于一切经验来说的因果规律的普遍有效性，它的先验性质，以及作为必然结果的对于可能经验的限制。但我不赞同关于此规律的先验性的证明[fn:1]，按照这种观点真实对象中各种变化彼此相继的次序只是由于这些变化的因果联系才被我们客观地认识。因而我对彼此相随的现象之间客观联系的单纯的把握就成为十分不确定的，所把握的连续并没有使我有权对对象中的连续做出任何判断，更甚我可以将把握的知觉次序加以颠倒，那末也就不存在任何客观地去确定这些知觉的东西。相反我主张，经验知觉中的连续取决于由身体（身体即直接的对象）从另外一些对象那里获得印象的连续，因而也就是客观的连续，这是一种直接地在对象中（而不是间接地）产生，并且不依赖于主体意志的连续，因而是可以不借助于任何对身体不断发生作用的对象之间的因果联系而被正确地认识的连续。

P93 康德和休谟在各自的证明中犯了彼此相反的错误，休谟主张一切后果不过是单纯的顺序，而康德认定一切顺序必定是后果。纯粹的知性确实只能设想出后果（有原因的结果），并且不能想象出单纯的顺序，而顺序只能为纯粹的感性所把握。关于事件在时间中前后相继的经验知识，与事物在时间中一个跟随另一个的一般方式，前一种知识是由纯粹的感性所提供并以这种知性条件，后一种知识是由纯粹的知性所提供并以这种知性为条件。我的关于连续的观点是这样：从时间的形式中获得关于连续仅仅可能性的知识，这种知识属于纯粹感性的范畴，恰恰以时间为形式的真实对象的连续是被我们经验地，因而是作为现实的连续来加以认识的。但只是由于通过知性，借助因果规律，我们才得到两个状态连续的必然性的知识——得到了关于变化的知识，并且就连完全能够想像出一个连续的必然性的事实也已经证明了因果规律先验地赋予我们。充足理由律是对于我们一切对象，也就是一切表象之间的必然联系的基本形式的一般表述，位于认识能力最深处，是一切表象的共同形式，并且是必然性观念的唯一源泉，在它的理由被确立后，除了包含关于后果的相继的观念外不包含其他任何东西，也没有比这观念更重要。充足理由律所以决定了以因果规律为特征的表象层次在时间中的连续次序，理由是时间是这些表象的形式，因而也就是在这里出现作为连续规则的必然联系形式。

[[./hg1.小逻辑-1817.org][小逻辑 1817]]

P91 事物自身与我们对于事物自身的认识完全是两回事，这种观点特别是康德的批判哲学所发挥出来的，与前些时代认为事情 Sache[fn:2] 与思想相符合是不成问题的信心正相反对。这种思想与事情的对立是近代哲学兴趣的转折点。但人类的自然信念却不以为这种对立是真实的。在日常生活中，我们也进行反思，但并未特别意识到单凭反思即可达到真理；我们进行思考，不顾其他，只是坚决相信思想与事情是符合的，而这种信念确是异常重要。但我们这时代有一种不健康的态度，足以引起怀疑与失望，认为我们的知识只是一种主观的知识，并且误认这种主观的知识是最后的东西。但是，真正讲来，真理应是客观的，并且应是规定一切个人信念的标准，只要个人的信念不符合这标准，这信念便是错误的。反之，据近来的看法，主观信念本身，单就其仅为主观形式的信念而言，不管其内容如何，已经就是好的，这样便没有评判它的真伪的标准——前面我们曾说过，“人心的使命即在于认识真理”，这是人类的一个旧信念，这话还包含有一层道理，即任何对象，外在的自然和内心的本性，举凡一切事物，其自身的真相，必然是思维所思的那样，所以思维即在于揭示出对象的真理。哲学的任务只在于使人类自古以来所相信于思维的性质，能得到显明的自觉而已。所以，哲学并无新的发明，我们这里通过我们的反思作用所提出的说法，已经是人人所直接固有的信念。

[fn:1] 康德《纯粹理性批判》德文第一版第 201 页；第五版第 246 页。
[fn:2] das Ding 一般译作 “物” 或 “事物”，das Sache 一般译成 “事情”，有时译成 “实质”，含有事物的 “内容实质” 之意。
