#+TITLE: 以因果规律形式为据关于生成的充足理由律
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

[[./as1.充足理由律的四重根-1813.org][充足理由律的四重根 1813]]

就所涉及的是对象状态的出现和消失而言，所有在我们表象的范围内呈现自身的对象都是通过它而被联结起来，也就是说，在时间的流动中形成了经验实在的复合体。

因果规律：当一个或几个真实的对象[fn:1]转变为任何一种新的状态时，另一个状态必定在它之前就存在了，新的状态根据这个在先状态而有规则地相继出现。这种前后相继称之为因果运动，伴随发生称之为变化，前一状态叫做原因，后一状态叫做结果。

- 当一种状态为造成一个新的状态的其他一切必要条件都已具备，而只缺一个条件时，这一个条件的最终来临，在某种意义上说就被称作是基本的原因，因为在这里得到了变化。但是如果排除这种考虑，那么任何作为原因状态的单一的条件，都不会仅仅由于它是最后出现而在确定因果联系的时候对其他条件具有一般的优先地位，从全面考虑的意义上说，只有导致它的后继状态出现的整体状态，才可被认为是原因。那些加在一起完成和构成原因的单个的必需物，可以被称作原因的要素，甚至称作原因的条件，所以原因是可以再进一步分解为这些要素或条件的。
- 因果规律的先验性质的唯一证明即这种先验性质任何时候都能从我们据以预期经验与因果规律相符合的绝对可靠性中找到确证，这种绝对可靠性被归之于因果规律的一种必然的确定性，这种确定性不同于任何其他以归纳为基础的确定性，根据这种确定性可以设想全部的经验世界中不存在因果规律的例外。

*因果规律是唯一并且专门涉及到物质状态的变化的，此外不涉及任何其他东西，因此如果不在讨论这些变化，就不应当引进因果规律。*

- 因果规律是一个预先的假定，是我们使它同我们一起来到世界上，借助于它我们对外部世界的知觉才成为可能的，正因如此我们才无权把来源于我们认识能力的原则扩展到我们认识能力的范围之外，使之独立于认识能力。

以因果规律为根源，产生两个必然结果作为先验的认识因而作为无可非议并且毫无例外的认识而被认可。

- 惯性规律。证明一个可能存在于其中的任何一种状态（静止状态以及任何一种运动状态），除非有某种原因伴随发生而将它改变或取消，必定是毫无变化、毫不减少或增大地保持原状。
- 实体不灭规律。因果规律只适用于物体的状态，但不适用于承受这些状态的存在，把这个存在称为实体[fn:2]，确切表明它是外在于一切产生和消失的。*实体既不能产生，也不能消失，在宇宙中存在的量既不能增加也不能减少。*[fn:3]

作为每一种变化的决定者的因果关系，根据三种不同形式使自己在自然界得到体现。

- 作为最严格意义上的原因的形式。使无机界中的变化随之产生的原因，也就是构成机械学、物理学和化学的主题的结果随之产生的原因，还阐明了在原因的状态承受着与它所造成结果的状态相等的变化。
- 作为刺激的形式。支配有机的生命世界，也就是支配着各种植物的生命和作为动物界生命中无意识部分的植物性成分，作用与反作用是不等的，原因的强化甚至可能导致相反的结果。[fn:4]
- 作为动机的形式。支配动物生命本身，也就是支配着一切动物外部的、有意识地进行的活动。动机的媒介就是认识，因而理智是为动机的感受性所需要的，动物的真正特征也就在于认识能力和表象能力。

原因、刺激和动机之间的区别显然只是存在物的接受性的不同程度的结果，接受性越强，所受影响的性质也就越可以微弱。“动机的形成”是经历认识的因果关系，理智是动机的工具，具有最高程度的接受性。再则人的双重理智，不仅具有直观的认识，也具有抽象的认识，这种抽象的认识并不局限于当前的东西。人具有理性，因而他具有运用明确的意识作出抉择的力量，能够对各种彼此互相排斥的动机进行权衡，换言之，*能够让这些动机在自己的意志面前进行较量*。

[fn:1] 真实的对象，这一术语表示的只不过是共同形成了经验实在复合体的各种直观的表象，其本身的实在性依然始终是观念上的。
[fn:2] 实体不过是物质的另一个名称。
[fn:3] P46 如果我们承认康德和拉普拉斯的假设，即假定每一个太阳系都由原始星云通过凝聚过程逐渐发展而来，我们就一刻也不会去设想原始的实体从无中产生的可能性：恰恰是由于实体不灭原则的超验性质，必须假定事先就存在着实体的微粒，以及由于某种原因它们聚集到了一起。
[fn:4] P50 一个动机只要被领悟就获得了结果，而刺激则始终需要有外部的，经常甚至内部的接触并且总是需要有一定的时间长度。
