#+TITLE: 哲学以有限事物的世界为对象
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

[[./hg1.小逻辑-1817.org][小逻辑 1817]]

研究有限事物的世界，研究自然界和人的精神，研究自然界和人的精神相互间的关系，以及它们与上帝（即二者的真理）的关系。

活生生的精神的范围、属于原始创造的和自身产生的精神所形成的世界，亦即属于意识所形成的外在和内心的世界。

*** 哲学必能熟知[fn:1]其对象，可以定义为对象的思维着的考察。

按照时间的次序，人的意识对于对象总是先形成表象，后才形成概念，而且唯有通过表象，依靠表象，人的能思的心灵才进而达到对于事物的思维的认识和*把握*。

- 意识的内容构成情绪、直观、印象、表象、目的、义务等等，以及思想和概念的规定性的要素，情绪、直观、印象等等就是这个内容所表现的诸形式。
- 这个内容，无论它仅是单纯被感觉着，或参杂有思想在内而被感觉着、直观着等等，甚或完全单纯地被思维着，它都保持为一样的东西。在任何一种形式里，或在多种混合的形式里，这个内容都是意识的对象。
- 哲学的内容就是*现实*（Wirklichkeit），这种内容的最初的意识便叫做经验。

对于思维的内容必须指出其必然性，对于思维的对象的存在及其规定必须加以证明，才足以满足对于事物作思维着的考察的要求。
足以令理性自身满足的形式，就是广义的必然性。

- 作为情感、直觉或表象等形式而出现，这些形式必须与作为形式的思维本身区别开来。
- 忽略了一般的思想与哲学上的反思的区别，会误以为这类的反思是我们达到永恒或达到真理的主要条件，甚至是唯一途径。[fn:2]
  + 想知道外界对象和事变，以及内心的情绪、直观、意见、表象等的真理必须加以反复思索（Nachdenken）。而对于情绪、表象等加以反复思索，无论如何，至少可以说是把情绪表象等转化为思想了。
  + 后思（Nachdenken）首先包含了哲学的原则（在此处兼有原始或开端的意义），在路德的宗教改革之后一开始就不是单纯的思想，而是指向现象界的无限量的材料方面，取材于人类对于外界和内心，对于当前的外界自然和当前的心灵和心情的自己的直观和知觉。
- 一般科学一方面基于直接的事实，给予的材料，或权宜的假设，主要目标在于求得规律、普遍命题或一种理论；另一方面以心灵对象为经验的知识无法把握，与之关系纯是外在的和偶然的，心灵对象彼此关系也是外在的和偶然的。这两种情形下都不能满足必然性的形式，所以凡是志在弥补这种缺陷以达到真正必然性的知识的反思，就是思辩的思维，亦即真正的哲学思维。这种思辩思维所特有的*普遍形式*，就是概念。
  + 哲学与科学的区别在于范畴的变换，思辩的逻辑包含有以前的逻辑与形而上学，保存有同样的思想形式、规律和对象，但同时又用较深广的范畴去发挥和改造它们。

哲学最高目的在于确认思想与经验的一致，并达到自觉的理性与存在于事物中的理性的和解，亦即达到*理性与现实的和解*。

- 对于同一内容的意识，哲学与别的认识方式既然仅有形式上的区别，所以哲学必然与现实和经验相一致，至少可以看成是考验哲学真理的外在的试金石。
- 黑格尔《法哲学原理》序言：“凡是合乎理性的东西都是现实的，凡是现实的东西都是合乎理性的。”

[fn:1] 黑格尔“熟知非真知”，即只是对眼前事物熟视无睹，未加深知。
[fn:2] 后思，德文作 Nachdenken，英文作 reflection，亦即反思。反思以思想的本身为内容，力求思想自觉其为思想。
