#+TITLE: 批判哲学
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

[[./hg1.小逻辑-1817.org][小逻辑 1817]]

批判哲学与经验主义相同，把经验当作知识的唯一基础，不过不以基于经验的知识为真理，而是仅把它看成对于现象的知识，首先把从经验分析中所得来的要素即感觉材料和感觉普遍联系两者的区别作为出发点。

- 一方面认为知觉本身所包含的只是个别的东西，只是连续发生的事情，一方面同时坚持普遍性与必然性对于构成我们所谓经验也有其主要的功能。因为这有普遍性和必然性的成分，是不能从经验的或感觉的成分产生，所以属于思维的自发性，或说先天的。思维的范畴或知性的概念构成经验知识的客观性。它们一般包含有联系作用，凭借这些范畴或概念的联系作用，形成先天的综合判断，也就是说形成了对立者的原始的联系。

首先按照主观性与客观性一般的对立的关系对形而上学以及别的科学上和日常观念中所用的知性概念的价值加以考察，*并未进入思想范畴的内容和彼此的关系*。[[./hg1-syb.纯知性范畴.org][纯知性范畴]]

- 这种对立，涉及经验两种成分的区别并将之扩大，所谓主观性包括经验的总体，把经验的两个成分都包括在内，除了*物自体*外更没有别的与主观性相对立的客观性了。
- 思维的特殊的先天形式虽然具有客观性，但仍然只是被认作主观的活动，用一种系统化的方式列举出来，而这些系统化的范畴，只是建筑在心理的和历史的基础上。

以此其主要课题是考察在什么限度内，思想的形式能够得到关于真理的知识，而不是未经思想考验便接受范畴。

- 康德特别要求在求知以前先考验知识的能力，即思维的形式本身叶必须当作知识的对象加以考察，但并不意味着在得到知识以前已在认识，所以必须在认识的过程中将思维形式的活动和对于思维形式的批判结合在一起。[fn:1]

通常意义总以为那与自己对立、感官可以觉察的是本身存在、独立不依的，反过来思想是依赖他物、没有独立存在的。但真正讲来，只有感官可以觉察之物才是真正附属的、无独立存在的，而思想倒是原始的、真正独立存在的。因此康德把符合思想规律的东西（普遍性和必然性）叫做客观的，感官所知觉的事物叫做主观的。

- 但进一步，所谓思维的客观性仍然只是主观，因为有普遍性和必然性的范畴却与*物自体*[fn:2]间有一个无法逾越的鸿沟隔开着。真正客观性应该是：思想不仅是我们的思想，同时又是事物的自身 an sich，或对象性的东西的本质。
- 客观性一词具有三个意义。第一为外在事物的意义，有别于主观、意谓、梦想；第二为康德所确认的意义（指普遍性与必然性），有别于感觉的偶然、特殊和主观；第三为上述提出的意义，指思想所把握的事物自身，有别于只是我们的思想，与事物的实质或事物的自身有区别。


[fn:1] P126 这种思想活动便叫做思想的矛盾发展 Dialektik，并不是从外面加给思维范畴，而毋宁是即内在于思维范畴本身内。
[fn:2] P132 这里所谓“物”也包含精神和上帝在内，表示一种抽象的对象。从一个对象抽出它对意识的一切联系、一切感觉印象，以及一切特定的思想就得到物自体的概念。这里所剩余的只是一个极端抽象、完全空虚的东西，只可以认作否定了表象、感觉、特定思维等等的彼岸世界，更可以简单看出这剩余仍不过只是思维的产物，只是空虚的自我或不断趋向纯粹抽象思维的产物。这个空虚自我把它自己本身的空虚的同一性当作对象，因而形成物自体的观念。
