#+TITLE: 经验主义
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

[[./hg1.小逻辑-1817.org][小逻辑 1817]]

以上述形而上学的蒙蔽，有两层需要：

- 要求一具体的内容，以补救知性的抽象理论，因为知性自身无法从它的抽象概念进展到特殊的规定的事实。
- 寻求一坚实的据点，以反对在抽象的知性范围内，按照有限思想规定的方法，去证明一切事物的可能性。

这两种需要首先有助于引导哲学思想趋向经验主义。经验主义力求从经验中，*从外在和内心的当前经验中去把握真理*，以代替纯从思想本身去寻求真理，两种需要均不是抽象的知性形而上学所能满足。这里所涉及的具体内容指意识的诸对象必须认为是自身规定的，而且是许多有差别的规定的统一。

形而上学为其界说（它的前提和它更确定的内容）寻求根据起见，也是从表象里、亦即首先从经验流出的内容里去求保证，而经验主义者将属于知觉、感觉和直观的内容提升为普遍的观念、命题和规律。但经验主义者把这类具体的内容抽象化，只有在这种条件下，这些抽象的原则或概念在其所从出的知觉印象之外便没有更广的意义和效用，而且除了在现象中即可说明的（因果）联系外，也没有别的联系或规律可以认为是合法的。所以经验的知识便在主观方面得到一坚实据点，这就是说，*意识从知觉里得到它自己的确定性和直接当前的可靠性*。

- 凡是真的，必定在现实世界中为感官所能感知。[fn:1]
- 凡我们认为应有效用的知识，必须亲眼看到，亲身经历到。

外在的世界为真实，虽然也承认有超感官的世界，但又认为对那一世界的知识是不可能找到的，因而认为我们的*知识须完全限于知觉的范围*。这个基本原则彻底发挥下去，就会成为后来的唯物论。[fn:2]

经验主义者难免不陷于一个根本错觉，应用物质、力以及一、多、普遍性、无限性等形而上学范畴，更进而依赖这些范畴的线索向前推论，因此便不能不假定并应用推论的形式。在这些情形下，经验主义中即已包含并运用形而上学的原则。

- 理性的驱迫力捉住这此时、此地、此物，无疑是具有无限的形式的，不过它们并非无限形式的真正实际存在。那外在世界本身是真实的，因为真理是真实的，而且必定有实际存在的。所以理性所寻求的无限原则是内在于这世界之中的，不过在感官所见的个别形象里，不足以表现其真正面目罢了。

经验主义者以知觉为把握当前实事的形式，但知识必进而在被知觉的个别事物中去寻求有普遍性和永久性的原则，这是由单纯知觉进展到经验的过程。

- 为形成经验必须主要地应用*分析*方法。这种分解过程的主旨即在于分解并拆散那些集在一起的规定，除我们主观的分析活动外，不增加任何成分。
- 经验主义在分析对象时陷入的就是自以为不增减改变任何成分，但却从知觉的直接性进展到了思想，将对象具体的内容转变成为抽象的了。
- 分析坚持事物的区别，但当区别仍然只是一些抽象概念，当这些思想被认作对象的本身时，便又退回到形而上学的前提，即认为事物的真理在思想中。

经验就其有别于*单纯的个别事实的个别知觉*而言有两个成分，一为个别的无限杂多的材料，一为具有普遍性与必然性的规定的形式。

- 经验呈现不可胜数的相同的知觉，但普遍性与一大堆事实完全是两回事。经验呈现前后相续的变化的知觉和地位接近的对象的知觉，但并不提供必然性的联系。如果把知觉当作真理的基础，普遍性与必然性便成为不合法的，一种主观的偶然性，一种单纯的习惯，其内容可以如此，可以不如此。
- 在这种经验的方式内，道德礼教的规章、法律以及宗教的信仰都显得带有偶然性，而失掉其客观性和内在的真理性。
- 休谟的怀疑论根本上假定经验、感觉、直观为真，进而怀疑普遍的原则和规律，由于他在感觉方面找不到证据。相对希腊的怀疑论，却远远没有把感觉直观作为判断真理的准则，反而首先对于感官事物的真实性加以怀疑。[fn:3]

[fn:1] P120 与经验主义一样，哲学也只认识什么是如此，凡是仅是应如此、而非是如此的事物，哲学并不过问。
[fn:2] P123 物质本身已经是一个抽象的东西，物质之所以为物质是无法知觉的。所以我们可以说没有物质这个东西，因为就存在着的物质来说，它永远是一种特定的具体的事物。
[fn:3] P135 如果把经验的事实认作构成思想之所以为思想的证件，那末无疑地就必须能在知觉中去准确地指出思想的本源。
