#+TITLE:     黑格尔谈神话的人类堕落
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs.css" />

[[./hg1-y2b.黑格尔认识形式.org][黑格尔认识形式]]
[[./hg1.小逻辑-1817.org][小逻辑 1817]]

P101 关于人的堕落的摩西神话，对于这种分裂的起源和后果曾经给了我们一个古老的观念。这个神话的内容形成了宗教信仰的理论基础，即关于人的原始罪恶及人有赖于神力的解救之必要的学说。试就人类堕落的神话加以仔细考察，便可看出，有如上面所说，这神话却表达了知识和精神生活间的普遍关系。精神生活在其素朴的本能的阶段，表现为无邪的天真和淳朴的信赖。但精神的本质在于扬弃这种自然素朴的状态，因为精神生活之所以异于自然生活，即在其不停留在它的自在存在的阶段，而力求达到自为存在。但这种分裂境地，同样也须加以扬弃，而精神总是要通过自力以返回它原来的统一。这样赢得的统一乃是精神的统一。而导致返回到这种统一的根本动力，即在于思维本身。这就是“击伤的是他的手，医伤的也是他的手” [fn:1]的意思。

神话中曾经这样说：亚当和夏娃，最初的人，或典型的人，被安置在一个果园里面，园中有一棵生命之树，有一棵善与恶知识之树。据说，上帝曾告诫过他们，禁止摘食知识之树的果子。关于生命之树暂且不提。这里所表示的意思，显然是说人不应寻求知识，而须长保持天真的境界。

再则，在摩西的神话里，使人离开那原始的谐和的机缘，乃是一外在的诱力，即蛇的引诱。其实，个人进入对立面，即是人本身意识的觉醒，这种受外力引诱是每个人所不断重演的历史。所以蛇的引诱象征善恶的分别，也包含在神性之内。而这种对于善恶的知识，实际上也是人所分享的。当人分有了这种知识时，他便享受了禁果，而与他自己的直接的存在破裂了。对自己的觉醒意识的初次反思，人们发现他们自身是裸体的。赤裸可以说是人的很朴素而基本的特性。他认裸体为可羞耻包含着他的自然存在和感性存在的分离。所以在人的羞耻的情绪里又可以找到穿衣服的精神的和道德的起源，而衣服适应单纯物质上的需要，倒反而只居于次要地位。

其次，尚须提一下上帝加诸世人的所谓谴责或灾难。天谴观念所着重之点，即在于指出天谴主要的关涉到人与自然的对立。男子应该汗流满面去劳动，女子应该忍受痛苦去生育。此种劳动，细究起来，一方面固是与自然分裂的结果，一方面也是对于这种分裂的征服。

摩西的神话，并不以亚当和夏娃被逐出乐园而结束。它还意味着更多的东西：“上帝说，看呀，亚当也成为相似于我们当中的一分子了，因为他知道什么是善和恶。”这些话表明知识是神圣的了，不似从前那样，把知识认为是不应该存在的东西了。在这里还包含有对于认为哲学只属于精神的有限性那样说法的一种显明的反驳。哲学是认识，也只有通过认识，人作为上帝的肖像这一原始的使命才会得到实现。这个神话又说到：上帝把人从伊甸园里驱逐出去了，以便阻止他吃那生命之树。这话的真义即在于指出就人的自然方面来说，他确是有限的，同时也是有死的，但就他在认识方面来说，他却是无限的。

教会上有一熟知的信条，认为人的本性是恶的，并称本性之恶为原始的罪恶。依这个说法，我们必须放弃一种肤浅的观念，即认原始罪恶只是基于最初的人的一种偶然行为。其实由精神的概念即可表明本性是恶的，我们无法想象除认人性为恶之外尚有别种看法。只要就人作为自然的人，就人的行为作为自然的人的行为来说，他所有的一切活动，都是他所不应有的。精神却正与自然相反，精神应是自由的，它是通过自己本身而成为它自己所应该那样。自然对人来说只是人应当加以改造的出发点。与这个有深刻意义的教会信条原始罪恶说正相反对的，便是近代启蒙时期兴起的一个学说，即认人性是善的，因此人应忠于他的本性。

[fn:1] 见《旧约全书・约伯记》第五章，中译本此句全文如下：“你不可轻看全能者的管教，因为他打破又缠裹；他击伤，用手医治。”
