#+TITLE: 有限的无限的思维
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

[[./hg1.小逻辑-1817.org][小逻辑 1817]]

思想对客观性第一态度是素朴的，没有意识到*自身所包含的矛盾和思想自身与信仰的对立*，却相信只靠反思作用即可认识真理，即可使客体的真实性质呈现在意识前面。

- 康德以前的形而上学认为思维的规定即是事物的基本规定，并根据这个前提，坚持思想可以认识一切存在，因而凡是思维所想本身就是被认识了的。它们认为抽象的孤立的思想概念即本身自足，可以用来表达真理而有效准，没有考察知性概念的真正内容和价值，也没有考察纯用谓词去说明绝对的形式是否妥当。
- 只能产生有限规定，并且只能在有限规定中活动的思维，便叫做知性。对有限事物必须用有限的名言以称谓之，这正是知性施展其功能的处所。

如果所有思维规定都受一种固定的对立的限制，这就是说，如果这些思维规定都只是有限的，那末思维便不适合于把握真理、认识绝对，而真理也不能显现于思维中。

- 思维规定的有限性有两层看法。第一，认为思维规定只能主观的，永远有一客观的（对象）和它们对立。第二，认为各思维规定的内容是有限的，因此各规定间即彼此对立，而且更尤其和绝对对立。
- 必须把有限的、单纯理智的思维与无限的理性的思维区别开。凡是直接地、个别地得来的思维规定，都是有限的规定。但真理本身是无限的，它不能用有限的范畴所能表达并带进意识的。
- 企图用有限的名词去规定理性的对象[fn:1]，就是旧形而上学的缺陷。再则这些谓词既是称谓一个主词的宾词，它们彼此间是有联系的，但就它们的内容而言，又是有差别的，所以它们都是外面拾取而来，彼此缺乏真正的联系。

思维的本质是无限的。就形式上讲，所谓有限之物指那物有它的终点，它的存在到某种限度为止，有限之物的持存在于它的对方有联系，这对方就是它的否定，并表明它自己就是有限之物的界限。但思维却自己在自己本身内，自己与自己本身相关联，并以自己本身为对象。

- 当思维思维它自己本身时，则思维的对象同时已不是对象了。换言之，此对象的客观外在性已变成被扬弃了的、观念的东西。思维的有限，只有当它停留在有限的规定里，并认这些有限规定为究竟至极的东西，反之一方面同样有规定，但一方面即在规定和限制过程中扬弃了规定和限制的缺陷。
- 有限与无限相互对立时，这本该认作代表全体的无限，仅表现为偏于一面，被有限所限制着的一面。但被限制的无限仍不过只是有限之物而已。
- 在逻辑学里，其内容须纯全为思想的形式所决定，如果将这些范畴用来作为上帝或较宽泛的绝对这类主词的谓词，不但是多余的，而且还令人误以为除思想本身的性质外尚另有别的标准。不仅如此，命题的形式，或者说判断的形式不适于表达具体的和玄思的真理，因为判断的形式总是片面，就只是片面而言，它就是不真的。

独断论坚执着非此必彼的方式，殊不知具体的玄思的真理恰好不是这样，恰好没有这种片面的坚执，因此也非片面的规定所能穷尽。玄思的真理包含有这些片面的规定自身联合起来的全体，而独断论则坚持各分离的规定，当作固定的真理。

说到自由思想，我们必须承认希腊哲学代表典型的自由思想，而经院哲学则否，因为经院哲学，正如这种形而上学，也同样接受一种现成给予的东西，亦即由教会给予的信条为其内容。我们近代的人，通过我们整个文化教养，已经被许多具有丰富深邃内容的观念所薰陶，要想超出其笼罩，是极其困难的。而古代希腊的哲学家，大都自觉他们是人，完全生活于活泼具体的感官的直观世界中，除了上天下地之外，别无其他前提，因为神话中的一些观念已早被他们抛在一边了。在这种有真实内容的环境中，思想是自由的，并且能返回到自己本身，纯粹自在，摆脱一切材料的限制。这种纯粹自在的思想就是翱翔于海阔天空的自由思想，在我们上面，或在我们下面，都没有东西束缚我们，我们孤寂地独立在那里沉思默想。

[fn:1] P109 东方的哲人用多名的说法去补救这一缺陷，譬如当他们规定神时便加给神许多名字，但同时也承认，名字的数目应该是无限多。
