#+TITLE: 哲学以真理为对象
#+OPTIONS: num:nil toc:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

[[./hg1.小逻辑-1817.org][小逻辑 1817]]

哲学以真理为对象，就真理的最高意义而言，上帝即是真理，而且唯有上帝才是真理。

纯思和概念的范围

通常我们总认为我们的表象应与这对象相符合叫做真理，这说法预先假定有一个对象，我们的表象应与这对象相符合。但反之，从哲学的意义来看，概况地抽象地讲来，*真理就是思想的内容与其自身的符合*。

** 凡是在意识内的都是可以经验的，它们的内容是无限的。

广义讲来，心灵（vovs）或精神（精神表示心灵的较深刻的意义）是世界的原因；狭义讲来，法律的、道德的和宗教的情绪其内容都只是以思维为根源和基地。

康德的批判哲学主要观点，即在于教人在进行探究上帝以及事物的本质等问题之前，先对于认识能力本身作一番考察工夫。但要想执行考察认识的工作，却只有在认识的活动过程中才可进行。考察所谓认识的工具，与对认识加以认识，乃是一回事。

** 哲学的要求可以是这样的：精神，作为感觉和直观，以感性事物为对象；作为想象，以形象为对象；作为意志，以目的为对象。但就精神相反于或仅相异于它的这些特定存在形式和它的各个对象而言，复要求它自己的最高的内在性，思维的满足，而以思维为它的对象。

认识到*思维自身的本性即是辩证法*，认识到思维作为理智必陷于矛盾、必自己否定其自身这一根本见解，构成逻辑学上一个主要的课题。

思维进展的次序总是超出自然的、感觉的意识，超出自感觉材料而推论的意识，提高到思维本身纯粹不杂的要素，因此首先对经验开始的状态取一种疏远的、否定的关系。这样，在这些现象的普遍本质的理念里，思维才得到自身的满足。

- 关于上帝的知识的独立性，本质上即是通过否定感官经验与超脱感官经验而得到的。但假如对知识的间接性加以片面的着重，把它认作制约性的条件，那末便可以说哲学最初起源于后天的事实，是依靠经验而产生的（其实，思维本质上就是对当前的直接经验的否定）。

思维自身的反思，从而达到经过中介的直接性，这就是思维的先天成分（das Apriorische），亦即思维的普遍性，思维一般存在它自身内。在普遍性里，思维得到自身的满足，但假如思维对于特殊性采取漠视态度，从而思维对于它自身的发展，也就采取漠视态度了。

- 经验科学的激励补救思维的这种抽象普遍性，一方面经验科学并不停留在个别现象的知觉里，乃是能用思维对于材料加工整理，发现普遍的特质、类别和规律，以供哲学思考；另一方面经验科学也包含有思维本身要进展到这些具体部门的真理的迫切要求。这些被吸收进哲学中的科学内容，由于经过思维的加工，从而取消其顽固的直接性和与料性，同时也就是思维基于自身的一种发展。
