#+TITLE: 反思的客观思想
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

[[./hg1.小逻辑-1817.org][小逻辑 1817]]

反思作用总是去寻求那固定的、长住的、自身规定的、统摄特殊的普遍原则，这种普遍原则就是事物的本质和真理。当规定普遍时，便与单纯直接的、外在的和个别的形成对立。普遍作为普遍是人所不见不闻，只对精神而存在的。[[./hume-kant.org][休谟因果到康德先验]]

在思维内即直接包含自由，因为思想是有着普遍性的活动，因而是一种抽象的自己和自己联系，换言之，就思维的主观性而言，乃是一个没有规定的自在存在，但就思维的内容而言，却又同时包含有事情及事情的各种规定，只有思维深入事物的实质，方能算得真思想。[[./hg1-y2b.黑格尔认识形式.org][黑格尔认识形式]]

- 逻辑学中所说的思想是指纯粹思想而言，所说精神也是纯粹自在的精神，亦即自由的精神，因为自由正是在他物中即是在自己本身中、自己依赖自己、自己是自己的决定者。
- 对逻辑规定加以自在自为的考察还有一层深远的意义，即在于我们是从思维的本身去推演出这些思维的规定，并且即从这些思维规定的本身来看它们是否是真的。并不是从外面把它们袭取而来并勉强给予定义，也不是把它们拿来与它们出现在我们意识中的形态漫加比较而指出其价值和有效性。

- 把真理认作自身的符合，构成逻辑学的真正兴趣。因为在通常意识里，关于思维规定的真理问题就完全不会发生。因此，逻辑学的职务也可以说是在于考察思维规定把握真理的能力和限度。

思想，按照这样的规定，可以叫客观的思想，甚至那些最初在普通形式逻辑里惯于只当作被意识了的思维形式，也可以算作客观的形式。

- 说思想作为客观思想是世界的内在本质，似乎这样一来就会以为自然事物也是有意识的，对此还有一方面把思维看成事物的内在活动、一方面说人与自然事物的区别在于有思维的矛盾。因此必须说自然界是一个没有意识的思想体系，或像谢林所说，一种顽冥化 versteinerte 的理智。为免除误会，最好用思想规定或思想范畴以代替思想一词。在这个思想范畴的体系里，**普遍意义下的主观与客观的对立是消除了的**。
- 思想不但构成外界事物的实体 Substanz，而且构成精神性的东西的普遍实体。就人是有思想的来说，他是一个有普遍性者，但只有当他意识到他自身的普遍性时，他才是有思想的。自然界不能使它所含蕴的理性 Nous 得到意识。
- 我们的表象表现出两种情况，或者内容虽是一个经过思考的内容，而形式却未经过思考，或者正与此相反，形式虽属于思想，而内容则与思想不相干。
    - 譬如当我说忿怒、玫瑰、希望等词，这些词所包含的内容都是感觉所熟悉的，但我用普遍的方式、用思想的形式，把这些内容说出来，这样就排斥了许多个别情况，只用普遍的语言来表达那个内容，但那个内容仍然是感性的。反之，当我有上帝的表象时，这内容诚然是纯思的，但形式却是感性的，像我直接亲自感觉到的上帝的形式那样。在前种情况下材料是外界给予的，而形式则属于思维，在第二种情况下思维是内容的源泉，但通过感觉的形式这内容表现为给与的东西，因此是外在地来到精神里的。
