#+TITLE: 形而上学自然的或理性的神学
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

[[./hg1.小逻辑-1817.org][小逻辑 1817]]

形而上学第四部分是自然的或理性的神学，研究上帝的概念或上帝存在的可能性，上帝存在的证明和上帝的特性。

知性所坚持的上帝概念最后只是一个空洞抽象的无确定的本质，一个纯粹的实在性或实证性。

- 理性神学目的在于确定理性本身究竟能够认识上帝到什么程度，而对于宗教达到思维的把握，所以真正的神学本质上同时必是宗教哲学，即在中世纪，同样如此。旧形而上学不是探讨上帝的理性科学，而是知性科学，思维仅仅活动于抽象的思维规定之中。而当理性科学所从事的，在于通过思维去规定上帝的表象，因此所得到的关于上帝的概念只是些肯定性和实在性的抽象概念，而排斥一切否定性的概念，于是上帝就被界说为一切存在中最真实的存在。
- *人的性灵很正当地要求具体的内容，但这种具体内容的出现就必须包含有规定性或否定性在自身内。*

用有限认识去证明上帝的存在总会陷于目的在寻求上帝存在的客观根据，而这客观根据又被表述为是以另一物为条件的一种东西。这种证明以知性的抽象同一为准则，陷于由有限过渡到无限的困难。[fn:1]

- 以此近代有人说上帝的存在是不能（用理智）证明的，而须直接体认。[[./descartes-spinoza.org][笛卡尔和斯宾诺莎对上帝、存在、理由的看法]]
- 理性的证明进程里不会让这个他物作为一个直接的东西、存在着的东西，而是指出这个出发点乃是一个中介和设定起来的东西，因而最后归结到同时认为上帝是自己扬弃中介、包含中介在自身内、真正直接的、原始的、自依而不依他的存在。[fn:2]

把有限世界认作真实的存在，把上帝看成与它对立，又会引起认为上帝与世界种种不同的看法。这些不同关系被认作上帝的特性，一方面它们必须是对一切有限情况的关系，其本身即是有限的性格，另一方面又同时必须是无限的。对这种矛盾，只能通过各种特性之量的增加的办法得到一个模糊溶解，将上帝的特性引到不确定的惝恍迷离的至高无上的感觉之中。

- 这种知性的无限性，这种纯粹的本质，本身仍然只是有限之物，因为它把特殊性排斥在外面，于是这特殊性便在外面否定它、限制它、与它对立。*这种形而上学未能达到具体的同一性，而只是固执着抽象的同一性。*


[fn:1] [[./as1.充足理由律的四重根-1813.org][充足理由律的四重根 1813]] P53 知性的主要作用就在于通过其特有的因果关系，连同以因果关系为前提的纯粹的感性形式时间和空间，从根本上创造和产生了由少数感官的原始材料组成的对象的外部世界。
[fn:2] P118 这只是我们凭借一有限事物以达到上帝的进程，在这进程里，上帝一方面好像是后于有限事物，但同时又是先于有限事物，而为它的绝对根据。
