#+TITLE: 小逻辑 1817
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs-book.css" />

* 哲学不可以假定表象所直接接受的为其对象，不可以假定在认识的开端和进程里有一种现成的认识方法。

哲学对象类似宗教对象。

哲学是以思想、范畴，或更确切地说，是以概念去代替表象。

具有思想与概念是一回事，知道符合这些思想和概念的表象、直观、情绪又是一回事。

假如哲学的看法与宗教的观念之间出现了差异，哲学必须辩明它的各种规定何以异于宗教观念的理由。

- [[./hg1-y0.哲学以真理为对象.org][哲学以真理为对象]]
- [[./hg-y1.哲学以有限事物的世界为对象.org][哲学以有限事物的世界为对象]]

** 就思想的全部普遍性而言，它就是理念或绝对。关于理念或绝对的科学，本质上应是一个体系，因为真理作为具体的，它必定是在自身中展开其自身，而且必定是联系在一起的和保持在一起的统一体，换言之，真理就是全体。全体的自由性，与各个环节的必然性，只有通过对各环节加以区别和规定才有可能。

哲学的每一部分都是一个*哲学全体*，哲学的理念在每一部分里只表达出一个特殊的规定性或因素。部分也是整体，只有打破它特殊因素予之限制，从而建立更广泛的整体而成必然的环节，进而终成理念全体。

各部门的初步划分，正如最初对于理念的认识一样，只能是某种预想的东西。达到概念的概念，自己满足自己，自己返回自己，哲学这门科学可以分为三部分：
须认识到个别部门的科学，每一部门的内容既是存在着的对象，同样又是直接地在这内容中向着它的较高范畴（kreis）的过渡，不曾并列，更非静止。

- 逻辑学，研究理念自在自为的科学。
- 自然哲学，研究理念的异在或外在化的科学。
- 精神哲学，研究理念由它的异在而返回到它自身的科学。

* 逻辑学研究纯粹理念，所谓纯粹理念就是思维的最抽象的要素所形成的理念。

就思维的通常主观的意义，思维是精神的许多活动或能力之一，与感觉、直观、想象、欲望意志等并列杂陈 → 思维活动的产物，思维的形式或规定性一般是普遍的抽象的东西。思维作为能动性，因而便可称能动的普遍 → 既然活动的产物是普遍性的，则思维便可称自身实现的普遍体 → 就思维被认主体而言，便是能思者，*存在的能思的主体的*简称就叫我。[[./hg1b.黑格尔言我.org][黑格尔言我]]

- 感性事物与思想的区别在于前者的特点是个别性的。既是个别之物也是彼此联系，所以凡是感性事物都是些彼此相外 Aussereinander 的个别东西，它们确切抽象的形式，是彼此并列 Nebeneinander 和彼此相续 Nacheinander 的。[[./engels-sensibility.org][恩格斯讨论感性相外、并列、相续问题]]

- 多种个别化的、简单的规定或谓词，不管有无内在联系，勉强连缀在一起，这些谓词虽以其主词为联系，但它们之间仍然是互相外在的。表象与知性的区别，在于知性尚能建立普遍与特殊、原因与效果等关系，从而使表象的孤立化的表象规定有必然性的联系，而表象只能让这些孤立化的规定在模糊的意识背景里彼此挨近排列。二者的区别还具有更大的重要性，因为一般讲来，哲学除了把表象转变为思想，更进一步把单纯抽象的思想转变为概念之外，没有别的工作。

** 思维和对象的关系是主动的，是对某物的反思，因此思维活动的产物、普遍概念就包含有事情的价值，亦即本质、内在实质、真理。

- [[./hg1-y2.反思的客观思想.org][反思的客观思想]]
- [[./hg1-y3.有限的无限的思维.org][有限的无限的思维]]

- [[./hg1-s1.形而上学本体论.org][形而上学本体论]]
- [[./hg1-s2.形而上学理性心理学&灵魂学.org][形而上学理性心理学&灵魂学]]
- [[./hg1-s3.形而上学宇宙论.org][形而上学宇宙论]]
- [[./hg1-s4.形而上学自然的或理性的神学.org][形而上学自然的或理性的神学]]


以上述形而上学的蒙蔽，有两层需要：

- 要求一具体的内容，以补救知性的抽象理论，因为知性自身无法从它的抽象概念进展到特殊的规定的事实。
- 寻求一坚实的据点，以反对在抽象的知性范围内，按照有限思想规定的方法，去证明一切事物的可能性。

这两种需要首先有助于引导哲学思想趋向经验主义。经验主义力求从经验中，*从外在和内心的当前经验中去把握真理*，以代替纯从思想本身去寻求真理，两种需要均不是抽象的知性形而上学所能满足。这里所涉及的具体内容指意识的诸对象必须认为是自身规定的，而且是许多有差别的规定的统一。

形而上学为其界说（它的前提和它更确定的内容）寻求根据起见，也是从表象里、亦即首先从经验流出的内容里去求保证，而经验主义者将属于知觉、感觉和直观的内容提升为普遍的观念、命题和规律。但经验主义者把这类具体的内容抽象化，只有在这种条件下，这些抽象的原则或概念在其所从出的知觉印象之外便没有更广的意义和效用，而且除了在现象中即可说明的（因果）联系外，也没有别的联系或规律可以认为是合法的。所以经验的知识便在主观方面得到一坚实据点，这就是说，*意识从知觉里得到它自己的确定性和直接当前的可靠性*。

- 凡是真的，必定在现实世界中为感官所能感知。[fn:1]
- 凡我们认为应有效用的知识，必须亲眼看到，亲身经历到。

外在的世界为真实，虽然也承认有超感官的世界，但又认为对那一世界的知识是不可能找到的，因而认为我们的*知识须完全限于知觉的范围*。这个基本原则彻底发挥下去，就会成为后来的唯物论。[fn:2]

经验主义者难免不陷于一个根本错觉，应用物质、力以及一、多、普遍性、无限性等形而上学范畴，更进而依赖这些范畴的线索向前推论，因此便不能不假定并应用推论的形式。在这些情形下，经验主义中即已包含并运用形而上学的原则。

- 理性的驱迫力捉住这此时、此地、此物，无疑是具有无限的形式的，不过它们并非无限形式的真正实际存在。那外在世界本身是真实的，因为真理是真实的，而且必定有实际存在的。所以理性所寻求的无限原则是内在于这世界之中的，不过在感官所见的个别形象里，不足以表现其真正面目罢了。

经验主义者以知觉为把握当前实事的形式，但知识必进而在被知觉的个别事物中去寻求有普遍性和永久性的原则，这是由单纯知觉进展到经验的过程。

- 为形成经验必须主要地应用*分析*方法。这种分解过程的主旨即在于分解并拆散那些集在一起的规定，除我们主观的分析活动外，不增加任何成分。
- 经验主义在分析对象时陷入的就是自以为不增减改变任何成分，但却从知觉的直接性进展到了思想，将对象具体的内容转变成为抽象的了。

分析坚持事物的区别，但当区别仍然只是一些抽象概念，当这些思想被认作对象的本身时，便又退回到形而上学的前提，即认为事物的真理在思想中。

[fn:1] P120 与经验主义一样，哲学也只认识什么是如此，凡是仅是应如此、而非是如此的事物，哲学并不过问。
[fn:2] P123 物质本身已经是一个抽象的东西，物质之所以为物质是无法知觉的。所以我们可以说没有物质这个东西，因为就存在着的物质来说，它永远是一种特定的具体的事物。
