#+TITLE: 孟子
#+OPTIONS: num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs.css" />

* 告子上

告子者，告，姓也；子，男子之通稱也；名不害。兼治儒墨之道者，嘗學於孟子，而不能純徹性命之理。《論語》曰：「子罕言命。」謂性命難言也。以告子能執弟子之問，故以題篇。

孫奭疏：此篇首論告子言性，所以次於萬章問孝之篇者，以其爲孝之道，其本在性也，故此篇首以告子之言性，遂爲篇題，次於《萬章》，不亦宜乎。

第一章

*◎ 告子曰：「性，猶杞柳也；義，猶桮棬也。以人性為仁義，猶以杞柳為桮棬。」*

趙岐註：告子以爲人性爲才幹，義爲成器，猶以杞柳之木為桮棬也。

孫奭疏：桮，素樸也。棬，器之似屈轉木作也。

朱熹《孟子集註》：性者，人生所稟之天理也。杞柳，柜柳。桮棬，屈木所為，若卮匜之屬。告子言人性本無仁義，必待矯揉而後成，如荀子性惡之說也。

*◎ 孟子曰：「子能順杞柳之性而以為桮棬乎？將戕賊杞柳而後以為桮棬也？*

趙岐註：戕猶殘也。子能順完杞柳，不傷其性，而成桮棬乎？將以斤斧殘賊之，乃可以爲桮棬乎？言必殘賊也。

*◎ 如將戕賊杞柳而以為桮棬，則亦將戕賊人以為仁義與？率天下之人而禍仁義者，必子之言夫！」*

趙岐註：孟子言以人身爲仁義，豈可復殘傷其形體乃成仁義邪？明不可比桮棬。以告子轉性爲仁義，若轉木以成器，必殘賊之，故曰率人以禍仁義者，必子之言。

朱熹《孟子集註》：言如此，則天下之人皆以仁義為害性而不肯為，是因子之言而為仁義之禍也。

孫奭疏：一章言養性長義，順夫自然，殘木爲器，變而後成。

第二章

*◎ 告子曰：「性猶湍水也，決諸東方則東流，決諸西方則西流。人性之無分於善不善也，猶水之無分於東西也。」*

趙岐註：告子以喻人性若是水也，善惡隨物而化，無本善不善之性也。

孫奭疏：湍，圜，縈迴之水，決之使流於東方則東流之，使之流西方則西流之。

朱熹《孟子集註》：湍，波流瀠回之貌也。告子因前說而小變之，近於楊子善惡混之說。

*◎ 孟子曰：「水信無分於東西，無分於上下乎？人性之善也，猶水之就下也。人無有不善，水無有不下。*

趙岐註：人性生而有善，猶水之欲下也。所以知人皆有善性，似水無有不下者也。

朱熹《孟子集註》：言水誠不分東西矣，然豈不分上下乎？性即天理，未有不善者也。

*◎ 今夫水搏而躍之，可使過顙；激而行之，可使在山。是豈水之性哉？其勢則然也。人之可使為不善，其性亦猶是也。」*

趙岐註：人以手跳水，可使過顙，激之可令上山，皆迫於勢耳，非水之性也。

朱熹《孟子集註》：

搏，擊也。躍，跳也。顙，額也。水之過額在山，皆不就下也。然其本性未嘗不就下，但為博激所使而逆其性耳。

此章言性本善，故順之而無不善；本無惡，故反之而後為惡，非本無定體，而可以無所不為也。

孫奭疏：二章言人之欲善，由水好下，迫勢激躍，失其素真，是以守正性者爲君子，隨曲拂者爲小人也。

第三章

*◎ 告子曰：「生之謂性。」*

趙岐註：凡物生同類皆同性。

朱熹《孟子集註》：生，指人物之所以知覺運動者而言。告子論性，前後四章，語雖不同，然其大指不外乎此，與近世佛氏所謂作用是性者略相似。

*◎ 孟子曰：「生之謂性也，猶白之謂白與？」曰：「然。」「白羽之白也，猶白雪之白；白雪之白，猶白玉之白歟？」曰：「然。」*

趙岐註：孟子以爲羽性輕，雪性消，玉性堅，雖俱白，其性不同。告子以三白之性同邪？告子曰然，誠以爲同也。

朱熹《孟子集註》：白之謂白，猶言凡物之白者，同謂之白，更無差別也。白羽以下，孟子再問而告子曰然，則是謂凡有生者同是一性矣。

*◎ 「然則犬之性，猶牛之性；牛之性，猶人之性與？」*

孫奭疏：孟子所以言此者，以其犬之性，金畜也，故其性守；牛之性，土畜也，故其性順；夫人受天地之中，萬物俱備於我者也，是其稟陰與陽之氣所生也，故其性能柔能剛：是爲不同者。

朱熹《孟子集註》：

孟子又言若果如此，則犬牛與人皆有知覺，皆能運動，其性皆無以異矣，於是告子自知其說之非而不能對也。

愚按：性者，人之所得於天之理也；生者，人之所得於天之氣也。性，形而上者也；氣，形而下者也。人物之生，莫不有是性，亦莫不有是氣。然以氣言之，則知覺運動，人與物若不異也；以理言之，則仁義禮智之稟豈物之所得而全哉？此人之性所以無不善，而為萬物之靈也。告子不知性之為理，而以所謂氣者當之，是以杞柳湍水之喻，食色無善無不善之說，縱橫繆戾，紛紜舛錯，而此章之誤乃其本根。所以然者，蓋徒知知覺運動之蠢然者，人與物同；而不知仁義禮智之粹然者，人與物異也。孟子以是折之，其義精矣。

孫奭疏：三章言物雖有性，性各殊異，惟人之性，與善俱生。

第四章

*◎ 告子曰：「食色，性也。仁，內也，非外也；義，外也，非內也。」*

趙岐註：人之甘食、悅色者，人之性也。仁由內出，義在外也，不從己身出也。

朱熹《孟子集註》：告子以人之知覺運動者為性，故言人之甘食悅色者即其性。故仁愛之心生於內，而事物之宜由乎外。學者但當用力於仁，而不必求合於義也。

*◎ 孟子曰：「何以謂仁內義外也？」曰：「彼長而我長之，非有長於我也；猶彼白而我白之，從其白於外也，故謂之外也。」*

趙岐註：告子言見彼人年老長大，故我長敬之。長大者，非在我者也，猶白色見於外者也。

朱熹《孟子集註》：我長之，我以彼為長也；我白之，我以彼為白也。

*◎ 曰：「異於白馬之白也，無以異於白人之白也；不識長馬之長也，無以異於長人之長歟？且謂長者義乎？長之者義乎？」*

趙岐註：孟子曰：長異於白，白馬白人，同謂之白可也，不知敬老馬無異於敬老人邪。且謂老者爲有義乎？將謂敬老者爲有義乎？且敬老者，己也，何以爲外也。

孫奭疏：蓋白馬之白與白人之白者，彼白而我白之耳，我何容心於其間哉，固無異也；長馬之長與長人之長，則有欽不欽之心矣，此所以有異焉。以其長人之長者有欽，長馬之長者無欽，是則長者在彼，長之者在我，而義自長之者生，非自長者生也。

朱熹《孟子集註》：張氏曰：「上異於二字疑衍。」李氏曰：「或有闕文焉。」愚按：白馬白人，所謂彼白而我白之也；長馬長人，所謂彼長而我長之也。白馬白人不異，而長馬長人不同，是乃所謂義也。義不在彼之長，而在我長之之心，則義之非外明矣。

*◎ 曰：「吾弟則愛之，秦人之弟則不愛也，是以我為悅者也，故謂之內。長楚人之長，亦長吾之長，是以長為悅者也，故謂之外也。」*

趙岐註：告子曰：愛從己則己心悅，故謂之內。所悅喜老者在外，故曰外也。

孫奭疏：謂我之弟則親愛之，秦人之弟則我不愛，是愛以我爲悅者也，愛主仁，故謂仁爲內也；敬長楚人之長者，亦敬長吾之長者，是以長爲悅者也，長主義，故謂義爲外也。

朱熹《孟子集註》：言愛主於我，故仁在內；敬主於長，故義在外。

*◎ 曰：「耆秦人之炙，無以異於耆吾炙。夫物則亦有然者也，然則耆炙亦有外歟？」*

趙岐註：孟子曰：耆炙同等，情出於中。敬楚人之老，與敬己之老，亦同己情性敬之。雖非己炙，同美，故曰物則有然者也。如耆炙之意，豈在外邪。言楚、秦，喻遠也。

孫奭疏：吾之長者吾長之，楚人之長吾亦長之，長之亦皆自我者也，告子謂之以長爲悅，則非矣。是亦猶秦人之炙與吾之炙雖不同，而嗜之者，皆自我也。如是，則義果非生於外者也。云炙者，《周書》曰：「黃帝始燔肉爲炙」是也。

朱熹《孟子集註》：

言長之耆之，皆出於心也。

林氏曰：「告子以食色為性，故因其所明者而通之。」

自篇首至此四章，告子之辯屢屈，而屢變其說以求勝，卒不聞其能自反而有所疑也。此正其所謂不得於言勿求於心者，所以卒於鹵莽而不得其正也。

孫奭疏：四章言事雖在外，行其事者，皆發於中。明仁義由內，所以曉告子之惑也。

第五章

*◎ 孟季子問公都子曰：「何以謂義內也？」*

朱熹《孟子集註》：孟季子，疑孟仲子之弟也。蓋聞孟子之言而未達，故私論之。

*◎ 曰：「行吾敬，故謂之內也。」*

趙岐註：以敬在心而行之，故言內也。

朱熹《孟子集註》：所敬之人雖在外，然知其當敬而行吾心之敬以敬之，則不在外也。

*◎ 「鄉人長於伯兄一歲，則誰敬？」曰：「敬兄。」「酌則誰先？」曰：「先酌鄉人。」「所敬在此，所長在彼，果在外，非由內也。」*

朱熹《孟子集註》：伯，長也。酌，酌酒也。此皆季子問、公都子答，而季子又言，如此則敬長之心，果不由中出也。

*◎ 公都子不能答，以告孟子。孟子曰：「敬叔父乎？敬弟乎？彼將曰：『敬叔父。』曰：『弟為尸則誰敬？』彼將曰：『敬弟。』子曰：『惡在其敬叔父也？』彼將曰：『在位故也。』子亦曰：『在位故也。』庸敬在兄，斯須之敬在鄉人。」*

趙岐註：孟子使公都子答季子如此，言弟以在尸位，故敬之；鄉人以在賓位，故先酌之耳。

朱熹《孟子集註》：尸，祭祀所主以象神，雖子弟為之，然敬之當如祖考也。在位，弟在尸位，鄉人在賓客之位也。庸，常也。斯須，暫時也。言因時制宜，皆由中出也。

*◎ 季子聞之，曰：「敬叔父則敬，敬弟則敬，果在外，非由內也。」公都子曰：「冬日則飲湯，夏日則飲水，然則飲食亦在外也？」*

趙岐註：湯、水雖異名，其得寒、溫者中心也。雖隨敬之所在，亦中心敬之，猶飲食從人所欲，豈可復謂之外也。

范祖禹曰：「二章問答，大指略同，皆反覆譬喻以曉當世，使明仁義之在內，則知人之性善，而皆可以為堯舜矣。」

孫奭疏：五章言凡人隨形，不本其原，賢者達情，知所以然。

第六章

*◎ 公都子曰：「告子曰：『性無善無不善也。』*

趙岐註：公都子道告子以爲人性在化，無本善不善也。

朱熹《孟子集註》：此亦「生之謂性、食色性也」之意，近世蘇氏、胡氏之說蓋如此。

*◎ 或曰：『性可以為善，可以為不善；是故文武興，則民好善；幽厲興，則民好暴。』*

朱熹《孟子集註》：此即湍水之說也。

*◎ 或曰：『有性善，有性不善；是故以堯為君而有象，以瞽瞍為父而有舜；以紂為兄之子且以為君，而有微子啟、王子比干。』*

趙岐註：公都子曰：或人者以爲各有性，善惡不可化移，堯爲君，象爲臣，不能使之爲善；瞽瞍爲父，不能化舜爲惡；紂爲君，又與微子、比干有兄弟之親，亦不能使其二子爲不仁：是亦各有性也矣。

朱熹《孟子集註》：韓子性有三品之說蓋如此。按此文，則微子、比干皆紂之叔父，而書稱微子為商王元子，疑此或有誤字。

*◎ 今曰『性善』，然則彼皆非歟？」*

趙岐註：公都子曰：告子之徒，其論如此，今孟子曰人性盡善，然則彼之所言皆爲非歟？

朱熹《孟子集註》：歟，平聲。

*◎ 孟子曰：「乃若其情，則可以為善矣，乃所謂善也。*

趙岐註：若，順也。性與情相爲表裏，性善勝情，情則從之。《孝經》云：『此哀戚之情』，情從性也。能順此情，使之善者，真所謂善也。

朱熹《孟子集註》：乃若，發語辭。情者，性之動也。人之情，本但可以為善而不可以為惡，則性之本善可知矣。

*◎ 若夫為不善，非才之罪也。*

趙岐註：若隨人而強作善者，非善者之善也。若爲不善者，非所受天才之罪，物動之故也。

孫奭疏：若夫人爲不善耳，非天之降才爾殊也，其所以爲不善者，乃自汩喪之耳，故言非禀天才之罪也……蓋人之性，本則善之，而欲爲善者，非性也，以其情然也；情之能爲善者，非情然也，以其才也。

# 自註：性有所發，情有所感，才有所爲。	2016.11.23.

朱熹《孟子集註》：才，猶材質，人之能也。人有是性，則有是才，性既善則才亦善。人之為不善，乃物欲陷溺而然，非其才之罪也。

*◎ 惻隱之心，人皆有之；羞惡之心，人皆有之；恭敬之心，人皆有之；是非之心，人皆有之。惻隱之心，仁也；羞惡之心，義也；恭敬之心，禮也；是非之心，智也。仁義禮智，非由外鑠我也，我固有之也，弗思耳矣。故曰：『求則得之，舍則失之。』或相倍蓰而無算者，不能盡其才者也。*

趙岐註：人之善惡，或相倍蓰，或至於無筭者，不能相與計多少，言其絕遠也。所以惡乃至是者，不能自盡其才性也。

朱熹《孟子集註》：恭者，敬之發於外者也；敬者，恭之主於中者也。鑠，以火銷金之名，自外以至內也。算，數也。言四者之心人所固有，但人自不思而求之耳，所以善惡相去之遠，由不思不求而不能擴充以盡其才也。前篇言是四者為仁義禮智之端，而此不言端者，彼欲其擴而充之，此直因用以著其本體，故言有不同耳。

*◎ 詩曰：『天生蒸民，有物有則。民之秉夷，好是懿德。』孔子曰：『為此詩者，其知道乎！故有物必有則，民之秉夷也，故好是懿德。』」*

朱熹《孟子集註》：

詩大雅烝民之篇。蒸，詩作烝，眾也。物，事也。則，法也。夷，詩作彝，常也。懿，美也。有物必有法：如有耳目，則有聰明之德；有父子，則有慈孝之心，是民所秉執之常性也，故人之情無不好此懿德者。以此觀之，則人性之善可見，而公都子所問之三說，皆不辯而自明矣。

程子曰：「性即理也，理則堯舜至於塗人一也。才稟於氣，氣有清濁，稟其清者為賢，稟其濁者為愚。學而知之，則氣無清濁，皆可至於善而復性之本，湯武身之是也。孔子所言下愚不移者，則自暴自棄之人也。」又曰：「論性不論氣，不備；論氣不論性，不明，二之則不是。」

張載曰：「形而後有氣質之性，善反之則天地之性存焉。故氣質之性，君子有弗性者焉。」

愚按：程子此說才字，與孟子本文小異。蓋孟子專指其發於性者言之，故以為才無不善；程子兼指其稟於氣者言之，則人之才固有昏明強弱之不同矣，張子所謂氣質之性是也。二說雖殊，各有所當，然以事理考之，程子為密。蓋氣質所稟雖有不善，而不害性之本善；性雖本善，而不可以無省察矯揉之功，學者所當深玩也。

孫奭疏：六章言天之生人，皆有善性，引而趨之，善惡異衢，高下相懸，賢愚舛殊，尋其本者，乃能一諸。

第七章

*◎ 孟子曰：「富歲，子弟多賴；凶歲，子弟多暴，非天之降才爾殊也，其所以陷溺其心者然也。*

趙岐註：子弟，凡人之子弟也。

朱熹《孟子集註》：富歲，豐年也。賴，借也。豐年衣食饒足，故有所顧藉而為善；凶年衣食不足，故有以陷溺其心而為暴。

*◎ 今夫麰麥，播種而耰之，其地同，樹之時又同，浡然而生，至於日至之時，皆熟矣。雖有不同，則地有肥磽，雨露之養，人事之不齊也。*

趙岐註：《詩》云：「貽我來麰」，言人性之同，如此麰麥，其不同者，人事、雨澤有不足，地之有肥、饒耳。

孫奭疏：「貽我來麰」，此蓋《周頌·思文》之篇，言后稷配天之詩也。饒，《說文》云：「饒，石地名也。」

朱熹《孟子集註》：麰，大麥也。耰，覆種也。日至之時，謂當成熟之期也。磽，瘠薄也。

*◎ 故凡同類者，舉相似也，何獨至於人而疑之？聖人與我同類者。*

趙岐註：聖人亦人也，其相覺者，以心知耳。故體類與人同，故舉相似也。

朱熹《孟子集註》：聖人亦人耳，其性之善，無不同也。

*◎ 故龍子曰：『不知足而為屨，我知其不為蕢也。』屨之相似，天下之足同也。*

趙岐註：龍子，古賢人也。雖不知足大小，作履者猶不更作蕢。

朱熹《孟子集註》：蕢，草器也。不知人足之大小而為之屨，雖未必適中，然必似足形，不至成蕢也。

*◎ 口之於味有同耆也，易牙先得我口之所耆者也。如使口之於味也，其性與人殊，若犬、馬之與我不同類也，則天下何耆皆從易牙之於味也？至於味，天下期於易牙，是天下之口相似也。*

趙岐註：人口之所耆者相似，故皆以易牙爲知味，言口之同也。

孫奭疏：《左傳》云：易牙，齊桓公大夫也。淄、澠二水爲食，易牙亦知二水之味。桓公不信，數試始驗。是易牙爲知味者也。

朱熹《孟子集註》：易牙，古之知味者。言易牙所調之味，則天下皆以為美也。

*◎ 惟耳亦然。至於聲，天下期於師曠，是天下之耳相似也。*

趙岐註：耳亦猶口也，天下皆以師曠爲知聲之微妙也。

朱熹《孟子集註》：師曠，能審音者也。言師曠所和之音，則天下皆以為美也。

*◎ 惟目亦然。至於子都，天下莫不知其姣也。不知子都之姣者，無目者也。*

趙岐註：《詩》云：「不見子都，乃見狂且。」儻無目者，乃不知子都好耳，言目之同也。

孫奭疏：「不見子都，乃見狂且」，《詩·國風·山有扶蘇》之篇文也。註云：「都，世之美好者。狂，狂人也。且，辭也。」箋云：「人之好色，不往覩子都，反往覩狂醜之人。」凡此是知子都爲美好者也。

朱熹《孟子集註》：子都，古之美人也。姣，好也。

*◎ 故曰：口之於味也，有同耆焉；耳之於聲也，有同聽焉；目之於色也，有同美焉。至於心，獨無所同然乎？心之所同然者何也？謂理也，義也。聖人先得我心之所同然耳。故理義之悅我心，猶芻豢之悅我口。」*

朱熹《孟子集註》：然，猶可也。草食曰芻，牛羊是也；榖食曰豢，犬豕是也。

程子曰：「在物為理，處物為義，體用之謂也。孟子言人心無不悅理義者，但聖人則先知先覺乎此耳，非有以異於人也。」又曰：「理義之悅我心，猶芻豢之悅我口，此語親切有味。須實體察得理義之悅心，真猶芻豢之悅口，始得。」

/孫奭疏：理出於性命，天之所爲也；義出於道德，人之所爲也：而理、義出於人心所同然也。是則天之使我有是之謂命，天命之謂性，是性命本乎天，故爲天之所爲也。天之所爲雖妙，然而未嘗不有理焉，如此，豈非其理有出於性命者乎！人能存其性命而不失之者，是所謂有其道德也，故爲人之所爲者也。人之所爲道德雖妙，然而未嘗不有義存焉，如此，則豈非其義有出於人心者乎！合而言之，則性命道德是爲理義，雖是理義，出於性命道德者耳。/

孫奭疏：七章言人稟性俱有好憎，耳目口心，所悅者同，或爲君子，或爲小人，猶麰麥不齊，雨露使然也。孟子言是，所以勗而進之。

第八章

*◎ 孟子曰：「牛山之木嘗美矣，以其郊於大國也，斧斤伐之，可以為美乎？是其日夜之所息，雨露之所潤，非無萌櫱之生焉，牛羊又從而牧之，是以若彼濯濯也。人見其濯濯也，以為未嘗有材焉，此豈山之性也哉？*

朱熹《孟子集註》：牛山，齊之東南山也。邑外謂之郊，言牛山之木，前此固嘗美矣，今為大國之郊，伐之者眾，故失其美耳。息，生長也。日夜之所息，謂氣化流行未嘗間斷，故日夜之閒，凡物皆有所生長也，萌，芽也。櫱，芽之旁出者也。濯濯，光潔之貌。材，材木也。言山木雖伐，猶有萌櫱，而牛羊又從而害之，是以至於光潔而無草木也。

*◎ 雖存乎人者，豈無仁義之心哉？其所以放其良心者，亦猶斧斤之於木也，旦旦而伐之，可以為美乎？其日夜之所息，平旦之氣，其好惡與人相近也者幾希，則其旦晝之所為，有梏亡之矣。梏之反覆，則其夜氣不足以存；夜氣不足以存，則其違禽獸不遠矣。人見其禽獸也，而以為未嘗有才焉者，是豈人之情也哉？*

趙岐註：言雖在人之性，亦猶此山之有草木也，人豈無仁義之心邪？幾，豈也。豈希，言不遠也。旦晝，日晝也。

孫奭疏：平旦則未至於晝，旦晝所以爲日之中矣。梏，手械也。利欲之制善，使不得爲，猶梏之制手也。

朱熹《孟子集註》：良心者，本然之善心，即所謂仁義之心也。平旦之氣，謂未與物接之時，清明之氣也。好惡與人相近，言得人心之所同然也。幾希，不多也。梏，械也。反覆，展轉也。言人之良心雖已放失，然其日夜之間，亦必有所生長。故平旦未與物接，其氣清明之際，良心猶必有發見者。但其發見至微，而旦晝所為之不善，又已隨而梏亡之，如山木既伐，猶有萌櫱，而牛羊又牧之也。晝之所為，既有以害其夜之所息，又不能勝其晝之所為，是以展轉相害。至於夜氣之生，日以寖薄，而不足以存其仁義之良心，則平旦之氣亦不能清，而所好惡遂與人遠矣。

*◎ 故苟得其養，無物不長；苟失其養，無物不消。*

趙岐註：誠得其養，若雨露於草木，法度於仁義，何有不長也；誠失其養，若斧斤牛羊之消草木，利欲之消仁義，何有不盡也。

朱熹《孟子集註》：山木人心，其理一也。

*◎ 孔子曰：『操則存，舍則亡；出入無時，莫知其鄉。』惟心之謂與？」*

趙岐註：鄉猶里，以喻居也。

朱熹《孟子集註》：

孔子言心，操之則在此，舍之則失去，其出入無定時，亦無定處如此。孟子引之，以明心之神明不測，得失之易，而保守之難，不可頃刻失其養。學者當無時而不用其力，使神清氣定，常如平旦之時，則此心常存，無適而非仁義也。

程子曰：「心豈有出入，亦以操舍而言耳。操之之道，敬以直內而已。」

愚聞之師曰：「人，理義之心未嘗無，惟持守之即在爾。若於旦晝之間，不至梏亡，則夜氣愈清。夜氣清，則平旦未與物接之時，湛然虛明氣象，自可見矣。」孟子發此夜氣之說，於學者極有利，宜熟玩而深省之也。

孫奭疏：八章言秉心持正，使邪不干，猶止斧斤，不伐牛山，山則木茂，人則稱仁。

第九章

*◎ 孟子曰：「無或乎王之不智也。*

趙岐註：時人有怪王不智而孟子不輔之，故言此也。

朱熹《孟子集註》：或，與惑同，疑怪也。王，疑指齊王。

*◎ 雖有天下易生之物也，一日暴之，十日寒之，未有能生者也。吾見亦罕矣，吾退而寒之者至矣，吾如有萌焉何哉？*

朱熹《孟子集註》：暴，溫之也。我見王之時少，猶一日暴之也，我退則諂諛雜進之日多，是十日寒之也。雖有萌櫱之生，我亦安能如之何哉？

*◎ 今夫弈之為數，小數也；不專心致志，則不得也。*

趙岐註：弈，博也，或曰圍棊。《論語》曰：「不有博弈者乎？」數，技也。

孫奭疏：《說文》：「弈從升，言速兩手而執之。棋者，所執之子，圍而相殺，故謂之圍棊。」稱弈者，又取其落弈之義也。

*◎ 弈秋，通國之善弈者也。使弈秋誨二人弈，其一人專心致志，惟弈秋之為聽。一人雖聽之，一心以為有鴻鵠將至，思援弓繳而射之，雖與之俱學，弗若之矣。為是其智弗若與？曰：非然也。」*

趙岐註：有人名秋，通一國皆謂之善弈，曰弈秋。

孫奭疏：傳記有云弈秋，通國之善弈也，有過者止而聽之，則弈敗。笙汩之也。又云疑首，天下之善算也，有鴻鵠過，彎弧擬問以三五，則不知，鴻鵠之亂也。是亦孟子之言與。

朱熹《孟子集註》：

程子為講官，言於上曰：「人主一日之閒，接賢士大夫之時多，親宦官宮妾之時少；則可以涵養氣質，而熏陶德性。」時不能用，識者恨之。

范祖禹曰：「人君之心，惟在所養。君子養之以善則智，小人養之以惡則愚。然賢人易疏，小人易親，是以寡不能勝眾，正不能勝邪。自古國家治日常少，而亂日常多，蓋以此也。」

孫奭疏：九章言弈爲小數，不精不能，一人善之，十人惡之，若竭其道，何由智哉？《詩》云：「濟濟多士，文王以寧」，此之謂也。

第十章

*◎ 孟子曰：「魚，我所欲也；熊掌，亦我所欲也，二者不可得兼，舍魚而取熊掌者也。生，亦我所欲也；義，亦我所欲也，二者不可得兼，舍生而取義者也。*

孫奭疏：魚在水之物，熊蹯在山之物，欲在水，不可兼得於在山者，在山又不可兼得在水者，故二者不可兼得也。

朱熹《孟子集註》：魚與熊掌皆美味，而熊掌尤美也。

*◎ 生亦我所欲，所欲有甚於生者，故不為苟得也；死亦我所惡，所惡有甚於死者，故患有所不辟也。*

朱熹《孟子集註》：釋所以舍生取義之意。得，得生也。欲生惡死者，雖眾人利害之常情；而欲惡有甚於生死者，乃秉彝義理之良心，是以欲生而不為苟得，惡死而有所不避也。

*◎ 如使人之所欲莫甚於生，則凡可以得生者，何不用也？使人之所惡莫甚於死者，則凡可以辟患者，何不為也？*

朱熹《孟子集註》：設使人無秉彝之良心，而但有利害之私情，則凡可以偷生免死者，皆將不顧禮義而為之矣。

*◎ 由是則生而有不用也，由是則可以辟患而有不為也。*

朱熹《孟子集註》：由其必有秉彝之良心，是以其能舍生取義如此。

*◎ 是故所欲有甚於生者，所惡有甚於死者，非獨賢者有是心也，人皆有之，賢者能勿喪耳。*

朱熹《孟子集註》：羞惡之心，人皆有之，但眾人汨於利欲而忘之，惟賢者能存之而不喪耳。

*◎ 一簞食，一豆羹，得之則生，弗得則死。嘑爾而與之，行道之人弗受；蹴爾而與之，乞人不屑也。*

趙岐註：行道之人，凡人以其賤己，故不肯受也。蹴，蹋也。以足踐蹋與之，乞人不潔之，亦由其小，故輕而不受也。

朱熹《孟子集註》：豆，木器也。嘑，咄啐之貌。行道之人，路中凡人也。蹴，踐踏也。乞人，丐乞之人也。不屑，不以為潔也。言雖欲食之急而猶惡無禮，有寧死而不食者。是其羞惡之本心，欲惡有甚於生死者，人皆有之也。

*◎ 萬鍾則不辨禮義而受之。萬鍾於我何加焉？為宮室之美、妻妾之奉、所識窮乏者得我與？*

趙岐註：鍾，量器也。己身不能獨食萬鍾也，豈不爲廣美宮室、供奉妻妾、施與所知之人窮乏者也。

孫奭疏：晏子曰：「齊舊四量：豆、區、釜、鍾，四升爲豆，四豆爲區，四區爲釜，釜十爲鍾。」

朱熹《孟子集註》：萬鐘於我何加，言於我身無所增益也。所識窮乏者得我，謂所知識之窮乏者感我之惠也。上言人皆有羞惡之心，此言眾人所以喪之。由此三者，蓋理義之心雖曰固有，而物欲之蔽，亦人所易昏也。

*◎ 鄉為身死而不受，今為宮室之美為之；鄉為身死而不受，今為妻妾之奉為之；鄉為身死而不受，今為所識窮乏者得我而為之，是亦不可以已乎？此之謂失其本心。」*

趙岐註：鄉者不得簞食而食則身死，尚不受也，今爲此三者爲之，是不亦可以止乎！

朱熹《孟子集註》：言三者身外之物，其得失比生死為甚輕。鄉為身死猶不肯受嘑蹴之食，今乃為此三者而受無禮義之萬鍾，是豈不可以止乎？本心，謂羞惡之心。此章言羞惡之心，人所固有。或能決死生於危迫之際，而不免計豐約於宴安之時，是以君子不可頃刻而不省察於斯焉。

孫奭疏：十章言舍生取義，義之大者也，簞食、萬鍾，用有輕重，縱彼納此，蓋違其本，凡人皆然，君子則否，所以殊也。

第十一章

*◎ 孟子曰：「仁，人心也；義，人路也。*

孫奭疏：仁者是人之心也，是人人皆有之者也；義者是人之路也，是人人皆得而行之者也。

朱熹《孟子集註》：仁者心之德，程子所謂心如榖種，仁則其生之性，是也。然但謂之仁，則人不知其切於己，故反而名之曰人心，則可以見其為此身酬酢萬變之主，而不可須臾失矣。義者行事之宜，謂之人路，則可以見其為出入往來必由之道，而不可須臾舍矣。

*◎ 舍其路而弗由，放其心而不知求，哀哉！*

朱熹《孟子集註》：哀哉二字，最宜詳味，令人惕然有深省處。

*◎ 人有雞犬放，則知求之；有放心，而不知求。*

朱熹《孟子集註》：程子曰：「心至重，雞犬至輕。雞犬放則知求之，心放而不知求，豈愛其至輕而忘其至重哉？弗思而已矣。」愚謂上兼言仁義，而此下專論求放心者，能求放心，則不違於仁而義在其中矣。

*◎ 學問之道無他，求其放心而已矣。」*

孫奭疏：以其人之所以學問者，亦以精此仁義也。

朱熹《孟子集註》：學問之事，固非一端，然其道則在於求其放心而已。蓋能如是則志氣清明，義理昭著，而可以上達；不然則昏昧放逸，雖曰從事於學，而終不能有所發明矣。

程子曰：「聖賢千言萬語，只是欲人將已放之心約之，使反復入身來，自能尋向上去，下學而上達也。」

孫奭疏：十一章言由路求心，爲得其本，追逐雞狗，務其末也。

第十二章

*◎ 孟子曰：「今有無名之指，屈而不信，非疾痛害事也，如有能信之者，則不遠秦楚之路，為指之不若人也。*

趙岐註：無名指者，非手之用指也。

孫奭疏：蓋云秦、楚者，以其秦、楚相去最爲遠者也，故取爲己言，指屈尚不遠秦、楚之路而求信，況心即在於己爲最進者也，尚不能求之耶。

朱熹《孟子集註》：無名指，手之第四指也。

*◎ 指不若人，則知惡之；心不若人，則不知惡，此之謂不知類也。」*

#+BEGIN_QUOTE
荀子曰：「相形不如論心，论心不如择术。」
#+END_QUOTE

趙岐註：心不若人，可惡之大者也，而反惡指，故曰不知其類也。類，事也。

朱熹《孟子集註》：不知類，言其不知輕重之等也。

孫奭疏：十二章言舍大惡小，不知其要，憂指忘心，不嚮於道。是以君子惡之也。

第十三章

*◎ 孟子曰：「拱把之桐梓，人苟欲生之，皆知所以養之者。至於身，而不知所以養之者，豈愛身不若桐梓哉？弗思甚也。」*

朱熹《孟子集註》：拱，兩手所圍也。把，一手所握也。桐梓，二木名。

孫奭疏：十三章言莫知養身而養樹木，失事違務，不得所急，所以誡未達者也。

第十四章

*◎ 孟子曰：「人之於身也，兼所愛。兼所愛，則兼所養也。無尺寸之膚不愛焉，則無尺寸之膚不養也。所以考其善不善者，豈有他哉？於己取之而已矣。*

趙岐註：人之所愛則養之，於身也，一尺一寸之膚養相及也。

孫奭疏：尺寸之膚者，則心存乎中，又有居待而言者也，且心爲一身之君，所謂心爲天君者也。荀子云：「心居中虛，以治五官。」此之謂也。言人既愛尺寸之膚，雖心亦在所愛焉；既養尺寸之膚，雖心亦在所養焉。所以愛養心者，亦以仁義之道考其善不善，於己取之而已矣。

朱熹《孟子集註》：人於一身，固當兼養，然欲考其所養之善否者，惟在反之於身，以審其輕重而已矣。

*◎ 體有貴賤，有小大。無以小害大，無以賤害貴。養其小者為小人，養其大者為大人。*

朱熹《孟子集註》：賤而小者，口腹也；貴而大者，心志也。

*◎ 今有場師，舍其梧檟，養其樲棘，則為賤場師焉。*

趙岐註：場以治殼。圃，園也。

朱熹《孟子集註》：場師，治場圃者。梧，桐也；檟，梓也，皆美材也。樲棘，小棗，非美材也。

*◎ 養其一指，而失其肩背而不知也，則為狼疾人也。*

趙岐註：謂醫養人疾，治其一指，而不知其肩背之有疾，以至於害之，此爲狼藉亂不知治疾之人也。

朱熹《孟子集註》：狼善顧，疾則不能，故以為失肩背之喻。

*◎ 飲食之人，則人賤之矣，為其養小以失大也。*

朱熹《孟子集註》：飲食之人，專養口腹者也。

*◎ 飲食之人，無有失也，則口腹豈適為尺寸之膚哉？」*

朱熹《孟子集註》：此言若使專養口腹，而能不失其大體，專口腹之養，軀命所關，不但為尺寸之膚而已。但養小之人，無不失其大者，故口腹雖所當養，而終不可以小害大，賤害貴也。

孫奭疏：十四章言養其行，治其正，俱用智力，善惡相厲，是以君子居處思義，飲食思禮。

第十五章

*◎ 公都子問曰：「鈞是人也，或為大人，或為小人，何也？」孟子曰：「從其大體為大人，從其小體為小人。」*

趙岐註：大體，心思禮義。小體，縱恣情慾。

朱熹《孟子集註》：鈞，同也。從，隨也。大體，心也。小體，耳目之類也。

*◎ 曰：「鈞是人也，或從其大體，或從其小體，何也？」曰：「耳目之官不思，而蔽於物，物交物，則引之而已矣。心之官則思，思則得之，不思則不得也。此天之所與我者，先立乎其大者，則其小者弗能奪也。此為大人而已矣。」*

趙岐註：公都子言人何獨有從小體也。官，精神所在也，謂人有五官六府。物，事也。利慾之事來交引其精神，心官不思善，故失其道而陷爲小人也。

朱熹《孟子集註》：官之為言司也。耳司聽，目司視，各有所職而不能思，是以蔽於外物。既不能思而蔽於外物，則亦一物而已。又以外物交於此物，其引之而去不難矣。心則能思，而以思為職。凡事物之來，心得其職，則得其理，而物不能蔽；失其職，則不得其理，而物來蔽之。此三者，皆天之所以與我者，而心為大。若能有以立之，則事無不思，而耳目之欲不能奪之矣，此所以為大人也。

/范浚《心箴》曰：「茫茫堪輿，俯仰無垠。人於其間，眇然有身。是身之微，大倉稊米，參為三才，曰惟心耳。往古來今，孰無此心？心為形役，乃獸乃禽。惟口耳目，手足動靜，投閒抵隙，為厥心病。一心之微，眾欲攻之，其與存者，嗚呼幾希！君子存誠，克念克敬，天君泰然，百體從令。」/

孫奭疏：十五章言天與人性，先立其大，心官思之，邪不乖越，故謂之大人也。

第十六章

*◎ 孟子曰：「有天爵者，有人爵者。仁義忠信，樂善不倦，此天爵也；公卿大夫，此人爵也。*

趙岐註：天爵以德，人爵以祿。

朱熹《孟子集註》：天爵者，德義可尊，自然之貴也。

*◎ 古之人修其天爵，而人爵從之。*

朱熹《孟子集註》：修其天爵，以為吾分之所當然者耳。人爵從之，蓋不待求之而自至也。

*◎ 今之人修其天爵，以要人爵；既得人爵，而棄其天爵，則惑之甚者也，終亦必亡而已矣。」*

朱熹《孟子集註》：要，求也。修天爵以要人爵，其心固已惑矣；得人爵而棄天爵，則其惑又甚焉，終必并其所得之人爵而亡之也。

孫奭疏：十六章言古人修天爵，自樂之也；今要人爵，以誘待也；得人棄天，道之忌也；惑以招亡，小人事也。

第十七章

*◎ 孟子曰：「欲貴者，人之同心也。人人有貴於己者，弗思耳。*

趙岐註：人皆有同欲貴之心，人人自有貴者在己身，不思之耳。在己者，謂仁義廣譽也。

朱熹《孟子集註》：貴於己者，謂天爵也。

*◎ 人之所貴者，非良貴也。趙孟之所貴，趙孟能賤之。*

趙岐註：人之所自有也者，他人不能賤之也。

孫奭疏：良貴者，不以爵而貴者，是謂良貴。趙孟者，即晉襄公之臣趙盾者是也，是爲晉卿。然入爲晉卿，出則爲盟主，是謂貴矣，奈何其賢則不及趙襄，其良則不及宣子，則所貴特人爵之貴耳。

朱熹《孟子集註》：人之所貴，謂人以爵位加己而後貴也。良者，本然之善也。趙孟，晉卿也。能以爵祿與人而使之貴，則亦能奪之而使之賤矣。若良貴，則人安得而賤之哉？

*◎ 詩云：『既醉以酒，既飽以德。』言飽乎仁義也，所以不願人之膏粱之味也；令聞廣譽施於身，所以不願人之文繡也。」*

趙岐註：膏梁，細梁如膏者也。

孫奭疏：《禮》云公食大夫，則稻梁爲嘉膳，則膏梁，味之至珍者也。《詩》以一裳爲顯服，則文繡爲服之至美者也。聞，名聲，而人所聞之也。

朱熹《孟子集註》：詩大雅既醉之篇。飽，充足也。願，欲也。膏，肥肉。粱，美榖。令，善也。聞，亦譽也。文繡，衣之美者也。仁義充足而聞譽彰著，皆所謂良貴也。尹焞曰：「言在我者重，則外物輕。」

孫奭疏：十七章言所貴在身，人不知求，膏梁文繡，己之所優，趙孟所貴，何能比之，是以君子貧而樂也。

第十八章

*◎ 孟子曰：「仁之勝不仁也，猶水勝火。今之為仁者，猶以一杯水，救一車薪之火也；不熄，則謂之水不勝火，此又與於不仁之甚者也。*

朱熹《孟子集註》：與，猶助也。仁之能勝不仁，必然之理也。但為之不力，則無以勝不仁，而人遂以為真不能勝，是我之所為有以深助於不仁者也。

*◎ 亦終必亡而已矣。」*

朱熹《孟子集註》：言此人之心，亦且自怠於為仁，終必并與其所為而亡之。趙氏曰：「言為仁不至，而不反諸己也。」

孫奭疏：十八章言爲仁不至，不反求諸己，謂水勝火，熄而後已，不仁之甚，終爲亡矣。

第十九章

*◎ 孟子曰：「五穀者，種之美者也；苟為不熟，不如荑稗。夫仁亦在乎熟之而已矣。」*

朱熹《孟子集註》：荑稗，草之似榖者，其實亦可食，然不能如五穀之美也。但五穀不熟，則反不如荑稗之熟；猶為仁而不熟，則反不如為他道之有成。是以為仁必貴乎熟，而不可徒恃其種之美，又不可以仁之難熟，而甘為他道之有成也。

尹焞曰：「日新而不已則熟。」

孫奭疏：十九章言功毀幾成，人在慎終，五穀不熟，荑稗是勝，是以爲仁，必其成也。

第二十章

*◎ 孟子曰：「羿之教人射，必志於彀；學者亦必志於彀。*

朱熹《孟子集註》：羿，善射者也。志，猶期也。彀，弓滿也。滿而後發，射之法也。學，謂學射。

*◎ 大匠誨人，必以規矩；學者亦必以規矩。」*

朱熹《孟子集註》：大匠，工師也。規矩，匠之法也。此章言事必有法，然後可成，師舍是則無以教，弟子舍是則無以學。曲藝且然，況聖人之道乎？

孫奭疏：二十章言彀張规矩，以喻爲仁，學不爲仁，由是二教，失其法而行之者也。

* 告子下

第一章

*◎ 任人有問屋廬子曰：「禮與食孰重？」曰：「禮重。」*

朱熹《孟子集註》：任，國名。屋廬子，名連，孟子弟子也。

*◎ 「色與禮孰重？」*

朱熹《孟子集註》：任人復問也。

*◎ 曰：「禮重。」曰：「以禮食，則飢而死；不以禮食，則得食，必以禮乎？親迎，則不得妻；不親迎，則得妻，必親迎乎！」 屋廬子不能對，明日之鄒以告孟子。孟子曰：「於答是也何有？*

朱熹《孟子集註》：何有，不難也。

*◎ 不揣其本而齊其末，方寸之木可使高於岑樓。*

朱熹《孟子集註》：本，謂下。末，謂上。方寸之木至卑，喻食色。岑樓，樓之高銳似山者，至高，喻禮。若不取其下之平，而升寸木於岑樓之上，則寸木反高，岑樓反卑矣。

*◎ 金重於羽者，豈謂一鉤金與一輿羽之謂哉？*

朱熹《孟子集註》：鉤，帶鉤也。金木重而帶鉤小，故輕，喻禮有輕於食色者；羽本輕而一輿多，故重，喻食色有重於禮者。

*◎ 取食之重者，與禮之輕者而比之，奚翅食重？取色之重者，與禮之輕者而比之，奚翅色重？*

朱熹《孟子集註》：禮食親迎，禮之輕者也。飢而死以滅其性，不得妻而廢人倫，食色之重者也。奚翅，猶言何但。言其相去懸絕，不但有輕重之差而已。

*◎ 往應之曰：『紾兄之臂而奪之食，則得食；不紾，則不得食，則將紾之乎？踰東家牆而摟其處子，則得妻；不摟，則不得妻，則將摟之乎？』」*

朱熹《孟子集註》：紾，戾也。摟，牽也。處子，處女也。此二者，禮與食色皆其重者，而以之相較，則禮為尤重也。此章言義理事物，其輕重固有大分，然於其中，又各自有輕重之別。聖賢於此，錯綜斟酌，毫髮不差，固不肯枉尺而直尋，亦未嘗膠柱而調瑟，所以斷之，一視於理之當然而已矣。

*◎ 曹交問曰：「人皆可以為堯舜，有諸？」孟子曰：「然。」*

朱熹《孟子集註》：趙氏曰：「曹交，曹君之弟也。」人皆可以為堯舜，疑古語，或孟子所嘗言也。

*◎ 交聞文王十尺，湯九尺，今交九尺四寸以長，食粟而已，如何則可？」*

第二章

朱熹《孟子集註》：曹交問也。食粟而已，言無他材能也。

*◎ 曰：「奚有於是？亦為之而已矣。有人於此，力不能勝一匹雛，則為無力人矣；今曰舉百鈞，則為有力人矣。然則舉烏獲之任，是亦為烏獲而已矣。夫人豈以不勝為患哉？弗為耳。*

朱熹《孟子集註》：匹，字本作鴄，鴨也，從省作匹。禮記說「匹為鶩」是也。烏獲，古之有力人也，能舉移千鈞。

*◎ 徐行後長者謂之弟，疾行先長者謂之不弟。夫徐行者，豈人所不能哉？所不為也。堯舜之道，孝弟而已矣。*

朱熹《孟子集註》：

陳氏曰：「孝弟者，人之良知良能，自然之性也。堯舜人倫之至，亦率是性而已。豈能加毫末於是哉？」

楊時曰：「堯舜之道大矣，而所以為之，乃在夫行止疾徐之閒，非有甚高難行之事也，百姓蓋日用而不知耳。」

*◎ 子服堯之服，誦堯之言，行堯之行，是堯而已矣；子服桀之服，誦桀之言，行桀之行，是桀而已矣。」*

朱熹《孟子集註》：言為善為惡，皆在我而已。詳曹交之問。淺陋麤率，必其進見之時，禮貌衣冠言動之閒，多不循理，故孟子告之如此兩節云。

*◎ 曰：「交得見於鄒君，可以假館，願留而受業於門。」*

朱熹《孟子集註》：假館而後受業，又可見其求道之不篤。

*◎ 曰：「夫道，若大路然，豈難知哉？人病不求耳。子歸而求之，有餘師。」*

朱熹《孟子集註》：言道不難知，若歸而求之事親敬長之閒，則性分之內，萬理皆備，隨處發見，無不可師，不必留此而受業也。曹交事長之禮既不至，求道之心又不篤，故孟子教之以孝弟，而不容其受業。蓋孔子餘力學文之意，亦不屑之教誨也。

第三章

*◎ 公孫丑問曰：「高子曰：『小弁，小人之詩也。』」孟子曰：「何以言之？」曰：「怨。」*

朱熹《孟子集註》：高子，齊人也。小弁，小雅篇名。周幽王娶申后，生太子宜臼；又得褒姒，生伯服，而黜申后、廢宜臼。於是宜臼之傅為作此詩，以敘其哀痛迫切之情也。

*◎ 曰：「固哉，高叟之為詩也！有人於此，越人關弓而射之，則己談笑而道之；無他，疏之也。其兄關弓而射之，則己垂涕泣而道之；無他，戚之也。小弁之怨，親親也。親親，仁也。固矣夫，高叟之為詩也！」*

朱熹《孟子集註》：固，謂執滯不通也。為，猶治也。越，蠻夷國名。道，語也。親親之心，仁之發也。

*◎ 曰：「凱風何以不怨？」*

朱熹《孟子集註》：凱風，邶風篇名。衛有七子之母，不能安其室，七子作此以自責也。

*◎ 曰：「凱風，親之過小者也；小弁，親之過大者也。親之過大而不怨，是愈疏也；親之過小而怨，是不可磯也。愈疏，不孝也；不可磯，亦不孝也。*

朱熹《孟子集註》：磯，水激石也。不可磯，言微激之而遽怒也。

*◎ 孔子曰：『舜其至孝矣，五十而慕。』」*

朱熹《孟子集註》：言舜猶怨慕，小弁之怨，不為不孝也。趙氏曰：「生之膝下，一體而分。喘息呼吸，氣通於親。當親而疏，怨慕號天。是以小弁之怨，未足為愆也。」

第四章

*◎ 宋牼將之楚，孟子遇於石丘。*

朱熹《孟子集註》：宋，姓；牼，名。石丘，地名。

*◎ 曰：「先生將何之？」*

朱熹《孟子集註》：趙氏曰：「學士年長者，故謂之先生。」

*◎ 曰：「吾聞秦楚構兵，我將見楚王說而罷之。楚王不悅，我將見秦王說而罷之，二王我將有所遇焉。」*

朱熹《孟子集註》：時宋牼方欲見楚王，恐其不悅，則將見秦王也。遇，合也。按莊子書：「有宋鉼者，禁攻寢兵，救世之戰。上說下教，強聒不舍。」疏云：「齊宣王時人。」以事考之，疑即此人也。

*◎ 曰：「軻也請無問其詳，願聞其指。說之將何如？」曰：「我將言其不利也。」曰：「先生之志則大矣，先生之號則不可。*

朱熹《孟子集註》：徐氏曰：「能於戰國擾攘之中，而以罷兵息民為說，其志可謂大矣；然以利為名，則不可也。」

*◎ 先生以利說秦楚之王，秦楚之王悅於利，以罷三軍之師，是三軍之士樂罷而悅於利也。為人臣者懷利以事其君，為人子者懷利以事其父，為人弟者懷利以事其兄。是君臣、父子、兄弟終去仁義，懷利以相接，然而不亡者，未之有也。先生以仁義說秦楚之王，秦楚之王悅於仁義，而罷三軍之師，是三軍之士樂罷而悅於仁義也。為人臣者懷仁義以事其君，為人子者懷仁義以事其父，為人弟者懷仁義以事其兄，是君臣、父子、兄弟去利，懷仁義以相接也。然而不王者，未之有也。何必曰利？」*

朱熹《孟子集註》：此章言休兵息民，為事則一，然其心有義利之殊，而其效有興亡之異，學者所當深察而明辨之也。

第五章

*◎ 孟子居鄒，季任為任處守，以幣交，受之而不報。處於平陸，儲子為相，以幣交，受之而不報。*

朱熹《孟子集註》：趙氏曰：「季任，任君之弟。任君朝會於鄰國，季任為之居守其國也。儲子，齊相也。」不報者，來見則當報之，但以幣交，則不必報也。

*◎ 他日由鄒之任，見季子；由平陸之齊，不見儲子。屋廬子喜曰：「連得閒矣。」*

朱熹《孟子集註》：屋廬子知孟子之處此必有義理，故喜得其閒隙而問之。

*◎ 問曰：「夫子之任見季子，之齊不見儲子，為其為相與？」*

朱熹《孟子集註》：言儲子但為齊相，不若季子攝守君位，故輕之邪？

*◎ 曰：「非也。書曰：『享多儀，儀不及物曰不享，惟不役志于享。』*

朱熹《孟子集註》：書周書洛誥之篇。享，奉上也。儀，禮也。物，幣也。役，用也。言雖享而禮意不及其幣，則是不享矣，以其不用志於享故也。

*◎ 為其不成享也。」*

朱熹《孟子集註》：孟子釋書意如此。

*◎ 屋廬子悅。或問之。屋廬子曰：「季子不得之鄒，儲子得之平陸。」*

朱熹《孟子集註》：徐氏曰：「季子為君居守，不得往他國以見孟子，則以幣交而禮意已備。儲子為齊相，可以至齊之境內而不來見，則雖以幣交，而禮意不及其物也。」

第六章

*◎ 淳于髡曰：「先名實者，為人也；後名實者，自為也。夫子在三卿之中，名實未加於上下而去之，仁者固如此乎？」*

朱熹《孟子集註》：名，聲譽也。實，事功也。言以名實為先而為之者，是有志於救民也；以名實為後而不為者，是欲獨善其身者也。名實未加於上下，言上未能正其君，下未能濟其民也。

*◎ 孟子曰：「居下位，不以賢事不肖者，伯夷也；五就湯，五就桀者，伊尹也；不惡汙君，不辭小官者，柳下惠也。三子者不同道，其趨一也。一者何也？曰：仁也。君子亦仁而已矣，何必同？」*

朱熹《孟子集註》：仁者，無私心而合天理之謂。

楊時曰：「伊尹之就湯，以三聘之勤也。其就桀也，湯進之也。湯豈有伐桀之意哉？其進伊尹以事之也，欲其悔過遷善而已。伊尹既就湯，則以湯之心為心矣；及其終也，人歸之，天命之，不得已而伐之耳。若湯初求伊尹，即有伐桀之心，而伊尹遂相之以伐桀，是以取天下為心也。以取天下為心，豈聖人之心哉？」

*◎ 曰：「魯繆公之時，公儀子為政，子柳、子思為臣，魯之削也滋甚。若是乎賢者之無益於國也！」*

朱熹《孟子集註》：公儀子，名休，為魯相。子柳，泄柳也。削，地見侵奪也。髡譏孟子雖不去，亦未必能有為也。

*◎ 曰：「虞不用百里奚而亡，秦穆公用之而霸。不用賢則亡，削何可得與？」*

朱熹《孟子集註》：百里奚，事見前篇。

*◎ 曰：「昔者王豹處於淇，而河西善謳；緜駒處於高唐，而齊右善歌；華周、杞梁之妻善哭其夫，而變國俗。有諸內必形諸外。為其事而無其功者，髡未嘗覩之也。是故無賢者也，有則髡必識之。」*

朱熹《孟子集註》：王豹，衛人，善謳。淇，水名。緜駒，齊人，善歌。高唐，齊西邑。華周、杞梁，二人皆齊臣，戰死於莒。其妻哭之哀，國俗化之皆善哭。髡以此譏孟子仕齊無功，未足為賢也。

*◎ 曰：「孔子為魯司寇，不用，從而祭，燔肉不至，不稅冕而行。不知者以為為肉也。其知者以為為無禮也。乃孔子則欲以微罪行，不欲為苟去。君子之所為，眾人固不識也。」*

朱熹《孟子集註》：

按《史記》：「孔子為魯司寇，攝行相事。齊人聞而懼，於是以女樂遺魯君。季桓子與魯君往觀之，怠於政事。子路曰：『夫子可以行矣。』孔子曰：『魯今且郊，如致膰于大夫，則吾猶可以止。』桓子卒受齊女樂，郊又不致膰俎于大夫，孔子遂行。」

孟子言以為為肉者，固不足道；以為為無禮，則亦未為深知孔子者。蓋聖人於父母之國，不欲顯其君相之失，又不欲為無故而苟去，故不以女樂去，而以膰肉行。其見幾明決，而用意忠厚，固非眾人所能識也。然則孟子之所為，豈髡之所能識哉？

尹焞曰：「淳于髡未嘗知仁，亦未嘗識賢也，宜乎其言若是。」

第七章

*◎ 孟子曰：「五霸者，三王之罪人也；今之諸侯，五霸之罪人也；今之大夫，今之諸侯之罪人也。*

朱熹《孟子集註》：趙氏曰：「五霸：齊桓、晉文、秦穆、宋襄、楚莊也。三王，夏禹、商湯、周文、武也。」丁氏曰：「夏昆吾，商大彭、豕韋，周齊桓、晉文，謂之五霸。」

*◎ 天子適諸侯曰巡狩，諸侯朝於天子曰述職。春省耕而補不足，秋省斂而助不給。入其疆，土地辟，田野治，養老尊賢，俊傑在位，則有慶，慶以地。入其疆，土地荒蕪，遺老失賢，掊克在位，則有讓。一不朝，則貶其爵；再不朝，則削其地；三不朝，則六師移之。是故天子討而不伐，諸侯伐而不討。五霸者，摟諸侯以伐諸侯者也，故曰：五霸者，三王之罪人也。*

朱熹《孟子集註》：慶，賞也，益其地以賞之也。掊克，聚斂也。讓，責也。移之者，誅其人而變置之也。討者，出命以討其罪，而使方伯連帥帥諸侯以伐之也。伐者奉天子之命，聲其罪而伐之也。摟，牽也。五霸牽諸侯以伐諸侯，不用天子之命也。自入其疆至則有讓，言巡狩之事；自一不朝至六師移之，言述職之事。

*◎ 五霸，桓公為盛。葵丘之會諸侯，束牲、載書而不歃血。初命曰：『誅不孝，無易樹子，無以妾為妻。』再命曰：『尊賢育才，以彰有德。』三命曰：『敬老慈幼，無忘賓旅。』四命曰：『士無世官，官事無攝，取士必得，無專殺大夫。』五命曰：『無曲防，無遏糴，無有封而不告。』曰：『凡我同盟之人，既盟之後，言歸于好。』今之諸侯，皆犯此五禁，故曰：今之諸侯，五霸之罪人也。*

朱熹《孟子集註》：

按《春秋》傳：「僖公九年，葵丘之會，陳牲而不殺。讀書加於牲上，壹明天子之禁。」

樹，立也。已立世子，不得擅易。初命三事，所以修身正家之要也。賓，賓客也。旅，行旅也。皆當有以待之，不可忽忘也。士世祿而不世官，恐其未必賢也。官事無攝，當廣求賢才以充之，不可以闕人廢事也。取士必得，必得其人也。無專殺大夫，有罪則請命於天子而後殺之也。無曲防，不得曲為隄防，壅泉激水，以專小利，病鄰國也。無遏糴，鄰國凶荒，不得閉糴也。無有封而不告者，不得專封國邑而不告天子也。

*◎ 長君之惡其罪小，逢君之惡其罪大。今之大夫，皆逢君之惡，故曰：今之大夫，今之諸侯之罪人也。」*

朱熹《孟子集註》：君有過不能諫，又順之者，長君之惡也。君之過未萌，而先意導之者，逢君之惡也。

林氏曰：「邵子有言：『治春秋者，不先治五霸之功罪，則事無統理，而不得聖人之心。春秋之閒，有功者未有大於五霸，有過者亦未有大於五霸。故五霸者，功之首，罪之魁也。』孟子此章之義，其亦若此也與？然五霸得罪於三王，今之諸侯得罪於五霸，皆出於異世，故得以逃其罪。至於今之大夫，其得罪於今之諸侯，則同時矣；而諸侯非惟莫之罪也，乃反以為良臣而厚禮之。不以為罪而反以為功，何其謬哉！」

第八章

*◎ 魯欲使慎子為將軍。*

朱熹《孟子集註》：慎子，魯臣。

*◎ 孟子曰：「不教民而用之，謂之殃民。殃民者，不容於堯舜之世。*

朱熹《孟子集註》：教民者，教之禮義，使知入事父兄，出事長上也。用之，使之戰也。

*◎ 一戰勝齊，遂有南陽，然且不可。」*

朱熹《孟子集註》：是時魯蓋欲使慎子伐齊，取南陽也。故孟子言就使慎子善戰有功如此，且猶不可。

*◎ 慎子勃然不悅曰：「此則滑釐所不識也。」*

朱熹《孟子集註》：滑釐，慎子名。

*◎ 曰：「吾明告子。天子之地方千里；不千里，不足以待諸侯。諸侯之地方百里；不百里，不足以守宗廟之典籍。*

朱熹《孟子集註》：待諸侯，謂待其朝覲聘問之禮。宗廟典籍，祭祀會同之常制也。

*◎ 周公之封於魯，為方百里也；地非不足，而儉於百里。太公之封於齊也，亦為方百里也；地非不足也，而儉於百里。*

朱熹《孟子集註》：二公有大勳勞於天下，而其封國不過百里。儉，止而不過之意也。

*◎ 今魯方百里者五，子以為有王者作，則魯在所損乎？在所益乎？*

朱熹《孟子集註》：魯地之大，皆并吞小國而得之。有王者作，則必在所損矣。

*◎ 徒取諸彼以與此，然且仁者不為，況於殺人以求之乎？*

朱熹《孟子集註》：徒，空也，言不殺人而取之也。

*◎ 君子之事君也，務引其君以當道，志於仁而已。」*

朱熹《孟子集註》：當道，謂事合於理，志仁，謂心在於仁。

第九章

*◎ 孟子曰：「今之事君者曰：『我能為君辟土地，充府庫。』今之所謂良臣，古之所謂民賊也。君不鄉道，不志於仁，而求富之，是富桀也。*

朱熹《孟子集註》：辟，開墾也。

*◎ 『我能為君約與國，戰必克。』今之所謂良臣，古之所謂民賊也。君不鄉道，不志於仁，而求為之強戰，是輔桀也。*

朱熹《孟子集註》：約，要結也。與國，和好相與之國也。

*◎ 由今之道，無變今之俗，雖與之天下，不能一朝居也。」*

朱熹《孟子集註》：言必爭奪而至於危亡也。

第十章

*◎ 白圭曰：「吾欲二十而取一，何如？」*

朱熹《孟子集註》：白圭，名丹，周人也。欲更稅法，二十分而取其一分。林氏曰：「按史記：白圭能薄飲食，忍嗜欲，與童僕同苦樂。樂觀時變，人棄我取，人取我與，以此居積致富。其為此論，蓋欲以其術施之國家也。」

*◎ 孟子曰：「子之道，貉道也。*

朱熹《孟子集註》：貉，音陌。貉，北方夷狄之國名也。

*◎ 萬室之國，一人陶，則可乎？」曰：「不可，器不足用也。」*

朱熹《孟子集註》：孟子設喻以詰圭，而圭亦知其不可也。

*◎ 曰：「夫貉，五穀不生，惟黍生之。無城郭、宮室、宗廟、祭祀之禮，無諸侯幣帛饔飧，無百官有司，故二十取一而足也。*

朱熹《孟子集註》：北方地寒，不生五穀，黍早熟，故生之。饔飧，以飲食饋客之禮也。

*◎ 今居中國，去人倫，無君子，如之何其可也？*

朱熹《孟子集註》：無君臣、祭祀、交際之禮，是去人倫；無百官有司，是無君子。

*◎ 陶以寡，且不可以為國，況無君子乎？*

朱熹《孟子集註》：因其辭以折之。

*◎ 欲輕之於堯舜之道者，大貉小貉也；欲重之於堯舜之道者，大桀小桀也。」*

朱熹《孟子集註》：什一而稅，堯舜之道也。多則桀，寡則貉。今欲輕重之，則是小貉、小桀而已。

第十一章

*◎ 白圭曰：「丹之治水也愈於禹。」*

朱熹《孟子集註》：趙氏曰：「當時諸侯有小水，白圭為之築隄，壅而注之他國。」

*◎ 孟子曰：「子過矣。禹之治水，水之道也。*

朱熹《孟子集註》：順水之性也。

*◎ 是故禹以四海為壑，今吾子以鄰國為壑。*

朱熹《孟子集註》：壑，受水處也。

*◎ 水逆行，謂之洚水。洚水者，洪水也，仁人之所惡也。吾子過矣。」*

朱熹《孟子集註》：水逆行者，下流壅塞，故水逆流，今乃壅水以害人，則與洪水之災無異矣。

第十二章

*◎ 孟子曰：「君子不亮，惡乎執？」*

朱熹《孟子集註》：亮，信也，與諒同。惡乎執，言凡事苟且，無所執持也。

第十三章

*◎ 魯欲使樂正子為政。孟子曰：「吾聞之，喜而不寐。」*

朱熹《孟子集註》：喜其道之得行。

*◎ 公孫丑曰：「樂正子強乎？」曰：「否。」「有知慮乎？」曰：「否。」「多聞識乎？」曰：「否。」*

朱熹《孟子集註》：此三者，皆當世之所尚，而樂正子之所短，故丑疑而歷問之。

*◎ 「然則奚為喜而不寐？」*

朱熹《孟子集註》：丑問也。

*◎ 曰：「其為人也好善。」*

朱熹《孟子集註》：好，去聲，下同。

*◎ 「好善足乎？」*

朱熹《孟子集註》：丑問也。

*◎ 曰：「好善優於天下，而況魯國乎？*

朱熹《孟子集註》：優，有餘裕也。言雖治天下，尚有餘力也。

*◎ 夫苟好善，則四海之內，皆將輕千里而來告之以善。*

朱熹《孟子集註》：輕，易也，言不以千里為難也。

*◎ 夫苟不好善，則人將曰：『訑訑，予既已知之矣。』訑訑之聲音顏色，距人於千里之外。士止於千里之外，則讒諂面諛之人至矣。與讒諂面諛之人居，國欲治，可得乎？」*

朱熹《孟子集註》：訑訑，自足其智，不嗜善言之貌。君子小人，迭為消長。直諒多聞之士遠，則讒諂面諛之人至，理勢然也。此章言為政，不在於用一己之長，而貴於有以來天下之善。

第十四章

*◎ 陳子曰：「古之君子何如則仕？」孟子曰：「所就三，所去三。*

朱熹《孟子集註》：其目在下。

*◎ 迎之致敬以有禮，言將行其言也，則就之；禮貌未衰，言弗行也，則去之。*

朱熹《孟子集註》：所謂見行可之仕，若孔子於季桓子是也。受女樂而不朝，則去之矣。

*◎ 其次，雖未行其言也，迎之致敬以有禮，則就之；禮貌衰，則去之。*

朱熹《孟子集註》：所謂際可之仕，若孔子於衛靈公是也。故與公游於囿，公仰視蜚鴈而後去之。

*◎ 其下，朝不食，夕不食，飢餓不能出門戶。君聞之曰：『吾大者不能行其道，又不能從其言也，使飢餓於我土地，吾恥之。』周之，亦可受也，免死而已矣。」*

朱熹《孟子集註》：所謂公養之仕也。君之於民，固有周之之義，況此又有悔過之言，所以可受。然未至於飢餓不能出門戶，則猶不受也。其曰免死而已，則其所受亦有節矣。

第十五章

*◎ 孟子曰：「舜發於畎畝之中，傅說舉於版築之閒，膠鬲舉於魚鹽之中，管夷吾舉於士，孫叔敖舉於海，百里奚舉於市。*

朱熹《孟子集註》：舜耕歷山，三十登庸。說築傅嚴，武丁舉之。膠鬲遭亂，鬻販魚鹽，文王舉之。管仲囚於士官，桓公舉以相國。孫叔敖隱處海濱，楚莊王舉之為令尹。百里奚事見前篇。

*◎ 故天將降大任於是人也，必先苦其心志，勞其筋骨，餓其體膚，空乏其身，行拂亂其所為，所以動心忍性，曾益其所不能。*

朱熹《孟子集註》：降大任，使之任大事也，若舜以下是也。空，窮也。乏，絕也。拂，戾也，言使之所為不遂，多背戾也。動心忍性，謂竦動其心，堅忍其性也。然所謂性，亦指氣稟食色而言耳。

程子曰：「若要熟，也須從這裡過。」

*◎ 人恆過，然後能改；困於心，衡於慮，而後作；徵於色，發於聲，而後喻。*

朱熹《孟子集註》：恆，常也。猶言大率也。橫，不順也。作，奮起也。徵，驗也。喻，曉也。此又言中人之性，常必有過，然後能改。蓋不能謹於平日，故必事勢窮蹙，以至困於心，橫於慮，然後能奮發而興起；不能燭於幾微，故必事理暴著，以至驗於人之色，發於人之聲，然後能警悟而通曉也。

*◎ 入則無法家拂士，出則無敵國外患者，國恆亡。*

朱熹《孟子集註》：此言國亦然也。法家，法度之世臣也。拂士，輔弼之賢士也。

*◎ 然後知生於憂患而死於安樂也。」*

朱熹《孟子集註》：以上文觀之，則知人之生全，出於憂患，而死亡由於安樂矣。

尹焞曰：「言困窮拂鬱，能堅人之志，而熟人之仁，以安樂失之者多矣。」

第十六章

*◎ 孟子曰：「教亦多術矣，予不屑之教誨也者，是亦教誨之而已矣。」*

朱熹《孟子集註》：多術，言非一端。屑，潔也。不以其人為潔而拒絕之，所謂不屑之教誨也。其人若能感此，退自修省，則是亦我教誨之也。

尹焞曰：「言或抑或揚，或與或不與，各因其材而篤之，無非教也。」

* 盡心上

第一章

*◎ 孟子曰：「盡其心者，知其性也。知其性，則知天矣。*

朱熹《孟子集註》：心者，人之神明，所以具眾理而應萬事者也。性則心之所具之理，而天又理之所從以出者也。人有是心，莫非全體，然不窮理，則有所蔽而無以盡乎此心之量。故能極其心之全體而無不盡者，必其能窮夫理而無不知者也。既知其理，則其所從出。亦不外是矣。以大學之序言之，知性則物格之謂，盡心則知至之謂也。

*◎ 存其心，養其性，所以事天也。*

朱熹《孟子集註》：存，謂操而不舍；養，謂順而不害。事，則奉承而不違也。

*◎ 殀壽不貳，修身以俟之，所以立命也。」*

朱熹《孟子集註》：

殀壽，命之短長也。貳，疑也。不貳者，知天之至，修身以俟死，則事天以終身也。立命，謂全其天之所付，不以人為害之。

程子曰：「心也、性也、天也，一理也。自理而言謂之天，自稟受而言謂之性，自存諸人而言謂之心。」

張載曰：「由太虛，有天之名；由氣化，有道之名；合虛與氣，有性之名；合性與知覺，有心之名。」

愚謂盡心知性而知天，所以造其理也；存心養性以事天，所以履其事也。不知其理，固不能履其事；然徒造其理而不履其事，則亦無以有諸己矣。知天而不以殀壽貳其心，智之盡也；事天而能修身以俟死，仁之至也。智有不盡，固不知所以為仁；然智而不仁，則亦將流蕩不法，而不足以為智矣。

第二章

*◎ 孟子曰：「莫非命也，順受其正。*

朱熹《孟子集註》：人物之生，吉凶禍福，皆天所命。然惟莫之致而至者，乃為正命，故君子修身以俟之，所以順受乎此也。

*◎ 是故知命者，不立乎巖牆之下。*

朱熹《孟子集註》：命，謂正命。巖牆，牆之將覆者。知正命，則不處危地以取覆壓之禍。

*◎ 盡其道而死者，正命也。*

朱熹《孟子集註》：盡其道，則所值之吉凶，皆莫之致而至者矣。

*◎ 桎梏死者，非正命也。」*

朱熹《孟子集註》：桎梏，所以拘罪人者。言犯罪而死，與立巖牆之下者同，皆人所取，非天所為也。此章與上章蓋一時之言，所以發其末句未盡之意。

第三章

*◎ 孟子曰：「求則得之，舍則失之，是求有益於得也，求在我者也。*

朱熹《孟子集註》：在我者，謂仁義禮智，凡性之所有者。

*◎ 求之有道，得之有命，是求無益於得也，求在外者也。」*

朱熹《孟子集註》：有道，言不可妄求。有命，則不可必得。在外者，謂富貴利達，凡外物皆是。趙氏曰：「言為仁由己，富貴在天，如不可求，從吾所好。」

第四章

*◎ 孟子曰：「萬物皆備於我矣。*

朱熹《孟子集註》：此言理之本然也。大則君臣父子，小則事物細微，其當然之理，無一不具於性分之內也。

*◎ 反身而誠，樂莫大焉。*

朱熹《孟子集註》：誠，實也。言反諸身，而所備之理，皆如惡惡臭、好好色之實然，則其行之不待勉強而無不利矣，其為樂孰大於是。

*◎ 強恕而行，求仁莫近焉。」*

朱熹《孟子集註》：強，勉強也。恕，推己以及人也。反身而誠則仁矣，其有未誠，則是猶有私意之隔，而理未純也。故當凡事勉強，推己及人，庶幾心公理得而仁不遠也。此章言萬物之理具於吾身，體之而實，則道在我而樂有餘；行之以恕，則私不容而仁可得。

第五章

*◎ 孟子曰：「行之而不著焉，習矣而不察焉，終身由之而不知其道者，眾也。」*

朱熹《孟子集註》：著者，知之明；察者，識之精。言方行之而不能明其所當然，既習矣而猶不識其所以然，所以終身由之而不知其道者多也。

第六章

*◎ 孟子曰：「人不可以無恥。無恥之恥，無恥矣。」*

朱熹《孟子集註》：趙氏曰：「人能恥己之無所恥，是能改行從善之人，終身無復有恥辱之累矣。」

第七章

*◎ 孟子曰：「恥之於人大矣。*

朱熹《孟子集註》：恥者，吾所固有羞惡之心也。存之則進於聖賢，失之則入於禽獸，故所繫為甚大。

*◎ 為機變之巧者，無所用恥焉。*

朱熹《孟子集註》：為機械變詐之巧者，所為之事皆人所深恥，而彼方且自以為得計，故無所用其愧恥之心也。

*◎ 不恥不若人，何若人有？」*

朱熹《孟子集註》：但無恥一事不如人，則事事不如人矣。或曰：「不恥其不如人，則何能有如人之事。」其義亦通。或問：「人有恥不能之心如何？」程子曰：「恥其不能而為之可也，恥其不能而掩藏之不可也。」

第八章

*◎ 孟子曰：「古之賢王好善而忘勢，古之賢士何獨不然？樂其道而忘人之勢。故王公不致敬盡禮，則不得亟見之。見且由不得亟，而況得而臣之乎？」*

朱熹《孟子集註》：言君當屈己以下賢，士不枉道而求利。二者勢若相反，而實則相成，蓋亦各盡其道而已。

第九章

*◎ 孟子謂宋句踐曰：「子好遊乎？吾語子遊。*

朱熹《孟子集註》：宋，姓。句踐，名。遊，遊說也。

*◎ 人知之，亦囂囂；人不知，亦囂囂。」*

朱熹《孟子集註》：趙氏曰：「囂囂，自得無欲之貌。」

*◎ 曰：「何如斯可以囂囂矣？」曰：「尊德樂義，則可以囂囂矣。*

朱熹《孟子集註》：德，謂所得之善。尊之，則有以自重，而不慕乎人爵之榮。義，謂所守之正。樂之，則有以自安，而不殉乎外物之誘矣。

*◎ 故士窮不失義，達不離道。*

朱熹《孟子集註》：言不以貧賤而移，不以富貴而淫，此尊德樂義見於行事之實也。

*◎ 窮不失義，故士得己焉；達不離道，故民不失望焉。*

朱熹《孟子集註》：得己，言不失己也。民不失望，言人素望其興道致治，而今果如所望也。

*◎ 古之人，得志，澤加於民；不得志，脩身見於世。窮則獨善其身，達則兼善天下。」*

朱熹《孟子集註》：見，謂名實之顯著也。此又言士得己、民不失望之實。此章言內重而外輕，則無往而不善。

第十章

*◎ 孟子曰：「待文王而後興者，凡民也。若夫豪傑之士，雖無文王猶興。」*

朱熹《孟子集註》：興者，感動奮發之意。凡民，庸常之人也。豪傑，有過人之才智者也。蓋降衷秉彝，人所同得，惟上智之資無物欲之蔽，為能無待於教，而自能感發以有為也。

第十一章

*◎ 孟子曰：「附之以韓魏之家，如其自視欿然，則過人遠矣。」*

朱熹《孟子集註》：附，益也。韓魏，晉卿富家也。欿然，不自滿之意。尹焞曰：「言有過人之識，則不以富貴為事。」

第十二章

*◎ 孟子曰：「以佚道使民，雖勞不怨；以生道殺民，雖死不怨殺者。」*

程子曰：「以佚道使民，謂本欲佚之也，播榖乘屋之類是也。以生道殺民，謂本欲生之也，除害去惡之類是也。蓋不得已而為其所當為，則雖咈民之欲而民不怨，其不然者反是。」

第十三章

*◎ 孟子曰：「霸者之民，驩虞如也；王者之民，皞皞如也。*

朱熹《孟子集註》：驩虞，與歡娛同。皞皞，廣大自得之貌。

程子曰：「驩虞，有所造為而然，豈能久也？耕田鑿井，帝力何有於我？如天之自然，乃王者之政。」

楊時曰：「所以致人驩虞，必有違道干譽之事；若王者則如天，亦不令人喜，亦不令人怒。」

*◎ 殺之而不怨，利之而不庸，民日遷善而不知為之者。*

朱熹《孟子集註》：此所謂皞皞如也。庸，功也。豐氏曰：「因民之所惡而去之，非有心於殺之也，何怨之有？因民之所利而利之，非有心於利之也，何庸之有？輔其性之自然，使自得之，故民日遷善而不知誰之所為也。」

*◎ 夫君子所過者化，所存者神，上下與天地同流，豈曰小補之哉？」*

朱熹《孟子集註》：君子，聖人之通稱也。所過者化，身所經歷之處，即人無不化，如舜之耕歷山而田者遜畔，陶河濱而器不苦窳也。所存者神，心所存主處便神妙不測，如孔子之立斯立、道斯行、綏斯來、動斯和，莫知其所以然而然也。是其德業之盛，乃與天地之化同運並行，舉一世而甄陶之，非如霸者但小小補塞其罅漏而已。此則王道之所以為大，而學者所當盡心也。

第十四章

*◎ 孟子曰：「仁言，不如仁聲之入人深也。*

程子曰：「仁言，謂以仁厚之言加於民。仁聲，謂仁聞，謂有仁之實而為眾所稱道者也。此尤見仁德之昭著，故其感人尤深也。」

*◎ 善政，不如善教之得民也。*

朱熹《孟子集註》：政，謂法度禁令，所以制其外也。教，謂道德齊禮，所以格其心也。

*◎ 善政民畏之，善教民愛之；善政得民財，善教得民心。」*

朱熹《孟子集註》：得民財者，百姓足而君無不足也；得民心者，不遺其親，不後其君也。

第十五章

*◎ 孟子曰：「人之所不學而能者，其良能也；所不慮而知者，其良知也。*

朱熹《孟子集註》：良者，本然之善也。程子曰：「良知良能，皆無所由；乃出於天，不繫於人。」

*◎ 孩提之童，無不知愛其親者；及其長也，無不知敬其兄也。*

朱熹《孟子集註》：長，上聲，下同。孩提，二三歲之閒，知孩笑、可提抱者也。愛親敬長，所謂良知良能者也。

*◎ 親親，仁也；敬長，義也。無他，達之天下也。」*

朱熹《孟子集註》：言親親敬長，雖一人之私，然達之天下無不同者，所以為仁義也。

第十六章

*◎ 孟子曰：「舜之居深山之中，與木石居，與鹿豕遊，其所以異於深山之野人者幾希。及其聞一善言，見一善行，若決江河，沛然莫之能禦也。」*

朱熹《孟子集註》：居深山，謂耕歷山時也。蓋聖人之心，至虛至明，渾然之中，萬理畢具。一有感觸，則其應甚速，而無所不通，非孟子造道之深，不能形容至此也。

第十七章

*◎ 孟子曰：「無為其所不為，無欲其所不欲，如此而已矣。」*

朱熹《孟子集註》：李氏曰：「有所不為不欲，人皆有是心也。至於私意一萌，而不能以禮義制之，則為所不為、欲所不欲者多矣。能反是心，則所謂擴充其羞惡之心者，而義不可勝用矣，故曰如此而已矣。」

第十八章

*◎ 孟子曰：「人之有德慧術知者，恆存乎疢疾。*

朱熹《孟子集註》：德慧者，德之慧。術知者，術之知。疢疾，猶災患也。言人必有疢疾，則能動心忍性，增益其所不能也。

*◎ 獨孤臣孽子，其操心也危，其慮患也深，故達。」*

朱熹《孟子集註》：孤臣，遠臣；孽子，庶子，皆不得於君親，而常有疢疾者也。達，謂達於事理，即所謂德慧術知也。

第十九章

*◎ 孟子曰：「有事君人者，事是君則為容悅者也。*

朱熹《孟子集註》：阿殉以為容，逢迎以為悅，此鄙夫之事、妾婦之道也。

*◎ 有安社稷臣者，以安社稷為悅者也。*

朱熹《孟子集註》：言大臣之計安社稷，如小人之務悅其君，眷眷於此而不忘也。

*◎ 有天民者，達可行於天下而後行之者也。*

朱熹《孟子集註》：民者，無位之稱。以其全盡天理，乃天之民，故謂之天民。必其道可行於天下，然後行之；不然，則寧沒世不見知而不悔，不肯小用其道以殉於人也。

張載曰：「必功覆斯民然後出，如伊呂之徒。」

*◎ 有大人者，正己而物正者也。」*

朱熹《孟子集註》：大人，德盛而上下化之，所謂「見龍在田，天下文明」者。此章言人品不同，略有四等。容悅佞臣不足言。安社稷則忠矣，然猶一國之士也。天民則非一國之士矣，然猶有意也。無意無必，惟其所在而物無不化，惟聖者能之。

第二十章

*◎ 孟子曰：「君子有三樂，而王天下不與存焉。*

朱熹《孟子集註》：樂，音洛。王、與，皆去聲，下並同。

*◎ 父母俱存，兄弟無故，一樂也。*

朱熹《孟子集註》：此人所深願而不可必得者，今既得之，其樂可知。

*◎ 仰不愧於天，俯不怍於人，二樂也。*

程子曰：「人能克己，則仰不愧，俯不怍，心廣體胖，其樂可知，有息則餒矣。」

*◎ 得天下英才而教育之，三樂也。*

朱熹《孟子集註》：盡得一世明睿之才，而以所樂乎己者教而養之，則斯道之傳得之者眾，而天下後世將無不被其澤矣。聖人之心所願欲者，莫大於此，今既得之，其樂為何如哉？

*◎ 君子有三樂，而王天下不與存焉。」*

朱熹《孟子集註》：林氏曰：「此三樂者，一係於天，一係於人。其可以自致者，惟不愧不怍而已，學者可不勉哉？」

第二十一章

*◎ 孟子曰：「廣土眾民，君子欲之，所樂不存焉。*

朱熹《孟子集註》：地闢民聚，澤可遠施，故君子欲之，然未足以為樂也。

*◎ 中天下而立，定四海之民，君子樂之，所性不存焉。*

朱熹《孟子集註》：其道大行，無一夫不被其澤，故君子樂之，然其所得於天者則不在是也。

*◎ 君子所性，雖大行不加焉，雖窮居不損焉，分定故也。*

朱熹《孟子集註》：分者，所得於天之全體，故不以窮達而有異。

*◎ 君子所性，仁義禮智根於心。其生色也，睟然見於面，盎於背，施於四體，四體不言而喻。」*

朱熹《孟子集註》：

上言所性之分，與所欲所樂不同，此乃言其蘊也。仁義禮智，性之四德也。根，本也。生，發見也。睟然，清和潤澤之貌。盎，豐厚盈溢之意。施於四體，謂見於動作威儀之閒也。喻，曉也。四體不言而喻，言四體不待吾言，而自能曉吾意也。蓋氣稟清明，無物欲之累，則性之四德根本於心，其積之盛，則發而著見於外者，不待言而無不順也。

程子曰：「睟面盎背，皆積盛致然。四體不言而喻，惟有德者能之。」

此章言君子固欲其道之大行，然其所得於天者，則不以是而有所加損也。

第二十二章

*◎ 孟子曰：「伯夷辟紂，居北海之濱，聞文王作興，曰：『盍歸乎來！吾聞西伯善養老者。』太公辟紂，居東海之濱，聞文王作興，曰：『盍歸乎來！吾聞西伯善養老者。』天下有善養老，則仁人以為己歸矣。*

朱熹《孟子集註》：己歸，謂己之所歸。餘見前篇。

*◎ 五畝之宅，樹牆下以桑，匹婦蠶之，則老者足以衣帛矣。五母雞，二母彘，無失其時，老者足以無失肉矣。百畝之田，匹夫耕之，八口之家足以無饑矣。*

朱熹《孟子集註》：此文王之政也。一家養母雞五，母彘二也。餘見前篇。

*◎ 所謂西伯善養老者，制其田里，教之樹畜，導其妻子，使養其老。五十非帛不煖，七十非肉不飽。不煖不飽，謂之凍餒。文王之民，無凍餒之老者，此之謂也。」*

朱熹《孟子集註》：田，謂百畝之田。里，謂五畝之宅。樹，謂耕桑。畜，謂雞彘也。趙氏曰：「善養老者，教導之使可以養其老耳，非家賜而人益之也。」

第二十三章

*◎ 孟子曰：「易其田疇，薄其稅斂，民可使富也。*

朱熹《孟子集註》：易，治也。疇，耕治之田也。

*◎ 食之以時，用之以禮，財不可勝用也。*

朱熹《孟子集註》：教民節儉，則財用足也。

*◎ 民非水火不生活，昏暮叩人之門戶，求水火，無弗與者，至足矣。聖人治天下，使有菽粟如水火。菽粟如水火，而民焉有不仁者乎？」*

朱熹《孟子集註》：水火，民之所急，宜其愛之而反不愛者，多故也。尹焞曰：「言禮義生於富足，民無常產，則無常心矣。」

第二十四章

*◎ 孟子曰：「孔子登東山而小魯，登太山而小天下。故觀於海者難為水，遊於聖人之門者難為言。*

朱熹《孟子集註》：此言聖人之道大也。東山，蓋魯城東之高山，而太山則又高矣。此言所處益高，則其視下益小；所見既大，則其小者不足觀也。難為水，難為言，猶仁不可為眾之意。

*◎ 觀水有術，必觀其瀾。日月有明，容光必照焉。*

朱熹《孟子集註》：此言道之有本也。瀾，水之湍急處也。明者，光之體；光者，明之用也。觀水之瀾，則知其源之有本矣；觀日月於容光之隙無不照，則知其明之有本矣。

*◎ 流水之為物也，不盈科不行；君子之志於道也，不成章不達。」*

朱熹《孟子集註》：言學當以漸，乃能至也。成章，所積者厚，而文章外見也。達者，足於此而通於彼也。此章言聖人之道大而有本，學之者必以其漸，乃能至也。

第二十五章

*◎ 孟子曰：「雞鳴而起，孳孳為善者，舜之徒也。*

朱熹《孟子集註》：孳孳，勤勉之意。言雖未至於聖人，亦是聖人之徒也。

*◎ 雞鳴而起，孳孳為利者，蹠之徒也。*

朱熹《孟子集註》：蹠，盜蹠也。

*◎ 欲知舜與蹠之分，無他，利與善之閒也。」*

朱熹《孟子集註》：

程子曰：「言閒者，謂相去不遠，所爭毫末耳。善與利，公私而已矣。纔出於善，便以利言也。」

楊時曰：「舜蹠之相去遠矣，而其分，乃在利善之閒而已，是豈可以不謹？然講之不熟，見之不明，未有不以利為義者，又學者所當深察也。」

或問：「雞鳴而起，若未接物，如何為善？」程子曰：「只主於敬，便是為善。」

第二十六章

*◎ 孟子曰：「楊子取為我，拔一毛而利天下，不為也。*

朱熹《孟子集註》：楊子，名朱。取者，僅足之意。取為我者，僅足於為我而已，不及為人也。列子稱其言曰，「伯成子高不以一毫利物」，是也。

*◎ 墨子兼愛，摩頂放踵利天下，為之。*

朱熹《孟子集註》：墨子，名翟。兼愛，無所不愛也。摩頂，摩突其頂也。放，至也。

*◎ 子莫執中，執中為近之，執中無權，猶執一也。*

朱熹《孟子集註》：子莫，魯之賢人也。知楊墨之失中也，故度於二者之閒而執其中。近，近道也。權，稱錘也，所以稱物之輕重而取中也。執中而無權，則膠於一定之中而不知變，是亦執一而已矣。

程子曰：「中字最難識，須是默識心通。且試言一廳，則中央為中；一家，則廳非中而堂為中；一國，則堂非中而國之中為中，推此類可見矣。」又曰：「中不可執也，識得則事事物物皆有自然之中，不待安排，安排著則不中矣。」

*◎ 所惡執一者，為其賊道也，舉一而廢百也。」*

朱熹《孟子集註》：賊，害也。為我害仁，兼愛害義，執中者害於時中，皆舉一而廢百者也。此章言道之所貴者中，中之所貴者權。

楊時曰：「禹稷三過其門而不入，苟不當其可，則與墨子無異。顏子在陋巷，不改其樂，苟不當其可，則與楊氏無異。子莫執為我兼愛之中而無權，鄉鄰有鬬而不知閉戶，同室有鬬而不知救之，是亦猶執一耳，故孟子以為賊道。禹、稷、顏回，易地則皆然，以其有權也；不然，則是亦楊墨而已矣。」

第二十七章

*◎ 孟子曰：「飢者甘食，渴者甘飲，是未得飲食之正也，飢渴害之也。豈惟口腹有飢渴之害？人心亦皆有害。*

朱熹《孟子集註》：口腹為飢渴所害，故於飲食不暇擇，而失其正味；人心為貧賤所害，故於富貴不暇擇，而失其正理。

*◎ 人能無以飢渴之害為心害，則不及人不為憂矣。」*

朱熹《孟子集註》：人能不以貧賤之故而動其心，則過人遠矣。

第二十八章

*◎ 孟子曰：「柳下惠不以三公易其介。」*

朱熹《孟子集註》：介，有分辨之意。柳下惠進不隱賢，必以其道，遺佚不怨，阨窮不憫，直道事人，至於三黜，是其介也。此章言柳下惠和而不流，與孔子論夷齊不念舊惡意正相類，皆聖賢微顯闡幽之意也。

第二十九章

*◎ 孟子曰：「有為者辟若掘井，掘井九軔而不及泉，猶為棄井也。」*

朱熹《孟子集註》：八尺為仞。言鑿井雖深，然未及泉而止，猶為自棄其井也。呂侍講曰：「仁不如堯，孝不如舜，學不如孔子，終未入於聖人之域，終未至於天道，未免為半塗而廢、自棄前功也。」

第三十章

*◎ 孟子曰：「堯舜，性之也；湯武，身之也；五霸，假之也。*

朱熹《孟子集註》：堯舜天性渾全，不假修習。湯武修身體道，以復其性。五霸則假借仁義之名，以求濟其貪欲之私耳。

*◎ 久假而不歸，惡知其非有也。」*

朱熹《孟子集註》：歸，還也。有，實有也。言竊其名以終身，而不自知其非真有。或曰：「蓋歎世人莫覺其偽者。」亦通。舊說，久假不歸，即為真有，則誤矣。

尹焞曰：「性之者，與道一也；身之者，履之也，及其成功則一也。五霸則假之而已，是以功烈如彼其卑也。」

第三十一章

*◎ 公孫丑曰：「伊尹曰：『予不狎于不順。』放太甲于桐，民大悅。太甲賢。又反之，民大悅。*

朱熹《孟子集註》：子不狎于不順，太甲篇文。狎，習見也。不順，言太甲所為，不順義理也。餘見前篇。

*◎ 賢者之為人臣也，其君不賢，則固可放與？」孟子曰：「有伊尹之志，則可；無伊尹之志，則篡也。」*

朱熹《孟子集註》：伊尹之志，公天下以為心而無一毫之私者也。

第三十二章

*◎ 公孫丑曰：「詩曰『不素餐兮』，君子之不耕而食，何也？」孟子曰：「君子居是國也，其君用之，則安富尊榮；其子弟從之，則孝弟忠信。『不素餐兮』，孰大於是？」*

朱熹《孟子集註》：詩魏國風伐檀之篇。素，空也。無功而食祿，謂之素餐，此與告陳相、彭更之意同。

第三十三章

*◎ 王子墊問曰：「士何事？」*

朱熹《孟子集註》：墊，齊王之子也。上則公卿大夫，下則農工商賈，皆有所事；而士居其閒，獨無所事，故王子問之也。

*◎ 孟子曰：「尚志。」*

朱熹《孟子集註》：尚，高尚也。志者，心之所之也。士既未得行公、卿、大夫之道，又不當為農、工、商、賈之業，則高尚其志而已。

*◎ 曰：「何謂尚志？」曰：「仁義而已矣。殺一無罪，非仁也；非其有而取之，非義也。居惡在？仁是也；路惡在？義是也。居仁由義，大人之事備矣。」*

朱熹《孟子集註》：非仁非義之事，雖小不為；而所居所由，無不在於仁義，此士所以尚其志也。大人，謂公、卿、大夫。言士雖未得大人之位，而其志如此，則大人之事體用已全。若小人之事，則固非所當為也。

第三十四章

*◎ 孟子曰：「仲子，不義與之齊國而弗受，人皆信之，是舍簞食豆羹之義也。人莫大焉亡親戚、君臣、上下。以其小者信其大者，奚可哉？」*

朱熹《孟子集註》：仲子，陳仲子也。言仲子設若非義而與之齊國，必不肯受。齊人皆信其賢，然此但小廉耳。其辟兄離母，不食君祿，無人道之大倫，罪莫大焉。豈可以小廉信其大節，而遂以為賢哉？

第三十五章

*◎ 桃應問曰：「舜為天子，皋陶為士，瞽瞍殺人，則如之何？」*

朱熹《孟子集註》：桃應，孟子弟子也。其意以為舜雖愛父，而不可以私害公；皋陶雖執法，而不可以刑天子之父。故設此問，以觀聖賢用心之所極，非以為真有此事也。

*◎ 孟子曰：「執之而已矣。」*

朱熹《孟子集註》：言皋陶之心，知有法而已，不知有天子之父也。

*◎ 「然則舜不禁與？」*

朱熹《孟子集註》：桃應問也。

*◎ 曰：「夫舜惡得而禁之？夫有所受之也。」*

朱熹《孟子集註》：言皋陶之法，有所傳受，非所敢私，雖天子之命亦不得而廢之也。

*◎ 「然則舜如之何？」*

朱熹《孟子集註》：桃應問也。

*◎ 曰：「舜視棄天下，猶棄敝蹝也。竊負而逃，遵海濱而處，終身訢然，樂而忘天下。」*

朱熹《孟子集註》：蹝，草履也。遵，循也。言舜之心。知有父而已，不知有天下也。孟子嘗言舜視天下猶草芥，而惟順於父母可以解憂，與此意互相發。此章言為士者，但知有法，而不知天子父之為尊；為子者，但知有父，而不知天下之為大。蓋其所以為心者，莫非天理之極，人倫之至。學者察此而有得焉，則不待較計論量，而天下無難處之事矣。

第三十六章

*◎ 孟子自范之齊，望見齊王之子。喟然歎曰：「居移氣，養移體，大哉居乎！夫非盡人之子與？」*

朱熹《孟子集註》：范，齊邑。居，謂所處之位。養，奉養也。言人之居處，所繫甚大，王子亦人子耳，特以所居不同，故所養不同而其氣體有異也。

*◎ 孟子曰：*

朱熹《孟子集註》：張鄒皆云羨文也。

*◎ 「王子宮室、車馬、衣服多與人同，而王子若彼者，其居使之然也；況居天下之廣居者乎？*

朱熹《孟子集註》：廣居，見前篇。尹焞曰：「睟然見於面，盎於背，居天下之廣居者然也。」

*◎ 魯君之宋，呼於垤澤之門。守者曰：『此非吾君也，何其聲之似我君也？』此無他，居相似也。」*

朱熹《孟子集註》：垤澤，宋城門名也。孟子又引此事為證。

第三十七章

*◎ 孟子曰：「食而弗愛，豕交之也；愛而不敬，獸畜之也。*

朱熹《孟子集註》：交，接也。畜，養也。獸，謂犬馬之屬。

*◎ 恭敬者，幣之未將者也。*

朱熹《孟子集註》：將，猶奉也。詩曰：「承筐是將。」

程子曰：「恭敬雖因威儀幣帛而後發見，然幣之未將時，已有此恭敬之心，非因幣帛而後有也。」

*◎ 恭敬而無實，君子不可虛拘。」*

朱熹《孟子集註》：此言當時諸侯之待賢者，特以幣帛為恭敬，而無其實也。拘，留也。

第三十八章

*◎ 孟子曰：「形色，天性也；惟聖人，然後可以踐形。」*

朱熹《孟子集註》：人之有形有色，無不各有自然之理，所謂天性也。踐，如踐言之踐。蓋眾人有是形，而不能盡其理，故無以踐其形；惟聖人有是形，而又能盡其理，然後可以踐其形而無歉也。

程子曰：「此言聖人盡得人道而能充其形也。蓋人得天地之正氣而生，與萬物不同。既為人，須盡得人理，然後稱其名。眾人有之而不知，賢人踐之而未盡，能充其形，惟聖人也。」

楊時曰：「天生烝民，有物有則。物者，形色也。則者，性也。各盡其則，則可以踐形矣。」

第三十九章

*◎ 齊宣王欲短喪。公孫丑曰：「為朞之喪，猶愈於已乎？」*

朱熹《孟子集註》：已，猶止也。

*◎ 孟子曰：「是猶或紾其兄之臂，子謂之姑徐徐云爾，亦教之孝弟而已矣。」*

朱熹《孟子集註》：紾，戾也。教之以孝弟之道，則彼當自知兄之不可戾，而喪之不可短矣。孔子曰：「子生三年，然後免於父母之懷，予也有三年之愛於其父母乎？」所謂教之以孝弟者如此。蓋示之以至情之不能已者，非強之也。

*◎ 王子有其母死者，其傅為之請數月之喪。公孫丑曰：「若此者，何如也？」*

朱熹《孟子集註》：陳氏曰：「王子所生之母死，厭於嫡母而不敢終喪。其傅為請於王，欲使得行數月之喪也。時又適有此事，丑問如此者，是非何如？」按《儀禮》：「公子為其母練冠、麻衣、縓緣，既葬除之。」疑當時此禮已廢，或既葬而未忍即除，故請之也。

*◎ 曰：「是欲終之而不可得也。雖加一日愈於已，謂夫莫之禁而弗為者也。」*

朱熹《孟子集註》：言王子欲終喪而不可得，其傅為請，雖止得加一日，猶勝不加。我前所譏，乃謂夫莫之禁而自不為者耳。此章言三年通喪，天經地義，不容私意有所短長。示之至情，則不肖者有以企而及之矣。

第四十章

*◎ 孟子曰：「君子之所以教者五：*

朱熹《孟子集註》：下文五者，蓋因人品高下，或相去遠近先後之不同。

*◎ 有如時雨化之者，*

朱熹《孟子集註》：時雨，及時之雨也。草木之生，播種封植，人力已至而未能自化，所少者，雨露之滋耳。及此時而雨之，則其化速矣。教人之妙，亦猶是也，若孔子之於顏曾是已。

*◎ 有成德者，有達財者，*

朱熹《孟子集註》：財，與材同。此各因其所長而教之者也。成德，如孔子之於冉閔；達財，如孔子之於由賜。

*◎ 有答問者，*

朱熹《孟子集註》：就所問而答之，若孔孟之於樊遲、萬章也。

*◎ 有私淑艾者。*

朱熹《孟子集註》：私，竊也。淑，善也。艾，治也。人或不能及門受業，但聞君子之道於人，而竊以善治其身，是亦君子教誨之所及，若孔孟之於陳亢、夷之是也。孟子亦曰：「予未得為孔子徒也，予私淑諸人也。」

*◎ 此五者，君子之所以教也。」*

朱熹《孟子集註》：聖賢施教，各因其材，小以成小，大以成大，無棄人也。

第四十一章

*◎ 公孫丑曰：「道則高矣，美矣，宜若登天然，似不可及也。何不使彼為可幾及而日孳孳也？」 孟子曰：「大匠不為拙工改廢繩墨，羿不為拙射變其彀率。*

朱熹《孟子集註》：彀率，彎弓之限也。言教人者，皆有不可易之法，不容自貶以殉學者之不能也。

*◎ 君子引而不發，躍如也。中道而立，能者從之。」*

朱熹《孟子集註》：引，引弓也。發，發矢也。躍如，如踴躍而出也。因上文彀率，而言君子教人，但授以學之之法，而不告以得之之妙，如射者之引弓而不發矢，然其所不告者，已如踴躍而見於前矣。中者，無過不及之謂。中道而立，言其非難非易。能者從之，言學者當自勉也。此章言道有定體，教有成法；卑不可抗，高不可貶；語不能顯，默不能藏。

第四十二章

*◎ 孟子曰：「天下有道，以道殉身；天下無道，以身殉道。*

朱熹《孟子集註》：殉，如殉葬之殉，以死隨物之名也。身出則道在必行，道屈則身在必退，以死相從而不離也。

*◎ 未聞以道殉乎人者也。」*

朱熹《孟子集註》：以道從人，妾婦之道。

第四十三章

*◎ 公都子曰：「滕更之在門也，若在所禮。而不答，何也？」*

朱熹《孟子集註》：趙氏曰：「滕更，滕君之弟，來學者也。」

*◎ 孟子曰：「挾貴而問，挾賢而問，挾長而問，挾有勳勞而問，挾故而問，皆所不答也。滕更有二焉。」*

朱熹《孟子集註》：趙氏曰：「二，謂挾貴、挾賢也。」尹焞曰：「有所挾，則受道之心不專，所以不答也。」此言君子雖誨人不倦，又惡夫意之不誠者。

第四十四章

*◎ 孟子曰：「於不可已而已者，無所不已；於所厚者薄，無所不薄也。*

朱熹《孟子集註》：已，止也。不可止，謂所不得不為者也。所厚，所當厚者也。此言不及者之弊。

*◎ 其進銳者，其退速。」*

朱熹《孟子集註》：進銳者，用心太過，其氣易衰，故退速。三者之弊，理勢必然，雖過不及之不同，然卒同歸於廢弛。

第四十五章

*◎ 孟子曰：「君子之於物也，愛之而弗仁；於民也，仁之而弗親。親親而仁民，仁民而愛物。」*

朱熹《孟子集註》：物，謂禽獸草木。愛，謂取之有時，用之有節。

程子曰：「仁，推己及人，如老吾老以及人之老，於民則可，於物則不可。統而言之則皆仁，分而言之則有序。」

楊時曰：「其分不同，故所施不能無差等，所謂理一而分殊者也。」

尹焞曰：「何以有是差等？一本故也，無偽也。」

第四十六章

*◎ 孟子曰：「知者無不知也，當務之為急；仁者無不愛也，急親賢之為務。堯舜之知而不徧物，急先務也；堯舜之仁不徧愛人，急親賢也。*

朱熹《孟子集註》：知者之知，並去聲。知者固無不知，然常以所當務者為急，則事無不治，而其為知也大矣；仁者固無不愛，然常急於親賢，則恩無不洽，而其為仁也博矣。

*◎ 不能三年之喪，而緦小功之察；放飯流歠，而問無齒決，是之謂不知務。」*

朱熹《孟子集註》：

三年之喪，服之重者也。緦麻三月，小功五月，服之輕者也。察，致詳也。放飯，大飯。流歠，長歠，不敬之大者也。齒決，嚙斷乾肉，不敬之小者也。問，講求之意。

此章言君子之於道，識其全體，則心不狹；知所先後，則事有序。

豐氏曰：「智不急於先務，雖徧知人之所知、徧能人之所能，徒弊精神，而無益於天下之治矣。仁不急於親賢，雖有仁民愛物之心，小人在位，無由下達，聰明日蔽於上，而惡政日加於下，此孟子所謂不知務也。」

* 盡心下

第一章

*◎ 孟子曰：「不仁哉，梁惠王也！仁者以其所愛及其所不愛，不仁者以其所不愛及其所愛。」*

朱熹《孟子集註》：親親而仁民，仁民而愛物，所謂以其所愛及其所不愛也。

*◎ 公孫丑曰：「何謂也？」「梁惠王以土地之故，糜爛其民而戰之，大敗，將復之，恐不能勝，故驅其所愛子弟以殉之，是之謂以其所不愛及其所愛也。」*

朱熹《孟子集註》：梁惠王以下，孟子答辭也。糜爛其民，使之戰鬬，糜爛其血肉也。復之，復戰也。子弟，謂太子申也。以土地之故及其民，以民之故及其子，皆以其所不愛及其所愛也。此承前篇之末三章之意，言仁人之恩，自內及外；不仁之禍，由疏逮親。

第二章

*◎ 孟子曰：「春秋無義戰。彼善於此，則有之矣。*

朱熹《孟子集註》：春秋每書諸侯戰伐之事，必加譏貶，以著其擅興之罪，無有以為合於義而許之者。但就中彼善於此者則有之，如召陵之師之類是也。

*◎ 征者上伐下也，敵國不相征也。」*

朱熹《孟子集註》：征，所以正人也。諸侯有罪，則天子討而正之，此春秋所以無義戰也。

第三章

*◎ 孟子曰：「盡信書，則不如無書。*

程子曰：「載事之辭，容有重稱而過其實者，學者當識其義而已；苟執於辭，則時或有害於義，不如無書之愈也。」

*◎ 吾於武成，取二三策而已矣。*

朱熹《孟子集註》：武成，周書篇名，武王伐紂歸而記事之書也。策，竹簡也。取其二三策之言，其餘不可盡信也。

程子曰：「取其奉天伐暴之意，反政施仁之法而已。」

*◎ 仁人無敵於天下。以至仁伐至不仁，而何其血之流杵也？」*

朱熹《孟子集註》：杵，舂杵也。或作鹵，楯也。武成言武王伐紂，紂之「前徒倒戈，攻于後以北，血流漂杵」。孟子言此則其不可信者。然書本意，乃謂商人自相殺，非謂武王殺之也。孟子之設是言，懼後世之惑，且長不仁之心耳。

第四章

*◎ 孟子曰：「有人曰：『我善為陳，我善為戰。』大罪也。*

朱熹《孟子集註》：制行伍曰陳，交兵曰戰。

*◎ 國君好仁，天下無敵焉。 南面而征北狄怨，東面而征西夷怨。曰：『奚為後我？』*

朱熹《孟子集註》：此引湯之事以明之，解見前篇。

*◎ 武王之伐殷也，革車三百兩，虎賁三千人。*

朱熹《孟子集註》：又以武王之事明之也。兩，車數，一車兩輪也。千，書序作百。

*◎ 王曰：『無畏！寧爾也，非敵百姓也。』若崩厥角稽首。*

朱熹《孟子集註》：書太誓文與此小異。孟子之意當云王謂商人曰：「無畏我也。我來伐紂，本為安寧汝，非敵商之百姓也。」於是商人稽首至地，如角之崩也。

*◎ 征之為言正也，各欲正己也，焉用戰？」*

朱熹《孟子集註》：民為暴君所虐，皆欲仁者來正己之國也。

第五章

*◎ 孟子曰：「梓匠輪輿能與人規矩，不能使人巧。」*

朱熹《孟子集註》：尹焞曰：「規矩，法度可告者也。巧則在其人，雖大匠亦末如之何也已。蓋下學可以言傳，上達必由心悟，莊周所論斲輪之意蓋如此。」

第六章

*◎ 孟子曰：「舜之飯糗茹草也，若將終身焉；及其為天子也，被袗衣，鼓琴，二女果，若固有之。」*

朱熹《孟子集註》：飯，食也。糗，乾糒也。茹，亦食也。袗，畫衣也。二女，堯二女也。果，女侍也。言聖人之心，不以貧賤而有慕於外，不以富貴而有動於中，隨遇而安，無預於己，所性分定故也。

第七章

*◎ 孟子曰：「吾今而後知殺人親之重也：殺人之父，人亦殺其父；殺人之兄，人亦殺其兄。然則非自殺之也，一閒耳。」*

朱熹《孟子集註》：言吾今而後知者，必有所為而感發也。一閒者，我往彼來，閒一人耳，其實與自害其親無異也。

范祖禹曰：「知此則愛敬人之親，人亦愛敬其親矣。」

第八章

*◎ 孟子曰：「古之為關也，將以禦暴。*

朱熹《孟子集註》：譏察非常。

*◎ 今之為關也，將以為暴。」*

范祖禹曰：「古之耕者什一，後世或收大半之稅，此以賦斂為暴也。文王之囿，與民同之；齊宣王之囿，為阱國中，此以園囿為暴也。後世為暴，不止於關，若使孟子用於諸侯，必行文王之政，凡此之類，皆不終日而改也。」

第九章

*◎ 孟子曰：「身不行道，不行於妻子；使人不以道，不能行於妻子。」*

朱熹《孟子集註》：身不行道者，以行言之。不行者，道不行也。使人不以道者，以事言之。不能行者，令不行也。

第十章

*◎ 孟子曰：「周于利者，凶年不能殺；周于德者，邪世不能亂。」*

朱熹《孟子集註》：周，足也，言積之厚則用有餘。

第十一章

*◎ 孟子曰：「好名之人，能讓千乘之國；苟非其人，簞食豆羹見於色。」*

朱熹《孟子集註》：好名之人，矯情干譽，是以能讓千乘之國；然若本非能輕富貴之人，則於得失之小者，反不覺其真情之發見矣。蓋觀人不於其所勉，而於其所忽，然後可以見其所安之實也。

第十二章

*◎ 孟子曰：「不信仁賢，則國空虛。*

朱熹《孟子集註》：空虛，言若無人然。

*◎ 無禮義，則上下亂。*

朱熹《孟子集註》：禮義，所以辨上下，定民志。

*◎ 無政事，則財用不足。」*

朱熹《孟子集註》：生之無道，取之無度，用之無節故也。尹焞曰：「三者以仁賢為本。無仁賢，則禮義政事，處之皆不以其道矣。」

第十三章

*◎ 孟子曰：「不仁而得國者，有之矣；不仁而得天下，未之有也。」*

朱熹《孟子集註》：言不仁之人，騁其私智，可以盜千乘之國，而不可以得丘民之心。鄒氏曰：「自秦以來，不仁而得天下者有矣；然皆一再傳而失之，猶不得也。所謂得天下者，必如三代而後可。」

第十四章

*◎ 孟子曰：「民為貴，社稷次之，君為輕。*

朱熹《孟子集註》：社，土神。稷，榖神。建國則立壇壝以祀之。蓋國以民為本，社稷亦為民而立，而君之尊，又係於二者之存亡，故其輕重如此。

*◎ 是故得乎丘民而為天子，得乎天子為諸侯，得乎諸侯為大夫。*

朱熹《孟子集註》：丘民，田野之民，至微賤也。然得其心，則天下歸之。天子至尊貴也，而得其心者，不過為諸侯耳，是民為重也。

*◎ 諸侯危社稷，則變置。*

朱熹《孟子集註》：諸侯無道，將使社稷為人所滅，則當更立賢君，是君輕於社稷也。

*◎ 犧牲既成，粢盛既潔，祭祀以時，然而旱乾水溢，則變置社稷。」*

朱熹《孟子集註》：祭祀不失禮，而土榖之神不能為民禦災捍患，則毀其壇壝而更置之，亦年不順成，八蜡不通之意，是社稷雖重於君而輕於民也。

第十五章

*◎ 孟子曰：「聖人，百世之師也，伯夷、柳下惠是也。故聞伯夷之風者，頑夫廉，懦夫有立志；聞柳下惠之風者，薄夫敦，鄙夫寬。奮乎百世之上。百世之下，聞者莫不興起也。非聖人而能若是乎，而況於親炙之者乎？」*

朱熹《孟子集註》：興起，感動奮發也。親炙，親近而熏炙之也，餘見前篇。

第十六章

*◎ 孟子曰：「仁也者，人也。合而言之，道也。」*

朱熹《孟子集註》：

仁者，人之所以為人之理也。然仁，理也；人，物也。以仁之理，合於人之身而言之，乃所謂道者也。

程子曰：「中庸所謂率性之謂道是也。」

或曰：「外國本，人也之下，有『義也者宜也，禮也者履也，智也者知也，信也者實也』，凡二十字。」今按如此，則理極分明，然未詳其是否也。

第十七章

*◎ 孟子曰：「孔子之去魯，曰：『遲遲吾行也。』去父母國之道也。去齊，接淅而行，去他國之道也。」*

朱熹《孟子集註》：重出。

第十八章

*◎ 孟子曰：「君子之戹於陳蔡之閒，無上下之交也。」*

朱熹《孟子集註》：君子，孔子也。戹，與厄同，君臣皆惡，無所與交也。

第十九章

*◎ 貉稽曰：「稽大不理於口。」*

朱熹《孟子集註》：趙氏曰：「貉姓，稽名，為眾口所訕。」理，賴也。今按漢書無俚，方言亦訓賴。

*◎ 孟子曰：「無傷也。士憎茲多口。*

朱熹《孟子集註》：趙氏曰：「為士者，益多為眾口所訕。」按此則憎當從土，今本皆從心，蓋傳寫之誤。

*◎ 詩云：『憂心悄悄，慍于羣小。』孔子也。『肆不殄厥慍，亦不隕厥問。』文王也。」*

朱熹《孟子集註》：

詩邶風柏舟，及大雅緜之篇也。

悄悄，憂貌。慍，怒也。本言衛之仁人見怒於羣小。孟子以為孔子之事，可以當之。

肆，發語辭。隕，墜也。問，聲問也。本言太王事昆夷，雖不能殄絕其慍怒，亦不自墜其聲問之美。孟子以為文王之事，可以當之。

尹焞曰：「言人顧自處如何，盡其在我者而已。」

第二十章

*◎ 孟子曰：「賢者以其昭昭，使人昭昭；今以其昬昬，使人昭昭。」*

朱熹《孟子集註》：昭昭，明也。昬昬，闇也。尹焞曰：「大學之道，在自昭明德，而施於天下國家，其有不順者寡矣。」

第二十一章

*◎ 孟子謂高子曰：「山徑之蹊閒，介然用之而成路。為閒不用，則茅塞之矣。今茅塞子之心矣。」*

朱熹《孟子集註》：徑，小路也。蹊，人行處也。介然，倏然之頃也。用，由也。路，大路也。為閒，少頃也。茅塞，茅草生而塞之也。言理義之心，不可少有閒斷也。

第二十二章

*◎ 高子曰：「禹之聲，尚文王之聲。」*

朱熹《孟子集註》：尚，加尚也。豐氏曰：「言禹之樂，過於文王之樂。」

*◎ 孟子曰：「何以言之？」曰：「以追蠡。」*

朱熹《孟子集註》：豐氏曰：「追，鐘紐也。周禮所謂旋蟲是也。蠡者，齧木蟲也。言禹時鐘在者，鐘紐如蟲齧而欲絕，蓋用之者多，而文王之鐘不然，是以知禹之樂過於文王之樂也。」

*◎ 曰：「是奚足哉？城門之軌，兩馬之力與？」*

朱熹《孟子集註》：

豐氏曰：「奚足，言此何足以知之也。軌，車轍迹也。兩馬，一車所駕也。城中之涂容九軌，車可散行，故其轍迹淺；城門惟容一車，車皆由之，故其轍迹深。蓋日久車多所致，非一車兩馬之力，能使之然也。言禹在文王前千餘年，故鐘久而紐絕；文王之鐘，則未久而紐全，不可以此而議優劣也。」

此章文義本不可曉，舊說相承如此，而豐氏差明白，故今存之，亦未知其是否也。

第二十三章

*◎ 齊饑。陳臻曰：「國人皆以夫子將復為發棠，殆不可復。」*

朱熹《孟子集註》：先時齊國嘗饑，孟子勸王發棠邑之倉，以振貧窮。至此又饑，陳臻問言齊人望孟子復勸王發棠，而又自言恐其不可也。

*◎ 孟子曰：「是為馮婦也。晉人有馮婦者，善搏虎，卒為善士。則之野，有眾逐虎。虎負嵎，莫之敢攖。望見馮婦，趨而迎之。馮婦攘臂下車。眾皆悅之，其為士者笑之。」*

朱熹《孟子集註》：手執曰搏。卒為善士，後能改行為善也。之，適也。負，依也。山曲曰嵎。攖，觸也。笑之，笑其不知止也。疑此時齊王已不能用孟子，而孟子亦將去矣，故其言如此。

第二十四章

*◎ 孟子曰：「口之於味也，目之於色也，耳之於聲也，鼻之於臭也，四肢之於安佚也，性也，有命焉，君子不謂性也。*

朱熹《孟子集註》：

程子曰：「五者之欲，性也。然有分，不能皆如其願，則是命也。不可謂我性之所有，而求必得之也。」

愚按：不能皆如其願，不止為貧賤。蓋雖富貴之極，亦有品節限制，則是亦有命也。

*◎ 仁之於父子也，義之於君臣也，禮之於賓主也，智之於賢者也，聖人之於天道也，命也，有性焉，君子不謂命也。」*

朱熹《孟子集註》：

程子曰：「仁義禮智天道，在人則賦於命者，所稟有厚薄清濁，然而性善可學而盡，故不謂之命也。」

張載曰：「晏嬰智矣，而不知仲尼。是非命邪？」

愚按：所稟者厚而清，則其仁之於父子也至，義之於君臣也盡，禮之於賓主也恭，智之於賢否也哲，聖人之於天道也，無不脗合而純亦不已焉。薄而濁，則反是，是皆所謂命也。或曰：「者」當作否，「人」衍字，更詳之。

愚聞之師曰：「此二條者，皆性之所有而命於天者也。然世之人，以前五者為性，雖有不得，而必欲求之；以後五者為命，一有不至，則不復致力，故孟子各就其重處言之，以伸此而抑彼也。張子所謂『養則付命於天，道則責成於己』。其言約而盡矣。」

第二十五章

*◎ 浩生不害問曰：「樂正子，何人也？」孟子曰：「善人也，信人也。」*

朱熹《孟子集註》：趙氏曰：「浩生，姓；不害，名，齊人也。」

*◎ 「何謂善？何謂信？」*

朱熹《孟子集註》：不害問也。

*◎ 曰：「可欲之謂善，*

朱熹《孟子集註》：天下之理，其善者必可欲，其惡者必可惡。其為人也，可欲而不可惡，則可謂善人矣。

*◎ 有諸己之謂信。*

朱熹《孟子集註》：凡所謂善，皆實有之，如惡惡臭，如好好色，是則可謂信人矣。

張載曰：「志仁無惡之謂善，誠善於身之謂信。」

*◎ 充實之謂美，*

朱熹《孟子集註》：力行其善，至於充滿而積實，則美在其中而無待於外矣。

*◎ 充實而有光輝之謂大，*

朱熹《孟子集註》：和順積中，而英華發外；美在其中，而暢於四支，發於事業，則德業至盛而不可加矣。

*◎ 大而化之之謂聖，*

朱熹《孟子集註》：大而能化，使其大者泯然無復可見之迹，則不思不勉、從容中道，而非人力之所能為矣。

張載曰：「大可為也，化不可為也，在熟之而已矣。」

*◎ 聖而不可知之之謂神。*

程子曰：「聖不可知，謂聖之至妙，人所不能測。非聖人之上，又有一等神人也。」

*◎ 樂正子，二之中，四之下也。」*

朱熹《孟子集註》：蓋在善信之閒，觀其從於子敖，則其有諸己者或未實也。

張載曰：「顏淵、樂正子皆知好仁矣。樂正子志仁無惡而不致於學，所以但為善人信人而已；顏子好學不倦，合仁與智，具體聖人，獨未至聖人之止耳。」

程子曰：「士之所難者，在有諸己而已。能有諸己，則居之安，資之深，而美且大可以馴致矣。徒知可欲之善，而若存若亡而已，則能不受變於俗者鮮矣。」

尹焞曰：「自可欲之善，至於聖而不可知之神，上下一理。擴充之至於神，則不可得而名矣。」

第二十六章

*◎ 孟子曰：「逃墨必歸於楊，逃楊必歸於儒。歸，斯受之而已矣。*

朱熹《孟子集註》：墨氏務外而不情，楊氏太簡而近實，故其反正之漸，大略如此。歸斯受之者，憫其陷溺之久，而取其悔悟之新也。

*◎ 今之與楊墨辯者，如追放豚，既入其苙，又從而招之。」*

朱熹《孟子集註》：放豚，放逸之豕豚也。苙，闌也。招，罥也，羈其足也。言彼既來歸，而又追咎其既往之失也。此章見聖賢之於異端，距之甚嚴，而於其來歸，待之甚恕。距之嚴，故人知彼說之為邪；待之恕，故人知此道之可反，仁之至，義之盡也。

第二十七章

*◎ 孟子曰：「有布縷之征，粟米之征，力役之征。君子用其一，緩其二。用其二而民有殍，用其三而父子離。」*

朱熹《孟子集註》：征賦之法，歲有常數，然布縷取之於夏，粟米取之於秋，力役取之於冬，當各以其時；若并取之，則民力有所不堪矣。今兩稅三限之法，亦此意也。尹焞曰：「言民為邦本，取之無度，則其國危矣。」

第二十八章

*◎ 孟子曰：「諸侯之寶三：土地，人民，政事。寶珠玉者，殃必及身。」*

朱熹《孟子集註》：尹焞曰：「言寶得其寶者安，寶失其寶者危。」

第二十九章

*◎ 盆成括仕於齊。孟子曰：「死矣盆成括！」盆成括見殺。門人問曰：「夫子何以知其將見殺？」曰：「其為人也小有才，未聞君子之大道也，則足以殺其軀而已矣。」*

朱熹《孟子集註》：盆成，姓；括，名也。恃才妄作，所以取禍。徐氏曰：「君子道其常而已。括有死之道焉，設使幸而獲免，孟子之言猶信也。」

第三十章

*◎ 孟子之滕，館於上宮。有業屨於牖上，館人求之弗得。*

朱熹《孟子集註》：館，舍也。上宮，別宮名。業屨，織之有次業而未成者，蓋館人所作，置之牖上而失之也。

*◎ 或問之曰：「若是乎從者之廋也？」曰：「子以是為竊屨來與？」曰：「殆非也。夫子之設科也，往者不追，來者不距。苟以是心至，斯受之而已矣。」*

朱熹《孟子集註》：或問之者，問於孟子也。廋，匿也。言子之從者，乃匿人之物如此乎？孟子答之，而或人自悟其失，因言此從者固不為竊屨而來，但夫子設置科條以待學者，苟以向道之心而來，則受之耳，雖夫子亦不能保其往也。門人取其言，有合於聖賢之指，故記之。

第三十一章

*◎ 孟子曰：「人皆有所不忍，達之於其所忍，仁也；人皆有所不為，達之於其所為，義也。*

朱熹《孟子集註》：惻隱羞惡之心，人皆有之，故莫不有所不忍不為，此仁義之端也。然以氣質之偏、物欲之蔽，則於他事或有不能者。但推所能，達之於所不能，則無非仁義矣。

*◎ 人能充無欲害人之心，而仁不可勝用也；人能充無穿踰之心，而義不可勝用也。*

朱熹《孟子集註》：充，滿也。穿，穿穴；踰，踰牆，皆為盜之事也。能推所不忍，以達於所忍，則能滿其無欲害人之心，而無不仁矣；能推其所不為，以達於所為，則能滿其無穿踰之心，而無不義矣。

*◎ 人能充無受爾汝之實，無所往而不為義也。*

朱熹《孟子集註》：此申說上文充無穿踰之心之意也。蓋爾汝人所輕賤之稱，人雖或有所貪昧隱忍而甘受之者，然其中心必有慚忿而不肯受之之實。人能即此而推之，使其充滿無所虧缺，則無適而非義矣。

*◎ 士未可以言而言，是以言餂之也；可以言而不言，是以不言餂之也，是皆穿踰之類也。」*

朱熹《孟子集註》：餂，探取之也。今人以舌取物曰餂，即此意也。便佞隱默，皆有意探取於人，是亦穿踰之類。然其事隱微，人所易忽，故特舉以見例。明必推無穿踰之心，以達於此而悉去之，然後為能充其無穿踰之心也。

第三十二章

*◎ 孟子曰：「言近而指遠者，善言也；守約而施博者，善道也。君子之言也，不下帶而道存焉。*

朱熹《孟子集註》：古人視不下於帶，則帶之上，乃目前常見至近之處也。舉目前之近事，而至理存焉，所以為言近而指遠也。

*◎ 君子之守，修其身而天下平。*

朱熹《孟子集註》：此所謂守約而施博也。

*◎ 人病舍其田而芸人之田，所求於人者重，而所以自任者輕。」*

朱熹《孟子集註》：此言不守約而務博施之病。

第三十三章

*◎ 孟子曰：「堯舜，性者也；湯武，反之也。*

朱熹《孟子集註》：性者，得全於天，無所汙壞，不假修為，聖之至也。反之者，修為以復其性，而至於聖人也。

程子曰：「性之反之，古未有此語，蓋自孟子發之。」

呂大臨曰：「無意而安行，性者也，有意利行，而至於無意，復性者也。堯舜不失其性，湯武善反其性，及其成功則一也。」

*◎ 動容周旋中禮者，盛德之至也；哭死而哀，非為生者也；經德不回，非以干祿也；言語必信，非以正行也。*

朱熹《孟子集註》：中、為、行，並去聲。細微曲折，無不中禮，乃其盛德之至。自然而中，而非有意於中也。經，常也。回，曲也。三者亦皆自然而然，非有意而為之也，皆聖人之事，性之之德也。

*◎ 君子行法，以俟命而已矣。」*

朱熹《孟子集註》：法者，天理之當然者也。君子行之，而吉凶禍福有所不計，蓋雖未至於自然，而已非有所為而為矣。此反之之事，董子所謂「正其義不謀其利，明其道不計其功」，正此意也。

程子曰：「動容周旋中禮者，盛德之至。行法以俟命者，『朝聞道夕死可矣』之意也。」

呂大臨曰：「法由此立，命由此出，聖人也；行法以俟命，君子也。聖人性之，君子所以復其性也。」

第三十四章

*◎ 孟子曰：「說大人，則藐之，勿視其巍巍然。*

朱熹《孟子集註》：趙氏曰：「大人，當時尊貴者也。藐，輕之也。巍巍，富貴高顯之貌。藐焉而不畏之，則志意舒展，言語得盡也。」

*◎ 堂高數仞，榱題數尺，我得志弗為也；食前方丈，侍妾數百人，我得志弗為也；般樂飲酒，驅騁田獵，後車千乘，我得志弗為也。在彼者，皆我所不為也；在我者，皆古之制也，吾何畏彼哉？」*

朱熹《孟子集註》：榱，桷也。題，頭也。食前方丈，饌食列於前者，方一丈也。此皆其所謂巍巍然者，我雖得志，有所不為，而所守者皆古聖賢之法，則彼之巍巍者，何足道哉！

楊時曰：「孟子此章，以己之長，方人之短，猶有此等氣象，在孔子則無此矣。」

第三十五章

*◎ 孟子曰：「養心莫善於寡欲。其為人也寡欲，雖有不存焉者，寡矣；其為人也多欲，雖有存焉者，寡矣。」*

朱熹《孟子集註》：欲，如口鼻耳目四支之欲，雖人之所不能無，然多而不節，未有不失其本心者，學者所當深戒也。

程子曰：「所欲不必沈溺，只有所向便是欲。」

第三十六章

*◎ 曾皙嗜羊棗，而曾子不忍食羊棗。*

朱熹《孟子集註》：羊棗，實小黑而圓，又謂之羊矢棗。曾子以父嗜之，父歿之後，食必思親，故不忍食也。

*◎ 公孫丑問曰：「膾炙與羊棗孰美？」孟子曰：「膾炙哉！」公孫丑曰：「然則曾子何為食膾炙而不食羊棗？」曰：「膾炙所同也，羊棗所獨也。諱名不諱姓，姓所同也，名所獨也。」*

朱熹《孟子集註》：肉聶而切之為膾。炙，炙肉也。

第三十七章

*◎ 萬章問曰：「孔子在陳曰：『盍歸乎來！吾黨之士狂簡，進取，不忘其初。』孔子在陳，何思魯之狂士？」*

朱熹《孟子集註》：盍，何不也。狂簡，謂志大而略於事。進取，謂求望高遠。不忘其初，謂不能改其舊也。此語與論語小異。

*◎ 孟子曰：「孔子『不得中道而與之，必也狂獧乎！狂者進取，獧者有所不為也』。孔子豈不欲中道哉？不可必得，故思其次也。」*

朱熹《孟子集註》：不得中道，至有所不為，據論語亦孔子之言。然則孔子字下當有曰字。論語道作行，獧作狷。有所不為者，知恥自好，不為不善之人也。孔子豈不欲中道以下，孟子言也。

*◎ 「敢問何如斯可謂狂矣？」*

朱熹《孟子集註》：萬章問。

*◎ 曰：「如琴張、曾皙、牧皮者，孔子之所謂狂矣。」*

朱熹《孟子集註》：琴張，名牢，字子張。子桑戶死，琴張臨其喪而歌。事見莊子。雖未必盡然，要必有近似者。曾皙見前篇。季武子死，曾皙倚其門而歌，事見檀弓。又言志異乎三子者之撰，事見論語。牧皮，未詳。

*◎ 「何以謂之狂也？」*

萬章問。

*◎ 曰：「其志嘐嘐然，曰『古之人，古之人』。夷考其行而不掩焉者也。*

朱熹《孟子集註》：嘐嘐，志大言大也。重言古之人，見其動輒稱之，不一稱而已也。夷，平也。掩，覆也。言平考其行，則不能覆其言也。

程子曰：「曾皙言志，而夫子與之。蓋與聖人之志同，便是堯舜氣象也，特行有不掩焉耳，此所謂狂也。」

*◎ 狂者又不可得，欲得不屑不潔之士而與之，是獧也，是又其次也。*

朱熹《孟子集註》：此因上文所引，遂解所以思得獧者之意。狂，有志者也；獧，有守者也。有志者能進於道，有守者不失其身。屑，潔也。

*◎ 孔子曰：『過我門而不入我室，我不憾焉者，其惟鄉原乎！鄉原，德之賊也。』」曰：「何如斯可謂之鄉原矣？」*

朱熹《孟子集註》：鄉人，非有識者。原，與愿同。荀子「原愨」，字皆讀作愿，謂謹愿之人也。故鄉里所謂愿人，謂之鄉原。孔子以其似德而非德，故以為德之賊。過門不入而不恨之，以其不見親就為幸，深惡而痛絕之也。萬章又引孔子之言而問也。

*◎ 曰：「『何以是嘐嘐也？言不顧行，行不顧言，則曰：古之人，古之人。行何為踽踽涼涼？生斯世也，為斯世也，善斯可矣。』閹然媚於世也者，是鄉原也。」*

朱熹《孟子集註》：踽踽，獨行不進之貌。涼涼，薄也，不見親厚於人也。鄉原譏狂者曰：何用如此嘐嘐然，行不掩其言，而徒每事必稱古人邪？又譏狷者曰：何必如此踽踽涼涼，無所親厚哉？人既生於此世，則但當為此世之人，使當世之人皆以為善則可矣，此鄉原之志也。閹，如奄人之奄，閉藏之意也。媚，求悅於人也。孟子言此深自閉藏，以求親媚於世，是鄉原之行也。

*◎ 萬子曰：「一鄉皆稱原人焉，無所往而不為原人，孔子以為德之賊，何哉？」*

朱熹《孟子集註》：原，亦謹厚之稱，而孔子以為德之賊，故萬章疑之。

*◎ 曰：「非之無舉也，刺之無刺也；同乎流俗，合乎汙世；居之似忠信，行之似廉潔；眾皆悅之，自以為是，而不可與入堯舜之道，故曰德之賊也。*

朱熹《孟子集註》：呂侍講曰：「言此等之人，欲非之則無可舉，欲刺之則無可刺也。」流俗者，風俗頹靡，如水之下流，眾莫不然也。汙，濁也。非忠信而似忠信，非廉潔而似廉潔。

*◎ 孔子曰：『惡似而非者：惡莠，恐其亂苗也；惡佞，恐其亂義也；惡利口，恐其亂信也；惡鄭聲，恐其亂樂也；惡紫，恐其亂朱也；惡鄉原，恐其亂德也。』*

朱熹《孟子集註》：孟子又引孔子之言以明之。莠，似苗之草也。佞，才智之稱，其言似義而非義也。利口，多言而不實者也。鄭聲，淫樂也。樂，正樂也。紫，閒色。朱，正色也。鄉原不狂不獧，人皆以為善，有似乎中道而實非也，故恐其亂德。

*◎ 君子反經而已矣。經正，則庶民興；庶民興，斯無邪慝矣。」*

朱熹《孟子集註》：反，復也。經，常也，萬世不易之常道也。興，興起於善也。邪慝，如鄉原之屬是也。世衰道微，大經不正，故人人得為異說以濟其私，而邪慝并起，不可勝正，君子於此，亦復其常道而已。常道既復，則民興於善，而是非明白，無所回互，雖有邪慝，不足以惑之矣。

尹焞曰：「君子取夫狂獧者，蓋以狂者志大而可與進道，獧者有所不為，而可與有為也。所惡於鄉原，而欲痛絕之者，為其似是而非，惑人之深也。絕之之術無他焉，亦曰反經而已矣。」

第三十八章

*◎ 孟子曰：「由堯舜至於湯，五百有餘歲，若禹、皋陶，則見而知之；若湯，則聞而知之。*

朱熹《孟子集註》：趙氏曰：「五百歲而聖人出，天道之常；然亦有遲速，不能正五百年，故言有餘也。」尹焞曰：「知，謂知其道也。」

*◎ 由湯至於文王，五百有餘歲，若伊尹、萊朱則見而知之；若文王，則聞而知之。*

朱熹《孟子集註》：趙氏曰：「萊朱，湯賢臣。」或曰：「即仲虺也，為湯左相。」

*◎ 由文王至於孔子，五百有餘歲，若太公望、散宜生，則見而知之；若孔子，則聞而知之。*

朱熹《孟子集註》：散，氏；宜生，名；文王賢臣也。子貢曰：「文武之道，未墜於地，在人。賢者識其大者，不賢者識其小者，莫不有文武之道焉。夫子焉不學？」此所謂聞而知之也。

*◎ 由孔子而來至於今，百有餘歲，去聖人之世，若此其未遠也；近聖人之居，若此其甚也，然而無有乎爾，則亦無有乎爾。」*

朱熹《孟子集註》：

林氏曰：「孟子言孔子至今時未遠，鄒魯相去又近，然而已無有見而知之者矣；則五百餘歲之後，又豈復有聞而知之者乎？」

愚按：此言，雖若不敢自謂已得其傳，而憂後世遂失其傳，然乃所以自見其有不得辭者，而又以見夫天理民彝不可泯滅，百世之下，必將有神會而心得之者耳。故於篇終，歷序羣聖之統，而終之以此，所以明其傳之有在，而又以俟後聖於無窮也，其指深哉！

# 有宋元豐八年，河南程顥伯淳卒。潞公文彥博題其墓曰：「明道先生。」而其弟頤正叔序之曰：「周公歿，聖人之道不行；孟軻死，聖人之學不傳。道不行，百世無善治；學不傳，千載無真儒。無善治，士猶得以明夫善治之道，以淑諸人，以傳諸後；無真儒，則天下貿貿焉莫知所之，人欲肆而天理滅矣。先生生乎千四百年之後，得不傳之學於遺經，以興起斯文為己任。辨異端，闢邪說，使聖人之道渙然復明於世。蓋自孟子之後，一人而已。然學者於道不知所向，則孰知斯人之為功？不知所至，則孰知斯名之稱情也哉？」
