#+TITLE: 孟子·告子上下 / 盡心上下 註疏摘抄
#+OPTIONS: toc:1 num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./emacs.css" />

* 告子上

趙岐註：告子者，告，姓也；子，男子之通稱也；名不害。兼治儒墨之道者，嘗學於孟子，而不能純徹性命之理。《論語》曰：「子罕言命。」謂性命難言也。以告子能執弟子之問，故以題篇。

孫奭疏：此篇首論告子言性，所以次於萬章問孝之篇者，以其爲孝之道，其本在性也，故此篇首以告子之言性，遂爲篇題，次於《萬章》，不亦宜乎。

** 第一章

*◎ 告子曰：「性，猶杞柳也；義，猶桮棬也。以人性為仁義，猶以杞柳為桮棬。」*

趙岐註：告子以爲人性爲才幹，義爲成器，猶以杞柳之木為桮棬也。

孫奭疏：桮，素樸也。棬，器之似屈轉木作也。

朱熹《孟子集註》：性者，人生所稟之天理也。杞柳，柜柳。桮棬，屈木所為，若卮匜之屬。告子言人性本無仁義，必待矯揉而後成，如荀子性惡之說也。

#+begin_quote
《荀子·性惡》：工人斲木而成器，器生於工人之偽，非故生於木之性也。聖人積思慮，習偽故，以生禮義而起法度。然則禮義法度者，是生於聖人之偽，非故生於人之性也。

《荀子·性惡》：檃栝之生於枸木也，繩墨之起於不直也，立君上，明禮義，為性惡也。
#+end_quote

李贄評：`義猶桮棬也`不敢說仁字。

*◎ 孟子曰：「子能順杞柳之性而以為桮棬乎？將戕賊杞柳而後以為桮棬也？*

趙岐註：戕，猶殘也。子能順完杞柳，不傷其性，而成桮棬乎？將以斤斧殘賊之，乃可以爲桮棬乎？言必殘賊也。

焦循正義：傷殘則不能完全，故以順為完。

*◎ 如將戕賊杞柳而以為桮棬，則亦將戕賊人以為仁義與？率天下之人而禍仁義者，必子之言夫！」*

趙岐註：孟子言以人身爲仁義，豈可復殘傷其形體乃成仁義邪？明不可比桮棬。以告子轉性爲仁義，若轉木以成器，必殘賊之，故曰率人以禍仁義者，必子之言。夫，歎辭也。

朱熹《孟子集註》：言如此，則天下之人皆以仁義為害性而不肯為，是因子之言而為仁義之禍也。

正義：一章言養性長義，順夫自然，殘木爲器，變而後成。吿子道偏，見有不純，內仁外義，違人之端，孟子拂之，不假以言也。`劉熙《釋名·釋言語》云：「順，循也。循其理也。」孟子所謂「順性」即《中庸》所云「率性」。`

焦循正義：蓋人性所以有仁義者，正以其能變通，異乎物之性也。以己之心，通乎人之心，則仁也。知其不宜，變而之乎宜，則義也。仁義由於能變通，人能變通，故性善；物不能變通，故性不善，豈可以草木之性比人之性？杞柳為桮棬，在形體不在性，性不可變也。人為仁義，在性不在形體，性能變也。此所以禍仁義，而孟子所以辨也。

** 第二章

*◎ 告子曰：「性猶湍水也，決諸東方則東流，決諸西方則西流。人性之無分於善不善也，猶水之無分於東西也。」*

趙岐註：告子以喻人性若是水也，善惡隨物而化，無本善不善之性也。

孫奭疏：湍，圜，縈迴之水，決之使流於東方則東流之，使之流西方則西流之。

朱熹《孟子集註》：湍，波流瀠回之貌也。告子因前說而小變之，近於楊子善惡混之說。

焦循正義：隨物而化，謂習於善則善，習於惡則惡也。乃人性有上智下愚之不移，則不得謂隨物而化也。

*◎ 孟子曰：「水信無分於東西，無分於上下乎？人性之善也，猶水之就下也。人無有不善，水無有不下。*

趙岐註：水誠無分東西，故決之而往也。水豈無分於上下乎，水性但欲下耳。人性生而有善，猶水之欲下也。所以知人皆有善性，似水無有不下者也。

朱熹《孟子集註》：言水誠不分東西矣，然豈不分上下乎？性即天理，未有不善者也。

*◎ 今夫水搏而躍之，可使過顙；激而行之，可使在山。是豈水之性哉？其勢則然也。人之可使為不善，其性亦猶是也。」*

趙岐註：人以手跳水，可使過顙，激之可令上山，皆迫於勢耳，非水之性也。

朱熹《孟子集註》：

#+begin_verse
搏，擊也。躍，跳也。顙，額也。水之過額在山，皆不就下也。然其本性未嘗不就下，但為博激所使而逆其性耳。

此章言性本善，故順之而無不善；本無惡，故反之而後為惡，非本無定體，而可以無所不為也。
#+end_verse

正義：二章言人之欲善，猶水好下，迫勢激躍，失其素真，是以守正性者爲君子，隨曲拂者爲小人也。`真之義同於正，故上言素真，下言正性。`

#+BEGIN_QUOTE
《莊子·刻意》：故素也者，謂其無所與雜也；純也者，謂其不虧其神也。能體純素，謂之真人。
#+END_QUOTE

焦循正義：吿子始以不順其性為善，既知順其性為善矣，又並以順其性為不善，云杞柳，云湍水，皆儗不於倫也。

** 第三章

*◎ 告子曰：「生之謂性。」*

趙岐註：凡物生同類皆同性。

朱熹《孟子集註》：生，指人物之所以知覺運動者而言。告子論性，前後四章，語雖不同，然其大指不外乎此，與近世佛氏所謂作用是性者略相似。

#+BEGIN_QUOTE
《荀子·正名》：生之所以然者谓之性。性之和所生，精合感应，不事而自然谓之性。

《春秋繁露·深察名號》：如其生之自然之資，謂之性。性者質也。詰性之質於善之名，能中之與？既不能中矣，而尚謂之質善，何哉？性之名不得離質。離質如毛，則非性已，不可不察也。
#+END_QUOTE

焦循正義：物生同類者，謂人與人同類，物與物同類。物之中則犬與犬同類，牛與牛同類。人與物不同類，則人與物之性不同。趙氏（岐）蓋探孟子之旨而言之，非告子意也。

*◎ 孟子曰：「生之謂性也，猶白之謂白與？」曰：「然。」「白羽之白也，猶白雪之白；白雪之白，猶白玉之白歟？」曰：「然。」*

趙岐註：猶見白物皆謂之同白，無異性也。孟子以爲羽性輕，雪性消，玉性堅，雖俱白，其性不同。問告子，子以三白之性同邪？告子曰然，誠以爲同也。

朱熹《孟子集註》：白之謂白，猶言凡物之白者，同謂之白，更無差別也。白羽以下，孟子再問而告子曰然，則是謂凡有生者同是一性矣。

焦循正義：孟子先詰之，得其瑕而後辨。

*◎ 「然則犬之性，猶牛之性；牛之性，猶人之性與？」*

孫奭疏：孟子所以言此者，以其犬之性，金畜也，故其性守；牛之性，土畜也，故其性順；夫人受天地之中，萬物俱備於我者也，是其稟陰與陽之氣所生也，故其性能柔能剛：是爲不同者。

朱熹《孟子集註》：

#+begin_verse
孟子又言若果如此，則犬牛與人皆有知覺，皆能運動，其性皆無以異矣，於是告子自知其說之非而不能對也。

愚按：性者，人之所得於天之理也；生者，人之所得於天之氣也。性，形而上者也；氣，形而下者也。人物之生，莫不有是性，亦莫不有是氣。然以氣言之，則知覺運動，人與物若不異也；以理言之，則仁義禮智之稟豈物之所得而全哉？此人之性所以無不善，而為萬物之靈也。告子不知性之為理，而以所謂氣者當之，是以杞柳湍水之喻，食色無善無不善之說，縱橫繆戾，紛紜舛錯，而此章之誤乃其本根。所以然者，蓋徒知知覺運動之蠢然者，人與物同；而不知仁義禮智之粹然者，人與物異也。孟子以是折之，其義精矣。
#+end_verse

程瑤田《通藝錄·論學小記》：有天地然後有天地之性，有人然後有人之性，有物然後有物之性。有天地人物，則必有其質，有其形，有其氣矣。有質有形有氣，斯有是性，是性從其質其形其氣而有者也。是故天地位矣，則必有元亨利貞之德，是天地之性善也。人生矣，則必有仁義禮智之德，是人之性善也。使以性為超乎質形氣之上，則未有天地之先，先有此性，是性生天地，天地又具此性，以生人物。如是則不但人之性善，即物之性安得不善。惟指其質形氣而言，故物之性斷乎不能如人性之善。然則人之所以異於物者，異於其質形氣而已矣。

正義：三章言物雖有性，性各殊異，惟人之性，與善俱生。赤子入井，以發其誠。告子一之，知其麤矣，孟子精之，是在其中。

#+BEGIN_QUOTE
《禮記·樂記》：人生而靜，天之性也。感於物而動，性之欲也。物至知知，然後好惡形焉。 /_知知者，人能知而又知，禽獸知聲不能知音，一知不能又知。_/
#+END_QUOTE

** 第四章

*◎ 告子曰：「食色，性也。仁，內也，非外也；義，外也，非內也。」*

趙岐註：人之甘食、悅色者，人之性也。仁由內出，義在外也，不從己身出也。

朱熹《孟子集註》：告子以人之知覺運動者為性，故言人之甘食悅色者即其性。故仁愛之心生於內，而事物之宜由乎外。學者但當用力於仁，而不必求合於義也。

焦循正義：飲食男女，人之大欲存焉。欲在是，性即在是。仁由內出，義在外也，不從己身出也。義外非內，是人性中本無義矣。性本無義，將人物之性同。告子始以仁義同比桮棬，則仁亦在性外，此分仁義言之。《管子·戒篇》云：「仁從中出，義從外作。」朱長春云：「仁內義外昉於此。」告子亦有本之言。

*◎ 孟子曰：「何以謂仁內義外也？」曰：「彼長而我長之，非有長於我也；猶彼白而我白之，從其白於外也，故謂之外也。」*

趙岐註：告子言見彼人年老長大，故我長敬之。長大者，非在我者也，猶白色見於外者也。

朱熹《孟子集註》：我長之，我以彼為長也；我白之，我以彼為白也。

*◎ 曰：「異。於白馬之白也，無以異於白人之白也。不識長馬之長也，無以異於長人之長歟？且謂長者義乎？長之者義乎？」*

趙岐註：孟子曰長異於白，白馬白人，同謂之白可也，不知敬老馬無異於敬老人邪。且謂老者爲有義乎？將謂敬老者爲有義乎？且敬老者，己也，何以爲外也。

孫奭疏：蓋白馬之白與白人之白者，彼白而我白之耳，我何容心於其間哉，固無異也；長馬之長與長人之長，則有欽不欽之心矣，此所以有異焉。以其長人之長者有欽，長馬之長者無欽，是則長者在彼，長之者在我，而義自長之者生，非自長者生也。

朱熹《孟子集註》：張氏曰：「上異於二字疑衍。」李氏曰：「或有闕文焉。」愚按：白馬白人，所謂彼白而我白之也；長馬長人，所謂彼長而我長之也。白馬白人不異，而長馬長人不同，是乃所謂義也。義不在彼之長，而在我長之之心，則義之非外明矣。

焦循正義：言長人之長，必用我心長之，分明權在長之者而不在長者。長之既在我心，則權度悉由中出，安得以義為外乎？長之權全在我，安得云非有長於我也？

*◎ 曰：「吾弟則愛之，秦人之弟則不愛也，是以我為悅者也，故謂之內。長楚人之長，亦長吾之長，是以長為悅者也，故謂之外也。」*

趙岐註：告子曰愛從己則己心悅，故謂之內。所悅喜老者在外，故曰外也。

孫奭疏：謂我之弟則親愛之，秦人之弟則我不愛，是愛以我爲悅者也，愛主仁，故謂仁爲內也；敬長楚人之長者，亦敬長吾之長者，是以長爲悅者也，長主義，故謂義爲外也。

朱熹《孟子集註》：言愛主於我，故仁在內；敬主於長，故義在外。

焦循正義：弟同而愛與不愛異，是愛之權在我；長同則長之無不同，是長之權在彼。

*◎ 曰：「耆秦人之炙，無以異於耆吾炙，夫物則亦有然者也。然則耆炙亦有外歟？」*

趙岐註：孟子曰耆炙同等，情出於中。敬楚人之老，與敬己之老，亦同己情性敬之。雖非己炙，同美，故曰物則有然者也。如耆炙之意，豈在外邪。言楚、秦，喻遠也。

孫奭疏：吾之長者吾長之，楚人之長吾亦長之，長之亦皆自我者也，告子謂之以長爲悅，則非矣。是亦猶秦人之炙與吾之炙雖不同，而嗜之者，皆自我也。如是，則義果非生於外者也。云炙者，《周書》曰：「黃帝始燔肉爲炙」是也。

焦循正義：耆，猶愛也。《音義》云：「耆，本亦作嗜。」知吾所以嗜之者由心辨其美，則知吾所以長之者由心識其長。若謂義之同長為外，則食之同美亦可謂之外乎。告子既知甘食為性，故孟子以嗜炙明之。孟子、告子居齊，故以秦楚為遠。

朱熹《孟子集註》：

#+begin_verse
言長之耆之，皆出於心也。

林氏曰：「告子以食色為性，故因其所明者而通之。」

自篇首至此四章，告子之辯屢屈，而屢變其說以求勝，卒不聞其能自反而有所疑也。此正其所謂不得於言勿求於心者，所以卒於鹵莽而不得其正也。
#+end_verse

正義：四章言事雖在外，行其事者，皆發於中。明仁義由內，所以曉告子之惑也。

** 第五章

*◎ 孟季子問公都子曰：「何以謂義內也？」*

朱熹《孟子集註》：孟季子，疑孟仲子之弟也。蓋聞孟子之言而未達，故私論之。

趙佑《溫故錄》：孟仲子為孟子從昆弟而學於孟子，則孟季子當亦其倫，何至執告子之言，重相駁難，全背孟子。殆別一人，故注無文與？

*◎ 曰：「行吾敬，故謂之內也。」*

趙岐註：以敬在心而行之，故言內也。

朱熹《孟子集註》：所敬之人雖在外，然知其當敬而行吾心之敬以敬之，則不在外也。

*◎ 「鄉人長於伯兄一歲，則誰敬？」曰：「敬兄。」「酌則誰先？」曰：「先酌鄉人。」「所敬在此，所長在彼，果在外，非由內也。」*

趙岐註：果，猶竟也。

朱熹《孟子集註》：伯，長也。酌，酌酒也。此皆季子問、公都子答，而季子又言，如此則敬長之心，果不由中出也。

*◎ 公都子不能答，以告孟子。孟子曰：「敬叔父乎？敬弟乎？彼將曰：『敬叔父。』曰：『弟為尸則誰敬？』彼將曰：『敬弟。』子曰：『惡在其敬叔父也？』彼將曰：『在位故也。』子亦曰：『在位故也。』庸敬在兄，斯須之敬在鄉人。」*

趙岐註：孟子使公都子答季子如此，言弟以在尸位，故敬之；鄉人以在賓位，故先酌之耳。常敬在兄，斯須之敬在鄉人也。

朱熹《孟子集註》：尸，祭祀所主以象神，雖子弟為之，然敬之當如祖考也。在位，弟在尸位，鄉人在賓客之位也。庸，常也。斯須，暫時也。言因時制宜，皆由中出也。

焦循正義：庸敬、斯須之敬，因事轉移，隨時通變，吾心確有權衡，此真義內也。

#+BEGIN_QUOTE
董仲舒《春秋繁露》：義者，謂宜在我而後可以稱義，故言義者，合我與宜以為一言，以此操之，義之言我也。故曰有為而得義者，謂之自得，有為而失義者，謂之自失；人好義者，謂之自好，人不好義者，謂之不自好；以此参之，義我也明矣。
#+END_QUOTE

*◎ 季子聞之，曰：「敬叔父則敬，敬弟則敬，果在外，非由內也。」公都子曰：「冬日則飲湯，夏日則飲水，然則飲食亦在外也？」*

趙岐註：湯、水雖異名，其得寒、溫者中心也。雖隨敬之所在，亦中心敬之，猶飲食從人所欲，豈可復謂之外也。

焦循正義：故飲湯飲水，外也，酌其時宜而飲者，中心也。敬叔父敬弟，外也，酌其所在而敬者，中心也。孟子言位，公都子言時，義之變通，時與位而已矣。孟子學孔子之時，而闡發乎通變神化之道，全以隨在轉移為用，所謂「集義」也。而告子造「義外」之說，不隨人為轉移，故以「勿求於氣」「勿求於心」為「不動心」，與孟子之道適相反。「義外」之說破，則通變神化之用明矣。

范祖禹曰：「二章問答，大指略同，皆反覆譬喻以曉當世，使明仁義之在內，則知人之性善，而皆可以為堯舜矣。」

正義：五章言凡人隨形，不本其原，賢者達情，知所以然。季子信之，猶若告子，公都受命，然後乃理。

** 第六章

*◎ 公都子曰：「告子曰：『性無善無不善也。』*

趙岐註：公都子道告子以爲人性在化，無本善不善也。 /_化，變化也。_/

朱熹《孟子集註》：此亦「生之謂性、食色性也」之意，近世蘇氏、胡氏之說蓋如此。

*◎ 或曰：『性可以為善，可以為不善；是故文武興，則民好善；幽厲興，則民好暴。』*

朱熹《孟子集註》：此即湍水之說也。

*◎ 或曰：『有性善，有性不善，是故以堯為君而有象，以瞽瞍為父而有舜，以紂為兄之子且以為君，而有微子啟、王子比干。』*

趙岐註：公都子曰或人者以爲各有性，善惡不可化移，堯爲君，象爲臣，不能使之爲善；瞽瞍爲父，不能化舜爲惡；紂爲君，又與微子、比干有兄弟之親，亦不能使其二子爲不仁：是亦各有性也矣。

#+BEGIN_QUOTE
王允《論衡·本性》：周人世碩以為人性有善有惡，舉人之善性，養而致之，則善長；惡性而致之，則惡長。故世子作《養書》一篇。宓子賤、漆雕開、公孫尼子之徒亦論性情，與世子相出入。孟子作《性善》之篇，以為「人性皆善，及其不善，物亂之也。」謂人生於天地，皆稟善性，長大與物交接者，放縱悖亂，不善日以生矣。若孟子之言，人幼小之時，無有不善也。 /_焦循正義：《漢書·藝文志·世子》二十一篇，名碩，陳人，七十子之弟子。《韓非子》八儒有漆雕氏之儒，世子或其徒與？蓋或人二說，皆原於聖門，而各得其一偏。可以為善，可以為不善，所謂「性相近，習相遠」也。有性善有性不善，所謂「上智與下愚不移」者也。_/
#+END_QUOTE

朱熹《孟子集註》：韓子性有三品之說蓋如此。按此文，則微子、比干皆紂之叔父，而書稱微子為商王元子，疑此或有誤字。

顧炎武《日知錄》：以紂為弟，且以為君，而有微子啟；以紂為兄之子，且以為君，而有王子比干。並言之，則於文有所不便，故舉此以該彼，此古人文章之善。

陸九淵《與周元忠書》：以紂為兄之子，此是公都子引當時人言。《史記》微子是紂庶兄，皆帝乙之子也。比干則但云紂之親戚，太史公亦莫知為誰子也。今據公都所引文義，則是以微子、比干為帝乙之弟，而紂於二人為兄之子也。此是孟子所載，與史記不同處。

*◎ 今曰『性善』，然則彼皆非歟？」*

趙岐註：公都子曰：告子之徒，其論如此，今孟子曰人性盡善，然則彼之所言皆爲非歟？

朱熹《孟子集註》：歟，平聲。

戴震《孟子字義疏證》：

#+begin_verse
問告子言「生之謂性」，言「性無善無不善」，言「食色性也，仁內義外」，朱子以為同於釋氏；其「杞柳」「湍水」之喻，又以為同於荀揚；然則荀揚亦與釋氏同與？曰否。荀揚所謂性者，古今同謂之性，即後儒稱為氣質之性者也，但不當遺理、義而以為惡耳。在孟子時，則公都子引或曰「性可以為善，可以為不善」，或曰「有性善，有性不善」，言不同而所指之性同。荀子見於聖人生而神明者，不可概之人人，其下皆學而後善，順其自然則流於惡，故以惡加之。論似偏，與「有性不善」合。然謂禮義為聖心，是聖人之性獨善，實兼公都子兩引或曰之說。揚子見於長善則為善人，長惡則為惡人，故曰「人之性也善惡混」，又曰「學則正，否則邪」，與荀子論斷似参差而匪異。

韓子言「性之品有上中下三，上焉者善焉而已矣，中焉者可導而上下也，下焉者惡焉而已矣」，此即公都子兩引或曰之說，會通為一。朱子云「氣質之性固有美惡之不同矣，然以其初而言，皆不甚相遠，習於善則善，習於惡則惡，於是始相遠耳」「人之氣質，相近之中又有美惡，一定，而非習之所能移也。」直會通公都子兩引或曰之說解論語矣。程子云「有自幼而善，有自幼而惡，是氣稟有然也。善固性也，然惡亦不可不謂之性也」，此與「有性善，有性不善」合，而於「性可以為善，可以為不善」亦未嘗不兼，特彼仍其性之名，此別之曰氣稟耳。程子又云：「『人生而靜』以上不容說，纔說性時，便已不是性也。」朱子釋之云：「『人生而靜』以上是人物未生時，止可謂之理，未可名為性，所謂在天曰命也。纔說性時便是人生以後，此理已墮在形氣中，不全是性之本體矣。所謂在人曰性也。」據樂記，「人生而靜」與「感於物而動」對言之，謂方其未感，非謂人物未生也。中庸「天命之謂性」，謂氣稟之不齊，各限於生初，非以理為在天在人異其名也。況如其說，是孟子乃追溯人物未生、未可名性之時而曰性善。若就名性之時，已是人生以後，已墮在形氣中，安得斷之曰善？

由是言之，將天下今古惟上聖之性不失其性之本體，自上聖而下．語人之性，皆失其性之本體。人之為人，舍氣稟氣質，將以何者謂之人哉？是孟子言人無有不善者，程子、朱子言人無有不惡，其視理儼如有物，以善歸理，雖顯遵孟子性善之云，究之孟子就人言之者，程、朱乃離人而空論夫理，故謂孟子「論性不論氣不備」。若不視理如有物，而其見於氣質不善，卒難通於孟子之直斷曰善。宋儒立說，似同於孟子而實異，似異於荀子而實同也。孟子不曰「性無有不善」，而曰「人無有不善」。性者，飛潛動植之通名；性善者，論人之性也。如飛潛動植，舉凡品物之性，皆就其氣類別之。人物分於陰陽五行以成性，舍氣類，更無性之名。

程子、朱子見於生知安行者罕睹，謂氣質不得概之曰善，荀揚之見固如是也。特以如此則悖於孟子，故截氣質為一性，言君子不謂之性；截理義為一性，別而歸之天，以附合孟子。其歸之天不歸之聖人者，以理為人與我。是理者，我之本無也，以理為天與我，庶幾湊泊附著，可融為一。是借天為說，聞者不復疑於本無，遂信天與之得為本有耳。彼荀子見學之不可以已，非本無何待於學？而程子、朱子亦見學之不可以已，其本有者，何以又待於學？故謂「為氣質所汙壞」，以便於言本有者之轉而如本無也。於是性之名移而加之理，而氣化生人生物，適以病性。

性譬水之清，因地而汙濁，不過從老、莊、釋氏所謂真宰真空者之受形以後，昏昧於欲，而改變其說。特彼以真宰真空為我，形體為非我，此仍以氣質為我，難言性為非我，則惟歸之天與我而後可謂之我有，亦惟歸之天與我而後可為完全自足之物，斷之為善，惟使之截然別於我，而後雖天與我完全自足，可以咎我之壞之而待學以復之，以水之清喻性，以受汙而濁喻性墮於形氣中污壞，以澄之而清喻學。

水靜則能清，老、莊、釋氏之主於無欲，主於靜寂是也。因改變其說為主敬，為存理，依然釋氏教人認本來面目，教人常惺惺之法。若夫古賢聖之由博學、審問、慎思、明辨、篤行以擴而充之者，豈徒澄清已哉！程子、朱子於老、莊、釋氏既入其室、操其矛矣，然改變其言，以為六經、孔、孟如是，按諸荀子差近之，而非六經、孔、孟也。
#+end_verse

焦循正義：《禮記·樂記》云：「好惡無節於內，知誘於外，不能反躬，天理滅矣。」註云：「理，猶性也。」以性為理，自鄭氏已言之，非起於宋儒也。理之言分也。《大戴記·本命篇》云：「分於道之謂命。」性由於命，即分於道。性之猶理，亦猶其分也。惟其分，故有不同；亦惟其分，故性即指氣質而言。性不妨歸諸理，而理則非真宰真空耳。

*◎ 孟子曰：「乃若其情，則可以為善矣，乃所謂善也。*

趙岐註：若，順也。性與情相爲表裏，性善勝情，情則從之。《孝經》云：「此哀戚之情」，情從性也。能順此情，使之善者，真所謂善也。

朱熹《孟子集註》：乃若，發語辭。情者，性之動也。人之情，本但可以為善而不可以為惡，則性之本善可知矣。

*◎ 若夫為不善，非才之罪也。*

趙岐註：若隨人而強作善者，非善者之善也。若爲不善者，非所受天才之罪，物動之故也。

孫奭疏：若夫人爲不善耳，非天之降才爾殊也，其所以爲不善者，乃自汩喪之耳，故言非禀天才之罪也……蓋人之性，本則善之，而欲爲善者，非性也，以其情然也；情之能爲善者，非情然也，以其才也。

朱熹《孟子集註》：才，猶材質，人之能也。人有是性，則有是才，性既善則才亦善。人之為不善，乃物欲陷溺而然，非其才之罪也。

程瑤田《通藝錄·論學小記》：孟子「性善」之說，以情驗性之指，正孔子「性相近」之義疏矣。情其善之自然而發者也，才其能求本然之善而無不得者也，性善故情善而才亦善也。誠意之功，在毋自欺，而毋自欺之事曰慎獨，意非私意之謂，乃真好真惡之情發於性者。此真好真惡之情，人皆有之，孟子所謂「乃若其情，可以為善」者也。

#+BEGIN_QUOTE
《說文解字·心部》：性，人之陽氣，性善者也。情，人之陰氣，有欲者。
#+END_QUOTE

*◎ 惻隱之心，人皆有之；羞惡之心，人皆有之；恭敬之心，人皆有之；是非之心，人皆有之。惻隱之心，仁也；羞惡之心，義也；恭敬之心，禮也；是非之心，智也。仁義禮智，非由外鑠我也，我固有之也，弗思耳矣。故曰：『求則得之，舍則失之。』或相倍蓰而無算者，不能盡其才者也。*

趙岐註：仁義禮智，人皆有其端，懷之於內，非從外消鑠我也。求存之，則可得而用之。舍縱之，則亡失之矣。人之善惡，或相倍蓰，或至於無筭者，不能相與計多少，言其絕遠也。所以惡乃至是者，不能自盡其才性也。故使有惡人，非天獨與此人惡性。其有下愚不移者，譬如被疾不成之人，所謂童昏也。

朱熹《孟子集註》：恭者，敬之發於外者也；敬者，恭之主於中者也。鑠，以火銷金之名，自外以至內也。算，數也。言四者之心人所固有，但人自不思而求之耳，所以善惡相去之遠，由不思不求而不能擴充以盡其才也。前篇言是四者為仁義禮智之端，而此不言端者，彼欲其擴而充之，此直因用以著其本體，故言有不同耳。

戴震《孟子字義疏證》：人雖有智有愚，大致相近，而智愚之甚遠者蓋鮮。智愚者，遠近差等殊科，而非相反。善惡則相反之名，非遠近之名。

*◎ 詩曰：『天生蒸民，有物有則。民之秉夷，好是懿德。』孔子曰：『為此詩者，其知道乎！故有物必有則，民之秉夷也，故好是懿德。』」*

朱熹《孟子集註》：

#+begin_verse
詩大雅烝民之篇。蒸，詩作烝，眾也。物，事也。則，法也。夷，詩作彝，常也。懿，美也。有物必有法：如有耳目，則有聰明之德；有父子，則有慈孝之心，是民所秉執之常性也，故人之情無不好此懿德者。以此觀之，則人性之善可見，而公都子所問之三說，皆不辯而自明矣。

程子曰：「性即理也，理則堯舜至於塗人一也。才稟於氣，氣有清濁，稟其清者為賢，稟其濁者為愚。學而知之，則氣無清濁，皆可至於善而復性之本，湯武身之是也。孔子所言下愚不移者，則自暴自棄之人也。」又曰：「論性不論氣，不備；論氣不論性，不明，二之則不是。」

張載曰：「形而後有氣質之性，善反之則天地之性存焉。故氣質之性，君子有弗性者焉。」

愚按：程子此說才字，與孟子本文小異。蓋孟子專指其發於性者言之，故以為才無不善；程子兼指其稟於氣者言之，則人之才固有昏明強弱之不同矣，張子所謂氣質之性是也。二說雖殊，各有所當，然以事理考之，程子為密。蓋氣質所稟雖有不善，而不害性之本善；性雖本善，而不可以無省察矯揉之功，學者所當深玩也。
#+end_verse

程瑤田《通藝錄·論學小記》：天分以與人而限之於天者，謂之命。人受天之所命，而成之於己者，謂之性。此限於天而成於己者，及其見於事為，又有無過無不及之分，以為之則。是則也，以德之極地言之，謂之中庸。以聖人本諸人之四德之性，緣於人情而制以與人遵守者言之，謂之威儀之禮。蓋即其限於天成於己者之所以不待學而可知，不待習而可能者也。亦即其限於天成於己者之所學焉而愈知，習焉而愈能者也，是之謂性善。 /_孔子釋詩，增「必」字「也」字「故」字，而性善之以見矣。_/

正義：六章言天之生人，皆有善性，引而趨之，善惡異衢，高下相懸，賢愚舛殊，尋其本者，乃能一諸。

** 第七章

*◎ 孟子曰：「富歲子弟多賴，凶歲子弟多暴，非天之降才爾殊也，其所以陷溺其心者然也。*

趙岐註：子弟，凡人之子弟也。賴，善。暴，惡也。非天降下才性與之異，以飢寒之阨，陷溺其心，使為惡者也。

朱熹《孟子集註》：富歲，豐年也。賴，借也。豐年衣食饒足，故有所顧藉而為善；凶年衣食不足，故有以陷溺其心而為暴。

阮元曰：「富歲子弟多賴」，賴即嬾。按《說文·女部》云：「嬾，懈也。從女，賴聲。一曰䭆也。」貝部云：「賴，赢也。從貝，剌聲。」《禮記·月令》云「不可以贏」，注云：「贏，猶解也。」解卽懈。贏、賴、解同義。然則富歲子弟多賴，謂其粒米狼戾，民多懈怠。《禮記·月令》「不可以贏」，卽是不可以嬾。而子弟多賴，卽是子弟多懈也。賴與暴俱是陷溺其心。若謂豐年多善，凶年多惡，未聞温飽之家皆由禮者矣。 /_焦循正義：阮氏說是也。_/

*◎ 今夫麰麥，播種而耰之，其地同，樹之時又同，浡然而生，至於日至之時，皆熟矣。雖有不同，則地有肥磽，雨露之養，人事之不齊也。*

趙岐註：《詩》云：「貽我來麰」，言人性之同，如此麰麥。其不同者，人事、雨澤有不足，地之有肥、饒耳。

孫奭疏：「貽我來麰」，此蓋《周頌·思文》之篇，言后稷配天之詩也。饒，《說文》云：「饒，石地名也。」

朱熹《孟子集註》：麰，大麥也。耰，覆種也。日至之時，謂當成熟之期也。磽，瘠薄也。

*◎ 故凡同類者，舉相似也，何獨至於人而疑之？聖人與我同類者。*

趙岐註：聖人亦人也，其相覺者，以心知耳。故體類與人同，故舉相似也。

朱熹《孟子集註》：聖人亦人耳，其性之善，無不同也。

*◎ 故龍子曰：『不知足而為屨，我知其不為蕢也。』屨之相似，天下之足同也。*

趙岐註：龍子，古賢人也。雖不知足大小，作履者猶不更作蕢。

朱熹《孟子集註》：蕢，草器也。不知人足之大小而為之屨，雖未必適中，然必似足形，不至成蕢也。

*◎ 口之於味有同耆也，易牙先得我口之所耆者也。如使口之於味也，其性與人殊，若犬、馬之與我不同類也，則天下何耆皆從易牙之於味也？至於味，天下期於易牙，是天下之口相似也。*

趙岐註：人口之所耆者相似，故皆以易牙爲知味，言口之同也。

孫奭疏：《左傳》云：易牙，齊桓公大夫也。淄、澠二水爲食，易牙亦知二水之味。桓公不信，數試始驗。是易牙爲知味者也。

朱熹《孟子集註》：易牙，古之知味者。言易牙所調之味，則天下皆以為美也。

#+BEGIN_QUOTE
《戰國策·魏策》：齊桓公夜半不嗛，易牙乃煎熬燔炙，和調五味而進之，桓公食之而飽，至旦不覺，曰：「後世必有以味亡其國者。 」
#+END_QUOTE

*◎ 惟耳亦然。至於聲，天下期於師曠，是天下之耳相似也。*

趙岐註：耳亦猶口也，天下皆以師曠爲知聲之微妙也。

朱熹《孟子集註》：師曠，能審音者也。言師曠所和之音，則天下皆以為美也。

*◎ 惟目亦然。至於子都，天下莫不知其姣也。不知子都之姣者，無目者也。*

趙岐註：《詩》云：「不見子都，乃見狂且。」儻無目者，乃不知子都好耳，言目之同也。

孫奭疏：「不見子都，乃見狂且」，《詩·國風·山有扶蘇》之篇文也。註云：「都，世之美好者。狂，狂人也。且，辭也。」箋云：「人之好色，不往覩子都，反往覩狂醜之人。」凡此是知子都爲美好者也。

朱熹《孟子集註》：子都，古之美人也。姣，好也。

*◎ 故曰：口之於味也，有同耆焉；耳之於聲也，有同聽焉；目之於色也，有同美焉。至於心，獨無所同然乎？心之所同然者何也？謂理也，義也。聖人先得我心之所同然耳。故理義之悅我心，猶芻豢之悅我口。」*

朱熹《孟子集註》：然，猶可也。草食曰芻，牛羊是也；榖食曰豢，犬豕是也。

程子曰：「在物為理，處物為義，體用之謂也。孟子言人心無不悅理義者，但聖人則先知先覺乎此耳，非有以異於人也。」又曰：「理義之悅我心，猶芻豢之悅我口，此語親切有味。須實體察得理義之悅心，真猶芻豢之悅口，始得。」

孫奭疏：理出於性命，天之所爲也；義出於道德，人之所爲也：而理、義出於人心所同然也。是則天之使我有是之謂命，天命之謂性，是性命本乎天，故爲天之所爲也。天之所爲雖妙，然而未嘗不有理焉，如此，豈非其理有出於性命者乎！人能存其性命而不失之者，是所謂有其道德也，故爲人之所爲者也。人之所爲道德雖妙，然而未嘗不有義存焉，如此，則豈非其義有出於人心者乎！合而言之，則性命道德是爲理義，雖是理義，出於性命道德者耳。

戴震《孟子字義疏證》：

#+begin_verse
當孟子時，天下不知理義之為性，害道之言紛出以亂先王之法，是以孟子起而明之。人物之生，類至殊也。類也者，性之大別也。蓋孟子道性善，非言性於同也。人之性相近，胥善也。明理義之為性，所以正不知理義之為性者也，是故理義性也。由孟子而後，求其說而不得，則舉性之名而曰理也。

主才質而遺理義，荀子、告子是也。荀子以血氣心知之性，必教之理義，逆而變之，故謂「性惡」，而進其勸學修身之說。告子以上焉者無欲而靜，全其無善無不善，是為至矣。下焉者理義以梏之，使不為不善。荀子二理義於性之事能，儒者之未聞道也。告子貴性而外理義，異說之害道者也。凡遠乎《易》、《論語》、《孟子》之書者，性之說大致有三：以耳目百體之欲為說，謂理義而治之者也；以心之有覺為說，謂其神獨先，冲虛自然，理欲皆後也；以理為說，謂有欲有覺，人之私也。三者之於性也，非其所去，貴其所取。彼自貴其神，以為先形而立者，是不見於精氣為物，秀發乎神也。以有形體則有欲，而外形體、一死生、去情欲以安其神，冥是非、絕思慮以苟語自然。不知歸於必然，是為自然之極致，動靜胥得，神自安也。自孟子時，以欲為說，以覺為說，紛如矣。

心得其常，耳目百體得其順，純懿中正，如是謂之理義。故理義非他，心之所同然也。何以同然，心之明之所止，於事情區以別焉，無幾微爽失，則理義以名。專以性屬之理，而謂壞於形氣，是不見於理之所由名也。孟子曰「理義之悅心，真猶芻豢之悅口」，非喻言也。凡人行一事，有當於理義，其心氣必暢然自得，悖於理義，心氣必沮喪自失。以此見心之於理義，一同乎血氣之於嗜欲，皆性使然耳。 /_孟子言「養心莫善於寡欲」，明乎欲不可無也，寡之而已。_/

心之所同然始謂之理，謂之義；則未至於同然，存乎其人之意見，非理也，非義也。凡一人以為然，天下萬世皆曰是不可易也，此之謂同然。舉理以見心能區分，舉義以見心能裁斷。分之，各有其不易之則，名曰理；如斯而宜，名曰義。是故明理者，明其區分也；精義者，精其裁斷也。不明，往往界於疑似而生惑；不精，往往雜於偏私而害道。

失理者，限於質之味，所謂愚也。惟學可以增益其不足而進於智，益之不已，至於其極，如日月有明，容光必照，則聖人矣。此《中庸》「雖愚必明」，《孟子》「擴而充之之謂聖人」。神明之盛也，其於事靡不得理，斯仁義禮智全矣。
#+end_verse

正義：七章言人稟性俱有好憎，耳目口心，所悅者同，或爲君子，或爲小人，猶麰麥不齊，雨露使然也。孟子言是，所以勗而進之。

#+BEGIN_QUOTE
《大學》：好人之所惡，惡人之所好，是謂拂人之性。
#+END_QUOTE

李贄評：文章極有波瀾已妙絕矣，而曰聖人與我同類，聖人先得我心之所同，然置聖人於我下更有力量，與人皆可以爲堯舜處說得更直截矣。

** 第八章

*◎ 孟子曰：「牛山之木嘗美矣，以其郊於大國也，斧斤伐之，可以為美乎？是其日夜之所息，雨露之所潤，非無萌櫱之生焉，牛羊又從而牧之，是以若彼濯濯也。人見其濯濯也，以為未嘗有材焉，此豈山之性也哉？*

朱熹《孟子集註》：牛山，齊之東南山也。邑外謂之郊，言牛山之木，前此固嘗美矣，今為大國之郊，伐之者眾，故失其美耳。息，生長也。日夜之所息，謂氣化流行未嘗間斷，故日夜之閒，凡物皆有所生長也，萌，芽也。櫱，芽之旁出者也。濯濯，光潔之貌。材，材木也。言山木雖伐，猶有萌櫱，而牛羊又從而害之，是以至於光潔而無草木也。

閻若璩《四書釋地》：牛山齊之東南山，是趙氏 /_岐_/ 在複壁中所註，方向少錯，無論。今目驗在臨淄縣南十一里，亦在唐臨淄縣南二十一里，《括地志》所謂「管仲冢連在牛山上」是。

*◎ 雖存乎人者，豈無仁義之心哉？其所以放其良心者，亦猶斧斤之於木也，旦旦而伐之，可以為美乎？其日夜之所息，平旦之氣，其好惡與人相近也者幾希，則其旦晝之所為，有梏亡之矣。梏之反覆，則其夜氣不足以存；夜氣不足以存，則其違禽獸不遠矣。人見其禽獸也，而以為未嘗有才焉者，是豈人之情也哉！*

趙岐註：言雖在人之性，亦猶此山之有草木也，人豈無仁義之心邪？其日夜之思欲息長仁義，平旦之志氣，其好惡，凡人皆有與賢人相近之心。幾，豈也。豈希，言不遠也。旦晝，晝日也。其所為萬事，有梏亂之，使亡失其日夜之所息也。梏之反覆，利害干其心，其夜氣不能復存也。人見惡人禽獸之行，以為未嘗有善才性，此非人之情也。 /_焦循正義：旦晝猶云明日，謂今日夜所息平旦之氣，才能不遠於人，及明日出見紛華，所悅而所息者乃梏亡矣。_/

孫奭疏：梏，手械也。利欲之制善，使不得爲，猶梏之制手也。

朱熹《孟子集註》：良心者，本然之善心，即所謂仁義之心也。平旦之氣，謂未與物接之時，清明之氣也。好惡與人相近，言得人心之所同然也。幾希，不多也。梏，械也。反覆，展轉也。言人之良心雖已放失，然其日夜之間，亦必有所生長。故平旦未與物接，其氣清明之際，良心猶必有發見者。但其發見至微，而旦晝所為之不善，又已隨而梏亡之，如山木既伐，猶有萌櫱，而牛羊又牧之也。晝之所為，既有以害其夜之所息，又不能勝其晝之所為，是以展轉相害。至於夜氣之生，日以寖薄，而不足以存其仁義之良心，則平旦之氣亦不能清，而所好惡遂與人遠矣。 /_焦循正義：息則仁義之心存，梏則利害之見勝，梏之不已，則心但知有利害，不復能思欲息長仁義，是利害之邪，干犯仁義之良，故夜氣不足以存也。_/

#+BEGIN_QUOTE
《易·文言·坤》：積善之家，必有餘慶；積不善之家，必有餘殃。臣弒其君，子弒其父，非一朝一夕之故，其所由來者漸矣，由辯之不早辯也。
#+END_QUOTE

焦循正義：放者，存之反也。《呂氏春秋·順民篇》云「以與吳王爭一旦之死」，高誘註云：「旦，朝也。」旦旦猶云朝朝，亦即日日也。旦旦，言非一日也。日日放其良心，猶日日伐其山木。山木由此不美，人心亦由此不良。良亦美也。仁義不能無端生長，故趙氏以思欲明之。蓋雖放其良心，其始陷溺未深，尚知自悔，雖為不仁而思欲尚轉而及仁，雖為不義而思欲尚轉而及義。此思欲之所轉，即仁義之心所生長。放失之後，其平旦之氣，好惡尚與人相近，則「性善」可知矣。

*◎ 故苟得其養，無物不長；苟失其養，無物不消。*

趙岐註：誠得其養，若雨露於草木，法度於仁義，何有不長也；誠失其養，若斧斤牛羊之消草木，利欲之消仁義，何有不盡也。

朱熹《孟子集註》：山木人心，其理一也。

焦循正義：或謂靜以任其自然，非其義也。

*◎ 孔子曰：『操則存，舍則亡；出入無時，莫知其鄉。』惟心之謂與？」*

趙岐註：鄉猶里，以喻居也。

朱熹《孟子集註》：

#+begin_verse
孔子言心，操之則在此，舍之則失去，其出入無定時，亦無定處如此。孟子引之，以明心之神明不測，得失之易，而保守之難，不可頃刻失其養。學者當無時而不用其力，使神清氣定，常如平旦之時，則此心常存，無適而非仁義也。

程子曰：「心豈有出入，亦以操舍而言耳。操之之道，敬以直內而已。」

愚聞之師曰：「人，理義之心未嘗無，惟持守之即在爾。若於旦晝之間，不至梏亡，則夜氣愈清。夜氣清，則平旦未與物接之時，湛然虛明氣象，自可見矣。」孟子發此夜氣之說，於學者極有利，宜熟玩而深省之也。
#+end_verse

毛奇齡《聖門釋非錄》：「出入無時，莫知其鄉」，直接「惟心之謂」句，分明指心言，蓋存亡即出入也。惟心是一可存可亡、可出可入之物，故操舍惟命，若無出入，則無事操存矣。《大易》「憧憧往來」，往來者，出入也。《大學》心有所，心不在，有所不在，亦出入也。是心原可出入而操舍者，則因其出之入之也。

正義：八章言秉心持正，使邪不干，猶止斧斤，不伐牛山，山則木茂，人則稱仁。

** 第九章

*◎ 孟子曰：「無或乎王之不智也。*

趙岐註：時人有怪王不智而孟子不輔之，故言此也。

朱熹《孟子集註》：或，與惑同，疑怪也。王，疑指齊王。

*◎ 雖有天下易生之物也，一日暴之，十日寒之，未有能生者也。吾見亦罕矣，吾退而寒之者至矣，吾如有萌焉何哉？*

朱熹《孟子集註》：暴，溫之也。我見王之時少，猶一日暴之也，我退則諂諛雜進之日多，是十日寒之也。雖有萌櫱之生，我亦安能如之何哉？

*◎ 今夫弈之為數，小數也。不專心致志，則不得也。*

趙岐註：弈，博也，或曰圍棊。《論語》曰：「不有博弈者乎？」數，技也。雖小技，不專心則不得也。

孫奭疏：《說文》：「弈從升，言速兩手而執之。棋者，所執之子，圍而相殺，故謂之圍棊。」稱弈者，又取其落弈之義也。

焦循正義：數之為技，猶數之為術，即數之為藝。《禮記·少儀》「游於藝」，註云「藝，六藝夜。一曰五禮，二曰六樂，三曰五射，四曰五御，五曰六書，六曰九數。」九數為六藝之一，故數可稱藝。

*◎ 弈秋，通國之善弈者也。使弈秋誨二人弈，其一人專心致志，惟弈秋之為聽。一人雖聽之，一心以為有鴻鵠將至，思援弓繳而射之，雖與之俱學，弗若之矣。為是其智弗若與？曰非然也。」*

趙岐註：有人名秋，通一國皆謂之善弈，曰弈秋。 /_焦循正義：古之以技傳者，每稱之為名，如醫和、卜徒父是也。_/

孫奭疏：傳記有云弈秋，通國之善弈也，有過者止而聽之，則弈敗。笙汩之也。又云疑首，天下之善算也，有鴻鵠過，彎弧擬問以三五，則不知，鴻鵠之亂也。是亦孟子之言與。

朱熹《孟子集註》：

#+begin_verse
程子為講官，言於上曰：「人主一日之閒，接賢士大夫之時多，親宦官宮妾之時少；則可以涵養氣質，而熏陶德性。」時不能用，識者恨之。

范祖禹曰：「人君之心，惟在所養。君子養之以善則智，小人養之以惡則愚。然賢人易疏，小人易親，是以寡不能勝眾，正不能勝邪。自古國家治日常少，而亂日常多，蓋以此也。」
#+end_verse

焦循正義：智，即性之神明夜。弗若者，習相遠也。非然者，非性本相遠也。此章以智明性，與前章以仁義明性互見之。

正義：九章言弈爲小數，不精不能， /_不精即解不致志，不能即解不得_/ 一人善之，十人惡之，若竭其道，何由智哉？《詩》云：「濟濟多士，文王以寧」，此之謂也。

** 第十章

*◎ 孟子曰：「魚，我所欲也。熊掌，亦我所欲也。二者不可得兼，舍魚而取熊掌者也。生，亦我所欲也。義，亦我所欲也。二者不可得兼，舍生而取義者也。*

孫奭疏：魚在水之物，熊蹯在山之物，欲在水，不可兼得於在山者，在山又不可兼得在水者，故二者不可兼得也。

朱熹《孟子集註》：魚與熊掌皆美味，而熊掌尤美也。

*◎ 生亦我所欲，所欲有甚於生者，故不為苟得也；死亦我所惡，所惡有甚於死者，故患有所不辟也。*

朱熹《孟子集註》：釋所以舍生取義之意。得，得生也。欲生惡死者，雖眾人利害之常情；而欲惡有甚於生死者，乃秉彝義理之良心，是以欲生而不為苟得，惡死而有所不避也。

*◎ 如使人之所欲莫甚於生，則凡可以得生者，何不用也？使人之所惡莫甚於死者，則凡可以辟患者，何不為也？*

朱熹《孟子集註》：設使人無秉彝之良心，而但有利害之私情，則凡可以偷生免死者，皆將不顧禮義而為之矣。

焦循正義：欲生惡死，人物所同之性。乃人性則所欲有甚於生，所惡有甚於死，此其性善也，此其良心也。何以見其欲有甚於生，於其不為苟得見之。何以見其惡有甚於死，於其患有所不辟見之。惟其有此良心，乃能如是。使本無良心，則惟欲生而已，惟惡死而已。所欲無有甚於生，則何以不為苟得，所惡無有甚於死，則何以患有所不辟，反復以明人必有此良心。義不在生，亦不在死，當死而死，當生而生，聖人之權也。

*◎ 由是則生而有不用也，由是則可以辟患而有不為也。*

朱熹《孟子集註》：由其必有秉彝之良心，是以其能舍生取義如此。

*◎ 是故所欲有甚於生者，所惡有甚於死者，非獨賢者有是心也，人皆有之，賢者能勿喪耳。*

朱熹《孟子集註》：羞惡之心，人皆有之，但眾人汨於利欲而忘之，惟賢者能存之而不喪耳。

*◎ 一簞食，一豆羹，得之則生，弗得則死。嘑爾而與之，行道之人弗受；蹴爾而與之，乞人不屑也。*

趙岐註：行道之人，凡人以其賤己，故不肯受也。蹴，蹋也。以足踐蹋與之，乞人不潔之，亦由其小，故輕而不受也。

朱熹《孟子集註》：豆，木器也。嘑，咄啐之貌。行道之人，路中凡人也。蹴，踐踏也。乞人，丐乞之人也。不屑，不以為潔也。言雖欲食之急而猶惡無禮，有寧死而不食者。是其羞惡之本心，欲惡有甚於生死者，人皆有之也。

*◎ 萬鍾則不辨禮義而受之。萬鍾於我何加焉？為宮室之美、妻妾之奉、所識窮乏者得我與？*

趙岐註：言一簞食則貴禮，至於萬鐘，則不復辨別有禮義與不。鍾，量器也。萬鐘於己身何加益哉，己身不能獨食萬鍾也。豈不爲廣美宮室、供奉妻妾、施與所知之人窮乏者也。

孫奭疏：晏子曰：「齊舊四量：豆、區、釜、鍾，四升爲豆，四豆爲區，四區爲釜，釜十爲鍾。」

朱熹《孟子集註》：萬鐘於我何加，言於我身無所增益也。所識窮乏者得我，謂所知識之窮乏者感我之惠也。上言人皆有羞惡之心，此言眾人所以喪之。由此三者，蓋理義之心雖曰固有，而物欲之蔽，亦人所易昏也。

焦循正義：萬鐘或以禮或不以禮，以禮則義可受，不以禮則義不可受，此宜辨別者也。不辨，則有非禮而受者矣。

*◎ 鄉為身死而不受，今為宮室之美為之；鄉為身死而不受，今為妻妾之奉為之；鄉為身死而不受，今為所識窮乏者得我而為之，是亦不可以已乎？此之謂失其本心。」*

趙岐註：鄉者不得簞食而食則身死，尚不受也，今爲此三者爲之，是不亦可以止乎！

朱熹《孟子集註》：言三者身外之物，其得失比生死為甚輕。鄉為身死猶不肯受嘑蹴之食，今乃為此三者而受無禮義之萬鍾，是豈不可以止乎？本心，謂羞惡之心。此章言羞惡之心，人所固有。或能決死生於危迫之際，而不免計豐約於宴安之時，是以君子不可頃刻而不省察於斯焉。

正義：十章言舍生取義，義之大者也，簞食、萬鍾，用有輕重，縱彼納此，蓋違其本，凡人皆然，君子則否，所以殊也。

** 第十一章

*◎ 孟子曰：「仁，人心也；義，人路也。*

孫奭疏：仁者是人之心也，是人人皆有之者也；義者是人之路也，是人人皆得而行之者也。

朱熹《孟子集註》：仁者心之德，程子所謂心如榖種，仁則其生之性，是也。然但謂之仁，則人不知其切於己，故反而名之曰人心，則可以見其為此身酬酢萬變之主，而不可須臾失矣。義者行事之宜，謂之人路，則可以見其為出入往來必由之道，而不可須臾舍矣。

*◎ 舍其路而弗由，放其心而不知求，哀哉！*

朱熹《孟子集註》：哀哉二字，最宜詳味，令人惕然有深省處。

*◎ 人有雞犬放，則知求之，有放心而不知求，*

朱熹《孟子集註》：程子曰：「心至重，雞犬至輕。雞犬放則知求之，心放而不知求，豈愛其至輕而忘其至重哉？弗思而已矣。」愚謂上兼言仁義，而此下專論求放心者，能求放心，則不違於仁而義在其中矣。

*◎ 學問之道無他，求其放心而已矣。」*

孫奭疏：以其人之所以學問者，亦以精此仁義也。

朱熹《孟子集註》：學問之事，固非一端，然其道則在於求其放心而已。蓋能如是則志氣清明，義理昭著，而可以上達；不然則昏昧放逸，雖曰從事於學，而終不能有所發明矣。

程子曰：「聖賢千言萬語，只是欲人將已放之心約之，使反復入身來，自能尋向上去，下學而上達也。」

焦循正義：蓋所以放之、失之、舍之、喪之者，由於不能操之，所以不能求之也。何以操之，惟在學問而已。學問，即《中庸》所云「博學之，審問之」，《論語》所謂「博學而篤志，切問而近思」，孔子所云「好古敏求」，孟子所云「誦詩讀書」。聖人教人學以聚之，問以辨之者，無有他意，不過以求其放心而已。

正義：十一章言由路求心，爲得其本，追逐雞狗，務其末也。

** 第十二章

*◎ 孟子曰：「今有無名之指，屈而不信，非疾痛害事也。如有能信之者，則不遠秦楚之路，為指之不若人也。*

趙岐註：無名之指，手之第四指也。無名指者，非手之用指也。雖不疾痛妨害於事，猶欲信之，不遠秦楚，為指不若人故也。

孫奭疏：蓋云秦、楚者，以其秦、楚相去最爲遠者也，故取爲己言，指屈尚不遠秦、楚之路而求信，況心即在於己爲最進者也，尚不能求之耶。

*◎ 指不若人，則知惡之，心不若人，則不知惡，此之謂不知類也。」*

#+BEGIN_QUOTE
荀子曰：「相形不如論心，论心不如择术。」
#+END_QUOTE

趙岐註：心不若人，可惡之大者也，而反惡指，故曰不知其類也。類，事也。

朱熹《孟子集註》：不知類，言其不知輕重之等也。

焦循正義：《禮記·學記》云「九年知類通達」，註云「知類，知事義之比也。」

正義：十二章言舍大惡小，不知其要，憂指忘心，不嚮於道。是以君子惡之也。

** 第十三章

*◎ 孟子曰：「拱把之桐梓，人苟欲生之，皆知所以養之者。至於身，而不知所以養之者，豈愛身不若桐梓哉？弗思甚也。」*

趙岐註：人皆知灌溉而養之，至於養身之道，當以仁義，而不知用，豈於身不若桐梓哉，不思之甚也。

朱熹《孟子集註》：拱，兩手所圍也。把，一手所握也。桐梓，二木名。

正義：十三章言莫知養身而養樹木，失事違務，不得所急，所以誡未達者也。

** 第十四章

*◎ 孟子曰：「人之於身也，兼所愛。兼所愛，則兼所養也。無尺寸之膚不愛焉，則無尺寸之膚不養也。所以考其善不善者，豈有他哉？於己取之而已矣。*

趙岐註：人之所愛則養之，於身也，一尺一寸之膚養相及也。考知其善否，皆在己之所養也。

孫奭疏：尺寸之膚者，則心存乎中，又有居待而言者也，且心爲一身之君，所謂心爲天君者也。荀子云：「心居中虛，以治五官。」此之謂也。言人既愛尺寸之膚，雖心亦在所愛焉；既養尺寸之膚，雖心亦在所養焉。所以愛養心者，亦以仁義之道考其善不善，於己取之而已矣。

朱熹《孟子集註》：人於一身，固當兼養，然欲考其所養之善否者，惟在反之於身，以審其輕重而已矣。

*◎ 體有貴賤，有小大。無以小害大，無以賤害貴。養其小者為小人，養其大者為大人。*

朱熹《孟子集註》：賤而小者，口腹也；貴而大者，心志也。

*◎ 今有場師，舍其梧檟，養其樲棘，則為賤場師焉。*

趙岐註：場以治殼。圃，園也。言此以喻人舍大養小，故曰賤場師。 /_焦循正義：場為納禾稼而築，故云場以治穀。場人稱師，猶工師、醫師、漁師之屬。_/

朱熹《孟子集註》：場師，治場圃者。梧，桐也；檟，梓也，皆美材也。樲棘，小棗，非美材也。

*◎ 養其一指，而失其肩背而不知也，則為狼疾人也。*

趙岐註：謂醫養人疾，治其一指，而不知其肩背之有疾，以至於害之，此爲狼藉亂不知治疾之人也。

朱熹《孟子集註》：狼善顧，疾則不能，故以為失肩背之喻。

焦循正義：尋常養身，即但養一指，不致失其肩背。惟疾病隱於肩背而見於一指，醫但見其指有疾，而不能知疾之在肩背，徒治其指，而轉有傷於肩背。老子云「輕則失本」，王弼註云：「失本，謂喪身也。」狼藉猶紛錯，害而不知，此醫之昏憒暓亂者矣。

*◎ 飲食之人，則人賤之矣，為其養小以失大也。*

朱熹《孟子集註》：飲食之人，專養口腹者也。

*◎ 飲食之人，無有失也，則口腹豈適為尺寸之膚哉？」*

朱熹《孟子集註》：此言若使專養口腹，而能不失其大體，專口腹之養，軀命所關，不但為尺寸之膚而已。但養小之人，無不失其大者，故口腹雖所當養，而終不可以小害大，賤害貴也。

正義：十四章言養其行，治其正，俱用智力，善惡相厲，是以君子居處思義，飲食思禮。

#+BEGIN_QUOTE
《國語·楚語》：子西嘆于朝，藍尹亹曰：「吾聞君子唯獨居思念前世之崇替，與哀殯喪，于是有嘆，其餘則否。君子臨政思義，飲食思禮，同宴思樂，在樂思善，無有嘆焉。今吾子臨政而嘆，何也？」
#+END_QUOTE

** 第十五章

*◎ 公都子問曰：「鈞是人也，或為大人，或為小人，何也？」孟子曰：「從其大體為大人，從其小體為小人。」*

趙岐註：大體，心思禮義。小體，縱恣情慾。

朱熹《孟子集註》：鈞，同也。從，隨也。大體，心也。小體，耳目之類也。

焦循正義：同為平偏之義，鈞為均之通借字，故訓同也。

*◎ 曰：「鈞是人也，或從其大體，或從其小體，何也？」曰：「耳目之官不思，而蔽於物，物交物，則引之而已矣。心之官則思，思則得之，不思則不得也。此天之所與我者，先立乎其大者，則其小者弗能奪也。此為大人而已矣。」*

趙岐註：公都子言人何獨有從小體也。官，精神所在也，謂人有五官六府。物，事也。利慾之事來交引其精神，心官不思善，故失其道而陷爲小人也。

朱熹《孟子集註》：官之為言司也。耳司聽，目司視，各有所職而不能思，是以蔽於外物。既不能思而蔽於外物，則亦一物而已。又以外物交於此物，其引之而去不難矣。心則能思，而以思為職。凡事物之來，心得其職，則得其理，而物不能蔽；失其職，則不得其理，而物來蔽之。此三者，皆天之所以與我者，而心為大。若能有以立之，則事無不思，而耳目之欲不能奪之矣，此所以為大人也。

#+BEGIN_QUOTE
《呂氏春秋·仲春紀·貴生》：聖人深慮天下，莫貴於生。夫耳目鼻口，生之役也。耳雖欲聲，目雖欲色，鼻雖欲芬香，口雖欲滋味，害於生則止。在四官者不欲，利於生者則弗為。由此觀之，耳目鼻口，不得擅行，必有所制。譬之若官職，不得擅為，必有所制。此貴生之術也。 /_以耳目鼻口為四官，心為君，官制於君。_/
#+END_QUOTE

焦循正義：孟子稱耳目為官，亦稱心為官，蓋心雖能統耳目，而各有所司，心不能代耳司聽，代目司視，猶耳目能聽能視而不能思。耳目不能思，須受治於心之思；心不能司聽司視，而非心之思，則視聽不能不蔽於物。《廣雅·釋詁》云：「官，君也。」以其能治耳目之所司，則為君；以其各有所司，則君亦是官。

程瑤田《通藝錄·論學小記》：孟子謂「心之官則思，先立乎其大者」，謂心能主乎耳目，非離乎耳目之官而專致力於思。然則所謂「先立乎其大者」，舍視聽言動，無下手處也。不知循物，寂守其心，此異學之所以岐也。吾學則不然，吾於物之不當為者，而斷乎其不為，此吾志之定於其先，而立乎其大者。而至於耳目交物之時，而果能造不為之意，此之謂「無惡於志」，此之謂「慎獨」。

正義：十五章言天與人性，先立其大，心官思之，邪不乖越，故謂之大人也。

** 第十六章

*◎ 孟子曰：「有天爵者，有人爵者。仁義忠信，樂善不倦，此天爵也；公卿大夫，此人爵也。*

趙岐註：天爵以德，人爵以祿。

朱熹《孟子集註》：天爵者，德義可尊，自然之貴也。

*◎ 古之人修其天爵，而人爵從之。*

朱熹《孟子集註》：修其天爵，以為吾分之所當然者耳。人爵從之，蓋不待求之而自至也。

*◎ 今之人修其天爵，以要人爵；既得人爵，而棄其天爵，則惑之甚者也，終亦必亡而已矣。」*

朱熹《孟子集註》：要，求也。修天爵以要人爵，其心固已惑矣；得人爵而棄天爵，則其惑又甚焉，終必并其所得之人爵而亡之也。

正義：十六章言古人修天爵，自樂之也；今要人爵，以誘待也；得人棄天，道之忌也；惑以招亡，小人事也。

李贄評：若今之人只記得數百篇時文而已，并不知所謂修天爵也，可憐可憐。

** 第十七章

*◎ 孟子曰：「欲貴者，人之同心也。人人有貴於己者，弗思耳。*

趙岐註：人皆有同欲貴之心，人人自有貴者在己身，不思之耳。在己者，謂仁義廣譽也。

朱熹《孟子集註》：貴於己者，謂天爵也。

*◎ 人之所貴者，非良貴也。趙孟之所貴，趙孟能賤之。*

趙岐註：能貴人，能賤人，人之所自有者，他人不能賤之也。

孫奭疏：良貴者，不以爵而貴者，是謂良貴。趙孟者，即晉襄公之臣趙盾者是也，是爲晉卿。然入爲晉卿，出則爲盟主，是謂貴矣，奈何其賢則不及趙襄，其良則不及宣子，則所貴特人爵之貴耳。

朱熹《孟子集註》：人之所貴，謂人以爵位加己而後貴也。良者，本然之善也。趙孟，晉卿也。能以爵祿與人而使之貴，則亦能奪之而使之賤矣。若良貴，則人安得而賤之哉？

焦循正義：富貴則趙孟能貴能賤，此仁義之貴，比校富貴之貴所以為良，非良字有自有之訓也。良貴猶云最貴，非良貴猶云非最貴也。 /_自儒者誤以良為自有之訓，遂造為「致良知」之說。_/

*◎ 詩云：『既醉以酒，既飽以德。』言飽乎仁義也，所以不願人之膏粱之味也。令聞廣譽施於身，所以不願人之文繡也。」*

趙岐註：言飽德者，飽仁義於身，身之貴者也，不願人之膏粱矣。膏梁，細梁如膏者也。

孫奭疏：《禮》云公食大夫，則稻梁爲嘉膳，則膏梁，味之至珍者也。《詩》以一裳爲顯服，則文繡爲服之至美者也。聞，名聲，而人所聞之也。

朱熹《孟子集註》：詩大雅既醉之篇。飽，充足也。願，欲也。膏，肥肉。粱，美榖。令，善也。聞，亦譽也。文繡，衣之美者也。仁義充足而聞譽彰著，皆所謂良貴也。尹焞曰：「言在我者重，則外物輕。」

正義：十七章言所貴在身，人不知求，膏梁文繡，己之所優，趙孟所貴，何能比之，是以君子貧而樂也。

** 第十八章

*◎ 孟子曰：「仁之勝不仁也，猶水勝火。今之為仁者，猶以一杯水，救一車薪之火也。不熄，則謂之水不勝火，此又與於不仁之甚者也。*

趙岐註：為仁者亦若是，則與作不仁之甚者也。

孫奭疏：今之為仁者，不知反本心而為仁，如以一杯杓水而救一車薪之火也。

朱熹《孟子集註》：與，猶助也。仁之能勝不仁，必然之理也。但為之不力，則無以勝不仁，而人遂以為真不能勝，是我之所為有以深助於不仁者也。

*◎ 亦終必亡而已矣。」*

趙岐註：亡猶無也，亦終必亡仁矣。

焦循正義：趙氏 /_岐_/ 讀亡為無，以為終必無仁，蓋既自以為仁不勝不仁，則為仁之心沮，而為不仁之意萌，久而並此杯水之仁而亦喪之，則終於無仁而已矣。然則當不能勝之時，須自知仁之本微，發憤而充之擴之，則不勝進而為勝，何至於亡乎。

正義：十八章言爲仁不至，不反求諸己，謂水勝火，熄而後已。不仁之甚，終爲亡矣。為道不卒，無益於賢也。

#+BEGIN_QUOTE
《荀子·正論》：今宋子不能解人之惡侮，而務說人以勿辱夜，豈不過甚矣哉！金舌弊口，猶將無益也。不知其無益則不知，知其無益也，直以欺人則不仁，不仁不知，辱莫大焉。將以為有益於人，則與無益於人也。
#+END_QUOTE

焦循正義：趙氏以孟子言「與不仁之甚」，猶荀子言「與無益於人」，故用此語以明與字之義。宋子言見侮之不辱，將以為有益於人，不知同於無益於人。此言仁不勝不仁者自以為有仁，不知同於不仁之甚也。趙氏每以註中未詳者於章指補明，若此尤甚奧矣。

** 第十九章

*◎ 孟子曰：「五穀者，種之美者也。苟為不熟，不如荑稗。夫仁亦在乎熟之而已矣。」*

孫奭疏：此章與前章相類，亦若齊宣有愛牛之仁，而功不至於百姓；梁惠有移民之仁，而民不加多於鄰國：是為仁不成之過也。云荑稗者，即禾中之莁草也。

朱熹《孟子集註》：荑稗，草之似榖者，其實亦可食，然不能如五穀之美也。但五穀不熟，則反不如荑稗之熟；猶為仁而不熟，則反不如為他道之有成。是以為仁必貴乎熟，而不可徒恃其種之美，又不可以仁之難熟，而甘為他道之有成也。

尹焞曰：「日新而不已則熟。」

正義：十九章言功毀幾成，人在慎終，五穀不熟，荑稗是勝，是以爲仁必其成也。

** 第二十章

*◎ 孟子曰：「羿之教人射，必志於彀，學者亦必志於彀。*

趙岐註：彀，張也。張弩向的者，用思專時也。學者志道，猶射者之張也。 /_弓弩既張則心用於中的，故志專向於的。謂用思專於張弩之時，非謂用志於張弩也。_/

孫奭疏：孟子言羿為善射者，其教人射，必志在於勢。勢者，張弓也，張弓以其力分之所至處也。

朱熹《孟子集註》：羿，善射者也。志，猶期也。彀，弓滿也。滿而後發，射之法也。學，謂學射。

*◎ 大匠誨人，必以規矩，學者亦必以規矩。」*

趙岐註：大匠，功木之工。規所以為圓也，矩所以為方也。教人必須規矩，學者以仁義為法式，亦猶大匠以規矩者也。

孫奭疏：規所以為圓之度，矩所以為方之度，以其規矩為法度之至者也。

朱熹《孟子集註》：大匠，工師也。規矩，匠之法也。此章言事必有法，然後可成，師舍是則無以教，弟子舍是則無以學。曲藝且然，況聖人之道乎？

正義：二十章言事各有本，道有所隆，彀張规矩，以喻爲仁，學不爲仁，猶是二教，失其法而行之者也。

* 告子下

孫奭疏：此卷趙氏分為下卷者也。

** 第一章

*◎ 任人有問屋廬子曰：「禮與食孰重？」曰：「禮重。」*

#+BEGIN_QUOTE
《禮記》：「故食禮，主人親饋則客祭，主人不親饋則客不祭。故君子苟無禮，雖美不食焉。」
#+END_QUOTE

孫奭疏：任，薛同姓之國，在齊楚之間，在孟子居鄒之段。

朱熹《孟子集註》：任，國名。屋廬子，名連，孟子弟子也。

*◎ 「色與禮孰重？」*

朱熹《孟子集註》：任人復問也。

*◎ 曰：「禮重。」曰：「以禮食則飢而死，不以禮食則得食，必以禮乎？親迎則不得妻，不親迎則得妻，必親迎乎？」 屋廬子不能對，明日之鄒以告孟子。孟子曰：「於！答是也何有？*

#+BEGIN_QUOTE
《通典·禮十八·天子納后》：「夏氏親迎於庭。殷迎於堂。周制，限男女之歲，定婚姻之時，親迎於戶。」媒氏云：「令男三十而娶，女二十而嫁。」婚姻之時，即仲春之月。
#+END_QUOTE

趙岐註：於音鳥，歎辞也。

朱熹《孟子集註》：何有，不難也。

*◎ 不揣其本而齊其末，方寸之木可使高於岑樓。*

趙岐註：孟子言夫物當揣量其本，以齊等其末，知其小大輕重乃可言也。

孫奭疏：山小而高曰岑。曰樓者，蓋重屋曰樓，亦取其重高之意也。

朱熹《孟子集註》：本，謂下。末，謂上。方寸之木至卑，喻食色。岑樓，樓之高銳似山者，至高，喻禮。若不取其下之平，而升寸木於岑樓之上，則寸木反高，岑樓反卑矣。

*◎ 金重於羽者，豈謂一鉤金與一輿羽之謂哉？*

趙岐註：金重於羽，謂多少同而金重耳，一帶鉤之金，豈重一車羽邪？

朱熹《孟子集註》：鉤，帶鉤也。金木重而帶鉤小，故輕，喻禮有輕於食色者；羽本輕而一輿多，故重，喻食色有重於禮者。

*◎ 取食之重者與禮之輕者而比之，奚翅食重？取色之重者與禮之輕者而比之，奚翅色重？*

趙岐註：翅，辭也，若言何其重也。

朱熹《孟子集註》：禮食親迎，禮之輕者也。飢而死以滅其性，不得妻而廢人倫，食色之重者也。奚翅，猶言何但。言其相去懸絕，不但有輕重之差而已。

*◎ 往應之曰：『紾兄之臂而奪之食，則得食，不紾則不得食，則將紾之乎？踰東家牆而摟其處子，則得妻，不摟則不得妻，則將摟之乎？』」*

趙岐註：教屋盧子往應任人如是。

孫奭疏：所謂東家則託此言之矣，如謂鄰家也。

朱熹《孟子集註》：紾，戾也。摟，牽也。處子，處女也。此二者，禮與食色皆其重者，而以之相較，則禮為尤重也。此章言義理事物，其輕重固有大分，然於其中，又各自有輕重之別。聖賢於此，錯綜斟酌，毫髮不差，固不肯枉尺而直尋，亦未嘗膠柱而調瑟，所以斷之，一視於理之當然而已矣。

正義：一章言臨事量宜，權其輕重，以禮為先，食色為後，若有偏殊，從其大者。

** 第二章

*◎ 曹交問曰：「人皆可以為堯舜，有諸？」孟子曰：「然。」*

朱熹《孟子集註》：趙氏曰：「曹交，曹君之弟也。」人皆可以為堯舜，疑古語，或孟子所嘗言也。

*◎ 交聞文王十尺，湯九尺，今交九尺四寸以長，食粟而已，如何則可？」*

趙岐註：交聞文王與湯皆長而聖。今交亦長，獨但食粟而已，當如之何？

朱熹《孟子集註》：曹交問也。食粟而已，言無他材能也。

*◎ 曰：「奚有於是？亦為之而已矣。有人於此，力不能勝一匹雛，則為無力人。今曰舉百鈞，則為有力人矣。然則舉烏獲之任，是亦為烏獲而已矣。夫人豈以不勝為患哉？弗為耳。*

趙岐註：仁義之道，亦當為之乃為賢耳。百鈞，三千斤也。

朱熹《孟子集註》：匹，字本作鴄，鴨也，從省作匹。禮記說「匹為鶩」是也。烏獲，古之有力人也，能舉移千鈞。

*◎ 徐行後長者謂之弟，疾行先長者謂之不弟。夫徐行者，豈人所不能哉？所不為也。堯舜之道，孝悌而已矣。*

趙岐註：弟，順也。

陳暘曰：「孝弟者，人之良知良能，自然之性也。堯舜人倫之至，亦率是性而已。豈能加毫末於是哉？」

楊時曰：「堯舜之道大矣，而所以為之，乃在夫行止疾徐之閒，非有甚高難行之事也，百姓蓋日用而不知耳。」

*◎ 子服堯之服，誦堯之言，行堯之行，是堯而已矣；子服桀之服，誦桀之言，行桀之行，是桀而已矣。」*

趙岐註：堯服，衣服不踰禮也。堯言，仁義之言。堯行，孝悌之行。

朱熹《孟子集註》：言為善為惡，皆在我而已。詳曹交之問。淺陋麤率，必其進見之時，禮貌衣冠言動之閒，多不循理，故孟子告之如此兩節云。

*◎ 曰：「交得見於鄒君，可以假館，願留而受業於門。」*

趙岐：交欲學於孟子，願因鄒君假館舍，備門徒也。

朱熹《孟子集註》：假館而後受業，又可見其求道之不篤。

*◎ 曰：「夫道，若大路然，豈難知哉？人病不求耳。子歸而求之，有餘師。」*

朱熹《孟子集註》：言道不難知，若歸而求之事親敬長之閒，則性分之內，萬理皆備，隨處發見，無不可師，不必留此而受業也。曹交事長之禮既不至，求道之心又不篤，故孟子教之以孝弟，而不容其受業。蓋孔子餘力學文之意，亦不屑之教誨也。

正義：二章言天下大道，人竝由之，病於不為，不患不能，是以曹交請學，孟子辭焉。

** 第三章

*◎ 公孫丑問曰：「高子曰：『小弁，小人之詩也。』」孟子曰：「何以言之？」曰：「怨。」*

趙岐註：怨者，怨親之過，故謂之小人。

朱熹《孟子集註》：高子，齊人也。小弁，小雅篇名。周幽王娶申后，生太子宜臼；又得褒姒，生伯服，而黜申后、廢宜臼。於是宜臼之傅為作此詩，以敘其哀痛迫切之情也。

孫奭疏：後立為平王者，是宜臼者也。伯奇，宜臼也。

*◎ 曰：「固哉，高叟之為詩也！有人於此，越人關弓而射之，則己談笑而道之，無他，疏之也。其兄關弓而射之，則己垂涕泣而道之，無他，戚之也。小弁之怨，親親也。親親，仁也。固矣夫，高叟之為詩也！」*

趙岐註：孟子曰：陋哉！高父之為詩也。疏越人，故談笑。戚，親也，親其兄，故號泣而道之，怪怨之意也。

孫奭疏：高子老，孟子稱曰叟，蓋叟，長老之稱也。今且託以有人於此，是為越南蠻人，被人彎弓而射之，則己見之，則但談笑而道之也，此無他，是與越人疏也。其兄如被人彎弓而射之，則己見之必垂涕淚，號泣而道之，此無他，是與兄為親也。《小弁》之詩，其辭有怨，是親親之故也。

朱熹《孟子集註》：固，謂執滯不通也。為，猶治也。越，蠻夷國名。道，語也。親親之心，仁之發也。

*◎ 曰：「凱風何以不怨？」*

朱熹《孟子集註》：凱風，邶風篇名。衛有七子之母，不能安其室，七子作此以自責也。

*◎ 曰：「凱風，親之過小者也。小弁，親之過大者也。親之過大而不怨，是愈疏也。親之過小而怨，是不可磯也。愈疏，不孝也。不可磯，亦不孝也。*

趙岐註：《凱風》言「莫慰母心」，母心不悅也，知親之過小也。《小弁》曰「行有死人，尚或墐之」，而曾不閔己，知親之過大也。愈，益也。過已大矣，而孝子不怨思其親之意何為如是！是益疏之道也，故曰不孝。磯，激也。過小耳，而孝子感激，輙怨其親，是亦不孝也。

孫奭疏：云磯者，蓋磯，激也，若微切以感激之，以幾諫者也，譬如石之激水，順其流而激之耳。今乃謂親之不可幾諫，安得孝子乎？

*◎ 孔子曰：『舜其至孝矣，五十而慕。』」*

趙岐註：孔子以舜年五十而思慕其親不怠，稱曰孝之至矣，孝之不可以已也，知高叟譏《小弁》為不得矣。

朱熹《孟子集註》：言舜猶怨慕，小弁之怨，不為不孝也。趙氏曰：「生之膝下，一體而分。喘息呼吸，氣通於親。當親而疏，怨慕號天。是以小弁之怨，未足為愆也。」

正義：三章言生之膝下，一體而分，喘息呼吸，氣通於親，當親而疏，怨慕號天，是以小弁之怨，未足以為愆也。

** 第四章

*◎ 宋牼將之楚，孟子遇於石丘，*

孫奭疏：石丘則宋國地也。

朱熹《孟子集註》：宋，姓；牼，名。石丘，地名。

*◎ 曰：「先生將何之？」*

趙岐註：學士年長者，故謂之先生。

*◎ 曰：「吾聞秦楚構兵，我將見楚王說而罷之。楚王不悅，我將見秦王說而罷之，二王我將有所遇焉。」*

趙岐註：牼自謂往說二王，必有所遇，得從其志也。

朱熹《孟子集註》：時宋牼方欲見楚王，恐其不悅，則將見秦王也。遇，合也。按莊子書：「有宋鉼者，禁攻寢兵，救世之戰。上說下教，強聒不舍。」疏云：「齊宣王時人。」以事考之，疑即此人也。

#+BEGIN_QUOTE
荀子曰：「不知壹天下，建國家之權稱，上功用、大儉約而僈等，曾不足以容辨異、懸君臣。然而其持之有故，其言之成理，足以欺惑愚眾，是墨翟、宋銒也。」楊倞云：「宋銒，宋人，與孟子、尹文子、彭蒙、慎到同時。」
#+END_QUOTE

*◎ 曰：「軻也請無問其詳，願聞其指，說之將何如？」曰：「我將言其不利也。」曰：「先生之志則大矣，先生之號則不可。*

趙岐註：孟子敬宋牼，自稱其名曰軻。

朱熹《孟子集註》：徐氏曰：「能於戰國擾攘之中，而以罷兵息民為說，其志可謂大矣；然以利為名，則不可也。」

*◎ 先生以利說秦楚之王，秦楚之王悅於利，以罷三軍之師，是三軍之士樂罷而悅於利也。為人臣者懷利以事其君，為人子者懷利以事其父，為人弟者懷利以事其兄。是君臣、父子、兄弟終去仁義，懷利以相接，然而不亡者，未之有也。*

孫奭疏：萬二千五百人為軍，三軍之眾乃三萬七千五百人也。

李贄評：去仁義處加一終字有味，蓋仁義我所固有不可合之去者也，即去望其復來者也，曰終去則絕望矣，何等斟酌。

*先生以仁義說秦楚之王，秦楚之王悅於仁義，而罷三軍之師，是三軍之士樂罷而悅於仁義也。為人臣者懷仁義以事其君，為人子者懷仁義以事其父，為人弟者懷仁義以事其兄，是君臣、父子、兄弟去利，懷仁義以相接也。然而不王者，未之有也。何必曰利？」*

朱熹《孟子集註》：此章言休兵息民，為事則一，然其心有義利之殊，而其效有興亡之異，學者所當深察而明辨之也。

正義：四章言上之所欲，下以為俗，俗化於善，久而致平，俗化於惡，久而致傾。是以君子創業，慎其所以為名也。

** 第五章

*◎ 孟子居鄒，季任為任處守，以幣交，受之而不報。處於平陸，儲子為相，以幣交，受之而不報。*

趙岐註：季任，任君季弟也。任君朝會於鄰國，季任為之居守其國。平陸，齊下邑也。儲子，齊相也。

朱熹《孟子集註》：不報者，來見則當報之，但以幣交，則不必報也。

*◎ 他日，由鄒之任，見季子；由平陸之齊，不見儲子。屋廬子喜曰：「連得間矣。」*

趙岐註：連，屋盧子名也。

朱熹《孟子集註》：屋廬子知孟子之處此必有義理，故喜得其間隙而問之。

*◎ 問曰：「夫子之任見季子，之齊不見儲子，為其為相與？」*

朱熹《孟子集註》：言儲子但為齊相，不若季子攝守君位，故輕之邪？

*◎ 曰：「非也。書曰：『享多儀，儀不及物，曰不享。惟不役志于享。』為其不成享也。」*

#+BEGIN_QUOTE
孔安國《尚書正義》：「奉上謂之享。言奉上之道多威儀，威儀不及於禮物，惟曰不奉上。言人君惟不役志於奉上，則凡人化之，惟曰不奉上。」
#+END_QUOTE

趙岐註：享多儀，言享見之禮多儀法也。物，事也。儀不及事，謂有闕也，故曰不成享禮。儲子本禮不足，故我不見也。

朱熹《孟子集註》：書周書洛誥之篇。享，奉上也。儀，禮也。物，幣也。役，用也。言雖享而禮意不及其幣，則是不享矣，以其不用志於享故也。

*◎ 屋廬子悅。或問之，屋廬子曰：「季子不得之鄒，儲子得之平陸。」*

朱熹《孟子集註》：徐氏曰：「季子為君居守，不得往他國以見孟子，則以幣交而禮意已備。儲子為齊相，可以至齊之境內而不來見，則雖以幣交，而禮意不及其物也。」

正義：五章言君子交接，動不違禮，享見之儀，亢荅不差，是以孟子或見或否，各以其宜也。

** 第六章

*◎ 淳于髡曰：「先名實者，為人也。後名實者，自為也。夫子在三卿之中，名實未加於上下而去之，仁者固如此乎？」*

趙岐註：名者，有道德之名。實者，治國惠民之功實也。齊，大國，有三卿，謂孟子嘗處此三卿之中矣。

孫奭疏：言名生於實者也，有功利之實，斯有功利之名，進而治國濟民，則功利在所先，故先名實者為人；退而獨善其身，則功利在所後，故後名實者為自為。

朱熹《孟子集註》：名，聲譽也。實，事功也。言以名實為先而為之者，是有志於救民也；以名實為後而不為者，是欲獨善其身者也。名實未加於上下，言上未能正其君，下未能濟其民也。

*◎ 孟子曰：「居下位，不以賢事不肖者，伯夷也。五就湯，五就桀者，伊尹也。不惡汙君，不辭小官者，柳下惠也。三子者不同道，其趨一也。」*

楊時曰：「伊尹之就湯，以三聘之勤也。其就桀也，湯進之也。湯豈有伐桀之意哉？其進伊尹以事之也，欲其悔過遷善而已。伊尹既就湯，則以湯之心為心矣；及其終也，人歸之，天命之，不得已而伐之耳。若湯初求伊尹，即有伐桀之心，而伊尹遂相之以伐桀，是以取天下為心也。以取天下為心，豈聖人之心哉？」

*「一者何也？」曰：「仁也。君子亦仁而已矣，何必同？」*

孫奭疏：伯夷之仁，則見於必退以為清；伊尹之仁，則見於必進而為仁；下惠之仁，則見於不必進、亦不必退而為和。孟子所以引此三子而喻者，蓋謂之去齊，是亦伯夷之清者也，是亦有仁而已，故以是答淳于髡。

朱熹《孟子集註》：仁者，無私心而合天理之謂。

*◎ 曰：「魯繆公之時，公儀子為政，子柳、子思為臣，魯之削也滋甚。若是乎賢者之無益於國也。」*

朱熹《孟子集註》：公儀子，名休，為魯相。子柳，泄柳也。削，地見侵奪也。髡譏孟子雖不去，亦未必能有為也。

*◎ 曰：「虞不用百里奚而亡，秦穆公用之而霸。不用賢則亡，削何可得與？」*

趙岐註：百里奚所去國亡，所在國霸，無賢國亡，何但得削？

*◎ 曰：「昔者王豹處於淇，而河西善謳。緜駒處於高唐，而齊右善歌。華周、杞梁之妻善哭其夫，而變國俗。有諸內必形諸外。為其事而無其功者，髡未嘗覩之也。是故無賢者也，有則髡必識之。」*

趙岐註：衛地濱於淇水，在北流河之西，故曰處淇水而河西善謳，所謂鄭衛之聲也。髡曰：如是歌、哭者尚能變俗，有中則見外。為之而無功者，髡不聞也。有功，乃為賢者，不見其功，故謂之無賢者也。

朱熹《孟子集註》：王豹，衛人，善謳。淇，水名。緜駒，齊人，善歌。高唐，齊西邑。華周、杞梁，二人皆齊臣，戰死於莒。其妻哭之哀，國俗化之皆善哭。髡以此譏孟子仕齊無功，未足為賢也。

*◎ 曰：「孔子為魯司寇，不用，從而祭，燔肉不至，不稅冕而行。不知者以為為肉也，其知者以為為無禮也，乃孔子則欲以微罪行，不欲為苟去。君子之所為，眾人固不識也。」*

孫奭疏：微罪，以其孔子為司寇大夫之官，凡有祭，則大夫之當從君祭，既從祭之，禮有不備，所以有罪也。

朱熹《孟子集註》：

#+begin_verse
按《史記》：「孔子為魯司寇，攝行相事。齊人聞而懼，於是以女樂遺魯君。季桓子與魯君往觀之，怠於政事。子路曰：『夫子可以行矣。』孔子曰：『魯今且郊，如致膰于大夫，則吾猶可以止。』桓子卒受齊女樂，郊又不致膰俎于大夫，孔子遂行。」

孟子言以為為肉者，固不足道；以為為無禮，則亦未為深知孔子者。蓋聖人於父母之國，不欲顯其君相之失，又不欲為無故而苟去，故不以女樂去，而以膰肉行。其見幾明決，而用意忠厚，固非眾人所能識也。然則孟子之所為，豈髡之所能識哉？
#+end_verse

正義：六章言見幾而作，不俟終日，孔子將行，冕不及稅。庸人不識，課以功實。

李贄評：竟是相罵一場。

** 第七章

*◎ 孟子曰：「五霸者，三王之罪人也。今之諸侯，五霸之罪人也。今之大夫，今之諸侯之罪人也。*

趙岐註：五霸者，大國秉直道以率諸侯。

朱熹《孟子集註》：趙氏曰：「五霸：齊桓、晉文、秦穆、宋襄、楚莊也。三王，夏禹、商湯、周文、武也。」丁氏曰：「夏昆吾，商大彭、豕韋，周齊桓、晉文，謂之五霸。」

*◎ 天子適諸侯曰巡狩，諸侯朝於天子曰述職。春省耕而補不足，秋省斂而助不給。入其疆，土地辟，田野治，養老尊賢，俊傑在位，則有慶，慶以地。入其疆，土地荒蕪，遺老失賢，掊克在位，則有讓。一不朝則貶其爵，再不朝則削其地，三不朝則六師移之。是故天子討而不伐，諸侯伐而不討。五霸者，摟諸侯以伐諸侯者也。故曰：五霸者，三王之罪人也。*

孫奭疏：齊桓率諸侯以伐蔡，晉文率諸侯以滅曹，秦穆率諸侯以伐晉，宋襄率諸侯以伐楚，楚莊率諸侯以伐陳，是摟諸侯以伐諸侯者也。

朱熹《孟子集註》：慶，賞也，益其地以賞之也。掊克，聚斂也。讓，責也。移之者，誅其人而變置之也。討者，出命以討其罪，而使方伯連帥帥諸侯以伐之也。伐者奉天子之命，聲其罪而伐之也。摟，牽也。五霸牽諸侯以伐諸侯，不用天子之命也。自入其疆至則有讓，言巡狩之事；自一不朝至六師移之，言述職之事。

*◎ 五霸桓公為盛，葵丘之會諸侯，束牲載書而不歃血。初命曰：『誅不孝，無易樹子，無以妾為妻。』再命曰：『尊賢育才，以彰有德。』三命曰：『敬老慈幼，無忘賓旅。』四命曰：『士無世官，官事無攝，取士必得，無專殺大夫。』五命曰：『無曲防，無遏糴，無有封而不告。』曰：『凡我同盟之人，既盟之後，言歸于好。』今之諸侯，皆犯此五禁，故曰：今之諸侯，五霸之罪人也。*

朱熹《孟子集註》：

#+begin_verse
按《春秋》傳：「僖公九年，葵丘之會，陳牲而不殺。讀書加於牲上，壹明天子之禁。」

樹，立也。已立世子，不得擅易。初命三事，所以修身正家之要也。賓，賓客也。旅，行旅也。皆當有以待之，不可忽忘也。士世祿而不世官，恐其未必賢也。官事無攝，當廣求賢才以充之，不可以闕人廢事也。取士必得，必得其人也。無專殺大夫，有罪則請命於天子而後殺之也。無曲防，不得曲為隄防，壅泉激水，以專小利，病鄰國也。無遏糴，鄰國凶荒，不得閉糴也。無有封而不告者，不得專封國邑而不告天子也。
#+end_verse

*◎ 長君之惡其罪小，逢君之惡其罪大。今之大夫，皆逢君之惡，故曰：今之大夫，今之諸侯之罪人也。」*

趙岐註：君有惡命，臣長大而宣之，其罪在不能拒逆君命，故曰小也。逢，迎也。君之惡心未發，臣以諂媚逢迎之，而導君為非，故曰罪大。

朱熹《孟子集註》：君有過不能諫，又順之者，長君之惡也。君之過未萌，而先意導之者，逢君之惡也。

林氏曰：「邵子有言：『治春秋者，不先治五霸之功罪，則事無統理，而不得聖人之心。春秋之閒，有功者未有大於五霸，有過者亦未有大於五霸。故五霸者，功之首，罪之魁也。』孟子此章之義，其亦若此也與？然五霸得罪於三王，今之諸侯得罪於五霸，皆出於異世，故得以逃其罪。至於今之大夫，其得罪於今之諸侯，則同時矣；而諸侯非惟莫之罪也，乃反以為良臣而厚禮之。不以為罪而反以為功，何其謬哉！」

正義：七章言王道浸衰，轉為罪人，孟子傷之，是以博思古法，匡時君也。

** 第八章

*◎ 魯欲使慎子為將軍。*

朱熹《孟子集註》：慎子，魯臣。

*◎ 孟子曰：「不教民而用之，謂之殃民。殃民者，不容於堯舜之世。*

趙岐註：不教民以仁義而用之戰關，是使民有殃禍也。

朱熹《孟子集註》：教民者，教之禮義，使知入事父兄，出事長上也。用之，使之戰也。

*◎ 一戰勝齊，遂有南陽，然且不可。」*

趙岐註：山南曰陽，岱山之南，謂之南陽也。

朱熹《孟子集註》：是時魯蓋欲使慎子伐齊，取南陽也。故孟子言就使慎子善戰有功如此，且猶不可。

*◎ 慎子勃然不悅曰：「此則滑釐所不識也。」*

朱熹《孟子集註》：滑釐，慎子名。

*◎ 曰：「吾明告子：天子之地方千里，不千里，不足以待諸侯。諸侯之地方百里，不百里，不足以守宗廟之典籍。*

朱熹《孟子集註》：待諸侯，謂待其朝覲聘問之禮。宗廟典籍，祭祀會同之常制也。

*◎ 周公之封於魯為方百里也，地非不足，而儉於百里。太公之封於齊也，亦為方百里也，地非不足也，而儉於百里。*

朱熹《孟子集註》：二公有大勳勞於天下，而其封國不過百里。儉，止而不過之意也。

*◎ 今魯方百里者五，子以為有王者作，則魯在所損乎，在所益乎？*

朱熹《孟子集註》：魯地之大，皆并吞小國而得之。有王者作，則必在所損矣。

*◎ 徒取諸彼以與此，然且仁者不為，況於殺人以求之乎！*

朱熹《孟子集註》：徒，空也，言不殺人而取之也。

*◎ 君子之事君也，務引其君以當道，志於仁而已。」*

朱熹《孟子集註》：當道，謂事合於理，志仁，謂心在於仁。

正義：八章言招攜懷遠，貴以德禮，既用其兵，義勝為上，戰勝為下。

** 第九章

*◎ 孟子曰：「今之事君者曰：『我能為君辟土地，充府庫。』今之所謂良臣，古之所謂民賊也。君不鄉道，不志於仁，而求富之，是富桀也。*

趙岐註：辟土地，侵小國也。充府庫，重賦斂也。為惡君聚斂以富之，為富桀也，謂若夏桀也。

*◎ 『我能為君約與國，戰必克。』今之所謂良臣，古之所謂民賊也。君不鄉道，不志於仁，而求為之強戰，是輔桀也。*

朱熹《孟子集註》：約，要結也。與國，和好相與之國也。

*◎ 由今之道，無變今之俗，雖與之天下，不能一朝居也。」*

朱熹《孟子集註》：言必爭奪而至於危亡也。

正義：九章言善為國者，必藏於民，賊民以往，其餘何觀，變俗移風，非樂步化，以亂濟民，不知其善也。

** 第十章

*◎ 白圭曰：「吾欲二十而取一，何如？」*

朱熹《孟子集註》：白圭，名丹，周人也。欲更稅法，二十分而取其一分。林氏曰：「按《史記》：白圭能薄飲食，忍嗜欲，與童僕同苦樂。樂觀時變，人棄我取，人取我與，以此居積致富。其為此論，蓋欲以其術施之國家也。」

*◎ 孟子曰：「子之道，貉道也。*

朱熹《孟子集註》：貉，音陌。貉，北方夷狄之國名也。

*◎ 萬室之國，一人陶，則可乎？」曰：「不可，器不足用也。」*

朱熹《孟子集註》：孟子設喻以詰圭，而圭亦知其不可也。

*◎ 曰：「夫貉，五穀不生，惟黍生之。無城郭宮室、宗廟祭祀之禮，無諸侯幣帛饔飧，無百官有司，故二十取一而足也。*

趙岐註：無中國之禮，如此之用，故可二十取一而足也。

孫奭疏：朝食曰饔，夕食曰飧。

朱熹《孟子集註》：北方地寒，不生五穀，黍早熟，故生之。饔飧，以飲食饋客之禮也。

*◎ 今居中國，去人倫，無君子，如之何其可也？*

朱熹《孟子集註》：無君臣、祭祀、交際之禮，是去人倫；無百官有司，是無君子。

*◎ 陶以寡，且不可以為國，況無君子乎？*

朱熹《孟子集註》：因其辭以折之。

*◎ 欲輕之於堯舜之道者，大貉小貉也；欲重之於堯舜之道者，大桀小桀也。」*

朱熹《孟子集註》：什一而稅，堯舜之道也。多則桀，寡則貉。今欲輕重之，則是小貉、小桀而已。

正義：十章言先王典禮，萬世可遵，什一供貢，下富上尊。

#+BEGIN_QUOTE
《周禮·載師》：「凡任地，國宅無征，園廛二十而一，近郊十一，遠郊二十而三，甸、稍、縣、都皆無過十二，唯其漆林之征二十而五。」
#+END_QUOTE

正義：彼謂王幾之內所共多，故賦稅重，諸書所言什一，皆謂幾外之國。故鄭玄曰：「云什一而稅謂之徹。徹，通也。為天下之通法，言天下皆什一耳。」不言幾內亦什一也。

#+BEGIN_QUOTE
《孟子·滕文公上》：「無君子莫治野人，無野人莫養君子。請野九一而助，國中什一使自賦。」
#+END_QUOTE

李贄評：末二語最有關係，若無此二語，又爲富桀者口實矣。聖賢言語可謂滴水不漏，心服心服。

** 第十一章

*◎ 白圭曰：「丹之治水也愈於禹。」*

趙岐註：丹，名；圭，字也。當時諸侯有小水，白圭為治除之，因自謂過乎禹也。

*◎ 孟子曰：「子過矣。禹之治水，水之道也，是故禹以四海為壑。*

朱熹《孟子集註》：順水之性也。壑，受水處也。

*◎ 今吾子以鄰國為壑，水逆行，謂之洚水。洚水者，洪水也。仁人之所惡也，吾子過矣。」*

朱熹《孟子集註》：水逆行者，下流壅塞，故水逆流，今乃壅水以害人，則與洪水之災無異矣。

正義：十一章言君子除害，普為人也，白圭壑鄰，亦以狹矣。

** 第十二章

*◎ 孟子曰：「君子不亮，惡乎執？」*

趙岐註：若為君子之道，捨信將安所執之邪。

朱熹《孟子集註》：亮，信也，與諒同。惡乎執，言凡事苟且，無所執持也。

正義：十二章指言《論語》曰：「自古皆有死，民無信不立」，重信之至者也。

李贄評：亮，明也。

** 第十三章

*◎ 魯欲使樂正子為政。孟子曰：「吾聞之，喜而不寐。」*

趙岐註：樂正，姓也，名克。子，通稱，孟子弟子也，為魯臣。

朱熹《孟子集註》：喜其道之得行。

*◎ 公孫丑曰：「樂正子強乎？」曰：「否。」「有知慮乎？」曰：「否。」「多聞識乎？」曰：「否。」*

朱熹《孟子集註》：此三者，皆當世之所尚，而樂正子之所短，故丑疑而歷問之。

*◎ 「然則奚為喜而不寐？」*

朱熹《孟子集註》：丑問也。

*◎ 曰：「其為人也好善。」*

朱熹《孟子集註》：好，去聲，下同。

*◎ 「好善足乎？」*

朱熹《孟子集註》：丑問也。

*◎ 曰：「好善優於天下，而況魯國乎？*

朱熹《孟子集註》：優，有餘裕也。言雖治天下，尚有餘力也。

*◎ 夫苟好善，則四海之內，皆將輕千里而來告之以善。*

朱熹《孟子集註》：輕，易也，言不以千里為難也。

*◎ 夫苟不好善，則人將曰：『訑訑，予既已知之矣。』訑訑之聲音顏色，距人於千里之外。士止於千里之外，則讒諂面諛之人至矣。與讒諂面諛之人居，國欲治，可得乎？」*

#+BEGIN_QUOTE
《莊子·漁夫》：「希意導言以為諂，不擇是非而言以為諛，好言人之惡以為讒。」
#+END_QUOTE

孫奭疏：夫人苟好善，則四海之內，有善言之士，皆得不遠千里而來告之夜；苟不能好善，則四海之內，人將曰彼人之訑訑自足其智，不好善言，我既已知之，如此則訑訑之人，發聲音，形顏色，以距止人於千里之外。

朱熹《孟子集註》：訑訑，自足其智，不嗜善言之貌。君子小人，迭為消長。直諒多聞之士遠，則讒諂面諛之人至，理勢然也。此章言為政，不在於用一己之長，而貴於有以來天下之善。

正義：十三章言好善從人，聖人一概，禹聞讜言，荅之而拜。訑訑吐之，善人亦逝，善去惡來 ，道若合符。李登《聲類》云：「讜言，善言也。」

** 第十四章

*◎ 陳子曰：「古之君子何如則仕？」孟子曰：「所就三，所去三。*

趙岐註：陳臻問古之君子謂何禮可以仕也。

朱熹《孟子集註》：其目在下。

*◎ 迎之致敬以有禮，言將行其言也，則就之；禮貌未衰，言弗行也，則去之。*

趙岐註：所去就，謂下事也，禮者，接之以禮也。貌者，顏色和順，有樂賢之容。

朱熹《孟子集註》：所謂見行可之仕，若孔子於季桓子是也。受女樂而不朝，則去之矣。

*◎ 其次，雖未行其言也，迎之致敬以有禮，則就之；禮貌衰，則去之。*

趙岐註：禮衰，不敬也；貌衰，不悅也。

朱熹《孟子集註》：所謂際可之仕，若孔子於衛靈公是也。故與公游於囿，公仰視蜚鴈而後去之。

*◎ 其下，朝不食，夕不食，飢餓不能出門戶。君聞之，曰：『吾大者不能行其道，又不能從其言也。使飢餓於我土地，吾恥之。』周之，亦可受也，免死而已矣。」*

趙岐註：其下者，困而不能與之禄，則當去。矜其困而問之，苟免死而已。

朱熹《孟子集註》：所謂公養之仕也。君之於民，固有周之之義，況此又有悔過之言，所以可受。然未至於飢餓不能出門戶，則猶不受也。其曰免死而已，則其所受亦有節矣。

正義：十四章言仕雖正道，亦有量宜，聽言為上，禮貌次之，困而免死，斯為下矣。

** 第十五章

*◎ 孟子曰：「舜發於畎畝之中，傅說舉於版築之閒，膠鬲舉於魚鹽之中，管夷吾舉於士，孫叔敖舉於海，百里奚舉於市。*

趙岐註：舜耕歷山，二十徵庸。傳說築傅岩，武丁舉以為相。膠鬲，殷之賢臣，遭紂之亂，隱遁為商，文王於鬻販魚鹽之中得其人，舉之以為臣也。士，獄官也。管仲自魯囚執於士官，桓公舉以為相國。孫叔敖隱處耕於海濱，楚莊王舉之以為令尹。百里奚亡虞適秦，隱於都市，穆公舉之於市而以為相也。

*◎ 故天將降大任於是人也，必先苦其心志，勞其筋骨，餓其體膚，空乏其身，行拂亂其所為，所以動心忍性，曾益其所不能。*

朱熹《孟子集註》：降大任，使之任大事也，若舜以下是也。空，窮也。乏，絕也。拂，戾也，言使之所為不遂，多背戾也。動心忍性，謂竦動其心，堅忍其性也。然所謂性，亦指氣稟食色而言耳。

程子曰：「若要熟，也須從這裡過。」

*◎ 人恆過，然後能改。困於心，衡於慮，而後作。徵於色，發於聲，而後喻。*

趙岐註：衡，橫也，橫塞其慮於胸中。

孫奭疏：其大憔悴枯槁之容而驗於色，而後有吟詠嘆息之氣而發於聲，則人見其色、聞其聲，而後喻曉其所為矣。

朱熹《孟子集註》：恆，常也。猶言大率也。橫，不順也。作，奮起也。徵，驗也。喻，曉也。此又言中人之性，常必有過，然後能改。蓋不能謹於平日，故必事勢窮蹙，以至困於心，橫於慮，然後能奮發而興起；不能燭於幾微，故必事理暴著，以至驗於人之色，發於人之聲，然後能警悟而通曉也。

*◎ 入則無法家拂士，出則無敵國外患者，國恆亡。*

趙岐註：入，謂國內也。出，謂國外也。

孫奭疏：無大夫循守其職而為之法家，又無輔弼諫諍之士。

朱熹《孟子集註》：此言國亦然也。法家，法度之世臣也。拂士，輔弼之賢士也。

*◎ 然後知生於憂患，而死於安樂也。」*

朱熹《孟子集註》：以上文觀之，則知人之生全，出於憂患，而死亡由於安樂矣。

尹焞曰：「言困窮拂鬱，能堅人之志，而熟人之仁，以安樂失之者多矣。」

正義：十五章言聖賢困窮，天堅其志。次賢感激，乃奮其意。凡人佚樂，以喪知能。

** 第十六章

*◎ 孟子曰：「教亦多術矣，予不屑之教誨也者，是亦教誨之而已矣。」*

孫奭疏：孟子言教人之道，非特一術耳，以其多有也。蓋謂教亦多術者，有君子之五教，或三隅不反，則不復也；或叩兩端而竭；於鄙夫或瀆則不告；或謂子之歸求有餘師；或為挟貴而不荅：是教之多術矣。

朱熹《孟子集註》：多術，言非一端。屑，潔也。不以其人為潔而拒絕之，所謂不屑之教誨也。其人若能感此，退自修省，則是亦我教誨之也。

尹焞曰：「言或抑或揚，或與或不與，各因其材而篤之，無非教也。」

正義：十六章言學而見賤，恥之大者，激而厲之，能者以改，教誨之方，或析或引，同歸殊途，成之而已。

* 盡心上

趙岐註：盡心者，人之有心，為精氣主，思慮可否，然後行之。猶人法天，天之執持網維，以正二十八舍者，北辰也。《論語》曰：「北辰居其所，而眾星拱之。」心者，人之北辰也。苟存其心，養其性，所以事天也，故以「盡心」為篇題。

#+BEGIN_QUOTE
《漢書·天文志》：「斗為帝車，運于中央，臨制四海。分陰陽，建四時，均五行，移節度，定緒紀，皆繫於斗。」
#+END_QUOTE

孫奭疏：前篇章首論告子之言性，此篇章首以論盡心，蓋以情性有主於心，故次之以盡心也。

** 第一章

*◎ 孟子曰：「盡其心者，知其性也。知其性，則知天矣。*

趙岐註：性有仁、義、禮、智之端，心以制之，惟心為正。人能盡極其心，以思行善，則可謂知其性矣。知其性，則知天道之貴善者也。

孫奭疏：以其天之賦性，而性者人所以得於天也，然而心者又生於性，性則湛然自得，而心者又得以主之也。

朱熹《孟子集註》：心者，人之神明，所以具眾理而應萬事者也。性則心之所具之理，而天又理之所從以出者也。人有是心，莫非全體，然不窮理，則有所蔽而無以盡乎此心之量。故能極其心之全體而無不盡者，必其能窮夫理而無不知者也。既知其理，則其所從出。亦不外是矣。以大學之序言之，知性則物格之謂，盡心則知至之謂也。

*◎ 存其心，養其性，所以事天也。*

趙岐註：能存其心，養育其正性，可謂仁人。天道好生，仁人亦好生。天道無親，惟仁是與。行與天合，故曰所以事天也。

朱熹《孟子集註》：存，謂操而不舍；養，謂順而不害。事，則奉承而不違也。

*◎ 殀壽不貳，修身以俟之，所以立命也。」*

趙岐註：貳，二也。仁人之行，一度而已。雖見前人或殀或壽，終無二心改易其道。殀若顔淵，壽若邵公，皆歸之命。脩正其身，以待天命，此所以立命之本。

孫奭疏：以其殀壽皆定於未形有分之初，亦此而不二也，不可徼求之矣。

朱熹《孟子集註》：

#+begin_verse
殀壽，命之短長也。貳，疑也。不貳者，知天之至，修身以俟死，則事天以終身也。立命，謂全其天之所付，不以人為害之。

程子曰：「心也、性也、天也，一理也。自理而言謂之天，自稟受而言謂之性，自存諸人而言謂之心。」

張載曰：「由太虛，有天之名；由氣化，有道之名；合虛與氣，有性之名；合性與知覺，有心之名。」

愚謂盡心知性而知天，所以造其理也；存心養性以事天，所以履其事也。不知其理，固不能履其事；然徒造其理而不履其事，則亦無以有諸己矣。知天而不以殀壽貳其心，智之盡也；事天而能修身以俟死，仁之至也。智有不盡，固不知所以為仁；然智而不仁，則亦將流蕩不法，而不足以為智矣。
#+end_verse

正義：一章言盡心竭性，足以承天，殀壽禍福，秉心不違，立命之道，惟是為珍。

李贄評：首節先說心性天是一箇，不是三箇，下面便教人下手，故有兩『所以』字。事天時，天做主，立命時，我做主矣，存養到此方謂知性，方謂修身。曰修身，見皆實事，不但談玄說妙已也。

#+BEGIN_QUOTE
高攀龍《答葉臺山書》：故嘗妄意以為今日之學，寧守先儒之說，拘拘為尋行數墨，而不敢談玄說妙，自陷于不知之妄作。
#+END_QUOTE

** 第二章

*◎ 孟子曰：「莫非命也，順受其正。*

趙岐註：人之終，無非命也。命有三名，行善得善曰受命，行善得惡曰遭命，行惡得惡曰隨命。惟順受命為受其正也。

朱熹《孟子集註》：人物之生，吉凶禍福，皆天所命。然惟莫之致而至者，乃為正命，故君子修身以俟之，所以順受乎此也。

*◎ 是故知命者，不立乎巖牆之下。*

朱熹《孟子集註》：命，謂正命。巖牆，牆之將覆者。知正命，則不處危地以取覆壓之禍。

*◎ 盡其道而死者，正命也。*

趙岐註：盡修身之道，以壽終者，得正命也。

朱熹《孟子集註》：盡其道，則所值之吉凶，皆莫之致而至者矣。

*◎ 桎梏死者，非正命也。」*

孫奭疏：桎，足械也。梏，手械也。

朱熹《孟子集註》：桎梏，所以拘罪人者。言犯罪而死，與立巖牆之下者同，皆人所取，非天所為也。此章與上章蓋一時之言，所以發其末句未盡之意。

正義：二章言人必趨命，貴受其正，嚴墻之疑，君子遠之。

李贄評：順受二字乃是了生死，真訣可笑，道家言長生也，何不順受至此。

** 第三章

*◎ 孟子曰：「求則得之，舍則失之，是求有益於得也，求在我者也。*

趙岐註：事在於我。

朱熹《孟子集註》：在我者，謂仁義禮智，凡性之所有者。

*◎ 求之有道，得之有命，是求無益於得也，求在外者也。」*

#+BEGIN_QUOTE
荀子曰：「君子能為可貴，不能使人必貴己；能為可信，不能使人必信己；能為可用，不能使人必用己。故君子恥不脩，不恥見污；恥不信，不恥不見信；恥不能，不恥不見用。是以不誘於譽，不恐於誹，率道而行，端然正己，不為物傾側，夫是之謂誠君子。」
#+END_QUOTE

孫奭疏：有生之初性固有者，是為在我者也，是為天爵也。求之有道，則脩其天爵而人爵從之故也。既脩其天爵，而人爵或有不得者，是或得或否，是得之有命也。是則人爵求之無益於得也，是求之在外者也。以其人爵非身所專，故為在外者也。

朱熹《孟子集註》：有道，言不可妄求。有命，則不可必得。在外者，謂富貴利達，凡外物皆是。

正義：三章言為仁由己，富貴在天，故孔子曰：「如不可求，從吾所好。」

** 第四章

*◎ 孟子曰：「萬物皆備於我矣。*

朱熹《孟子集註》：此言理之本然也。大則君臣父子，小則事物細微，其當然之理，無一不具於性分之內也。

*◎ 反身而誠，樂莫大焉。*

趙岐註：反自思其身所施行，能皆實而無虛，則樂莫大焉。

朱熹《孟子集註》：誠，實也。言反諸身，而所備之理，皆如惡惡臭、好好色之實然，則其行之不待勉強而無不利矣，其為樂孰大於是。

*◎ 強恕而行，求仁莫近焉。」*

#+BEGIN_QUOTE
《劉向·說苑》：「夫仁者，必恕然後行，行一不義，殺一無罪，雖得高官大位，仁者不為也。」
#+END_QUOTE

趙岐註：當自強勉以忠恕之道，求仁之術，此最為近也。

朱熹《孟子集註》：強，勉強也。恕，推己以及人也。反身而誠則仁矣，其有未誠，則是猶有私意之隔，而理未純也。故當凡事勉強，推己及人，庶幾心公理得而仁不遠也。此章言萬物之理具於吾身，體之而實，則道在我而樂有餘；行之以恕，則私不容而仁可得。

正義：四章言每必以誠，恕己而行，樂在其中，仁之至也。

李贄評：爲未到家者設渡也，若不急去問渡，有沒于苦海而已，安能樂。張鼐云：上章既說求在我，而求之一字卻說得渾淪，從強恕下手，求在我着落處也。

** 第五章

*◎ 孟子曰：「行之而不著焉，習矣而不察焉，終身由之而不知其道者，眾也。」*

朱熹《孟子集註》：著者，知之明；察者，識之精。言方行之而不能明其所當然，既習矣而猶不識其所以然，所以終身由之而不知其道者多也。

孔思晦云：游魚潛海而不知海，飛鳥泛空而不知空，凡民由道而不知道，都是天性。

正義：五章言人有仁端，達之為道，凡夫用之，不知其為寳也。

** 第六章

*◎ 孟子曰：「人不可以無恥。無恥之恥，無恥矣。」*

#+BEGIN_QUOTE
《禮記》：「君子有五恥：朝不坐，燕不善，君子恥之；居其位，無其言，君子恥之；有其言，無其行，君子恥之；旣得之，又失之，君子恥之；地有餘而民不足，君子恥之。」或有「眾寡均而倍焉，君子恥之。」之言，而「朝不坐，燕不善，君子恥之。」略之。
#+END_QUOTE

趙岐註：人能恥己之無所恥，是能改行從善之人，終身無復有恥辱之累矣。

孫奭疏：人能無恥而尚有羞恥，是爲遷善遠罪之人，終身無復有恥辱累之矣。

正義：六章言恥身無分，獨無所恥，斯必遠辱，不爲憂焉。

李贄評：巧。

** 第七章

*◎ 孟子曰：「恥之於人大矣。*

趙岐註：恥者為不正之道，正人之所恥為也。

朱熹《孟子集註》：恥者，吾所固有羞惡之心也。存之則進於聖賢，失之則入於禽獸，故所繫為甚大。

*◎ 為機變之巧者，無所用恥焉。*

趙岐註：取為一切可勝敵之宜，無以錯於廉恥之心。

朱熹《孟子集註》：為機械變詐之巧者，所為之事皆人所深恥，而彼方且自以為得計，故無所用其愧恥之心也。

*◎ 不恥不若人，何若人有？」*

朱熹《孟子集註》：但無恥一事不如人，則事事不如人矣。或曰：「不恥其不如人，則何能有如人之事。」其義亦通。或問：「人有恥不能之心如何？」程子曰：「恥其不能而為之可也，恥其不能而掩藏之不可也。」

正義：七章言不慕大人，何能有恥。

李贄評：拳以恥提人者，只爲當時無恥者多也，于今日也又何如？

** 第八章

*◎ 孟子曰：「古之賢王好善而忘勢，古之賢士何獨不然？樂其道而忘人之勢。故王公不致敬盡禮，則不得亟見之。見且由不得亟，而況得而臣之乎？」*

趙岐註：亟，數也。

朱熹《孟子集註》：言君當屈己以下賢，士不枉道而求利。二者勢若相反，而實則相成，蓋亦各盡其道而已。

正義：八章言王公尊貴，以貴下賤之義；樂道忘勢，不以富貴動心之分；各崇所尚，則義不虧。

** 第九章

*◎ 孟子謂宋句踐曰：「子好遊乎？吾語子遊。*

趙岐註：好以道德遊，欲行其道者。

孫奭疏：子好逸遊乎？我今語以教子之遊也。

朱熹《孟子集註》：宋，姓。句踐，名。遊，遊說也。

*◎ 人知之亦囂囂，人不知亦囂囂。」*

趙岐註：囂囂，自得無欲之貌。

*◎ 曰：「何如斯可以囂囂矣？」曰：「尊德樂義，則可以囂囂矣。*

趙岐註：問何執守可囂囂也。能貴德而履之，樂義而行之，則可以囂囂無欲矣。

朱熹《孟子集註》：德，謂所得之善。尊之，則有以自重，而不慕乎人爵之榮。義，謂所守之正。樂之，則有以自安，而不殉乎外物之誘矣。

*◎ 故士窮不失義，達不離道。*

朱熹《孟子集註》：言不以貧賤而移，不以富貴而淫，此尊德樂義見於行事之實也。

*◎ 窮不失義，故士得己焉。達不離道，故民不失望焉。*

孫奭疏：德有所於內，義有所不為於外。既所貴在德，而盡性於內；所樂在義，而窮理於外。是以樂天知命，故人知不知，斯囂囂然自得矣。

朱熹《孟子集註》：得己，言不失己也。民不失望，言人素望其興道致治，而今果如所望也。

*◎ 古之人得志，澤加於民；不得志，脩身見於世。窮則獨善其身，達則兼善天下。」*

朱熹《孟子集註》：見，謂名實之顯著也。此又言士得己、民不失望之實。此章言內重而外輕，則無往而不善。

正義：九章言內定常滿，囂囂無憂，可出可處，故云以遊，修身立世，賤不失道，達善天下，乃用其實。

李贄評：既曰獨善其身，又曰修身見于世，固知非自了漢已也。

** 第十章

*◎ 孟子曰：「待文王而後興者，凡民也。若夫豪傑之士，雖無文王猶興。」*

趙岐註：自起以善守其身，正其行，不陷溺也。

朱熹《孟子集註》：興者，感動奮發之意。凡民，庸常之人也。豪傑，有過人之才智者也。蓋降衷秉彝，人所同得，惟上智之資無物欲之蔽，為能無待於教，而自能感發以有為也。

正義：十章言小人待化，乃不辟邪，君子特立，不為俗移。

李贄評：孟子此處激凡民爲豪傑也，非真有分別之見。

** 第十一章

*◎ 孟子曰：「附之以韓、魏之家，如其自視欿然，則過人遠矣。」*

趙岐註：韓、魏，晉六卿之富者也。

朱熹《孟子集註》：附，益也。欿然，不自滿之意。尹焞曰：「言有過人之識，則不以富貴為事。」

正義：十一章言人恃富盛，莫不驕矜，若能欿然，謂不如人，非但免過，卓絕乎凡。

** 第十二章

*◎ 孟子曰：「以佚道使民，雖勞不怨。以生道殺民，雖死不怨殺者。」*

趙岐註：謂教民趨農，役有常時，不使失業，當時雖勞，後獲其利，則佚矣，若「亟其乘屋」之類也，故曰不怨。謂殺大辟之罪者，以坐殺人故也。殺此罪人者，其意欲生民也，故伏罪而死，不怨殺也。

程子曰：「以佚道使民，謂本欲佚之也，播榖乘屋之類是也。以生道殺民，謂本欲生之也，除害去惡之類是也。蓋不得已而為其所當為，則雖咈民之欲而民不怨，其不然者反是。」

正義：十二章言勞人欲以佚之，殺人欲以生之，則民無怨讟也。

李贄評：見當時使民俱非佚道，殺民俱非生道耳，悲哉。

** 第十三章

*◎ 孟子曰：「霸者之民，驩虞如也；王者之民，皞皞如也。*

趙歧注：霸者行善恤民，恩澤暴見易知，故民驩虞樂之也。王者道大法天，浩浩而德難見也。

朱熹《孟子集註》：驩虞，與歡娛同。皞皞，廣大自得之貌。

程子曰：「驩虞，有所造為而然，豈能久也？耕田鑿井，帝力何有於我？如天之自然，乃王者之政。」

楊時曰：「所以致人驩虞，必有違道干譽之事；若王者則如天，亦不令人喜，亦不令人怒。」

*◎ 殺之而不怨，利之而不庸，民日遷善而不知為之者。*

趙岐註：言化遷善為之大道者也。

朱熹《孟子集註》：此所謂皞皞如也。庸，功也。豐稷曰：「因民之所惡而去之，非有心於殺之也，何怨之有？因民之所利而利之，非有心於利之也，何庸之有？輔其性之自然，使自得之，故民日遷善而不知誰之所為也。」

*◎ 夫君子所過者化，所存者神，上下與天地同流，豈曰小補之哉？」*

孫奭疏：蓋虞之為樂，必待虞度無患，然後為驩，則其樂淺；皞皞如也，以其使民舒通太平，自得而已，故於驩虞又有以間矣。驩，歡也。虞，安也。

朱熹《孟子集註》：君子，聖人之通稱也。所過者化，身所經歷之處，即人無不化，如舜之耕歷山而田者遜畔，陶河濱而器不苦窳也。所存者神，心所存主處便神妙不測，如孔子之立斯立、道斯行、綏斯來、動斯和，莫知其所以然而然也。是其德業之盛，乃與天地之化同運並行，舉一世而甄陶之，非如霸者但小小補塞其罅漏而已。此則王道之所以為大，而學者所當盡心也。

正義：十三章言王政浩浩，與天地同道；霸者德小，民人速覩：是以賢者志其大者也。

** 第十四章

*◎ 孟子曰：「仁言，不如仁聲之入人深也。*

趙岐註：仁言，政教法度之言也。仁聲，樂聲雅、頌也。仁言之政雖明，不如雅、頌感人心之深也。

程子曰：「仁言，謂以仁厚之言加於民。仁聲，謂仁聞，謂有仁之實而為眾所稱道者也。此尤見仁德之昭著，故其感人尤深也。」

*◎ 善政，不如善教之得民也。*

趙岐註：善政使民不違上，善教使民尚仁義，心易得也。

朱熹《孟子集註》：政，謂法度禁令，所以制其外也。教，謂道德齊禮，所以格其心也。

*◎ 善政，民畏之。善教，民愛之。善政得民財，善教得民心。」*

趙岐註：畏之，不逋怠，故賦役舉而財聚於一家也。愛之，樂風化而上下親，故歡心可得也。

孫奭疏：善政非不能得民，但得民財而已，又不若善教得民之心矣。

朱熹《孟子集註》：得民財者，百姓足而君無不足也；得民心者，不遺其親，不後其君也。

正義：十四章言明法審令，民趨君命，崇寬務化，民愛君德，故曰移風易俗，莫善於樂。

李贄評：後兩節便是前一節註腳，勿串合，串合反失本來血脈也。

** 第十五章

*◎ 孟子曰：「人之所不學而能者，其良能也。所不慮而知者，其良知也。*

趙岐註：不學而能，性所自能。良，甚也，是人之所能甚也。

朱熹《孟子集註》：良者，本然之善也。程子曰：「良知良能，皆無所由；乃出於天，不繫於人。」

*◎ 孩提之童，無不知愛其親者，及其長也，無不知敬其兄也。*

趙岐註：在襁褓，知孩笑可提抱者也。襁褓，負也。負，兒衣也，緻縷為之，廣八寸，長二尺，以負兒於背上者也。是亦知孩提為二三嵗。

朱熹《孟子集註》：長，上聲，下同。孩提，二三歲之閒，知孩笑、可提抱者也。愛親敬長，所謂良知良能者也。

*◎ 親親，仁也。敬長，義也。無他，達之天下也。」*

趙岐註：人，仁義之心少而皆有之，欲為善者無他。達，通也，但通此親親敬長之心，施之天下人也。

朱熹《孟子集註》：言親親敬長，雖一人之私，然達之天下無不同者，所以為仁義也。

正義：十五章言本性良能，仁義是也，達之天下，恕乎己也。

** 第十六章

*◎ 孟子曰：「舜之居深山之中，與木石居，與鹿豕遊，其所以異於深山之野人者幾希。及其聞一善言，見一善行，若決江河，沛然莫之能禦也。」*

趙岐註：希，遠也。

朱熹《孟子集註》：居深山，謂耕歷山時也。蓋聖人之心，至虛至明，渾然之中，萬理畢具。一有感觸，則其應甚速，而無所不通，非孟子造道之深，不能形容至此也。

正義：十六章言聖人潛隱，辟若神龍，亦能飛天，亦能潛藏，舜之謂也。

** 第十七章

*◎ 孟子曰：「無為其所不為，無欲其所不欲，如此而已矣。」*

趙岐註：無使人為己所不欲為者，無使人欲己所不欲者，每以身先之如此，則人道足也。

朱熹《孟子集註》：李氏曰：「有所不為不欲，人皆有是心也。至於私意一萌，而不能以禮義制之，則為所不為、欲所不欲者多矣。能反是心，則所謂擴充其羞惡之心者，而義不可勝用矣，故曰如此而已矣。」

正義：十七章言己所不欲，勿施於人，仲尼之道也。

** 第十八章

*◎ 孟子曰：「人之有德慧術知者，恆存乎疢疾。*

趙岐註：人所以有德行智慧道術才知者，在於有疢疾之人。疢疾之人、又力學，故能成德。

朱熹《孟子集註》：德慧者，德之慧。術知者，術之知。疢疾，猶災患也。言人必有疢疾，則能動心忍性，增益其所不能也。

孫奭疏：疢疾，人之有小疾，常霑在身不去者，是爲疢疾也。非謂德慧術智必繫有疢疾者，但常存乎疢疾之人而已。蓋有得於己謂之德，述而行之謂之術，然德又以慧連，術又以智連之者，以其德以慧明，術以智釋耳。是則所謂智慮生於憂患，豈非德慧術智存於疢疾之意有同歟？

*◎ 獨孤臣孽子，其操心也危，其慮患也深，故達。」*

趙岐註：此即人之疢疾也，自以孤微，懼於危殆之患而深慮之，勉為仁義，故至於達也。

朱熹《孟子集註》：孤臣，遠臣；孽子，庶子，皆不得於君親，而常有疢疾者也。達，謂達於事理，即所謂德慧術知也。

正義：十八章言孤孽自危，故能顯達，膏粱難正，多用沈溺，是故在上不驕，以戒諸侯也。

** 第十九章

*◎ 孟子曰：「有事君人者，事是君則為容悅者也。*

趙岐註：事君，求君之意，為苟容以悅君者也。

朱熹《孟子集註》：阿殉以為容，逢迎以為悅，此鄙夫之事、妾婦之道也。

*◎ 有安社稷臣者，以安社稷為悅者也。*

朱熹《孟子集註》：言大臣之計安社稷，如小人之務悅其君，眷眷於此而不忘也。

*◎ 有天民者，達可行於天下而後行之者也。*

趙岐註：天民，知道者也。可行而行，可止而止。

朱熹《孟子集註》：民者，無位之稱。以其全盡天理，乃天之民，故謂之天民。必其道可行於天下，然後行之；不然，則寧沒世不見知而不悔，不肯小用其道以殉於人也。

張載曰：「必功覆斯民然後出，如伊呂之徒。」

*◎ 有大人者，正己而物正者也。」*

趙岐註：大人，大丈夫不爲利害動移者也。正己物正，象天不言而萬物化成也。

朱熹《孟子集註》：大人，德盛而上下化之，所謂「見龍在田，天下文明」者。

正義：十九章言容悅凡臣，社稷股肱，天民行道，大人正身。

朱熹《孟子集註》：此章言人品不同，略有四等。容悅佞臣不足言。安社稷則忠矣，然猶一國之士也。天民則非一國之士矣，然猶有意也。無意無必，惟其所在而物無不化，惟聖者能之。

** 第二十章

*◎ 孟子曰：「君子有三樂，而王天下不與存焉。*

朱熹《孟子集註》：樂，音洛。王、與，皆去聲，下並同。

*◎ 父母俱存，兄弟無故，一樂也。*

朱熹《孟子集註》：此人所深願而不可必得者，今既得之，其樂可知。

*◎ 仰不愧於天，俯不怍於人，二樂也。*

程子曰：「人能克己，則仰不愧，俯不怍，心廣體胖，其樂可知，有息則餒矣。」

*◎ 得天下英才而教育之，三樂也。*

朱熹《孟子集註》：盡得一世明睿之才，而以所樂乎己者教而養之，則斯道之傳得之者眾，而天下後世將無不被其澤矣。聖人之心所願欲者，莫大於此，今既得之，其樂為何如哉？

*◎ 君子有三樂，而王天下不與存焉。」*

趙岐註：孟子重言，是美之也。

朱熹《孟子集註》：林氏曰：「此三樂者，一係於天，一係於人。其可以自致者，惟不愧不怍而已，學者可不勉哉？」

正義：二十章言保親之養，兄弟無他，誠不愧天，養育英才，賢人能之，樂過萬乘。

李贄評：此分明名教中樂事，故曰王天下不與存焉，即父母俱存、兄弟無故也。須自家不愧不怍，不然何樂之有，故三項都是名教中樂事。

#+BEGIN_QUOTE
《後漢紀·孝獻皇帝紀》：「夫君臣父子，名教之本也。然則名教之作，何為者也？蓋准天地之性，求之自然之理，擬議以制其名，因循以弘其教，辯物成器，以通天下之務者也。」
#+END_QUOTE

** 第二十一章

*◎ 孟子曰：「廣土眾民，君子欲之，所樂不存焉。*

趙岐註：廣土眾民，大國諸侯也。所樂不存，欲行禮也。

孫奭疏：君子者心欲好之，然其所樂不在此也。

朱熹《孟子集註》：地闢民聚，澤可遠施，故君子欲之，然未足以為樂也。

*◎ 中天下而立，定四海之民，君子樂之，所性不存焉。*

趙岐註：中天下而立，謂王者。所性不存，乃所謂性於仁義者也。

孫奭疏：君子者雖樂於此，然而稟天性不在此焉。

朱熹《孟子集註》：其道大行，無一夫不被其澤，故君子樂之，然其所得於天者則不在是也。

*◎ 君子所性，雖大行不加焉，雖窮居不損焉，分定故也。*

趙岐註：大行，行之於天下。窮居不失性也，分定故不變。

孫奭疏：君子欲廣土眾民，以其足以行道於一國故也，然其所樂又在於定四海之民，而未樂於此一國而已。雖樂在於中天下而立，定四海之民，得以行道於天下，奈何所性不在此焉。是則君子所稟天之性，雖大而行道於天下，且不能加益其性；雖窮居在下，且不能損減其性：以其所生之初，受之於天，有其分定故也。

朱熹《孟子集註》：分者，所得於天之全體，故不以窮達而有異。

*◎ 君子所性，仁義禮智根於心。其生色也，睟然見於面，盎於背，施於四體。四體不言而喻。」*

#+BEGIN_QUOTE
荀子曰：「君子之學入乎耳，著乎心，布乎四體，形乎動靜。」

荀子曰：「君子至德，默然而喻，未施而親，不怒而威。」
#+END_QUOTE

趙岐註：四者根生於心，色見於面。盎視其背而可知，其背盎盎然，盛流於四體。四體有匡國之綱，雖口不言，人自曉喻而知也。

朱熹《孟子集註》：上言所性之分，與所欲所樂不同，此乃言其蘊也。仁義禮智，性之四德也。根，本也。生，發見也。睟然，清和潤澤之貌。盎，豐厚盈溢之意。施於四體，謂見於動作威儀之閒也。喻，曉也。四體不言而喻，言四體不待吾言，而自能曉吾意也。蓋氣稟清明，無物欲之累，則性之四德根本於心，其積之盛，則發而著見於外者，不待言而無不順也。

程子曰：「睟面盎背，皆積盛致然。四體不言而喻，惟有德者能之。」

正義：二十一章言臨莅天下，君國子民，君子之樂，尚不與存。仁義内充，身體履方，四支不言，蟠辟用張，心邪意溺，進退無容，於是之際，知其不同也。

朱熹《孟子集註》：此章言君子固欲其道之大行，然其所得於天者，則不以是而有所加損也。

** 第二十二章

*◎ 孟子曰：「伯夷辟紂，居北海之濱，聞文王作興，曰：『盍歸乎來！吾聞西伯善養老者。』太公辟紂，居東海之濱，聞文王作興，曰：『盍歸乎來！吾聞西伯善養老者。』天下有善養老，則仁人以為己歸矣。*

朱熹《孟子集註》：己歸，謂己之所歸。

*◎ 五畝之宅，樹牆下以桑，匹婦蠶之，則老者足以衣帛矣。五母雞，二母彘，無失其時，老者足以無失肉矣。百畝之田，匹夫耕之，八口之家足以無饑矣。*

趙岐註：五雞、二彘，八口之家畜之，足以為畜產之本也。

朱熹《孟子集註》：此文王之政也。一家養母雞五，母彘二也。

*◎ 所謂西伯善養老者，制其田里，教之樹畜，導其妻子，使養其老。五十非帛不煖，七十非肉不飽。不煖不飽，謂之凍餒。文王之民，無凍餒之老者，此之謂也。」*

趙岐註：所謂無凍餒者，教導之使可以養老者耳，非家賜而人益之也。

朱熹《孟子集註》：田，謂百畝之田。里，謂五畝之宅。樹，謂耕桑。畜，謂雞彘也。

正義：二十二章言王政普大，教其常業，各養其老，使不凍餒。

** 第二十三章

*◎ 孟子曰：「易其田疇，薄其稅斂，民可使富也。*

趙岐註：易，治也。疇，一井也。教民治其田疇，薄其稅斂，不踰什一，則民富矣。

*◎ 食之以時，用之以禮，財不可勝用也。*

趙岐註：食取其征賦以時，用之以常禮，不踰禮以費財也，故畜積有餘，財不可勝用也。

朱熹《孟子集註》：教民節儉，則財用足也。

*◎ 民非水、火不生活，昏暮叩人之門戶求水、火，無弗與者，至足矣。聖人治天下，使有菽粟如水、火。菽粟如水、火，而民焉有不仁者乎？」*

趙岐註：水、火能生，人有不愛者，至饒足故也。菽粟饒多若是，民皆輕施於人，而何有不仁者也。

朱熹《孟子集註》：水火，民之所急，宜其愛之而反不愛者，多故也。尹焞曰：「言禮義生於富足，民無常產，則無常心矣。」

正義：二十三章言教民之道，富而節用，畜積有餘，焉有不仁，故曰倉廪實知禮節也。

** 第二十四章

*◎ 孟子曰：「孔子登東山而小魯，登太山而小天下。故觀於海者難為水，遊於聖人之門者難為言。*

趙岐註：所覽大者意大，觀小者志小也。

朱熹《孟子集註》：此言聖人之道大也。東山，蓋魯城東之高山，而太山則又高矣。此言所處益高，則其視下益小；所見既大，則其小者不足觀也。難為水，難為言，猶仁不可為眾之意。

*◎ 觀水有術，必觀其瀾。日月有明，容光必照焉。*

趙岐註：容光，小郤，言大明照幽微也。

#+BEGIN_QUOTE
《禮記·三年問》釋文：隙本作『卻』。

段玉裁《說文註》：《左傳》曰：『牆之隙壤，誰之咎也。』際，自分而合言之。隙，自合而分言之。引申之凡坼裂皆曰隙，假借以卻爲之。
#+END_QUOTE

焦循正義：舋則隙之小者，惟遮隔其光則已，苟有絲髮之際可以容納，則光必入而照焉。容光非小隙之名，至於小隙，極言其容之微者，以見其照之大也，故以小卻明容光。

朱熹《孟子集註》：此言道之有本也。瀾，水之湍急處也。明者，光之體；光者，明之用也。觀水之瀾，則知其源之有本矣；觀日月於容光之隙無不照，則知其明之有本矣。

*◎ 流水之為物也，不盈科不行。君子之志於道也，不成章不達。」*

趙岐註：盈，滿也。科，坎也。流水滿坎乃行，以喻君子之學必至成章，乃仕進者也。

朱熹《孟子集註》：言學當以漸，乃能至也。成章，所積者厚，而文章外見也。達者，足於此而通於彼也。此章言聖人之道大而有本，學之者必以其漸，乃能至也。

正義：二十四章言宏大明者無不照，包聖道者成其仁。是故賢者志大，宜為君子。

** 第二十五章

*◎ 孟子曰：「雞鳴而起，孳孳為善者，舜之徒也。*

朱熹《孟子集註》：孳孳，勤勉之意。言雖未至於聖人，亦是聖人之徒也。

*◎ 雞鳴而起，孳孳為利者，蹠之徒也。*

朱熹《孟子集註》：蹠，盜跖也。

#+BEGIN_QUOTE
《莊子·雜篇·盜跖》：孔子與柳下季為友，柳下季之弟，名曰盜跖。盜跖從卒九千人，橫行天下，侵暴諸侯，穴室樞戶，驅人牛馬，取人婦女，貪得忘親，不顧父母兄弟，不祭先祖。所過之邑，大國守城，小國入保，萬民苦之。

李奇註《漢書》云：「跖，秦之大盜也。」
#+END_QUOTE

*◎ 欲知舜與蹠之分，無他，利與善之間也。」*

朱熹《孟子集註》：

#+begin_verse
程子曰：「言閒者，謂相去不遠，所爭毫末耳。善與利，公私而已矣。纔出於善，便以利言也。」

楊時曰：「舜蹠之相去遠矣，而其分，乃在利善之閒而已，是豈可以不謹？然講之不熟，見之不明，未有不以利為義者，又學者所當深察也。」

《或問》：「雞鳴而起，若未接物，如何為善？」程子曰：「只主於敬，便是為善。」

程廷光曰：「知字最要緊。」
#+end_verse

正義：二十五章言好善從舜，好利從蹠，明明求之，常若不足，君子小人，各一趣也。

** 第二十六章

*◎ 孟子曰：「楊子取為我，拔一毛而利天下，不為也。*

朱熹《孟子集註》：楊子，名朱。取者，僅足之意。取為我者，僅足於為我而已，不及為人也。列子稱其言曰，「伯成子高不以一毫利物」，是也。

*◎ 墨子兼愛，摩頂放踵利天下，為之。*

趙岐註：摩突其頂至於踵，以利天下，己樂為之也。

朱熹《孟子集註》：墨子，名翟。兼愛，無所不愛也。摩頂，摩突其頂也。放，至也。

*◎ 子莫執中。執中為近之，執中無權，猶執一也。*

趙岐註：執中和，近聖人之道，然不權。聖人之重權。執中而不知權，猶執一介之人，不知時變也。

孫奭疏：子莫執中和之性而不專一者也，以其無爲己、兼愛之過而已。

朱熹《孟子集註》：子莫，魯之賢人也。知楊墨之失中也，故度於二者之閒而執其中。近，近道也。權，稱錘也，所以稱物之輕重而取中也。執中而無權，則膠於一定之中而不知變，是亦執一而已矣。

程子曰：「中字最難識，須是默識心通。且試言一廳，則中央為中；一家，則廳非中而堂為中；一國，則堂非中而國之中為中，推此類可見矣。」又曰：「中不可執也，識得則事事物物皆有自然之中，不待安排，安排著則不中矣。」

*◎ 所惡執一者，為其賊道也，舉一而廢百也。」*

朱熹《孟子集註》：賊，害也。為我害仁，兼愛害義，執中者害於時中，皆舉一而廢百者也。

楊時曰：「禹稷三過其門而不入，苟不當其可，則與墨子無異。顏子在陋巷，不改其樂，苟不當其可，則與楊氏無異。子莫執為我兼愛之中而無權，鄉鄰有鬬而不知閉戶，同室有鬬而不知救之，是亦猶執一耳，故孟子以為賊道。禹、稷、顏回，易地則皆然，以其有權也；不然，則是亦楊墨而已矣。」

朱熹《孟子集注》：二十六章言道之所貴者中，中之所貴者權。

** 第二十七章

*◎ 孟子曰：「飢者甘食，渴者甘飲，是未得飲食之正也，飢渴害之也。豈惟口腹有飢渴之害？人心亦皆有害。*

趙岐註：飢渴害其本所以知味之性，令人強甘之。

朱熹《孟子集註》：口腹為飢渴所害，故於飲食不暇擇，而失其正味；人心為貧賤所害，故於富貴不暇擇，而失其正理。

*◎ 人能無以飢渴之害為心害，則不及人不為憂矣。」*

趙岐註：人能守正，不爲邪利所害，雖謂富貴之事不及逮人，猶為君子。不爲善，人所憂患也。

朱熹《孟子集註》：人能不以貧賤之故而動其心，則過人遠矣。

正義：二十七章言饑不妄食，忍情抑欲，賤不失道，不爲苟求，能無心害，夫將何憂。

李贄評：甘字最阱人。此篇文字最顯最隱，味在言中，意在言表，真鏡中花水中月也。

** 第二十八章

*◎ 孟子曰：「柳下惠不以三公易其介。」*

趙岐註：柳下惠執弘大之志，不恥污君，不以三公榮位易其大量也。

朱熹《孟子集註》：介，有分辨之意。柳下惠進不隱賢，必以其道，遺佚不怨，阨窮不憫，直道事人，至於三黜，是其介也。

朱熹《孟子集註》：二十八章言柳下惠和而不流，與孔子論夷齊不念舊惡意正相類，皆聖賢微顯闡幽之意也。

** 第二十九章

*◎ 孟子曰：「有為者辟若掘井，掘井九軔而不及泉，猶為棄井也。」*

趙岐註：有爲，為仁義也。雖深而不及泉，喻有爲者能於中道而盡棄前行者也。

朱熹《孟子集註》：八尺為仞。言鑿井雖深，然未及泉而止，猶為自棄其井也。呂侍講曰：「仁不如堯，孝不如舜，學不如孔子，終未入於聖人之域，終未至於天道，未免為半塗而廢、自棄前功也。」

正義：二十九章言為仁由己，必在究之，九軔而輟，無益成功。

李贄評：此篇文字不過二十字，便有波濤萬丈，孟子之文真以氣勝者也。

** 第三十章

*◎ 孟子曰：「堯舜，性之也；湯武，身之也；五霸，假之也。*

趙岐註：性之，性好仁，自然也。身之，體之行仁，視之若身也。假之，假仁以正諸侯也。

朱熹《孟子集註》：堯舜天性渾全，不假修習。湯武修身體道，以復其性。五霸則假借仁義之名，以求濟其貪欲之私耳。

*◎ 久假而不歸，惡知其非有也？」*

趙岐註：五霸而能久假仁義，譬如假物久而不歸，安知其不真有也。

朱熹《孟子集註》：歸，還也。有，實有也。言竊其名以終身，而不自知其非真有。或曰：「蓋歎世人莫覺其偽者。」亦通。舊說，久假不歸即為真有，則誤矣。

#+BEGIN_QUOTE
楊雄《法言》：曰：「假儒衣書服而讀之，三月不歸，孰曰非儒也？」或曰：「何以處偽？」曰：「有人則作，無人則輟之謂偽。觀人者，審其作輟而已矣。」
#+END_QUOTE

尹焞曰：「性之者，與道一也；身之者，履之也，及其成功則一也。五霸則假之而已，是以功烈如彼其卑也。」

正義：三十章言仁在性體，其次假借，用而不已，實何以易，在其勉之也。

** 第三十一章

*◎ 公孫丑曰：「伊尹曰：『予不狎于不順。』放太甲于桐，民大悅。太甲賢，又反之，民大悅。賢者之為人臣也，其君不賢，則固可放與？」*

朱熹《孟子集註》：子不狎于不順，太甲篇文。狎，習見也。不順，言太甲所為，不順義理也。

*◎ 孟子曰：「有伊尹之志，則可；無伊尹之志，則篡也。」*

朱熹《孟子集註》：伊尹之志，公天下以為心而無一毫之私者也。

正義：三十一章言憂國忘家，意在出身，志在寧君，放惡攝政，伊周有焉，凡人志異，則生篡心。

李贄評：抹卻多少亂臣賊子之心。

** 第三十二章

*◎ 公孫丑曰：「詩曰『不素餐兮』，君子之不耕而食，何也？」孟子曰：「君子居是國也，其君用之，則安富尊榮；其子弟從之，則孝弟忠信。『不素餐兮』，孰大於是？」*

趙岐註：君子能使人化其道德，移其習俗，身安國富而保其尊榮，子弟孝悌而樂忠信，不素食之功，誰大於是？此詩蓋刺在位食鄙，無功而受祿，君子不得進仕爾。

朱熹《孟子集註》：詩，魏國風伐檀之篇。素，空也。無功而食祿，謂之素餐，此與告陳相、彭更之意同。

正義：三十二章言君子正己，以立於世，世美其道，君臣是貴，所過者化，何素食之謂也。

** 第三十三章

*◎ 王子墊問曰：「士何事？」*

孫奭疏：王子墊，齊王之子名墊也。

朱熹《孟子集註》：墊，齊王之子也。上則公卿大夫，下則農工商賈，皆有所事；而士居其閒，獨無所事，故王子問之也。

*◎ 孟子曰：「尚志。」*

趙岐註：尚，貴也，士當貴上於用志也。

朱熹《孟子集註》：尚，高尚也。志者，心之所之也。士既未得行公、卿、大夫之道，又不當為農、工、商、賈之業，則高尚其志而已。

*◎ 曰：「何謂尚志？」曰：「仁義而已矣。殺一無罪，非仁也。非其有而取之，非義也。居惡在？仁是也。路惡在？義是也。居仁由義，大人之事備矣。」*

趙岐註：欲知其所當居者仁為上，所由者義為貴，大人之事備矣。

朱熹《孟子集註》：非仁非義之事，雖小不為；而所居所由，無不在於仁義，此士所以尚其志也。大人，謂公、卿、大夫。言士雖未得大人之位，而其志如此，則大人之事體用已全。若小人之事，則固非所當為也。

正義：三十三章言人當尚志，志於善也，善之所由，仁與義也。

** 第三十四章

*◎ 孟子曰：「仲子不義與之齊國而弗受，人皆信之，是舍簞食豆羹之義也。人莫大焉亡親戚、君臣、上下。以其小者信其大者，奚可哉？」*

趙岐註：孟子以爲仲子之義，簞食豆羹無禮而不受，萬鍾則不辨禮義而受之也。不知仁義親戚上下之敘，何可以其小廉信以爲大哉？

#+BEGIN_QUOTE
孟子曰：「仲子，齊之世家也，兄戴，蓋祿萬鍾。以兄之祿為不義之祿而不食也，以兄之室為不義之室而不居也，辟兄離母，處於於陵。」

孟子曰：「於齊國之士，吾必以仲子為巨擘焉。雖然，仲子惡能廉？充仲子之操，則蚓而後可者也。夫蚓，上食槁壤，下飲黃泉。仲子所居之室，伯夷之所築與？抑亦盜跖之所築與？所食之粟，伯夷之所樹與？抑亦盜跖之所樹與？是未可知也。」
#+END_QUOTE

朱熹《孟子集註》：仲子，陳仲子也。言仲子設若非義而與之齊國，必不肯受。齊人皆信其賢，然此但小廉耳。其辟兄離母，不食君祿，無人道之大倫，罪莫大焉。豈可以小廉信其大節，而遂以為賢哉？

正義：三十四章言事有輕重，行有大小，以大包小可也，以小信大，未之聞也。

** 第三十五章

*◎ 桃應問曰：「舜為天子，皋陶為士，瞽瞍殺人，則如之何？」*

趙岐註：問皋陶為士官主執罪人，瞽瞍惡暴而殺人，則皋陶何如？

朱熹《孟子集註》：桃應，孟子弟子也。其意以為舜雖愛父，而不可以私害公；皋陶雖執法，而不可以刑天子之父。故設此問，以觀聖賢用心之所極，非以為真有此事也。

*◎ 孟子曰：「執之而已矣。」*

趙岐註：皋陶執之耳。

孫奭疏：但當執而不縱也。

朱熹《孟子集註》：言皋陶之心，知有法而已，不知有天子之父也。

*◎ 「然則舜不禁與？」*

趙岐註：桃應以爲舜為天子，使有司執其父，不禁止之邪？

朱熹《孟子集註》：桃應問也。

*◎ 曰：「夫舜惡得而禁之？夫有所受之也。」*

趙岐註：夫舜惡得禁之，夫天下乃受之於舜，當爲天理民，王法不曲，豈得禁之也。

朱熹《孟子集註》：言皋陶之法，有所傳受，非所敢私，雖天子之命亦不得而廢之也。

*◎ 「然則舜如之何？」曰：「舜視棄天下，猶棄敝蹝也。竊負而逃，遵海濱而處，終身訢然，樂而忘天下。」*

趙岐註：舜必負父而遠逃，終身訢然，忽忘天下之至貴也。

朱熹《孟子集註》：蹝，草履也。遵，循也。言舜之心。知有父而已，不知有天下也。孟子嘗言舜視天下猶草芥，而惟順於父母可以解憂，與此意互相發。此章言為士者，但知有法，而不知天子父之為尊；為子者，但知有父，而不知天下之為大。

正義：三十五章言奉法承天，政不可枉，大孝榮父，遺棄天下，虞舜之道，趨將如此。

李贄評：此處問答甚奇，道理甚正，非是弟子不能問，非是師亦不能答也。若在俗儒，當桃應問處，定答之曰「此時瞽瞍業已底豫，不想殺人了」，如此便許多道理、許多經濟一筆都勾。聖臣守法，聖子愛親，種種方便，後人那知。噫，今日聰慧子弟不少，桃應之問想時有之，多爲老頭巾一切腐語攔斷，豈不可惜。嘗言有善問者，須有善答者，有善答者，須有善問者，缺一不可。

#+BEGIN_QUOTE
王夫之《四書訓義》：凡一德之成，皆必顺乎性之所安，而不任其情之所流与气之所激。惟中国为礼义之邦，先王之风教陶镕其气质，而士君子以学术正其性情，故人咸有以喻其天性自然之理，则虽偏有一德者，亦不碍于大中至和之道。
#+END_QUOTE

** 第三十六章

*◎ 孟子自范之齊，望見齊王之子，喟然歎曰：「居移氣，養移體，大哉居乎！夫非盡人之子與？」*

趙岐註：居尊則氣高，居卑則氣下。居之移人氣志使之高涼，若供養之移人形身使充盛也。「大哉乎居」者，言當慎所居，人必居仁也。凡人與王子豈非盡是人之子也，王子居尊勢，故儀聲如是也。

朱熹《孟子集註》：范，齊邑。居，謂所處之位。養，奉養也。言人之居處，所繫甚大，王子亦人子耳，特以所居不同，故所養不同而其氣體有異也。

正義：三十六章言人性皆同，居使之異，君子居仁，小人處利，譬猶王子，殊於眾品也。

** 第三十七章

*◎ 孟子曰：「王子宮室、車馬、衣服多與人同，而王子若彼者，其居使之然也；況居天下之廣居者乎？*

趙岐註：謂行仁義，仁義在身，不言而喻也。

孫奭疏：言王子所居勢位能如此，而況居天下之廣居，以仁為居者乎？

朱熹《孟子集註》：廣居，見前篇。尹焞曰：「睟然見於面，盎於背，居天下之廣居者然也。」

*◎ 魯君之宋，呼於垤澤之門。守者曰：『此非吾君也，何其聲之似我君也？』此無他，居相似也。」*

趙岐註：人君之聲相似者，以其俱居尊勢，故音氣同也。以城門不自肯夜開，故君發聲耳。

朱熹《孟子集註》：垤澤，宋城門名也。孟子又引此事為證。

正義：三十七章言與服器用，人用不殊，尊貴居之，志氣以舒。是以居仁由義，盎然内優，胸中正者，眸子不瞀也。

** 第三十八章

*◎ 孟子曰：「食而弗愛，豕交之也。愛而不敬，獸畜之也。*

趙岐註：人之交接，但食之而不愛，若養豕也。愛而不敬，若人畜禽獸，但愛而不能敬也。

朱熹《孟子集註》：交，接也。畜，養也。獸，謂犬馬之屬。

*◎ 恭敬者，幣之未將者也。*

趙岐註：恭敬者如有幣帛，當以行禮，而未以命將行之也。

朱熹《孟子集註》：將，猶奉也。詩曰：「承筐是將。」

程子曰：「恭敬雖因威儀幣帛而後發見，然幣之未將時，已有此恭敬之心，非因幣帛而後有也。」

*◎ 恭敬而無實，君子不可虛拘。」*

趙岐註：恭敬貴實，如其無實，何可須拘致君子之心也。

孫奭疏：以其禮不可以徒虛而行，何必以恭敬修於内而為之本，幣帛以將之而為之末，則君子交接之道畢矣。

朱熹《孟子集註》：此言當時諸侯之待賢者，特以幣帛為恭敬，而無其實也。拘，留也。

正義：三十八章言取人之道，必以恭敬，恭敬貴實，虛則不應。

** 第三十九章

*◎ 孟子曰：「形色，天性也。惟聖人，然後可以踐形。」*

趙岐註：踐，履居之也。

孫奭疏：形有道之象，色為道之容，人之生也，性出於天命，道又出於率性，是以形之與色皆爲天性也。惟聖人能因形以求其性，體性以踐其形。形一定而不易者也，色則有喜怒哀樂之變，以其無常者也。

朱熹《孟子集註》：人之有形有色，無不各有自然之理，所謂天性也。踐，如踐言之踐。蓋眾人有是形，而不能盡其理，故無以踐其形；惟聖人有是形，而又能盡其理，然後可以踐其形而無歉也。

程子曰：「此言聖人盡得人道而能充其形也。蓋人得天地之正氣而生，與萬物不同。既為人，須盡得人理，然後稱其名。眾人有之而不知，賢人踐之而未盡，能充其形，惟聖人也。」

楊時曰：「天生烝民，有物有則。物者，形色也。則者，性也。各盡其則，則可以踐形矣。」

戴震《孟子字義疏證》：成是性，斯為是才。別而言之，曰命，曰性，曰才，合而言之，是謂天性。故孟子曰「形色，天性也。惟聖人，然後可以踐形。」人物成性不同，故形色各殊。人之形，官器利用大遠乎物，然而於人之道不能無失，是不踐此形也。猶言之而形不逮，是不踐此言也。踐形之與盡性盡其才，其義一也。

正義：三十九章言體德正容，大人所履，有表無裹，謂之柚梓，是以聖人乃堪踐形也。

李贄評：不曰盡性而曰踐形妙甚。孔子之耳順方是踐耳，他人都是聾，顏子之卓爾方是踐眼，他人都是瞎，孟子之睟面盎背、四體不言而喻方是踐身，他人都是疲癃殘疾、痿疲不仁之人。

#+BEGIN_QUOTE
陳北溪序《竹林精舍錄》：致知必一一平實，循序而進，而無一物之不格。力行必一一平實，循序而進，而無一事之不周。如顏子之博約，毋遽求顏子之卓爾。如曾子之所以為貫，毋遽求曾子之所以為一。
#+END_QUOTE

** 第四十章

*◎ 齊宣王欲短喪。公孫丑曰：「為朞之喪，猶愈於已乎？」*

孫奭疏：以謂朞年之喪，猶勝於止而不爲者矣。朞年，十二月也。

朱熹《孟子集註》：已，猶止也。

*◎ 孟子曰：「是猶或紾其兄之臂，子謂之姑徐徐云爾，亦教之孝弟而已矣。」*

趙岐註：今欲行其朞喪，亦猶曰徐徐之類也。

孫奭疏：是若或有紾戾其兄之臂者，子以爲之姑且徐徐然紾其兄之臂云爾。但黨教之以孝悌，不復戾兄之臂也。

朱熹《孟子集註》：紾，戾也。教之以孝弟之道，則彼當自知兄之不可戾，而喪之不可短矣。孔子曰：「子生三年，然後免於父母之懷，予也有三年之愛於其父母乎？」所謂教之以孝弟者如此。蓋示之以至情之不能已者，非強之也。

*◎ 王子有其母死者，其傅為之請數月之喪。公孫丑曰：「若此者，何如也？」*

趙岐註：王子之庶夫人死，迫於適夫人，不得行其喪親之數，其傳為請之於君，欲使得行數月喪。

朱熹《孟子集註》：陳暘曰：「王子所生之母死，厭於嫡母而不敢終喪。其傅為請於王，欲使得行數月之喪也。時又適有此事，丑問如此者，是非何如？」按《儀禮》：「公子為其母練冠、麻衣、縓緣，既葬除之。」疑當時此禮已廢，或既葬而未忍即除，故請之也。

*◎ 曰：「是欲終之而不可得也。雖加一日愈於已，謂夫莫之禁而弗為者也。」*

趙岐註：加益一日則愈於止，況數月乎？所謂不當者，謂無禁自欲短之，故譏之也。

朱熹《孟子集註》：言王子欲終喪而不可得，其傅為請，雖止得加一日，猶勝不加。我前所譏，乃謂夫莫之禁而自不為者耳。此章言三年通喪，天經地義，不容私意有所短長。示之至情，則不肖者有以企而及之矣。

正義：四十章言禮斷三年，孝者欲益，富貴怠厭，思減其日，君子正言，不可阿情。

** 第四十一章

*◎ 孟子曰：「君子之所以教者五。*

朱熹《孟子集註》：下文五者，蓋因人品高下，或相去遠近先後之不同。

*◎ 有如時雨化之者，*

孫奭疏：是其潤之以德，漸之以仁，善有萌芽，則誘之使敷秀，性有其材，則養之使長茂。

朱熹《孟子集註》：時雨，及時之雨也。草木之生，播種封植，人力已至而未能自化，所少者，雨露之滋耳。及此時而雨之，則其化速矣。教人之妙，亦猶是也，若孔子之於顏曾是已。

*◎ 有成德者，有達財者，*

孫奭疏：有成德者，以其因固有之德，但教而成之也。有達財者，以其有財之具而不能用者，則教而達之也。

朱熹《孟子集註》：財，與材同。此各因其所長而教之者也。成德，如孔子之於冉閔；達財，如孔子之於由賜。

#+BEGIN_QUOTE
子貢問曰：「賜也何如？」子曰：「女，器也。」曰：「何器也？」曰：「瑚璉也。」
#+END_QUOTE

*◎ 有答問者，*

孫奭疏：以其在於答問之間也，不憤不啓，不悱不發，舉一隅不以三隅反則不復也。

朱熹《孟子集註》：就所問而答之，若孔孟之於樊遲、萬章也。

*◎ 有私淑艾者。*

趙岐註：君子獨善其身，人法其仁，此亦教法之道無差也。

朱熹《孟子集註》：私，竊也。淑，善也。艾，治也。人或不能及門受業，但聞君子之道於人，而竊以善治其身，是亦君子教誨之所及，若孔孟之於陳亢、夷之是也。孟子亦曰：「予未得為孔子徒也，予私淑諸人也。」

*◎ 此五者，君子之所以教也。」*

趙岐註：申言之，孟子貴重此教之道也。

朱熹《孟子集註》：聖賢施教，各因其材，小以成小，大以成大，無棄人也。

正義：四十一章言教人之術，莫善五者，養育英才，君子所珍，聖所不倦，其惟誨人乎。

** 第四十二章

*◎ 公孫丑曰：「道則高矣美矣，宜若登天然，似不可及也。何不使彼為可幾及而日孳孳也？」*

趙岐註：令彼凡人可庶幾，使日孽孽自勉也。

*◎ 孟子曰：「大匠不為拙工改廢繩墨，羿不為拙射變其彀率。*

朱熹《孟子集註》：彀率，彎弓之限也。言教人者，皆有不可易之法，不容自貶以殉學者之不能也。

*◎ 君子引而不發，躍如也。中道而立，能者從之。」*

趙岐註：君子謂於射則引弓彀弩而不發，以待彀偶也。於道則中，道德之中，不以學者不能故卑下其道，將以須於能者往取之也。

朱熹《孟子集註》：引，引弓也。發，發矢也。躍如，如踴躍而出也。因上文彀率，而言君子教人，但授以學之之法，而不告以得之之妙，如射者之引弓而不發矢，然其所不告者，已如踴躍而見於前矣。中者，無過不及之謂。中道而立，言其非難非易。能者從之，言學者當自勉也。

正義：四十二章言曲高和寡，道大難追，然而履正者不枉，執德者不回，故曰人能宏道。

朱熹《孟子集註》：此章言道有定體，教有成法；卑不可抗，高不可貶；語不能顯，默不能藏。

** 第四十三章

*◎ 孟子曰：「天下有道，以道殉身。天下無道，以身殉道。*

#+BEGIN_QUOTE
子曰：「天下有道則見，無道則隱。」
#+END_QUOTE

趙岐註：殉，從也。天下有道，得行王政，道從身施功實也。天下無道，道不得行，以身從道，守道而隱。

朱熹《孟子集註》：殉，如殉葬之殉，以死隨物之名也。身出則道在必行，道屈則身在必退，以死相從而不離也。

*◎ 未聞以道殉乎人者也。」*

趙岐註：不聞以正道從俗人也。

正義：四十三章言窮達卷舒，屈伸異變，變流從顧，守者所慎，故曰金石獨止，不徇人也。

李贄評：殉字奇，非身有道者不能爲此言。

** 第四十四章

*◎ 公都子曰：「滕更之在門也，若在所禮。而不荅，何也？」*

趙岐註：滕更，滕君之弟，來學於孟子。言國君之弟而樂在門人中，宜荅見禮，而夫子不荅，何也？

*◎ 孟子曰：「挾貴而問，挾賢而問，挾長而問，挾有勳勞而問，挾故而問，皆所不荅也。滕更有二焉。」*

趙岐註：挾，接也。滕更有二焉，接貴接賢，故不荅矣。

朱熹《孟子集註》：此言君子雖誨人不倦，又惡夫意之不誠者。

尹焞曰：「有所挾，則受道之心不專，所以不答也。」

正義：四十四章言學尚虛己，師誨貴平，是以滕更恃二，孟子弗應。

** 第四十五章

*◎ 孟子曰：「於不可已而已者，無所不已。於所厚者薄，無所不薄也。*

趙岐註：於義所不當棄而棄之，則不可，所以不可而棄之，使無罪者咸恐懼也。於義當厚而反薄之，何不薄也。不憂見薄者，亦皆不自安矣。

朱熹《孟子集註》：已，止也。不可止，謂所不得不為者也。所厚，所當厚者也。此言不及者之弊。

*◎ 其進銳者，其退速。」*

朱熹《孟子集註》：進銳者，用心太過，其氣易衰，故退速。三者之弊，理勢必然，雖過不及之不同，然卒同歸於廢弛。

正義：四十五章言賞僭及淫，刑濫傷善，不僭不濫，詩人所紀。孫奭疏：《詩》之《商頌》，於《殷武》之篇有云「不僭不濫」。

李贄評：其進處又補前二者之缺，蓋恐于不可已者不已矣，于所厚者不薄矣，又或有進銳退速之病也。

** 第四十六章

*◎ 孟子曰：「君子之於物也，愛之而弗仁。於民也，仁之而弗親。親親而仁民，仁民而愛物。」*

趙岐註：物，謂凡物可以養人者也，當愛育之，而不加之仁，若犧牲不得不殺也。臨民以非己族類，故不得與親同也。先親其親戚，然後仁民，仁民然後愛物，用恩之次者也。

朱熹《孟子集註》：物，謂禽獸草木。愛，謂取之有時，用之有節。

程子曰：「仁，推己及人，如老吾老以及人之老，於民則可，於物則不可。統而言之則皆仁，分而言之則有序。」

楊時曰：「其分不同，故所施不能無差等，所謂理一而分殊者也。」

尹焞曰：「何以有是差等？一本故也，無偽也。」

正義：四十六章言君子布德，各有所施，事得其宜，故謂之義也。

** 第四十七章

*◎ 孟子曰：「知者無不知也，當務之為急。仁者無不愛也，急親賢之為務。堯舜之知而不徧物，急先務也。堯舜之仁不徧愛人，急親賢也。*

趙岐註：知者，知所務善也。仁者，務愛其賢也。物，事也。堯舜不徧知百工之事，不徧愛衆人。先愛賢使治民，不一一自往親加恩惠也。

朱熹《孟子集註》：知者之知，並去聲。知者固無不知，然常以所當務者為急，則事無不治，而其為知也大矣；仁者固無不愛，然常急於親賢，則恩無不洽，而其為仁也博矣。

*◎ 不能三年之喪，而緦、小功之察；放飯流歠，而問無齒決，是之謂不知務。」*

趙岐註：尚不能行三年之喪，而復察緦麻、小功之禮。齒決，斷肉置其餘也。於尊者前賜食，大飯長歠，不敬之大者，齒決，小過耳。言世之先務，捨大譏小，有若大飯長歠而問無齒決類也。

朱熹《孟子集註》：

#+begin_verse
三年之喪，服之重者也。緦麻三月，小功五月，服之輕者也。察，致詳也。放飯，大飯。流歠，長歠，不敬之大者也。齒決，嚙斷乾肉，不敬之小者也。問，講求之意。

此章言君子之於道，識其全體，則心不狹；知所先後，則事有序。

豐稷曰：「智不急於先務，雖徧知人之所知、徧能人之所能，徒弊精神，而無益於天下之治矣。仁不急於親賢，雖有仁民愛物之心，小人在位，無由下達，聰明日蔽於上，而惡政日加於下，此孟子所謂『不知務』也。」
#+end_verse

正義：四十七章言振裘持領，正羅維綱，君子百行，先務其崇，是以堯舜親賢，大化以隆道爲要也。

#+BEGIN_QUOTE
荀子曰：「學之經莫速乎好其人，隆禮次之。上不能好其人，下不能隆禮，安特將學雜識志，順詩書而已耳。則末世窮年，不免為陋儒而已。將原先王，本仁義，則禮正其經緯蹊徑也。若挈裘領，詘五指而頓之，順者不可勝數也。不道禮憲，以詩書為之，譬之猶以指測河也，以戈舂黍也，以錐餐壺也，不可以得之矣。故隆禮，雖未明，法士也；不隆禮，雖察辯，散儒也。」
#+END_QUOTE

* 盡心下

** 第一章

*◎ 孟子曰：「不仁哉！梁惠王也。仁者以其所愛及其所不愛，不仁者以其所不愛及其所愛。」*

趙岐註：梁，魏都也。以，用也。仁者用恩於所愛之臣民，王政不偏，普施德教，所不親愛者并蒙其恩澤也。用不仁之政加於所不親愛，則有灾傷，所親愛之臣民亦并被其害。惠王好戰殺人，故孟子曰不仁哉。

朱熹《孟子集註》：親親而仁民，仁民而愛物，所謂以其所愛及其所不愛也。

*◎ 公孫丑曰：「何謂也？」「梁惠王以土地之故，糜爛其民而戰之，大敗，將復之，恐不能勝，故驅其所愛子弟以殉之，是之謂以其所不愛及其所愛也。」*

趙岐註：殉，從也。所愛從其所不愛而往趨死亡，故曰及其所愛也。東敗於齊，長子死焉。

孫奭疏：《左傳》云：「未陣而薄之曰敗某師，大崩曰敗績。」今梁王之敗，獨謂之大敗者，以其敗某師與敗績不足言，故稱爲大敗。抑又言梁王不以義戰，以見梁王不仁之甚也。

朱熹《孟子集註》：梁惠王以下，孟子答辭也。糜爛其民，使之戰鬬，糜爛其血肉也。復之，復戰也。子弟，謂太子申也。以土地之故及其民，以民之故及其子，皆以其所不愛及其所愛也。此承前篇之末三章之意，言仁人之恩，自內及外；不仁之禍，由疏逮親。

李贄評：公孫丑曰『何謂也』，以下發揮孟子之意耳，非丑問而孟子答也。

正義：一章言發政施仁，一國被恩。好戰輕民，災及所親，著此魏王，以戒人君也。

** 第二章

*◎ 孟子曰：「春秋無義戰。彼善於此，則有之矣。*

趙岐註：彼此相覺有善惡耳，孔子舉毫毛之善，貶纎芥之惡，故皆錄之於春秋也。

#+BEGIN_QUOTE
王允《论衡·感类》：「孔子作春秋，舉毫毛之善，貶纎芥之惡，采善不逾其美，貶惡不溢其過。」
#+END_QUOTE

孫奭疏：孟子言春秋之世，凡兵之所起，皆小役大，弱役強。或因怒興師，或棄禮貪利，未嘗有禁暴救亂之義也。然而春秋雖謂無義戰，其彼國之戰有善於此國，未嘗無也。是以彼善於此，則有之矣。

朱熹《孟子集註》：春秋每書諸侯戰伐之事，必加譏貶，以著其擅興之罪，無有以為合於義而許之者。但就中彼善於此者則有之，如召陵之師之類是也。

*◎ 征者上伐下也，敵國不相征也。」*

趙岐註：上伐下謂之征，諸侯敵國不得相征。五霸之世，諸侯相征，於三王之法，皆不得其正者也。

孫奭疏：夫征者以上伐下，無有敵於我師，所以正彼之罪也。如抗敵之國，則相爲強弱以結禍亂，非上之所以伐下、罔有敵于我師者也，其勢皆足以相抗，皆出於交惡者也，故曰敵國不相征也。

朱熹《孟子集註》：征，所以正人也。諸侯有罪，則天子討而正之，此春秋所以無義戰也。

正義：二章言春秋撥亂，時多戰爭，事實違禮，以文反正。征伐誅討，不自王命，故曰無義戰也。

** 第三章

*◎ 孟子曰：「盡信書，則不如無書。*

趙岐註：書，尚書。經有所美，言事或過。人不能聞天，天不能問於民，萬年永保，皆不可得爲書，豈可案文而皆信之哉。

程子曰：「載事之辭，容有重稱而過其實者，學者當識其義而已；苟執於辭，則時或有害於義，不如無書之愈也。」

*◎ 吾於武成，取二三策而已矣。*

趙岐註：武成，逸《書》之篇名，言武王誅紂，戰鬭殺人，血流舂杵。

朱熹《孟子集註》：武成，周書篇名，武王伐紂歸而記事之書也。策，竹簡也。取其二三策之言，其餘不可盡信也。

程子曰：「取其奉天伐暴之意，反政施仁之法而已。」

*◎ 仁人無敵於天下，以至仁伐至不仁，而何其血之流杵也？」*

趙岐註：孟子言武王以至仁伐至不仁，殷人簞食壺漿而迎其師，何乃至於血流漂杵乎？故吾取《武成》兩三簡策可用者耳，其過辭則不取之也。

#+BEGIN_QUOTE
孔安國《尚書正義》：「武王之伐殷也，往則陳兵伐紂，歸放牛馬為獸，記識殷家美政善事而行用之。史敘其事，作《武成》。」
#+END_QUOTE

朱熹《孟子集註》：杵，舂杵也。或作鹵，楯也。武成言武王伐紂，紂之「前徒倒戈，攻于後以北，血流漂杵」。孟子言此則其不可信者。然書本意，乃謂商人自相殺，非謂武王殺之也。孟子之設是言，懼後世之惑，且長不仁之心耳。

李贄評：是恁麼眼讀書者都當作如是觀。

正義：三章言文之有美過實，聖人不改，錄其意也，非獨《書》云，《詩》亦有言「崧高極天，則百斯男」，是故取於《武成》二三策而已。

** 第四章

*◎ 孟子曰：「有人曰：『我善為陳，我善為戰。』大罪也。*

趙岐註：此人欲勸諸侯以攻戰也，故謂之有罪。

朱熹《孟子集註》：制行伍曰陳，交兵曰戰。

*◎ 國君好仁，天下無敵焉。 南面而征北狄怨，東面而征西夷怨。曰：『奚為後我？』*

趙岐註：好仁無敵，四夷怨望遲，願見征，何爲後我。

朱熹《孟子集註》：此引湯之事以明之，解見前篇。

*◎ 武王之伐殷也，革車三百兩，虎賁三千人。*

趙岐註：革車，兵車也。虎賁，武士爲小臣者也。

孔安國曰：「兵車，百夫長所載車，稱兩，一車步卒七十二人，凡二萬一千人，舉全數。虎賁，勇士稱也，若虎賁獸，言其猛也，皆百夫長也。」

朱熹《孟子集註》：又以武王之事明之也。兩，車數，一車兩輪也。千，書序作百。

*◎ 王曰：『無畏！寧爾也，非敵百姓也。』若崩厥角，稽首。*

朱熹《孟子集註》：書太誓文與此小異。孟子之意當云王謂商人曰：「無畏我也。我來伐紂，本為安寧汝，非敵商之百姓也。」於是商人稽首至地，如角之崩也。

*◎ 征之為言正也，各欲正己也，焉用戰？」*

朱熹《孟子集註》：民為暴君所虐，皆欲仁者來正己之國也。

正義：四章言民思明君，若旱望雨，以仁伐暴，誰不欣喜。是以殷民厥角，周師歌舞，焉用善戰，故云罪也。

** 第五章

*◎ 孟子曰：「梓匠輪輿，能與人規矩，不能使人巧。」*

#+BEGIN_QUOTE
韓愈《符讀書城南》：木之就規矩，在梓匠輪輿。人之能爲人，由腹有詩書。
#+END_QUOTE

趙岐註：人之巧在心，拙者雖得規矩，亦不能成器也。

尹焞曰：「規矩，法度可告者也。巧則在其人，雖大匠亦末如之何也已。蓋下學可以言傳，上達必由心悟，莊周所論斲輪之意蓋如此。」

李贄評：說過一番却又使人巧矣。

正義：五章言規矩之法，喻若典禮，人不志仁，雖誦典憲，不能以善。善人修道，公輸守繩，政成器美，惟度是應，得其理也。

** 第六章

*◎ 孟子曰：「舜之飯糗茹草也，若將終身焉；及其為天子也，被袗衣，鼓琴，二女果，若固有之。」*

孫奭疏：云糗，糒也，按《釋名》云：「糗，乾飯屑也。」云「袗，畫也」，《說文》云「袗，玄衣也。」云果，侍也，按許慎謂女侍曰倮，今釋果為侍，謂二女之侍舜，是以有惑於許慎之說而遂誤歟。蓋木實曰果，云果者，取其實而言也。

朱熹《孟子集註》：飯，食也。糗，乾糒也。茹，亦食也。袗，畫衣也。二女，堯二女也。果，女侍也。言聖人之心，不以貧賤而有慕於外，不以富貴而有動於中，隨遇而安，無預於己，所性分定故也。

李贄評：不但畫舜貌并畫舜之神矣。

正義：六章言阨窮不憫，貴而思降，凡人所難，虞舜獨隆，聖德所以殊也。

** 第七章

*◎ 孟子曰：「吾今而後知殺人親之重也：殺人之父，人亦殺其父；殺人之兄，人亦殺其兄。然則非自殺之也，一閒耳。」*

趙岐註：父仇不同天，兄仇不同國，以惡加人，人必加之，知其重也。

朱熹《孟子集註》：言吾今而後知者，必有所為而感發也。一閒者，我往彼來，閒一人耳，其實與自害其親無異也。

范祖禹曰：「知此則愛敬人之親，人亦愛敬其親矣。」

正義：七章言恕以行仁，遠禍之端，暴以殘民，招咎之患。是以君子好生惡殺，反諸身也。

** 第八章

*◎ 孟子曰：「古之為關也，將以禦暴。*

趙岐註：古之為關，將以禦暴亂，譏閉非常也。

朱熹《孟子集註》：譏察非常。

*◎ 今之為關也，將以為暴。」*

趙岐註：今之為關，反以征稅出入之人，將以為暴虐之道也。

范祖禹曰：「古之耕者什一，後世或收大半之稅，此以賦斂為暴也。文王之囿，與民同之；齊宣王之囿，為阱國中，此以園囿為暴也。後世為暴，不止於關，若使孟子用於諸侯，必行文王之政，凡此之類，皆不終日而改也。」

李贄評：從禦暴處挑出為暴來，文字極巧，讀之悽然惻然。

正義：八章言修理關梁，譏而不征，如以稅斂，非其式程，懼將為暴，故載之也。

#+BEGIN_QUOTE
《周禮·司關》：「凡四方之賓客叩關，則為之吿，有內外之送，則以節傳出納之。」
#+END_QUOTE

** 第九章

*◎ 孟子曰：「身不行道，不行於妻子；使人不以道，不能行於妻子。」*

趙岐註：身不自履行道德，而欲使人行道德，雖妻子不肯行之，言無所則效。使人不順其道理，不能使妻子順之，而況他人乎？

朱熹《孟子集註》：身不行道者，以行言之。不行者，道不行也。使人不以道者，以事言之。不能行者，令不行也。

正義：九章言率人之道，躬行為首。

#+BEGIN_QUOTE
《論語·子路》：「其身正，不令而行；其身不正，雖令不從。」

荀子曰：「有分義，則容天下而治，無分義，則一妻一妾而亂。」
#+END_QUOTE

** 第十章

*◎ 孟子曰：「周于利者，凶年不能殺；周于德者，邪世不能亂。」*

趙岐註：周達於利，營苟得之利而趨生，雖凶年不能殺之。周達於德，身欲行之，雖遭邪世，不能亂其志也。

孫奭疏：喻人之能盡其性，以為周于德者，則所守彌篤，故姦邪之世不能亂其志。蓋以戰國之時，無富而教之之術，此孟子所以救之以此。

朱熹《孟子集註》：周，足也，言積之厚則用有餘。

正義：十章言務利蹈姦，務德蹈仁，舍身取義，其道不均也。

** 第十一章

*◎ 孟子曰：「好名之人，能讓千乘之國。苟非其人，簞食豆羹見於色。」*

#+BEGIN_QUOTE
王守仁《傳習錄》：「至親與路人同是愛的，如簞食豆羹，得則生，不得則死，不能兩全。寧救至親，不救路人，心又忍得，這是道理合該如此。」
#+END_QUOTE

趙岐註：好不朽之名者，輕讓千乘，伯夷、季札之類是也。誠非好名者，爭簞食豆羹變色，訟之致禍，鄭子公染指魭羹之類是也。

孫奭疏：云「鄭子公染指魭羹」者，案魯宣公四年《左傳》云：「楚人獻黿於鄭靈公。公子宋與子家將見，子公之食指動，以示子家曰：『他日我如此，必嘗異味。』及入，宰夫將解黿，相視而笑。公問之，子家以告。及食大夫黿，召子公而弗與。子公怒，染指於鼎，嘗之而出。公怒，欲殺子公。子公與子家謀先，子家曰：『畜老猶憚殺之，而況君乎？』反譖子家，子家懼而從之。夏，弑靈公。故經書曰：『鄭子公嘉弑其君夷。』」是也。

朱熹《孟子集註》：好名之人，矯情干譽，是以能讓千乘之國；然若本非能輕富貴之人，則於得失之小者，反不覺其真情之發見矣。蓋觀人不於其所勉，而於其所忽，然後可以見其所安之實也。

正義：十一章言廉貪相殊，名亦卓異，故聞伯夷之風，懦夫有立志也。

** 第十二章

*◎ 孟子曰：「不信仁賢，則國空虛。*

趙岐註：不親信仁賢，仁賢去之，國無賢人，則曰空虛也。

朱熹《孟子集註》：空虛，言若無人然。

*◎ 無禮義，則上下亂。*

朱熹《孟子集註》：禮義，所以辨上下，定民志。

*◎ 無政事，則財用不足。」*

朱熹《孟子集註》：生之無道，取之無度，用之無節故也。尹焞曰：「三者以仁賢為本。無仁賢，則禮義政事，處之皆不以其道矣。」

正義：十二章言親賢正禮，明其五教，為政之源，聖人以三者為急也。

** 第十三章

*◎ 孟子曰：「不仁而得國者，有之矣；不仁而得天下，未之有也。」*

趙岐註：以其不仁，天下不與，故不得有天下焉。

朱熹《孟子集註》：言不仁之人，騁其私智，可以盜千乘之國，而不可以得丘民之心。鄒氏曰：「自秦以來，不仁而得天下者有矣；然皆一再傳而失之，猶不得也。所謂得天下者，必如三代而後可。」

李贄評：國與天下一物也。國指土地，有形者而言；天下指人心，無形者而言。

正義：十三章言王者當天，然後處之。桀紂幽厲，雖得猶失，不以善終，不能世祀，不為得也。

** 第十四章

*◎ 孟子曰：「民為貴，社稷次之，君為輕。*

趙岐註：君輕社稷，社稷輕於民。

朱熹《孟子集註》：社，土神。稷，榖神。建國則立壇壝以祀之。蓋國以民為本，社稷亦為民而立，而君之尊，又係於二者之存亡，故其輕重如此。

*◎ 是故得乎丘民而為天子，得乎天子為諸侯，得乎諸侯為大夫。*

趙岐註：丘，十六井也。天下丘民皆樂其政，則為天子，殷湯、周文是也。

孫奭疏：一丘為十六井，而一井為九夫之地也。今云十六井，蓋有一萬四千四百畝，為一百四十四夫所受者也。

朱熹《孟子集註》：丘民，田野之民，至微賤也。然得其心，則天下歸之。天子至尊貴也，而得其心者，不過為諸侯耳，是民為重也。

*◎ 諸侯危社稷，則變置。*

趙岐註：諸侯為危社稷之行，則變更立賢諸侯也。

朱熹《孟子集註》：諸侯無道，將使社稷為人所滅，則當更立賢君，是君輕於社稷也。

*◎ 犧牲既成，粢盛既潔，祭祀以時，然而旱乾水溢，則變置社稷。」*

趙岐註：犧牲已成肥腯，梁稻已成絜精，祭祀社稷常以春秋之時，然而其國有旱乾水溢之災，則毀社稷而更置之。

孫奭疏：社稷無功以及民，亦在所更立有功於民者為之也，是民又貴於社稷也。云社稷者，蓋先王立五土之神，祀以為社，立五穀之神，祀以為稷。以古推之，自颛帝以來，用句龍為社，柱為稷。及湯之旱，以棄易其柱。是亦知社稷之變置，又有見於湯之時然也。

#+BEGIN_QUOTE
全祖望《經史問答》：「蓋古人之加罰於社稷者有三等，年不順成，八蠟不通，乃暫停其祭，是罰之輕者。又甚，則遷其壇之地，罰稍重矣。又甚，則更其配食之神，罰最重。然亦未嘗輕舉此禮，蓋變置至神示，所關重大，故自湯而後，罕有行者。」
#+END_QUOTE

朱熹《孟子集註》：祭祀不失禮，而土榖之神不能為民禦災捍患，則毀其壇壝而更置之，亦年不順成，八蜡不通之意，是社稷雖重於君而輕於民也。

正義：十四章言得民為君，得君為臣，民為貴也。先黜諸侯，後毀社稷，君為輕也。重民敬祀，治之所先，故列其次而言之。

** 第十五章

*◎ 孟子曰：「聖人，百世之師也，伯夷、柳下惠是也。故聞伯夷之風者，頑夫廉，懦夫有立志；聞柳下惠之風者，薄夫敦，鄙夫寬。奮乎百世之上，百世之下聞者莫不興起也。非聖人而能若是乎？而況於親炙之者乎？」*

趙岐註：頑，貪。懦，弱。鄙，狹。百世，言其遠也。

孫奭疏：是則二人清和之風，奮發乎百世之上，而使百世之下聞其風者，無有不感激，而志意興起而化之也。然而非聖人，其能若是，使百世之下莫不興起者也。聞而化者尚如此，況當時有親見熏炙之者乎！

朱熹《孟子集註》：興起，感動奮發也。親炙，親近而熏炙之也。

正義：十五章言伯夷、柳下惠，變貪厲薄，千載聞之，猶有感激，謂之聖人，美其德也。

** 第十六章

*◎ 孟子曰：「仁也者，人也。合而言之，道也。」*

趙岐註：能行仁恩者，人也。人與仁合而言之，可以謂之有道也。

孫奭疏：孟子言為仁者，所以盡人道也，此仁者所以為人也。蓋人非仁不立，仁非人不行。合仁與人而言之，則人道盡矣。楊子云：「仁以人同。」

朱熹《孟子集註》：

#+begin_verse
仁者，人之所以為人之理也。然仁，理也；人，物也。以仁之理，合於人之身而言之，乃所謂道者也。

程子曰：「中庸所謂率性之謂道是也。」

或曰：「外國本，人也之下，有『義也者宜也，禮也者履也，智也者知也，信也者實也』，凡二十字。」今按如此，則理極分明，然未詳其是否也。
#+end_verse

正義：十六章言仁恩須人，人能宏道也。

** 第十七章

*◎ 孟子曰：「孔子之去魯，曰：『遲遲吾行也。』去父母國之道也。去齊，接淅而行，去他國之道也。」*

趙岐註：說已見上篇。

正義：十七章言孔子周流不遇，則之他國遠逝。惟魯斯戀，篤於父母國之義也。

** 第十八章

*◎ 孟子曰：「君子之戹於陳蔡之閒，無上下之交也。」*

#+BEGIN_QUOTE
《論語·憲問》：「君子之道三，我無能焉，仁者不憂，知者不惑，勇者不懼。」
#+END_QUOTE

趙岐註：孔子乃尚謙，不敢當君子之道，故可謂孔子為君子也。孔子所以厄於陳、蔡之間者，其國君臣皆惡，上下無所交接，故厄也。

孫奭疏：以其上無所事，雖死不為謟，下無所可與，雖死不為瀆，是為無交接也。

朱熹《孟子集註》：君子，孔子也。戹，與厄同，君臣皆惡，無所與交也。

正義：十八章言君子固窮，窮不變道。上下無交，無賢援也。

#+BEGIN_QUOTE
《論語·衛靈公》：「孔子在陳，絕糧，從者病，莫能興。子路慍見，曰：『君子亦有窮乎？』子曰：『君子固窮，小人窮斯濫矣。』 /_窮不變道者能如是乎！_/
#+END_QUOTE

** 第十九章

*◎ 貉稽曰：「稽大不理於口。」*

趙岐註：貉，姓。稽，名。為眾口所訕。理，賴也。謂孟子曰：「稽大不賴人之口，如之何也。」

朱熹《孟子集註》：今按漢書無俚，方言亦訓賴。

*◎ 孟子曰：「無傷也。士憎茲多口。*

趙岐註：審己之德，口無傷也。離於凡人而仕者，亦益多口。

朱熹《孟子集註》：按此則憎當從土，今本皆從心，蓋傳寫之誤。

*◎ 詩云：『憂心悄悄，慍于羣小。』孔子也。『肆不殄厥慍，亦不隕厥問。』文王也。」*

趙岐註：孔子論此詩，孔子亦有武叔之口，故曰孔子之所苦也。言文王不殞絕畎夷之慍怒，亦不能殞失文王之善聲問也。

孫奭疏：言憂悄悄常在心，見怒于羣小衆小人也。以其孔子刪此詩，亦不能免武叔之毀，故曰孔子尚如是憎多口也。言不能殄絕畎夷之慍怒，然亦不能殞失文王之善聲，故曰文王尚如此，亦憎多口也。此所以荅貉稽大不理於口，以為無傷也。

#+BEGIN_QUOTE
《論語·子張》：「叔孫、武叔毀仲尼。子路曰：『無以為也！仲尼不可毀也。他人之賢者，丘陵也，猶可逾也。仲尼，日月也，無得而逾焉。人雖欲自絕，其何傷於日月乎？多見其不知量也。』
#+END_QUOTE

朱熹《孟子集註》：

#+begin_verse
詩邶風柏舟，及大雅緜之篇也。

悄悄，憂貌。慍，怒也。本言衛之仁人見怒於羣小。孟子以為孔子之事，可以當之。

肆，發語辭。隕，墜也。問，聲問也。本言太王事昆夷，雖不能殄絕其慍怒，亦不自墜其聲問之美。孟子以為文王之事，可以當之。

尹焞曰：「言人顧自處如何，盡其在我者而已。」
#+end_verse

正義：十九章言正己信心，不患衆口。衆口諠譁，大聖所有，況於凡品之所能禦？故荅貉稽曰無傷也。

** 第二十章

*◎ 孟子曰：「賢者以其昭昭，使人昭昭；今以其昬昬，使人昭昭。」*

趙岐註：賢者治國，法度昭明。明於道德，是躬行之道可也。今之治國，法度昏昏，亂潰之政也，身不能治，而欲使人昭明，不可得也。

孫奭疏：孟子言有諸己然後求諸人之道也。是亦所謂曲其表而求影之正，濁其源而求流之清，同其旨。

朱熹《孟子集註》：昭昭，明也。昬昬，闇也。

尹焞曰：「大學之道，在自昭明德，而施於天下國家，其有不順者寡矣。」

李贄評：知使人昭，亦不昏矣。

正義：二十章言以明昭闇，闇者以開，以闇責明，闇者愈迷，賢者可遵，譏今之非也。

** 第二十一章

*◎ 孟子謂高子曰：「山徑之蹊間，介然用之而成路，為間不用，則茅塞之矣。今茅塞子之心矣。」*

趙岐註：高子，齊人也，嘗學於孟子，鄉道而未明，去而學於他術。喻高子學於仁義之道，當遂行之而反中止，正若山路，故曰：「茅塞子之心也。」

朱熹《孟子集註》：徑，小路也。蹊，人行處也。介然，倏然之頃也。用，由也。路，大路也。為閒，少頃也。茅塞，茅草生而塞之也。言理義之心，不可少有間斷也。

正義：聖人之道，學而時習，仁義在身常常被服，舍而弗修，猶茅是塞，明為善之不可倦也。

** 第二十二章

*◎ 高子曰：「禹之聲，尚文王之聲。」*

朱熹《孟子集註》：尚，加尚也。豐稷曰：「言禹之樂，過於文王之樂。」

*◎ 孟子曰：「何以言之？」曰：「以追蠡。」*

趙岐註：追，鐘鈕也，鈕磨齧處深矣。蠡，欲絕之貌也。

朱熹《孟子集註》：豐稷曰：「追，鐘紐也。周禮所謂旋蟲是也。蠡者，齧木蟲也。言禹時鐘在者，鐘紐如蟲齧而欲絕，蓋用之者多，而文王之鐘不然，是以知禹之樂過於文王之樂也。」

#+BEGIN_QUOTE
趙希鵠《洞天清祿集・古鐘鼎彝器辨》：禹之聲尚文王之，聲以追蠡，趙岐注：「以追為鐘紐。」於義未安 「追者琢也。」詩云：「追琢其章。」今畫家滴粉令凸起，猶謂之追粉。所謂追蠡，葢古銅器欵文追起處，漫滅也。趙氏釋蠡為絶亦非絶，葢剥蝕也。今人亦以器物用久而剥蝕者為蠡。
#+END_QUOTE

*◎ 曰：「是奚足哉？城門之軌，兩馬之力與？」*

朱熹《孟子集註》：

#+begin_verse
豐稷曰：「奚足，言此何足以知之也。軌，車轍迹也。兩馬，一車所駕也。城中之涂容九軌，車可散行，故其轍迹淺；城門惟容一車，車皆由之，故其轍迹深。蓋日久車多所致，非一車兩馬之力，能使之然也。言禹在文王前千餘年，故鐘久而紐絕；文王之鐘，則未久而紐全，不可以此而議優劣也。」

此章文義本不可曉，舊說相承如此，而豐稷差明白，故今存之，亦未知其是否也。
#+end_verse

正義：二十二章言前聖後聖，所尚者同，三王一體，何得相踰。欲以追蠡，未達一隅。孟子言之，將啓其蒙。

** 第二十三章

*◎ 齊饑。陳臻曰：「國人皆以夫子將復為發棠，殆不可復。」*

趙岐註：棠，齊邑也。

朱熹《孟子集註》：先時齊國嘗饑，孟子勸王發棠邑之倉，以振貧窮。至此又饑，陳臻問言齊人望孟子復勸王發棠，而又自言恐其不可也。

*◎ 孟子曰：「是為馮婦也。晉人有馮婦者，善搏虎，卒為善士。則之野，有眾逐虎。虎負嵎，莫之敢攖。望見馮婦，趨而迎之。馮婦攘臂下車。眾皆悅之，其為士者笑之。」*

趙岐註：卒，後也。善士者，以善搏虎有勇名也，故進以為士。之於野外，復見逐虎者。攖，迫也。虎依陬而怒，無敢迫近者也。馮婦恥不如前，見虎走而迎之，攘臂下車，欲復搏之，眾人悅其勇猛。其士之黨笑其不知止也。故孟子謂陳臻今欲復使我如發棠時言之於君，是則我為馮婦也，必為知者所笑也。

孫奭疏：言今齊王恃威虐以斂民，亦若虎之負嵎，以難合之說，述於暴人之前，又若迎而搏虎也。

朱熹《孟子集註》：手執曰搏。卒為善士，後能改行為善也。之，適也。負，依也。山曲曰嵎。攖，觸也。笑之，笑其不知止也。疑此時齊王已不能用孟子，而孟子亦將去矣，故其言如此。

李贄評：以客當主，文字大奇。

正義：二十三章言可為則從，不可則凶，言善則用，得其時也。非時逆指，猶若馮婦，暴虎無已，必有害也。

** 第二十四章

*◎ 孟子曰：「口之於味也，目之於色也，耳之於聲也，鼻之於臭也，四肢之於安佚也，性也，有命焉，君子不謂性也。*

趙岐註：四體謂之四肢，四肢懈倦，則思安佚不勞苦。此皆人性之所欲也，得居此樂者，有命祿，人不能皆如其願也。凡人則有情從欲而求可身，君子之道，則以仁義為先，禮節為制，不以性欲而苟求之也，故君子不謂之性也。

孫奭疏：得居於此樂者，以其有命存焉。君子以為有命，在所不求，而不可以幸得也，是所以不謂之性也。

朱熹《孟子集註》：

#+begin_verse
程子曰：「五者之欲，性也。然有分，不能皆如其願，則是命也。不可謂我性之所有，而求必得之也。」

愚按：不能皆如其願，不止為貧賤。蓋雖富貴之極，亦有品節限制，則是亦有命也。
#+end_verse

*◎ 仁之於父子也，義之於君臣也，禮之於賓主也，智之於賢者也，聖人之於天道也，命也，有性焉，君子不謂命也。」*

趙岐註：此皆命祿，遭遇乃得居而行之，不遇者不得施行。然亦才性有之，故可用也。凡人則歸之命祿，在天而已，不復治性。以君子之道，則修仁行義，修禮學知，庶幾聖人亹亹不倦，不但坐而聽命，故曰君子不謂命也。

孫奭疏：有是五者，皆稟乎天性也，以其有性存焉。君子以為有性，在所可求，而不可不勉也，是所以不謂之命也。

朱熹《孟子集註》：

#+begin_verse
程子曰：「仁義禮智天道，在人則賦於命者，所稟有厚薄清濁，然而性善可學而盡，故不謂之命也。」

張載曰：「晏嬰智矣，而不知仲尼。是非命邪？」

愚按：所稟者厚而清，則其仁之於父子也至，義之於君臣也盡，禮之於賓主也恭，智之於賢否也哲，聖人之於天道也，無不脗合而純亦不已焉。薄而濁，則反是，是皆所謂命也。或曰：「者」當作否，「人」衍字，更詳之。

愚聞之師曰：「此二條者，皆性之所有而命於天者也。然世之人，以前五者為性，雖有不得，而必欲求之；以後五者為命，一有不至，則不復致力，故孟子各就其重處言之，以伸此而抑彼也。張子所謂『養則付命於天，道則責成於己』。其言約而盡矣。」
#+end_verse

正義：二十四章言尊德樂道，不任佚性，治性勤禮，不專委命。君子所能，小人所病。究言其事，以勸戒也。

** 第二十五章

*◎ 浩生不害問曰：「樂正子，何人也？」孟子曰：「善人也，信人也。」*

趙岐註：浩生，姓；不害，名，齊人也。見孟子聞樂正子為政於魯而喜，故問樂正子何等人也。

*◎ 「何謂善？何謂信？」*

朱熹《孟子集註》：不害問也。

*◎ 曰：「可欲之謂善，*

趙岐註：己之可欲，乃使人欲之，是為善人。

朱熹《孟子集註》：天下之理，其善者必可欲，其惡者必可惡。其為人也，可欲而不可惡，則可謂善人矣。

*◎ 有諸己之謂信。*

趙岐註：有之於己，乃謂人有之，是為信人。

朱熹《孟子集註》：凡所謂善，皆實有之，如惡惡臭，如好好色，是則可謂信人矣。

張載曰：「志仁無惡之謂善，誠善於身之謂信。」

*◎ 充實之謂美，*

趙岐註：充實善信，使之不虛，是為美人，美德之人也。

朱熹《孟子集註》：力行其善，至於充滿而積實，則美在其中而無待於外矣。

*◎ 充實而有光輝之謂大，*

趙岐註：充實善信而宣揚之，使有光輝，是為大人。

朱熹《孟子集註》：和順積中，而英華發外；美在其中，而暢於四支，發於事業，則德業至盛而不可加矣。

*◎ 大而化之之謂聖，*

趙岐註：大行其道，使天下化之，是為聖人。

朱熹《孟子集註》：大而能化，使其大者泯然無復可見之迹，則不思不勉、從容中道，而非人力之所能為矣。

張載曰：「大可為也，化不可為也，在熟之而已矣。」

*◎ 聖而不可知之之謂神。*

趙岐註：有聖知之明，其道不可得知，是為神人。

程子曰：「聖不可知，謂聖之至妙，人所不能測。非聖人之上，又有一等神人也。」

*◎ 樂正子，二之中，四之下也。」*

朱熹《孟子集註》：蓋在善信之閒，觀其從於子敖，則其有諸己者或未實也。

張載曰：「顏淵、樂正子皆知好仁矣。樂正子志仁無惡而不致於學，所以但為善人信人而已；顏子好學不倦，合仁與智，具體聖人，獨未至聖人之止耳。」

程子曰：「士之所難者，在有諸己而已。能有諸己，則居之安，資之深，而美且大可以馴致矣。徒知可欲之善，而若存若亡而已，則能不受變於俗者鮮矣。」

尹焞曰：「自可欲之善，至於聖而不可知之神，上下一理。擴充之至於神，則不可得而名矣。」

正義：二十五章言神聖以下，優劣異差，樂正好善，應下二科，是以孟子為之喜也。

** 第二十六章

*◎ 孟子曰：「逃墨必歸於楊，逃楊必歸於儒。歸，斯受之而已矣。*

趙岐註：墨翟之道兼愛，無親疏之別，最為違禮。楊朱之道，為己愛身，雖違禮，尚得不敢毀傷之義。逃者去也，去邪歸正，故曰歸。去墨歸楊，去楊歸儒，則當受而安之也。

孫奭疏：儒者之道，幼學所以為己，壯而行之所以為人，故能兼愛。

朱熹《孟子集註》：墨氏務外而不情，楊氏太簡而近實，故其反正之漸，大略如此。歸斯受之者，憫其陷溺之久，而取其悔悟之新也。

*◎ 今之與楊墨辯者，如追放豚，既入其苙，又從而招之。」*

朱熹《孟子集註》：放豚，放逸之豕豚也。苙，闌也。招，罥也，羈其足也。言彼既來歸，而又追咎其既往之失也。此章見聖賢之於異端，距之甚嚴，而於其來歸，待之甚恕。距之嚴，故人知彼說之為邪；待之恕，故人知此道之可反，仁之至，義之盡也。

正義：二十六章言驅邪反正，正斯可矣，來者不綏，追其前罪，君子甚之，以為過也。

** 第二十七章

*◎ 孟子曰：「有布縷之征，粟米之征，力役之征。君子用其一，緩其二。用其二而民有殍，用其三而父子離。」*

趙岐註：布，軍卒以為衣也，縷，紩鐵甲之縷也。粟米，軍糧也。力役，民負荷廝養之役也。君子為政，雖遭軍旅，量其民力，不並此三役，更發異時。

孫奭疏：蓋征之者義也，緩之者仁也，惟君子以仁是守，以義是行，然而充類之至而義之盡者，君子所不為也。此孟子不得不權時而救時之弊也。

朱熹《孟子集註》：征賦之法，歲有常數，然布縷取之於夏，粟米取之於秋，力役取之於冬，當各以其時；若并取之，則民力有所不堪矣。今兩稅三限之法，亦此意也。

尹焞曰：「言民為邦本，取之無度，則其國危矣。」

李贄評：緩字精見，原是不費之惠也，皆經國至言。

正義：二十七章言原心量力，政之善者；繇役並興，以致離殍；養民輕斂，君之道也。

** 第二十八章

*◎ 孟子曰：「諸侯之寶三：土地，人民，政事。寶珠玉者，殃必及身。」*

趙岐註：諸侯正其封疆，不侵鄰國，鄰國不犯，寶土地也；使民以時，居不離散，寶人民也；修其德教，布其惠政，寶政事也。

尹焞曰：「言寶得其寶者安，寶失其寶者危。」

正義：二十八章言寶此三者，以為國珍，寶於珍玩，以殃其身。諸侯如茲，永無患也。

** 第二十九章

*◎ 盆成括仕於齊。孟子曰：「死矣盆成括！」盆成括見殺。門人問曰：「夫子何以知其將見殺？」曰：「其為人也小有才，未聞君子之大道也，則足以殺其軀而已矣。」*

趙岐註：嘗欲學於孟子，問道未達而去，後仕於齊。言括之為人，小有才，慧而未知君子仁義謙順之道，適足以害其身也。

朱熹《孟子集註》：盆成，姓；括，名也。恃才妄作，所以取禍。徐氏曰：「君子道其常而已。括有死之道焉，設使幸而獲免，孟子之言猶信也。」

李贄評：此老好相法，為人而小有才者危矣，然則君子之大道不可不聞也。請問如何為君子之大道？

正義：二十九章言小知自私，藏怨之府。大雅先人，福之所聚。勞謙終吉，君子道也。

** 第三十章

*◎ 孟子之滕，館於上宮。有業屨於牖上，館人求之弗得。*

趙岐註：上宮，樓也。孟子舍止賓客所館之樓上也。置之窗牖之上，客到之後，求之不得。

朱熹《孟子集註》：館，舍也。上宮，別宮名。業屨，織之有次業而未成者，蓋館人所作，置之牖上而失之也。

*◎ 或問之曰：「若是乎從者之廋也？」曰：「子以是為竊屨來與？」曰：「殆非也。」「夫子之設科也，往者不追，來者不距。苟以是心至，斯受之而已矣。」*

#+BEGIN_QUOTE
《論語・述而》：互鄉難與言，童子見，門人惑。子曰：「與其進也，不與其退也，唯何甚！人潔己以進，與其潔也，不保其往也。」
#+END_QUOTE

趙岐註：

#+begin_verse
孟子與門徒相隨，從車數十，故曰侍從者所竊匿也。

孟子謂館人曰：「子以是眾人來隨事我，本為欲竊屨故來邪。」館人曰：殆非為是來事夫子也，自知問之過也。

孟子曰：「夫我設教授之科，教人以道德也，其去者亦不追呼，來者亦不拒逆，誠以是學道之心來至，我則斯受之，亦不知其取之與否？」君子不能保其異心也。見館人言殆非為是來，亦云不能保知，謙以益之而已。
#+end_verse

朱熹《孟子集註》：或問之者，問於孟子也。廋，匿也。言子之從者，乃匿人之物如此乎？孟子答之，而或人自悟其失，因言此從者固不為竊屨而來，但夫子設置科條以待學者，苟以向道之心而來，則受之耳，雖夫子亦不能保其往也。門人取其言，有合於聖賢之指，故記之。

正義：三十章言教誨之道，受之如海，百川移流，不得有拒。雖獨竊屨，非己所絕。順荅小人，小人自咎，所謂造次必於是也。

** 第三十一章

*◎ 孟子曰：「人皆有所不忍，達之於其所忍，仁也。人皆有所不為，達之於其所為，義也。*

趙岐註：人皆有所愛，不忍加惡，推之以通於所不愛，皆令被德，此仁人也。人皆有不喜為，謂貧賤也，通之於其所喜為，謂富貴也。抑情止欲，使若所不喜為此者，義人也。

朱熹《孟子集註》：惻隱羞惡之心，人皆有之，故莫不有所不忍不為，此仁義之端也。然以氣質之偏、物欲之蔽，則於他事或有不能者。但推所能，達之於所不能，則無非仁義矣。

*◎ 人能充無欲害人之心，而仁不可勝用也。人能充無穿踰之心，而義不可勝用也。*

趙岐註：人皆有不害人之心，能充大之以為仁，仁不可勝用也。穿牆踰屋，姦利之心也。人既無此心，能充大之以為義，義不可勝用也。

朱熹《孟子集註》：充，滿也。穿，穿穴；踰，踰牆，皆為盜之事也。能推所不忍，以達於所忍，則能滿其無欲害人之心，而無不仁矣；能推其所不為，以達於所為，則能滿其無穿踰之心，而無不義矣。

*◎ 人能充無受爾汝之實，無所往而不為義也。*

趙岐註：爾汝之實，德行可輕賤，人所爾汝者也。既不見輕賤，不為人所爾汝，能充大而以自行，所至皆可以為義也。

朱熹《孟子集註》：此申說上文充無穿踰之心之意也。蓋爾汝人所輕賤之稱，人雖或有所貪昧隱忍而甘受之者，然其中心必有慚忿而不肯受之之實。人能即此而推之，使其充滿無所虧缺，則無適而非義矣。

*◎ 士未可以言而言，是以言餂之也。可以言而不言，是以不言餂之也，是皆穿踰之類也。」*

趙岐註：人之為士者，見尊貴者未可與言者而不與之言，欲以言取之也，是失言也。見可與言者而不與之言，不知賢人可與之言，而反欲以不言取之，是失人也。是皆趨利入邪無知之人，故曰穿踰之類也。

朱熹《孟子集註》：餂，探取之也。今人以舌取物曰餂，即此意也。便佞隱默，皆有意探取於人，是亦穿踰之類。然其事隱微，人所易忽，故特舉以見例。明必推無穿踰之心，以達於此而悉去之，然後為能充其無穿踰之心也。

李贄評：說得極入細，只是仁義透體耳。

正義：三十一章言善恕行義，充大其美，無受爾汝，何施不可。取人不知，失其臧否，比之穿踰，善亦遠矣。

** 第三十二章

*◎ 孟子曰：「言近而指遠者，善言也。守約而施博者，善道也。君子之言也，不下帶而道存焉。*

趙岐註：言近指遠，近言正心，遠可以事天也。守約施博，約守仁義，大可以施德於天下也。二者可謂善言善道也。正心守仁，皆在胸臆，吐口而言之，四體不與焉，故曰不下帶而道存焉。

孫奭疏：蓋帶者所以服之，近於人身也，故取而喻之，曰不下帶而道存，抑又見君子之言非特騰口說而已。

朱熹《孟子集註》：古人視不下於帶，則帶之上，乃目前常見至近之處也。舉目前之近事，而至理存焉，所以為言近而指遠也。

*◎ 君子之守，修其身而天下平。*

趙岐註：身正物正，天下平矣。

孫奭疏：以其君子之所守，特在脩身，而天下由是平矣，是所謂正己而物正者也。

朱熹《孟子集註》：此所謂守約而施博也。

*◎ 人病舍其田而芸人之田，所求於人者重，而所以自任者輕。」*

趙岐註：芸，治也。田以喻身，舍身不治，而欲責人治，是求人太重，自任太輕也。

朱熹《孟子集註》：此言不守約而務博施之病。

正義：三十二章言言道之善，以心為原，當求諸己。而責於人，君子尤之，況以妄芸。言失務也。

** 第三十三章

*◎ 孟子曰：「堯舜，性者也；湯武，反之也。*

趙岐註：堯舜之體性自善者也。殷湯、周武，反之於身，身安乃以施人，謂加善於民也。

朱熹《孟子集註》：性者，得全於天，無所汙壞，不假修為，聖之至也。反之者，修為以復其性，而至於聖人也。

程子曰：「性之反之，古未有此語，蓋自孟子發之。」

呂大臨曰：「無意而安行，性者也，有意利行，而至於無意，復性者也。堯舜不失其性，湯武善反其性，及其成功則一也。」

*◎ 動容周旋中禮者，盛德之至也；哭死而哀，非為生者也；經德不回，非以干祿也；言語必信，非以正行也。*

趙岐註：人動作容儀周旋中禮者，盛德之至。死者有德，哭者哀也。經，行也。體德之人，行其節操自不回邪，非以求祿位也。庸言必信，非必欲以正行為名也，性不忍欺人也。

孫奭疏：堯舜體性之自然，湯武反之於身、身安乃以施人，無非是禮也，故動容周旋中禮者，是為盛德之至也。

朱熹《孟子集註》：中、為、行，並去聲。細微曲折，無不中禮，乃其盛德之至。自然而中，而非有意於中也。經，常也。回，曲也。三者亦皆自然而然，非有意而為之也，皆聖人之事，性之之德也。

*◎ 君子行法，以俟命而已矣。」*

趙岐註：君子順性蹈德，行其法度，夭壽在天，行命以待之而已矣。

朱熹《孟子集註》：法者，天理之當然者也。君子行之，而吉凶禍福有所不計，蓋雖未至於自然，而已非有所為而為矣。此反之之事，董子所謂「正其義不謀其利，明其道不計其功」，正此意也。

程子曰：「動容周旋中禮者，盛德之至。行法以俟命者，『朝聞道夕死可矣』之意也。」

呂大臨曰：「法由此立，命由此出，聖人也；行法以俟命，君子也。聖人性之，君子所以復其性也。」

正義：三十三章言君子之行，動合禮中，不惑禍福，修身俟終。堯舜之盛，湯武之隆，不是過也。

** 第三十四章

*◎ 孟子曰：「說大人，則藐之，勿視其巍巍然。*

趙岐註：大人，當時之尊貴者也。藐，輕之也。巍巍，富貴高顯之貌。孟子言說此大人之法，心當有以輕藐之，勿敢視之巍巍富貴若此，而不畏之，則心舒意展，言語得盡而已。

*◎ 堂高數仞，榱題數尺，我得志弗為也。食前方丈，侍妾數百人，我得志弗為也。般樂飲酒，驅騁田獵，後車千乘，我得志弗為也。在彼者皆我所不為也，在我者皆古之制也，吾何畏彼哉？」*

趙岐註：仞，八尺也。大屋無尺丈之限，故言數仞也。極五味之饌食，列於前方一丈，侍妾眾多至數百人也。般，大也。

朱熹《孟子集註》：榱，桷也。題，頭也。食前方丈，饌食列於前者，方一丈也。此皆其所謂巍巍然者，我雖得志，有所不為，而所守者皆古聖賢之法，則彼之巍巍者，何足道哉！

楊時曰：「孟子此章，以己之長，方人之短，猶有此等氣象，在孔子則無此矣。」

李贄評：窮秀才氣。

正義：三十四章言富貴而驕，自遺咎也，茅茨采椽，聖堯表也。以賤說貴，懼有蕩心，心謂彼陋，以寧我神，故以所不為為之寶玩也。

** 第三十五章

*◎ 孟子曰：「養心莫善於寡欲。其為人也寡欲，雖有不存焉者，寡矣。其為人也多欲，雖有存焉者，寡矣。」*

#+BEGIN_QUOTE
荀子曰：「君子養心莫善於誠，致誠則無它事矣。唯仁之為守，唯義之為行。誠心守仁則形，形則神，神則能化矣。誠心行義則理，理則明，明則能變矣。變化代興，謂之天德。」
#+END_QUOTE

趙岐註：養，治也。寡，少也。欲，利欲也。雖有少欲而亡者，謂遭橫暴，若單豹臥深山而遇飢虎之類也，然亦寡矣。貪而不亡，蒙先人德業，若晉國栾黡之類也，然亦少矣，不存者衆。

朱熹《孟子集註》：欲，如口鼻耳目四支之欲，雖人之所不能無，然多而不節，未有不失其本心者，學者所當深戒也。

程子曰：「所欲不必沈溺，只有所向便是欲。」

李贄評：只說寡欲極是。

正義：三十五章言清靜寡欲，德之高者，畜聚積實，穢行之下。廉者招福，濁者速禍，雖有不然，蓋非常道，是以正路不可不由也。

** 第三十六章

*◎ 曾皙嗜羊棗，而曾子不忍食羊棗。*

趙岐註：羊棗，棗名也。曾子以父嗜羊棗，父沒之後，唯念其親不復食羊棗，故身不忍食也。

朱熹《孟子集註》：羊棗，實小黑而圓，又謂之羊矢棗。

*◎ 公孫丑問曰：「膾炙與羊棗孰美？」孟子曰：「膾炙哉！」公孫丑曰：「然則曾子何為食膾炙而不食羊棗？」曰：「膾炙所同也，羊棗所獨也。諱名不諱姓，姓所同也，名所獨也。」*

趙岐註：孟子言膾炙雖美，人所同嗜。獨曾子父嗜羊棗耳，故曾子不忍食也。譬如諱君父之名，不諱其姓。姓與族同之，名所獨也，故諱之也。

朱熹《孟子集註》：肉聶而切之為膾。炙，炙肉也。

正義：三十六章言情禮相扶，以禮制情；人所同然，禮則不禁。曾参至孝，思親異心，羊棗之感，終身不嘗。孟子嘉焉，故上章稱曰：「豈有非義而曾子言之者也。」`此謂公孫丑疑曾子為非義，而乃不知膾炙所同、羊棗之所獨，而曾子之心言之是或一於孝道，故云然也。`

** 第三十七章

*◎ 萬章問曰：「孔子在陳，曰：『盍歸乎來？吾黨之小子狂簡進取，不忘其初。』孔子在陳，何思魯之狂士？」*

趙岐註：孔子在陳，不遇賢人，上下無所交，蓋歎息思歸，欲見其鄉黨之士也。簡，大也。狂者，進取大道而不得其正者也。不忘其初，孔子思故舊也。《周禮》「五黨為州，五州為鄉」，故曰吾黨之士也。萬章怪孔子何為思魯之狂士者也。

朱熹《孟子集註》：盍，何不也。狂簡，謂志大而略於事。進取，謂求望高遠。不忘其初，謂不能改其舊也。此語與論語小異。

*◎ 孟子曰：「孔子『不得中道而與之，必也狂狷乎！狂者進取，狷者有所不為也』。孔子豈不欲中道哉？不可必得，故思其次也。」*

趙岐註：中道，中正之大道也。狂者能進取，狷者能不為不善。時無中道之人，以狂、狷次善者，故思之也。

朱熹《孟子集註》：不得中道，至有所不為，據論語亦孔子之言。然則孔子字下當有曰字。論語道作行，獧作狷。有所不為者，知恥自好，不為不善之人也。孔子豈不欲中道以下，孟子言也。

*◎ 「敢問何如斯可謂狂矣？」*

朱熹《孟子集註》：萬章問。

*◎ 曰：「如琴張、曾皙、牧皮者，孔子之所謂狂矣。」*

趙岐註：皆事孔子學者也。

孫奭疏：蓋《論語》嘗謂古之狂也肆，今之狂也蕩。皆學於孔子，進取於道而躐等者也，是謂古之狂者也。

朱熹《孟子集註》：琴張，名牢，字子張。子桑戶死，琴張臨其喪而歌，事見《莊子》。雖未必盡然，要必有近似者。曾皙見前篇。季武子死，曾皙倚其門而歌，事見檀弓。又言志異乎三子者之撰，事見論語。牧皮，未詳。

*◎ 「何以謂之狂也？」*

朱熹《孟子集註》：萬章問。

*◎ 曰：「其志嘐嘐然，曰『古之人，古之人』。夷考其行而不掩焉者也。*

趙岐註：考察其行，不能掩覆其言，是其狂也。

朱熹《孟子集註》：嘐嘐，志大言大也。重言古之人，見其動輒稱之，不一稱而已也。夷，平也。掩，覆也。

程子曰：「曾皙言志，而夫子與之。蓋與聖人之志同，便是堯舜氣象也，特行有不掩焉耳，此所謂狂也。」

*◎ 狂者又不可得，欲得不屑不絜之士而與之，是獧也，是又其次也。*

趙岐註：屑，絜也。不絜，污穢也。既不能得狂者，欲得有介之人，能恥賤惡行不絜者，則可與言矣。是獧人次於狂者也。

朱熹《孟子集註》：此因上文所引，遂解所以思得獧者之意。狂，有志者也；獧，有守者也。有志者能進於道，有守者不失其身。

*◎ 孔子曰：『過我門而不入我室，我不憾焉者，其惟鄉原乎！鄉原，德之賊也。』」曰：「何如斯可謂之鄉原矣？」*

趙岐註：憾，恨也。

朱熹《孟子集註》：鄉人，非有識者。原，與愿同。荀子「原愨」，字皆讀作愿，謂謹愿之人也。故鄉里所謂愿人，謂之鄉原。孔子以其似德而非德，故以為德之賊。過門不入而不恨之，以其不見親就為幸，深惡而痛絕之也。萬章又引孔子之言而問也。

*◎ 曰：「『何以是嘐嘐也？言不顧行，行不顧言，則曰『古之人，古之人。行何為踽踽涼涼？生斯世也，為斯世也善，斯可矣。』閹然媚於世也者，是鄉原也。」*

趙岐註：鄉原者，外欲慕古之人，而其心曰古之人何為空自踽踽涼涼，而生於今之世無所用之乎。以為生斯世，但當取為人所善善人則可矣。其實但為合衆之行。媚，愛也。

朱熹《孟子集註》：踽踽，獨行不進之貌。涼涼，薄也，不見親厚於人也。鄉原譏狂者曰：何用如此嘐嘐然，行不掩其言，而徒每事必稱古人邪？又譏狷者曰：何必如此踽踽涼涼，無所親厚哉？人既生於此世，則但當為此世之人，使當世之人皆以為善則可矣，此鄉原之志也。閹，如奄人之奄，閉藏之意也。媚，求悅於人也。孟子言此深自閉藏，以求親媚於世，是鄉原之行也。

*◎ 萬子曰：「一鄉皆稱原人焉，無所往而不為原人，孔子以為德之賊，何哉？」*

趙岐註：萬子即萬章也，孟子錄之，以其不解於聖人之意，故謂之萬子。子，男子之通稱也。萬子言人皆以為原善，所至亦謂之善人。

朱熹《孟子集註》：原，亦謹厚之稱，而孔子以為德之賊，故萬章疑之。

*◎ 曰：「非之無舉也，刺之無刺也。同乎流俗，合乎汙世。居之似忠信，行之似廉潔，眾皆悅之，自以為是，而不可與入堯舜之道，故曰德之賊也。*

趙岐註：無德而人以為有德，故曰德之賊也。

朱熹《孟子集註》：呂侍講曰：「言此等之人，欲非之則無可舉，欲刺之則無可刺也。」流俗者，風俗頹靡，如水之下流，眾莫不然也。汙，濁也。非忠信而似忠信，非廉潔而似廉潔。

*◎ 孔子曰：『惡似而非者，惡莠，恐其亂苗也；惡佞，恐其亂義也；惡利口，恐其亂信也；惡鄭聲，恐其亂樂也；惡紫，恐其亂朱也；惡鄉原，恐其亂德也。』*

趙岐註：似真而非真者，孔子之所惡也。

朱熹《孟子集註》：孟子又引孔子之言以明之。莠，似苗之草也。佞，才智之稱，其言似義而非義也。利口，多言而不實者也。鄭聲，淫樂也。樂，正樂也。紫，閒色。朱，正色也。鄉原不狂不獧，人皆以為善，有似乎中道而實非也，故恐其亂德。

*◎ 君子反經而已矣。經正則庶民興，庶民興，斯無邪慝矣。」*

趙岐註：君子治國家歸於常經，謂以仁、義、禮、智道化之，則眾民興起而家給人足矣。倉廪實而知禮節，安有為邪惡之行也。

朱熹《孟子集註》：反，復也。經，常也，萬世不易之常道也。興，興起於善也。邪慝，如鄉原之屬是也。世衰道微，大經不正，故人人得為異說以濟其私，而邪慝并起，不可勝正，君子於此，亦復其常道而已。常道既復，則民興於善，而是非明白，無所回互，雖有邪慝，不足以惑之矣。

尹焞曰：「君子取夫狂獧者，蓋以狂者志大而可與進道，獧者有所不為，而可與有為也。所惡於鄉原，而欲痛絕之者，為其似是而非，惑人之深也。絕之之術無他焉，亦曰反經而已矣。」

正義：三十七章言士行有科，人有等級，中道為上，狂、獧不合。似是而非，色厲內茬，鄉原之惡，聖人所甚。反經身行，民化於己，子率而正，孰敢不正也。

 

** 第三十八章

*◎ 孟子曰：「由堯舜至於湯，五百有餘歲。若禹、皋陶則見而知之，若湯則聞而知之。*

趙岐註：言五百歲而聖人一出，天道之常也。亦有遲速，不能正五百歲，故言有餘歲也。見而知之，謂輔佐也。通於大賢次聖者，亦得與在其間。親見聖人之道而佐行之，言易也。聞而知之者，聖人相去卓遠，數百歲之間變故眾多，踰聞前聖所行，追而遵之，以致其道，言難也。

尹焞曰：「知，謂知其道也。」

*◎ 由湯至於文王，五百有餘歲。若伊尹、萊朱則見而知之，若文王則聞而知之。*

趙岐註：《春秋傳》曰：「仲虺居薛，為湯左相。」是則伊尹為右相，故二人等德也。

朱熹《孟子集註》：趙氏曰：「萊朱，湯賢臣。」或曰：「即仲虺也，為湯左相。」

*◎ 由文王至於孔子，五百有餘歲。若太公望、散宜生，則見而知之，若孔子則聞而知之。*

趙岐註：呂尚有勇謀而為將，散宜生有文德而為相，故以相配而言之也。

朱熹《孟子集註》：散，氏；宜生，名；文王賢臣也。子貢曰：「文武之道，未墜於地，在人。賢者識其大者，不賢者識其小者，莫不有文武之道焉。夫子焉不學？」此所謂聞而知之也。

*◎ 由孔子而來，至於今，百有餘歲，去聖人之世，若此其未遠也；近聖人之居，若此其甚也。然而無有乎爾，則亦無有乎爾。」*

趙岐註：然而世謂之無有，此乃天不欲使我行道也。故重言之，知天意之審也。言「則亦」者，非實無有也，則亦當使為無有也。「乎爾」者，歎而不怨之辭也。

朱熹《孟子集註》：

#+begin_verse
林氏曰：「孟子言孔子至今時未遠，鄒魯相去又近，然而已無有見而知之者矣；則五百餘歲之後，又豈復有聞而知之者乎？」

愚按：此言，雖若不敢自謂已得其傳，而憂後世遂失其傳，然乃所以自見其有不得辭者，而又以見夫天理民彝不可泯滅，百世之下，必將有神會而心得之者耳。故於篇終，歷序羣聖之統，而終之以此，所以明其傳之有在，而又以俟後聖於無窮也，其指深哉！
#+end_verse

李贄評：看他文勢趕來孟子還是以見知自處，還是以聞知自處，何從來解者可笑也。

正義：三十八章言天地剖判，開元建始，三皇以來，人倫攸敘，宏析道德，班垂文采，莫貴乎聖人。聖人不出，名世承間，雖有此限，蓋有遇不遇焉。是以仲尼至「獲麟」而止，孟子以「無有乎爾」終其篇章，斯亦一契之趣也。
